// Peças (procuração, contrato, relatório semanal) e atualização ao cliente — downloads capturados no teste.
import { chromium } from '/tmp/node_modules/playwright-core/index.mjs'
let falhas = 0; const ok = (c, n) => { console.log((c ? 'PASS ' : 'FAIL ') + n); if (!c) falhas++ }
const b = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] }); const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } })
const p = await ctx.newPage(); const erros = []; p.on('pageerror', e => erros.push(e.message)); p.on('console', m => { if (m.type() === 'error') erros.push(m.text()) })
await p.addInitScript(() => { window.__dl = []; window.claude = { use: async n => n === 'downloads' ? { save: async o => { window.__dl.push(o) } } : null } })
await p.goto('file:///home/user/pasta/artefatos/crm-completo/dist/crm.html'); await p.waitForSelector('[data-testid=sidebar]')
const t = id => p.locator(`[data-testid="${id}"]`); const esp = () => p.waitForTimeout(150)
await p.evaluate(() => abrirFicha(6)); await esp(); await t('gerar-procuracao').click(); await esp()
let d = await p.evaluate(() => __dl.at(-1)); ok(d && /_PROCURACAO_/i.test(d.filename.toUpperCase().replace('Ç', 'C').replace('Ã', 'A')) || /Procura/i.test(d.filename), 'procuração baixada com nome padrão: ' + (d && d.filename))
ok(/PROCURAÇÃO/.test(d.data) && /Beatriz Cardoso/.test(d.data) && /ad judicia et extra/.test(d.data) && /Divórcio consensual — Beatriz/.test(d.data), 'procuração usa a qualificação e a demanda')
ok(/\[NOME DA ADVOGADA\]|Lara Café/.test(d.data) && /529\.982\.247-25/.test(d.data), 'dados da advogada e CPF da qualificação entram no texto')
ok(await p.evaluate(() => DB.atividades.some(a => /Procuração gerada/.test(a.texto)) && DB.auditoria.some(a => a.acao === 'gerar_peca')), 'geração fica na linha do tempo e na auditoria')
await p.keyboard.press('Escape')
await p.evaluate(() => { CONFIG.escritorio.oab = ''; ir('financeiro') }); await esp(); await p.evaluate(() => editarHonorario(DB.honorarios[0])); await esp(); await t('gerar-contrato').click(); await esp()
d = await p.evaluate(() => __dl.at(-1)); ok(/CONTRATO DE PRESTAÇÃO DE SERVIÇOS ADVOCATÍCIOS/.test(d.data) && /quatro mil e quinhentos reais/.test(d.data) && /em 3 parcelas mensais de R\$\s?1\.500,00/.test(d.data), 'contrato com valor por extenso e parcelas')
ok(/\[OAB\]/.test(d.data), 'dado faltante vira [MARCADOR] visível (não inventa)')
ok(/Lei nº 8\.906\/1994/.test(d.data) && /CLÁUSULA 4ª — DAS OBRIGAÇÕES/.test(d.data) && /sem prejuízo dos já vencidos/.test(d.data), 'cláusulas do modelo do escritório')
await p.keyboard.press('Escape')
await p.evaluate(() => abrirDemandaDetalhe(1)); await esp(); await t('atualizacao-cliente').click(); await esp()
const m = await t('atualizacao-texto').inputValue(); ok(/Olá, Beatriz!/.test(m) && /Próximos passos:/.test(m) && /Enviar:/.test(m), 'atualização para a cliente montada dos dados (documentos pendentes, próximos passos)')
ok(/Reunião: Reunião com cartório/.test(m), 'inclui o próximo compromisso da demanda')
await t('atualizacao-doc').click(); await esp(); d = await p.evaluate(() => __dl.at(-1)); ok(/RELATÓRIO SEMANAL/.test(d.data), 'relatório semanal (.doc)')
await t('atualizacao-conversa').click(); await esp(); ok((await t('comp-texto').inputValue()).startsWith('Olá, Beatriz!'), 'leva o texto para a conversa, para revisar e enviar')
ok(erros.length === 0, 'sem erros: ' + erros.slice(0, 3).join(' | ')); await b.close(); console.log(falhas ? falhas + ' falha(s)' : 'TUDO OK'); process.exit(falhas ? 1 : 0)
