import { atencao, buscaGlobal, etapaPessoaAposDemandas, funil, herdaPessoa, painelHoje, parcelar, planoExclusaoDemanda, relatorios, resumoFinanceiro, situacaoComercial, validarBackup, vazioDados } from '../../shared/utils/crmHtml'
let falhas = 0
const eq = (n: string, a: unknown, b: unknown) => { const ok = JSON.stringify(a) === JSON.stringify(b); console.log(`${ok ? 'PASS' : 'FAIL'} ${n}${ok ? '' : ' → ' + JSON.stringify(a) + ' ≠ ' + JSON.stringify(b)}`); if (!ok) falhas++ }
const hoje = '2026-10-01'
const D = vazioDados()
D.pessoas.push({ id: 'p1', nome: 'Ana Souza', etapa: 'proposta', tipo: 'contato', origem: 'Instagram', etapa_desde: '2026-09-20T10:00:00Z' }, { id: 'p2', nome: 'Bruno Lima', etapa: 'ativo', origem: 'Indicação' }, { id: 'p3', nome: 'Carla', etapa: 'nao_contratou', origem: 'Instagram' }, { id: 'p4', nome: 'Parte X', etapa: 'novo', tipo: 'relacionado' })
D.demandas.push({ id: 'd1', pessoa_id: 'p2', titulo: 'Inventário do pai', area: 'Sucessões', status: 'aberta' }, { id: 'd2', pessoa_id: 'p2', titulo: 'Guarda', area: 'Família', status: 'encerrada' })
D.processos.push({ id: 'pr1', demanda_id: 'd1', numero: '0000123-45.2026.8.05.0001', fase: 'conhecimento' })
D.partes.push({ id: 'pa1', demanda_id: 'd1', nome: 'Irmão' }); D.movimentacoes.push({ id: 'm1', processo_id: 'pr1', texto: 'Juntada' }); D.documentos.push({ id: 'do1', demanda_id: 'd1', tipo: 'pedido', status: 'pendente', nome: 'Certidão de óbito' })
D.tarefas.push({ id: 't1', titulo: 'Ligar', data: '2026-09-29', pessoa_id: 'p2' }, { id: 't2', titulo: 'Hoje', data: hoje }, { id: 't3', titulo: 'Feita', data: '2026-09-01', feito: true }, { id: 't4', titulo: 'Solta', data: '2026-10-05', demanda_id: 'd1' })
D.compromissos.push({ id: 'c1', tipo: 'prazo', titulo: 'Réplica', data: '2026-09-30' }, { id: 'c2', tipo: 'audiencia', titulo: 'Audiência', data: '2026-10-04', hora: '09:00' }, { id: 'c3', tipo: 'prazo', titulo: 'Recurso', data: hoje }, { id: 'c4', tipo: 'reuniao', titulo: 'Longe', data: '2026-11-01' })
D.honorarios.push({ id: 'h1', demanda_id: 'd1', status: 'contratado', valor_total: 3000 }, { id: 'h2', demanda_id: 'd2', status: 'proposta', valor_total: 999 })
D.lancamentos.push({ id: 'l1', honorario_id: 'h1', demanda_id: 'd1', valor: 1000, vencimento: '2026-09-10', pago_em: '2026-09-10' }, { id: 'l2', honorario_id: 'h1', demanda_id: 'd1', valor: 1000, vencimento: '2026-09-25' }, { id: 'l3', honorario_id: 'h1', demanda_id: 'd1', valor: 1000, vencimento: '2026-10-20' })

eq('ciclo: demanda aberta → ativo; encerrou a última → concluído; funil sem demanda não muda', [etapaPessoaAposDemandas({ id: 'p1', etapa: 'proposta' }, D.demandas), etapaPessoaAposDemandas({ id: 'p2', etapa: 'concluido' }, D.demandas), etapaPessoaAposDemandas({ id: 'p2', etapa: 'ativo' }, D.demandas.map(d => ({ ...d, status: 'encerrada' }))), etapaPessoaAposDemandas({ id: 'p3', etapa: 'nao_contratou' }, D.demandas)], ['proposta', 'ativo', 'concluido', 'nao_contratou'])
const pl = planoExclusaoDemanda('d1', D)
eq('apagar demanda: leva processo, parte, movimentação, documento; solta tarefa; BLOQUEIA por honorário', [pl.processos, pl.partes, pl.movimentacoes, pl.documentos, pl.soltar.tarefas, !!pl.bloqueio], [['pr1'], ['pa1'], ['m1'], ['do1'], ['t4'], true])
eq('demanda sem financeiro pode ser apagada', planoExclusaoDemanda('d2', D).bloqueio, 'Esta demanda tem honorários ou lançamentos financeiros. Apague-os no Financeiro antes (para não perder o controle do que é devido).'.length ? planoExclusaoDemanda('d2', D).bloqueio : '')
eq('d2 tem honorário em proposta → também bloqueia (qualquer honorário)', !!planoExclusaoDemanda('d2', D).bloqueio, true)
eq('a demanda manda na pessoa', herdaPessoa({ demanda_id: 'd1', pessoa_id: 'p1' }, D).pessoa_id, 'p2')
const f = resumoFinanceiro(D, hoje)
eq('financeiro: só contratado conta (3000), recebido 1000, a receber 2000, vencido 1000 (1 parcela), 30 dias: 1000', [f.contratado, f.recebido, f.aReceber, f.vencido, f.parcelasVencidas, f.proximos30], [3000, 1000, 2000, 1000, 1, 1000])
eq('parcelar 1000 em 3: centavo na primeira; mês curto', [parcelar(1000, 3, '2026-01-31').map(p => p.valor), parcelar(1000, 3, '2026-01-31').map(p => p.vencimento)], [[333.34, 333.33, 333.33], ['2026-01-31', '2026-02-28', '2026-03-31']])
eq('parcelar soma exata', parcelar(1234.56, 7, '2026-10-05').reduce((s, p) => Math.round((s + p.valor) * 100) / 100, 0), 1234.56)
eq('situação comercial', [situacaoComercial('d1', D), situacaoComercial('d2', D), situacaoComercial('zz', D)], ['contratada', 'proposta', 'sem_proposta'])
const ph = painelHoje(D, hoje)
eq('Hoje: tarefa atrasada, tarefa de hoje, prazo vencido, compromissos de hoje, próximos 7 dias, parcelas vencidas, pedidos pendentes', [ph.tarefasAtrasadas.map(t => t.id), ph.tarefasHoje.map(t => t.id), ph.prazosVencidos.map(c => c.id), ph.compromissosHoje.map(c => c.id), ph.proximos7.map(c => c.id), ph.parcelasVencidas.map(l => l.id), ph.docsPendentes], [['t1'], ['t2'], ['c1'], ['c3'], ['c2'], ['l2'], 1])
eq('Atenção: no máximo 5, prazo primeiro', [atencao(D, hoje).length, atencao(D, hoje)[0]!.tipo], [5, 'prazo'])
eq('lead parado há 5+ dias aparece', ph.leadsParados.map(p => p.id), ['p1'])
const fu = funil(D.pessoas)
eq('funil: relacionado fora; conversão = clientes ÷ (clientes + não contratou)', [fu.leadsTotal, fu.clientes, fu.naoContratou, fu.conversao], [1, 1, 1, 50])
eq('busca: por nome sem acento, por nº do processo (só dígitos), mínimo 2 letras', [buscaGlobal(D, 'carla').map(r => r.id), buscaGlobal(D, '0000123').map(r => r.ent), buscaGlobal(D, 'a').length], [['p3'], ['processos'], 0])
const rel = relatorios(D, hoje)
eq('relatórios: demandas abertas/encerradas, por área e origem, recebido no mês (outubro: 0; o pago foi em setembro)', [rel.demandasAbertas, rel.demandasEncerradas, rel.porArea, rel.porOrigem, rel.recebidoMes], [1, 1, { 'Sucessões': 1 }, { Instagram: 2, 'Indicação': 1 }, 0])
eq('backup: arquivo estranho recusado; válido normaliza', [validarBackup({}).ok, validarBackup({ tipo: 'crm-lara-cafe', dados: { pessoas: [{ id: 'a b' }] } }).ok, validarBackup({ tipo: 'crm-lara-cafe', dados: { pessoas: [{ id: 'a1', nome: 'X' }], lixo: [1] } }).total], [false, false, 1])
console.log(falhas ? `\n${falhas} FALHA(S)` : 'Todos os testes passaram'); process.exit(falhas ? 1 : 0)
