'use strict'
/* ============ Pessoas: Leads (funil), contato, ficha do cliente, Clientes, Mensagens, Remarketing ============ */
UI.leads = { q: '', area: '', mostrar: false }; UI.clientes = { q: '', f: 'todos' }; UI.msgs = { sel: null, q: '' }; UI.ficha = { aba: 'cliente' }

/* ---- cadastro de contato ---- */
function criarContatoReal(v) {
  const n = { ...(DB.contatos[0] ? Object.fromEntries(Object.keys(DB.contatos[0]).map(k => [k, null])) : {}), exemplo: false, real: true, site_id: null, id: proximoId('contatos'), created_at: agora(), updated_at: agora(), etapa: 'novo', etapa_desde: agora(), interesses: [], objecoes: [], consulta_em: null, nps: null, classificacao: null, classificacao_desde: null, motivo_perda: null, ultimo_contato_em: null, ultima_mensagem_em: null, proxima_acao: CRM.CADENCIA.novo.acao, proxima_data: hojeISO(), qualificacao: null, respostas: {}, drive_pasta_url: null, tem_filhos: null, ...v }
  DB.contatos.push(n); registrar(n.id, 'Anotação', 'Contato criado.'); auditar('criar_contato', n.nome); salvar('contatos'); return n
}
function editarContato(c) {
  const areas = Object.keys(CRM.AREAS)
  const campos = [{ chave: 'nome', rotulo: 'Nome', obrigatorio: true }, { chave: 'telefone', rotulo: 'Telefone / WhatsApp', tipo: 'tel', obrigatorio: true, dica: 'Com DDD. Ex.: (71) 99999-0000', valida: v => { const d = normalizarTelefone(v); if (d.length < 12) return 'Telefone incompleto.'; const o = DB.contatos.find(x => x.telefone === d && (!c || x.id !== c.id)); return o ? `Já cadastrado para ${o.nome}.` : null } },
    { chave: 'email', rotulo: 'E-mail', tipo: 'email' }, { chave: 'cidade', rotulo: 'Cidade' }, { chave: 'origem', rotulo: 'Origem', tipo: 'select', opcoes: [['', '—'], ...CRM.ORIGENS] }, { chave: 'area', rotulo: 'Área', tipo: 'select', opcoes: [['', '—'], ...areas] },
    { chave: 'demanda', rotulo: 'Demanda (assunto)' }, { chave: 'urgencia', rotulo: 'Urgência', tipo: 'select', opcoes: [['', '—'], ...CRM.URGENCIAS] }, { chave: 'sentimento', rotulo: 'Sentimento', tipo: 'select', opcoes: [['', '—'], ...CRM.SENTIMENTOS] }, { chave: 'data_nascimento', rotulo: 'Nascimento', tipo: 'data' },
    { chave: 'parte_contraria', rotulo: 'Parte contrária' }, { chave: 'resumo', rotulo: 'Resumo da situação', tipo: 'textarea' }, { chave: 'nao_contatar', rotulo: 'Não contatar (pediu para não receber mensagens)', tipo: 'check', largo: true }]
  const val = c ? { ...c, telefone: telefoneFormatado(c.telefone) } : { origem: '', urgencia: '' }
  modalForm(c ? 'Editar cadastro' : 'Novo contato', campos, val, v => {
    v.telefone = normalizarTelefone(v.telefone)
    if (c) { Object.assign(c, v, { updated_at: agora() }); registrar(c.id, 'Anotação', 'Cadastro atualizado.') } else criarContatoReal(v)
    salvar('contatos')
  }, { largura: 'max-w-2xl' })
}
function modalMotivoPerda(c) { modalForm('Não contratou — ' + c.nome, [{ chave: 'motivo_perda', rotulo: 'Motivo', tipo: 'select', opcoes: CRM.MOTIVOS_PERDA, obrigatorio: true, dica: 'Fora da área, encaminhado ou conflito de interesses: não entra no Remarketing.' }], { motivo_perda: CRM.MOTIVOS_PERDA[0] }, v => moverEtapa(c, 'perdido', v), { rotulo: 'Marcar' }) }
function modalConsulta(c) { modalForm('Agendar consulta — ' + c.nome, [{ chave: 'consulta_em', rotulo: 'Data e hora da consulta', tipo: 'datahora', obrigatorio: true }], { consulta_em: c.consulta_em }, v => moverEtapa(c, 'agendado', v), { rotulo: 'Agendar' }) }
function mudarEtapa(c, nova) { if (nova === 'agendado') return modalConsulta(c); if (nova === 'perdido') return modalMotivoPerda(c); const r = moverEtapa(c, nova); if (r.erro) aviso(r.erro, 'erro'); else { aviso('Movido para ' + CRM.etapa(nova).nome); render() } }

/* ================= LEADS (funil) ================= */
VIEWS.funil = () => {
  const { q, area, mostrar } = UI.leads; const abertas = CRM.ETAPAS.filter(e => e.aberta && e.id !== 'ativo'); const colunas = mostrar ? [...abertas, CRM.etapa('ativo'), CRM.etapa('concluido'), CRM.etapa('perdido')] : abertas
  const ok = c => (!q || semAcento([c.nome, c.demanda, c.telefone].join(' ')).includes(semAcento(q))) && (!area || c.area === area)
  const card = c => {
    const dias = diasEntre(diaDe(c.etapa_desde), hojeISO()); const sit = c.proxima_data ? situacaoOf(c.proxima_data) : null; const prox = CRM.ETAPAS.findIndex(e => e.id === c.etapa) + 1; const prox_ = CRM.ETAPAS[prox]
    const el = h('div', { class: 'rounded-2xl bg-white dark:bg-zinc-900 border border-gray-200/70 dark:border-zinc-800 p-3 shadow-sm hover:shadow-md transition-shadow cursor-grab', draggable: 'true', 'data-testid': 'lead-card', 'data-id': c.id },
      h('div', { class: 'flex items-start justify-between gap-2' }, h('button', { type: 'button', class: 'text-left font-semibold text-sm text-primary dark:text-cafe-creme hover:underline truncate', onclick: () => abrirFicha(c.id) }, c.nome || telefoneFormatado(c.telefone)), c.urgencia === 'Alta' ? badge('Alta', 'vermelho') : null),
      h('p', { class: 'text-[11px] text-gray-500 truncate mt-0.5' }, [c.area, c.demanda].filter(Boolean).join(' · ') || 'Sem demanda definida'),
      h('div', { class: 'flex flex-wrap gap-1 mt-2' }, c.origem ? h('span', { class: 'tag' }, c.origem) : null, h('span', { class: 'tag' }, dias === 0 ? 'hoje na etapa' : `${dias}d na etapa`), c.consulta_em && c.etapa === 'agendado' ? badge('Consulta ' + dataCurta(c.consulta_em) + ' ' + hhmm(c.consulta_em), 'roxo') : null),
      c.proxima_acao ? h('p', { class: 'text-[11px] mt-2 flex items-center gap-1 ' + (sit === 'atrasado' ? 'text-danger font-semibold' : 'text-gray-600 dark:text-zinc-300') }, ic('ph:arrow-fat-line-right-bold'), c.proxima_acao + (c.proxima_data ? ' · ' + diaRelativo(c.proxima_data) : '')) : null,
      h('div', { class: 'flex items-center justify-between gap-2 mt-2.5' }, h('select', { class: 'text-[11px] rounded-full border border-gray-200 dark:border-zinc-700 bg-transparent px-2 py-1 max-w-[9.5rem]', 'aria-label': 'Mover ' + c.nome + ' para', onchange: ev => { const v = ev.target.value; ev.target.value = ''; if (v) mudarEtapa(c, v) }, 'data-testid': 'mover' }, h('option', { value: '' }, 'Mover para…'), CRM.ETAPAS.filter(e => e.id !== c.etapa && e.id !== 'relacionado').map(e => h('option', { value: e.id }, e.nome))), prox_ && ['novo', 'qualificacao', 'agendado', 'diagnostico'].includes(c.etapa) ? btn('Avançar', { mini: true, tipo: 'sec', onclick: () => mudarEtapa(c, prox_.id), tid: 'avancar' }) : (c.etapa === 'proposta' ? btn('Contratou', { mini: true, tipo: 'sec', onclick: () => abrirDemandaForm(c.id), tid: 'contratou' }) : null)))
    el.addEventListener('dragstart', e => { e.dataTransfer.setData('text/plain', String(c.id)); e.dataTransfer.effectAllowed = 'move' }); return el
  }
  const col = e => {
    const cs = DB.contatos.filter(c => c.etapa === e.id && ok(c)).sort((a, b) => (a.proxima_data || '9') < (b.proxima_data || '9') ? -1 : 1)
    const z = h('div', { class: 'w-72 shrink-0 rounded-3xl bg-gray-200/50 dark:bg-zinc-900/60 p-3 flex flex-col gap-2', 'data-testid': 'coluna-' + e.id }, h('div', { class: 'px-1 pb-1' }, h('div', { class: 'flex items-center justify-between' }, h('h2', { class: 'text-sm font-bold text-primary dark:text-zinc-100' }, e.nome), h('span', { class: 'pill' }, cs.length)), h('p', { class: 'text-[11px] text-gray-500' }, e.hint)), cs.length ? cs.map(card) : h('p', { class: 'text-xs text-gray-400 text-center py-6 border border-dashed border-gray-300 dark:border-zinc-700 rounded-2xl' }, 'Solte um contato aqui'))
    z.addEventListener('dragover', ev => { ev.preventDefault(); z.classList.add('ring-2', 'ring-primary/40') }); z.addEventListener('dragleave', () => z.classList.remove('ring-2', 'ring-primary/40'))
    z.addEventListener('drop', ev => { ev.preventDefault(); z.classList.remove('ring-2', 'ring-primary/40'); const c = contato(ev.dataTransfer.getData('text/plain')); if (c && c.etapa !== e.id) mudarEtapa(c, e.id) }); return z
  }
  return pagina('Funil', 'Do primeiro contato à contratação. Arraste os cartões ou use “Avançar”. Cada etapa sugere a próxima ação.', [btn('Novo contato', { icone: 'ph:user-plus-bold', onclick: () => editarContato(null), tid: 'novo-contato' })],
    h('div', { class: 'flex flex-wrap items-center gap-3' }, h('div', { class: 'w-full sm:w-72' }, busca(q, v => { UI.leads.q = v; render() }, 'Buscar nome, demanda ou telefone')), h('select', { class: 'selecao', 'aria-label': 'Filtrar por área', onchange: ev => { UI.leads.area = ev.target.value; render() } }, h('option', { value: '' }, 'Todas as áreas'), Object.keys(CRM.AREAS).map(a => h('option', { value: a, selected: a === area }, a))), h('label', { class: 'flex items-center gap-2 text-sm' }, h('input', { type: 'checkbox', class: 'accent-[#6f5636]', checked: mostrar, onclick: () => { UI.leads.mostrar = !mostrar; render() } }), 'Mostrar clientes e encerrados')),
    h('div', { class: 'flex gap-3 overflow-x-auto pb-3 scrollbar-thin items-start', 'data-testid': 'funil' }, colunas.map(col)))
}

/* ================= FICHA DO CLIENTE (modal, 5 abas) ================= */
function abrirFicha(id, aba) {
  const c = contato(id); if (!c) return; if (aba) UI.ficha.aba = aba; let m
  const corpo = h('div', { 'data-testid': 'ficha' })
  const redesenhar = () => {
    const A = UI.ficha.aba; const abasL = [{ id: 'cliente', nome: 'Cliente', icone: 'ph:user-bold' }, { id: 'demandas', nome: 'Demandas', icone: 'ph:briefcase-bold', n: demandasDe(c.id).length }, { id: 'conversa', nome: 'Comunicação', icone: 'ph:chats-circle-bold', n: DB.comunicacoes.filter(x => x.contato_id === c.id && x.direcao === 'entrada' && !x.lida).length }, { id: 'financeiro', nome: 'Financeiro', icone: 'ph:wallet-bold' }, { id: 'historico', nome: 'Linha do tempo', icone: 'ph:clock-counter-clockwise-bold' }]
    corpo.replaceChildren(
      h('div', { class: 'flex flex-wrap items-center gap-3 mb-4' }, avatar(c.nome, true), h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'text-[10px] font-bold uppercase tracking-widest text-gray-400' }, CRM.codigoCliente(c.id)), h('h3', { class: 'font-serif text-xl text-primary dark:text-zinc-100 truncate' }, c.nome || 'Sem nome'), h('p', { class: 'text-xs text-gray-500' }, telefoneFormatado(c.telefone) + (c.email ? ' · ' + c.email : ''))), badgeEtapa(c.etapa), c.classificacao ? badge(CRM.CLASSIFICACOES[c.classificacao].nome, c.classificacao === 'promotora' ? 'verde' : c.classificacao === 'detratora' ? 'vermelho' : 'cinza') : null),
      h('div', { class: 'flex flex-wrap gap-2 mb-4' }, btn('Comunicar', { mini: true, icone: 'ph:chats-circle-bold', onclick: () => { UI.ficha.aba = 'conversa'; redesenhar() }, tid: 'ficha-msg' }), btn('Resumir com IA', { mini: true, tipo: 'sec', icone: 'ph:sparkle-bold', onclick: () => resumirCliente(c), tid: 'ia-resumir-cliente', class: 'ia-btn' }), btn('Registrar andamento', { mini: true, tipo: 'sec', icone: 'ph:note-pencil-bold', onclick: () => abrirAndamento(c) }), btn('Editar cadastro', { mini: true, tipo: 'sec', icone: 'ph:pencil-simple-bold', onclick: () => editarContato(c), tid: 'ficha-editar' }), btn('Excluir', { mini: true, tipo: 'fantasma', icone: 'ph:trash-bold', onclick: () => confirmar('Excluir cadastro?', `Apaga ${c.nome} e seus registros (tarefas, mensagens, honorários). Esta ação não pode ser desfeita. O CRM bloqueia se houver demandas.`, 'Excluir', () => { const r = excluirContato(c); if (r.erro) { aviso(r.erro, 'erro'); return } m.fechar(); render(); aviso('Cadastro excluído.') }), tid: 'ficha-excluir' })),
      abas(abasL, A, id => { UI.ficha.aba = id; redesenhar() }), h('div', { class: 'mt-4' }, { cliente: abaCliente, demandas: abaDemandas, conversa: abaConversa, financeiro: abaFinanceiro, historico: abaHistorico }[A](c, redesenhar)))
  }
  REDES.add(redesenhar); m = modal({ titulo: 'Ficha do cliente', largura: 'max-w-4xl', corpo, aoFechar: () => { REDES.delete(redesenhar); render() } }); redesenhar()
}
function abaCliente(c, red) {
  const q = c.qualificacao || {}; const lista_ = checklistAtendimento(c); const feitos = lista_.filter(i => i.feito).length
  const etapaSel = h('select', { class: 'selecao', 'aria-label': 'Etapa', 'data-testid': 'ficha-etapa', onchange: ev => { const v = ev.target.value; ev.target.value = c.etapa; mudarEtapa(c, v); setTimeout(red, 50) } }, CRM.ETAPAS.map(e => h('option', { value: e.id, selected: e.id === c.etapa }, e.nome)))
  const nps = h('div', { class: 'flex flex-wrap gap-1' }, Array.from({ length: 11 }, (_, n) => h('button', { type: 'button', class: 'w-8 h-8 rounded-full border text-xs font-semibold ' + (c.nps === n ? 'bg-primary text-white border-primary' : 'border-gray-300 dark:border-zinc-700 hover:border-primary'), onclick: () => { salvarNps(c, n); red() }, 'aria-label': 'Nota ' + n }, n)))
  const rev = { cpf: false, rg: false }
  const confid = (k) => { const span = h('span', {}, ''); const mostrar = () => { const v = q[k]; span.textContent = rev[k] ? (v || '—') : (CRM.mascararDocumento(v) || '—') }; mostrar(); return h('div', { class: 'min-w-0' }, h('p', { class: 'text-[10px] font-bold uppercase tracking-widest text-gray-400' }, k.toUpperCase()), h('p', { class: 'text-sm flex items-center gap-1.5' }, span, q[k] ? h('button', { type: 'button', class: 'text-gray-400 hover:text-primary', 'aria-label': 'Mostrar ou ocultar ' + k, onclick: () => { rev[k] = !rev[k]; if (rev[k]) auditar('ver_dado_confidencial', `${k} de ${c.nome}`); mostrar() } }, ic('ph:eye-bold')) : null)) }
  return h('div', { class: 'space-y-5' },
    painel('Situação', h('div', { class: 'grid gap-3 sm:grid-cols-2 lg:grid-cols-3' }, h('label', {}, rotuloCampo('Etapa'), etapaSel), campoLeitura('Próxima ação', c.proxima_acao ? `${c.proxima_acao}${c.proxima_data ? ' · ' + dataLonga(c.proxima_data) : ''}` : null), campoLeitura('Consulta', c.consulta_em ? dataHora(c.consulta_em) : null), campoLeitura('Área / demanda', [c.area, c.demanda].filter(Boolean).join(' · ')), campoLeitura('Origem', c.origem), campoLeitura('Urgência / sentimento', [c.urgencia, c.sentimento].filter(Boolean).join(' · ')), campoLeitura('Parte contrária', c.parte_contraria), campoLeitura('Nascimento', c.data_nascimento ? dataLonga(c.data_nascimento) : null), campoLeitura('Motivo (não contratou)', c.motivo_perda)), c.resumo ? h('p', { class: 'text-sm text-gray-600 dark:text-zinc-300 mt-3' }, c.resumo) : null),
    c.etapa !== 'perdido' && c.etapa !== 'relacionado' ? painel(`Checklist do atendimento (${feitos}/${lista_.length})`, lista_.length ? h('ul', { class: 'space-y-1.5' }, lista_.map(i => h('li', { class: 'flex items-start gap-2.5 text-sm' }, h('input', { type: 'checkbox', class: 'mt-1 accent-[#6f5636]', checked: i.feito, disabled: i.tipo === 'auto', 'aria-label': i.titulo, onclick: () => { CONFIG.checklist_manual[c.id] = { ...(CONFIG.checklist_manual[c.id] || {}), [i.chave]: !i.feito }; salvar('config'); red() } }), h('span', { class: 'flex-1 ' + (i.feito ? 'text-gray-400 line-through' : '') }, i.titulo, h('span', { class: 'block text-[11px] text-gray-400 no-underline' }, i.tipo === 'auto' ? 'Automático — ' + i.dica : 'Você marca — ' + i.dica)), badge(CRM.NOMES_FASES[i.fase] || 'Fase ' + i.fase, 'cinza')))) : estadoVazio('ph:list-checks-bold', 'Sem itens ainda')) : null,
    painel('Qualificação (para contrato e procuração)', h('div', { class: 'grid gap-3 sm:grid-cols-2 lg:grid-cols-3' }, campoLeitura('Nome completo', q.nome_completo), confid('cpf'), confid('rg'), campoLeitura('Estado civil', q.estado_civil), campoLeitura('Profissão', q.profissao), campoLeitura('Endereço', [q.endereco, q.bairro, q.cidade && q.cidade + '/' + (q.uf || '')].filter(Boolean).join(', '))), h('div', { class: 'mt-3 flex flex-wrap gap-2' }, btn('Gerar procuração (.doc)', { mini: true, tipo: 'sec', icone: 'ph:file-doc-bold', tid: 'gerar-procuracao', onclick: () => gerarProcuracao(c, (demandasDe(c.id).find(d => d.status === 'ativo' && d.tipo !== 'consultivo') || {}).id || null) }), btn('Editar qualificação', { mini: true, tipo: 'sec', icone: 'ph:pencil-simple-bold', onclick: () => modalForm('Qualificação', [{ chave: 'nome_completo', rotulo: 'Nome completo', largo: true }, { chave: 'cpf', rotulo: 'CPF', valida: v => v && !CRM.cpfValido(v) ? 'CPF inválido.' : null }, { chave: 'rg', rotulo: 'RG' }, { chave: 'orgao_emissor', rotulo: 'Órgão emissor' }, { chave: 'nacionalidade', rotulo: 'Nacionalidade' }, { chave: 'estado_civil', rotulo: 'Estado civil', tipo: 'select', opcoes: [['', '—'], ...CRM.ESTADOS_CIVIS] }, { chave: 'profissao', rotulo: 'Profissão' }, { chave: 'endereco', rotulo: 'Endereço', largo: true }, { chave: 'bairro', rotulo: 'Bairro' }, { chave: 'cep', rotulo: 'CEP' }, { chave: 'cidade', rotulo: 'Cidade' }, { chave: 'uf', rotulo: 'UF', tipo: 'select', opcoes: [['', '—'], ...CRM.UFS] }], q, v => { c.qualificacao = v; auditar('editar_qualificacao', c.nome); salvar('contatos') }, { largura: 'max-w-2xl' }) })), h('p', { class: 'text-[11px] text-gray-400 mt-2' }, 'CPF e RG ficam mascarados; revelar registra na Auditoria.')),
    painel('Drive do cliente', PainelDrive(c, {})),
    fichaPerguntas(c),
    ['concluido', 'ativo'].includes(c.etapa) ? painel('Satisfação (NPS)', h('p', { class: 'text-xs text-gray-500 mb-2' }, 'A nota de 0 a 10 classifica a cliente: 9–10 promotora, 7–8 neutra, 0–6 detratora.'), nps) : null)
}
function abaDemandas(c, red) {
  const ds = demandasDe(c.id)
  return h('div', { class: 'space-y-3' }, h('div', { class: 'flex justify-end' }, btn('Nova demanda', { mini: true, icone: 'ph:plus-bold', onclick: () => abrirDemandaForm(c.id), tid: 'ficha-nova-demanda' })), ds.length ? ds.map(x => cartaoDemanda(x, true)) : estadoVazio('ph:briefcase-bold', 'Nenhuma demanda', 'Ao abrir a primeira demanda contratada, o contato passa a Cliente ativo.'))
}
function abaConversa(c, red) { return Thread(c.id, {}) }
function abaFinanceiro(c, red) {
  const hs = DB.honorarios.filter(x => x.contato_id === c.id); const ls = DB.lancamentos.filter(x => x.contato_id === c.id)
  return h('div', { class: 'space-y-4' }, h('div', { class: 'flex justify-end gap-2' }, btn('Montar mensagem de proposta', { mini: true, tipo: 'sec', icone: 'ph:chat-circle-text-bold', onclick: () => abrirMensagem(c.id, '/proposta') }), btn('Novo honorário', { mini: true, icone: 'ph:plus-bold', onclick: () => editarHonorario(null, { contato_id: c.id }) })), hs.length ? tabela([{ nome: 'Demanda', cel: x => x.caso_id ? nomeDemanda(x.caso_id) : '—' }, { nome: 'Tipo', cel: x => x.tipo }, { nome: 'Valor', cel: x => brl2(x.valor), cls: 'tabular-nums' }, { nome: 'Status', cel: x => badge(x.status, x.status === 'Pago' ? 'verde' : x.status === 'Contratado' ? 'azul' : x.status === 'Cancelado' ? 'cinza' : 'ambar') }], hs, { clique: x => editarHonorario(x) }) : estadoVazio('ph:wallet-bold', 'Nenhum honorário registrado'), ls.length ? [h('h4', { class: 'section-label' }, 'Lançamentos'), lista(ls.map(l => [h('div', { class: 'flex-1 min-w-0' }, h('p', { class: 'font-semibold truncate' }, l.descricao), h('p', { class: 'text-[11px] text-gray-500' }, 'Vence ' + dataLonga(l.vencimento))), h('b', { class: 'tabular-nums' }, brl2(l.valor)), l.pago_em ? badge('Pago', 'verde') : badgeData(l.vencimento, 'Vencido')]))] : null)
}
function abaHistorico(c) {
  const todos = linhaDoTempo({ contato_id: c.id }); const tipos = ['Todos', ...new Set(todos.map(a => a.tipo))]; const estado = { f: 'Todos' }; const ct = h('div', {})
  const desenha = () => { const vis = estado.f === 'Todos' ? todos : todos.filter(a => a.tipo === estado.f); ct.replaceChildren(h('div', { class: 'flex flex-wrap gap-1.5 mb-3' }, tipos.map(t => h('button', { type: 'button', class: 'filtro-hist ' + (estado.f === t ? 'filtro-hist-ativo' : ''), onclick: () => { estado.f = t; desenha() } }, t))), vis.length ? h('ol', { class: 'relative border-l border-gray-200 dark:border-zinc-700 ml-2 space-y-3', 'data-testid': 'linha-tempo' }, vis.map(a => h('li', { class: 'pl-4 relative' }, h('span', { class: 'absolute -left-[5px] top-1.5 w-2.5 h-2.5 rounded-full bg-secondary' }), h('p', { class: 'text-[11px] text-gray-400' }, `${a.titulo} · ${dataHora(a.quando)}`), h('p', { class: 'text-sm whitespace-pre-line' }, a.texto)))) : estadoVazio('ph:clock-counter-clockwise-bold', 'Sem registros')) }
  desenha(); return h('div', {}, h('div', { class: 'flex justify-end mb-2' }, btn('Nova anotação', { mini: true, icone: 'ph:plus-bold', onclick: () => modalForm('Nova anotação', [{ chave: 'tipo', rotulo: 'Tipo', tipo: 'select', opcoes: ['Anotação', 'Documento recebido', 'Peça / pesquisa', 'Relacionamento'] }, { chave: 'texto', rotulo: 'Texto', tipo: 'textarea', obrigatorio: true }], { tipo: 'Anotação' }, v => { registrar(c.id, v.tipo, v.texto) }) })), ct)
}

/* ================= CLIENTES ================= */
VIEWS.clientes = () => {
  const { q, f } = UI.clientes; const base = DB.contatos.filter(c => ['ativo', 'concluido', 'relacionado'].includes(c.etapa))
  const ok = c => (!q || semAcento([c.nome, c.telefone, c.email].join(' ')).includes(semAcento(q))) && (f === 'todos' || (f === 'ativos' && c.etapa === 'ativo') || (f === 'concluidos' && c.etapa === 'concluido') || (f === 'pessoas' && c.etapa === 'relacionado'))
  const itens = base.filter(ok).sort((a, b) => (a.nome || '').localeCompare(b.nome || ''))
  return pagina('Clientes', 'Quem já contratou — e as pessoas ligadas aos casos (partes, herdeiros). Cada cliente com suas demandas.', [btn('Novo contato', { icone: 'ph:user-plus-bold', onclick: () => editarContato(null) })],
    h('div', { class: 'flex flex-wrap items-center gap-3 justify-between' }, filtros([{ id: 'todos', nome: 'Todos' }, { id: 'ativos', nome: 'Ativos' }, { id: 'concluidos', nome: 'Concluídos' }, { id: 'pessoas', nome: 'Pessoas cadastradas' }], f, id => { UI.clientes.f = id; render() }), h('div', { class: 'w-full sm:w-72' }, busca(q, v => { UI.clientes.q = v; render() }, 'Buscar cliente'))),
    itens.length ? h('div', { class: 'grid gap-3 md:grid-cols-2' }, itens.map(c => { const ds = demandasDe(c.id); return h('div', { class: 'painel !p-4 space-y-2', 'data-testid': 'cliente-card' }, h('div', { class: 'flex items-center gap-3' }, avatar(c.nome), h('div', { class: 'min-w-0 flex-1' }, h('button', { type: 'button', class: 'font-semibold text-primary dark:text-cafe-creme hover:underline truncate block max-w-full', onclick: () => abrirFicha(c.id) }, c.nome), h('p', { class: 'text-[11px] text-gray-500 truncate' }, telefoneFormatado(c.telefone))), badgeEtapa(c.etapa)), ds.length ? h('ul', { class: 'space-y-1' }, ds.map(x => h('li', { class: 'flex items-center gap-2 text-sm' }, ic('ph:briefcase-bold', 'text-gray-400'), h('button', { type: 'button', class: 'hover:underline truncate text-left flex-1', onclick: () => ir('demandas', { abrir: x.id }) }, x.titulo), badge(CRM.STATUS_DEMANDA[x.status], x.status === 'ativo' ? 'verde' : 'cinza')))) : h('p', { class: 'text-xs text-gray-400' }, c.etapa === 'relacionado' ? 'Parte ou interessado — não é lead nem cliente.' : 'Sem demandas.')) })) : estadoVazio('ph:users-bold', 'Nenhum cliente nesta visão'))
}

/* ================= MENSAGENS (biblioteca) ================= */
VIEWS.modelos = () => {
  const { q, sel } = UI.msgs; const cats = [...new Set(DB.modelos.map(m => m.categoria))].sort((a, b) => parseInt(a) - parseInt(b)); const ok = m => !q || semAcento(m.titulo + m.atalho + m.texto).includes(semAcento(q))
  const editar = m => modalForm(m ? 'Editar modelo' : 'Novo modelo', [{ chave: 'categoria', rotulo: 'Categoria', tipo: 'select', opcoes: cats }, { chave: 'titulo', rotulo: 'Título', obrigatorio: true }, { chave: 'atalho', rotulo: 'Atalho (começa com /)', obrigatorio: true, valida: v => !/^\/[a-z0-9-]+$/.test(v || '') ? 'Use /palavra-sem-acento.' : (DB.modelos.some(x => x.atalho === v && x !== m) ? 'Atalho já existe.' : null) }, { chave: 'texto', rotulo: 'Texto (use [NOME], [DATA], [HORA]…)', tipo: 'textarea', linhas: 8, obrigatorio: true }, { chave: 'ativo', rotulo: 'Ativo', tipo: 'check' }], m || { categoria: cats[0], ativo: true }, v => { if (m) Object.assign(m, v); else DB.modelos.push({ id: proximoId('modelos'), ordem: DB.modelos.length + 1, ...v }); salvar('modelos') }, { largura: 'max-w-2xl', extra: m ? btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Excluir modelo?', m.atalho, 'Excluir', () => { DB.modelos = DB.modelos.filter(x => x !== m); salvar('modelos'); render() }) }) : null })
  return pagina('Modelos de mensagem', `${DB.modelos.length} modelos do escritório, para WhatsApp e e-mail. Digite o atalho na conversa para usar.`, [btn('Novo modelo', { icone: 'ph:plus-bold', onclick: () => editar(null), tid: 'novo-modelo' })],
    h('div', { class: 'w-full sm:w-80' }, busca(q, v => { UI.msgs.q = v; render() }, 'Buscar modelo ou atalho')),
    cats.map(cat => { const ms = DB.modelos.filter(m => m.categoria === cat && ok(m)); return ms.length ? painel(cat.replace(/^\d+\.\s*/, ''), h('div', { class: 'grid gap-2 md:grid-cols-2' }, ms.map(m => h('div', { class: 'rounded-2xl border border-gray-200/70 dark:border-zinc-800 p-3 flex flex-col gap-1.5', 'data-testid': 'modelo' }, h('div', { class: 'flex items-center justify-between gap-2' }, h('p', { class: 'font-semibold text-sm truncate' }, m.titulo), h('code', { class: 'tag shrink-0' }, m.atalho)), h('p', { class: 'text-xs text-gray-500 line-clamp-3 whitespace-pre-line' }, m.texto), h('div', { class: 'flex gap-1.5 mt-auto pt-1' }, btn('Copiar', { mini: true, tipo: 'sec', onclick: () => copiar(preencherModelo(m.texto, null)) }), btn('Editar', { mini: true, tipo: 'fantasma', onclick: () => editar(m) }), m.ativo === false ? badge('Inativo', 'cinza') : null))))) : null }))
}

/* ================= REMARKETING ================= */
VIEWS.remarketing = () => {
  const el = remarketingElegiveis(); const fora = DB.contatos.filter(c => c.etapa === 'perdido' && (c.nao_contatar || CRM.MOTIVOS_SEM_REMARKETING.includes(c.motivo_perda)))
  const porDem = {}; el.forEach(x => { const k = [x.contato.area, x.contato.demanda].filter(Boolean).join(' · ') || 'Sem demanda'; (porDem[k] = porDem[k] || []).push(x) })
  const lin = x => h('div', { class: 'flex flex-wrap items-center gap-3 py-2.5', 'data-testid': 'remarketing-item' }, avatar(x.contato.nome), h('div', { class: 'min-w-0 flex-1' }, link(x.contato.nome, () => abrirFicha(x.contato.id)), h('p', { class: 'text-[11px] text-gray-500' }, `Motivo: ${x.contato.motivo_perda} · há ${x.dias} dias`)), x.pronto ? badge('Pronto para contato', 'verde') : badge(`Faltam ${x.faltam} dias`, 'cinza'), btn('Conteúdo', { mini: true, disabled: !x.pronto, icone: 'ph:chat-circle-text-bold', onclick: () => abrirMensagem(x.contato.id, '/remarketing'), tid: 'remarketing-msg' }), btn('Não contatar', { mini: true, tipo: 'fantasma', onclick: () => confirmar('Marcar “não contatar”?', x.contato.nome + ' sai do Remarketing e não recebe mais conteúdo.', 'Confirmar', () => { x.contato.nao_contatar = true; auditar('nao_contatar', x.contato.nome); salvar('contatos'); render() }, false) }))
  return pagina('Remarketing', `Quem não fechou, agrupado por demanda. Conteúdo a cada ${AUTO().remarketingDias} dias — nunca para quem pediu para não receber, nem fora da área, encaminhados ou conflito de interesses.`, null,
    Object.keys(porDem).length ? Object.entries(porDem).map(([k, v]) => painel(k + ` (${v.length})`, h('div', { class: 'divide-y divide-gray-100 dark:divide-zinc-800' }, v.map(lin)))) : estadoVazio('ph:arrow-counter-clockwise-bold', 'Ninguém no Remarketing', 'Quando um contato for marcado como “Não contratou”, ele entra aqui.'),
    fora.length ? painel('Fora do Remarketing (' + fora.length + ')', lista(fora.map(c => [avatar(c.nome), h('div', { class: 'flex-1' }, link(c.nome, () => abrirFicha(c.id)), h('p', { class: 'text-[11px] text-gray-500' }, c.nao_contatar ? 'Pediu para não receber' : c.motivo_perda)), badge('Sem remarketing', 'cinza')]))) : null)
}

/* ================= PESSOAS (módulo: Funil · Clientes · Remarketing) ================= */
UI.pes = { aba: 'funil' }
VIEWS.pessoas = (p) => {
  if (p && p.aba) { UI.pes.aba = p.aba; R.p = {} }
  const A = UI.pes.aba; const el = remarketingElegiveis().filter(x => x.pronto).length
  return modulo({ titulo: 'Pessoas', sub: 'Um só cadastro, três visões: quem está em conversa (funil), quem já é cliente e quem ficou para depois (remarketing).', abasDef: [{ id: 'funil', nome: 'Funil', icone: 'ph:kanban-bold', n: DB.contatos.filter(ehLead).length }, { id: 'clientes', nome: 'Clientes', icone: 'ph:users-bold' }, { id: 'remarketing', nome: 'Remarketing', icone: 'ph:arrow-counter-clockwise-bold', n: el || null }], ativa: A, aoMudar: id => { UI.pes.aba = id; render() }, conteudo: a => VIEWS[a]() })
}
