'use strict'
/* ============ Serviços jurídicos: Demandas, Processos/Procedimentos, Partes, Documentos ============ */
UI.demandas = { f: 'ativas', q: '' }; UI.processos = { f: 'todos', nat: 'todas', q: '' }; UI.docs = { demanda: null, f: 'todos' }; UI.demDet = { aba: 'visao' }
const procRotulo = v => CRM.PROCEDIMENTOS.find(p => p.valor === v)?.rotulo || 'Sem procedimento definido'
const servicoDe = v => v ? CRM.SERVICOS.find(s => s.id === v.split('/')[0]) : null
const varianteDe = v => { const s = servicoDe(v); return s?.variantes.find(x => x.id === v.split('/')[1]) }

function abrirDemandaForm(contatoId, dm) {
  const cs = DB.contatos.filter(c => c.etapa !== 'relacionado')
  const campos = [{ chave: 'contato_id', rotulo: 'Cliente', tipo: 'select', opcoes: cs.map(c => [c.id, c.nome]), numerico: true, obrigatorio: true }, { chave: 'titulo', rotulo: 'Título da demanda', obrigatorio: true, largo: true }, { chave: 'area', rotulo: 'Área', tipo: 'select', opcoes: [['', '—'], ...Object.keys(CRM.AREAS)] }, { chave: 'tipo', rotulo: 'Atuação', tipo: 'select', opcoes: Object.entries(CRM.TIPOS_DEMANDA), dica: 'Consultiva e documental não têm processo; judicial e extrajudicial sim.' }, { chave: 'procedimento', rotulo: 'Procedimento (define as etapas e os documentos)', tipo: 'select', opcoes: [['', '— sem procedimento —'], ...CRM.PROCEDIMENTOS.map(p => [p.valor, p.rotulo])], largo: true }, { chave: 'data_abertura', rotulo: 'Abertura', tipo: 'data' }, { chave: 'observacoes', rotulo: 'Observações', tipo: 'textarea' }]
  modalForm(dm ? 'Editar demanda' : 'Nova demanda', campos, dm || { contato_id: contatoId, tipo: 'documental', data_abertura: hojeISO(), area: contato(contatoId)?.area || '' }, v => {
    if (dm) { Object.assign(dm, v); registrar(dm.contato_id, 'Anotação', 'Demanda editada: ' + dm.titulo, dm.id); salvar('demandas') } else abrirDemanda({ ...v, procedimento: v.procedimento || null })
    if (!dm) aviso('Demanda aberta; documentos do checklist criados.')
  }, { largura: 'max-w-2xl' })
}
function cartaoDemanda(x, compacto) {
  const ps = processosDe(x.id); const r = docsResumo(x.contato_id, x.id)
  return h('div', { class: 'painel !p-4 space-y-2', 'data-testid': 'demanda-card' }, h('div', { class: 'flex flex-wrap items-start justify-between gap-2' }, h('div', { class: 'min-w-0' }, h('button', { type: 'button', class: 'text-left font-semibold text-primary dark:text-cafe-creme hover:underline', onclick: () => abrirDemandaDetalhe(x.id), 'data-testid': 'abrir-demanda' }, x.titulo), h('p', { class: 'text-[11px] text-gray-500' }, [!compacto ? nomeContato(x.contato_id) : null, x.area, procRotulo(x.procedimento)].filter(Boolean).join(' · '))), h('div', { class: 'flex gap-1.5' }, badge(CRM.TIPOS_DEMANDA[x.tipo], 'cafe'), badge(CRM.STATUS_DEMANDA[x.status], x.status === 'ativo' ? 'verde' : x.status === 'suspenso' ? 'ambar' : 'cinza'))),
    h('div', { class: 'flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-gray-500' }, h('span', {}, ps.length ? plural(ps.length, 'processo/procedimento', 'processos/procedimentos') : 'Sem processo'), r.total ? h('span', {}, `${r.ok}/${r.total} documentos${r.pend ? ` · ${r.pend} obrigatório(s) pendente(s)` : ''}`) : null, x.resultado ? h('span', {}, 'Resultado: ' + CRM.RESULTADOS_DEMANDA[x.resultado]) : null))
}
VIEWS.lista_demandas = (p) => {
  if (p && p.abrir) setTimeout(() => { R.p = {}; abrirDemandaDetalhe(p.abrir) }, 0)
  const { f, q } = UI.demandas; const ok = x => !q || semAcento(x.titulo + nomeContato(x.contato_id)).includes(semAcento(q))
  const grupos = { ativas: DB.demandas.filter(x => x.status === 'ativo' && ok(x)), suspensas: DB.demandas.filter(x => x.status === 'suspenso' && ok(x)), encerradas: DB.demandas.filter(x => x.status === 'encerrado' && ok(x)), todas: DB.demandas.filter(ok) }
  return pagina('Demandas', 'Cada serviço contratado por um cliente. A demanda define as etapas, os documentos e os processos.', [btn('Nova demanda', { icone: 'ph:plus-bold', onclick: () => abrirDemandaForm(null), tid: 'nova-demanda' })],
    h('div', { class: 'flex flex-wrap items-center gap-3 justify-between' }, filtros([{ id: 'ativas', nome: `Ativas (${grupos.ativas.length})` }, { id: 'suspensas', nome: `Suspensas (${grupos.suspensas.length})` }, { id: 'encerradas', nome: `Encerradas (${grupos.encerradas.length})` }, { id: 'todas', nome: 'Todas' }], f, id => { UI.demandas.f = id; render() }), h('div', { class: 'w-full sm:w-72' }, busca(q, v => { UI.demandas.q = v; render() }, 'Buscar demanda ou cliente'))),
    grupos[f].length ? h('div', { class: 'grid gap-3 md:grid-cols-2' }, grupos[f].map(x => cartaoDemanda(x))) : estadoVazio('ph:briefcase-bold', 'Nenhuma demanda nesta visão', 'Abra uma demanda quando o cliente contratar.', btn('Nova demanda', { onclick: () => abrirDemandaForm(null) })))
}

/* ---- detalhe da demanda (modal em abas) ---- */
function abrirDemandaDetalhe(id, aba) {
  const x = demanda(id); if (!x) return; if (aba) UI.demDet.aba = aba; let m; const corpo = h('div', { 'data-testid': 'demanda-detalhe' })
  const red = () => {
    const ps = processosDe(x.id); const abasL = [{ id: 'visao', nome: 'Visão geral', icone: 'ph:squares-four-bold' }, { id: 'analise', nome: 'Análise do escritório', icone: 'ph:scales-bold' }, { id: 'processos', nome: 'Processos', icone: 'ph:gavel-bold', n: ps.length }, { id: 'partes', nome: 'Partes', icone: 'ph:users-three-bold', n: DB.partes.filter(a => a.caso_id === x.id).length }, { id: 'docs', nome: 'Documentos', icone: 'ph:files-bold', n: docsDe(x.contato_id, x.id).length }, { id: 'comunicacao', nome: 'Comunicação', icone: 'ph:chats-circle-bold', n: comunicacoesDe(x.contato_id, x.id).length || null }, { id: 'ficha', nome: 'Informações', icone: 'ph:clipboard-text-bold' }]
    corpo.replaceChildren(h('div', { class: 'flex flex-wrap items-center gap-2 mb-4' }, h('div', { class: 'min-w-0 flex-1' }, h('h3', { class: 'font-serif text-xl text-primary dark:text-zinc-100' }, x.titulo), h('p', { class: 'text-xs text-gray-500' }, nomeContato(x.contato_id) + ' · ' + procRotulo(x.procedimento))), badge(CRM.TIPOS_DEMANDA[x.tipo], 'cafe'), badge(CRM.STATUS_DEMANDA[x.status], x.status === 'ativo' ? 'verde' : 'cinza')), abas(abasL, UI.demDet.aba, i => { UI.demDet.aba = i; red() }), h('div', { class: 'mt-4' }, { visao: dVisao, analise: dAnalise, processos: dProcessos, partes: dPartes, docs: dDocs, comunicacao: (x_) => Thread(x_.contato_id, { caso: x_.id }), ficha: dFicha }[UI.demDet.aba](x, red)))
  }
  REDES.add(red); m = modal({ titulo: 'Demanda', largura: 'max-w-4xl', corpo, aoFechar: () => { REDES.delete(red); render() } }); red()
}
function dVisao(x, red) {
  const sv = servicoDe(x.procedimento); const vr = varianteDe(x.procedimento); const feitas = (x.fases_ok || [])
  const encerrar = () => modalForm('Encerrar demanda', [{ chave: 'resultado', rotulo: 'Resultado', tipo: 'select', opcoes: Object.entries(CRM.RESULTADOS_DEMANDA), obrigatorio: true }], { resultado: 'exito' }, v => encerrarDemanda(x, v.resultado), { rotulo: 'Encerrar' })
  return h('div', { class: 'space-y-4' }, h('div', { class: 'flex flex-wrap gap-2' }, btn('Editar', { mini: true, tipo: 'sec', icone: 'ph:pencil-simple-bold', onclick: () => abrirDemandaForm(x.contato_id, x), tid: 'demanda-editar' }), x.status === 'ativo' ? [btn('Suspender', { mini: true, tipo: 'sec', onclick: () => { x.status = 'suspenso'; registrar(x.contato_id, 'Anotação', 'Demanda suspensa: ' + x.titulo, x.id); salvar('demandas'); red() } }), btn('Encerrar', { mini: true, icone: 'ph:flag-checkered-bold', onclick: encerrar, tid: 'demanda-encerrar' })] : btn('Reabrir', { mini: true, tipo: 'sec', onclick: () => { x.status = 'ativo'; x.resultado = null; x.data_encerramento = null; const c = contato(x.contato_id); if (c && c.etapa === 'concluido') moverEtapa(c, 'ativo'); registrar(x.contato_id, 'Anotação', 'Demanda reaberta: ' + x.titulo, x.id); salvar('demandas'); red() } }), btn('Tarefa', { mini: true, tipo: 'fantasma', icone: 'ph:check-square-bold', onclick: () => editarTarefa(null, { contato_id: x.contato_id, caso_id: x.id }) }), btn('Excluir', { mini: true, tipo: 'fantasma', icone: 'ph:trash-bold', tid: 'demanda-excluir', onclick: () => confirmar('Excluir demanda?', 'Remove a demanda, seus documentos e partes. O CRM bloqueia se houver processos.', 'Excluir', () => { const r = excluirDemanda(x); if (r.erro) aviso(r.erro, 'erro'); else { document.querySelector('[data-testid=fechar]')?.click(); render(); aviso('Demanda excluída.') } }) })),
    h('div', { class: 'grid gap-3 sm:grid-cols-3' }, campoLeitura('Área', x.area), campoLeitura('Abertura', dataLonga(x.data_abertura)), campoLeitura('Encerramento / resultado', x.data_encerramento ? `${dataLonga(x.data_encerramento)} · ${CRM.RESULTADOS_DEMANDA[x.resultado] || ''}` : null), h('div', { class: 'sm:col-span-3' }, campoLeitura('Observações', x.observacoes))),
    painel('Linha do tempo da demanda', (() => { const t = linhaDoTempo({ caso_id: x.id }).slice(0, 8); return t.length ? h('ol', { class: 'relative border-l border-gray-200 dark:border-zinc-700 ml-2 space-y-3', 'data-testid': 'tempo-demanda' }, t.map(a => h('li', { class: 'pl-4 relative' }, h('span', { class: 'absolute -left-[5px] top-1.5 w-2.5 h-2.5 rounded-full bg-secondary' }), h('p', { class: 'text-[11px] text-gray-400' }, `${a.titulo} · ${dataHora(a.quando)}`), h('p', { class: 'text-sm whitespace-pre-line line-clamp-3' }, a.texto)))) : h('p', { class: 'text-sm text-gray-500' }, 'Sem registros ainda.') })(), h('div', { class: 'mt-2' }, btn('Resumir demanda com IA', { mini: true, tipo: 'sec', icone: 'ph:sparkle-bold', onclick: () => resumirDemanda(x), tid: 'ia-resumir-demanda', class: 'ia-btn' }))), sv && vr ? painel(`Etapas do procedimento — ${sv.nome} (${vr.nome})`, h('ol', { class: 'space-y-2' }, vr.fases.map((f, i) => h('li', { class: 'flex items-start gap-2.5' }, h('input', { type: 'checkbox', class: 'mt-1 accent-[#6f5636]', checked: feitas.includes(i), 'aria-label': f.titulo, onclick: () => { x.fases_ok = feitas.includes(i) ? feitas.filter(k => k !== i) : [...feitas, i]; registrar(x.contato_id, 'Anotação', `Etapa ${feitas.includes(i) ? 'reaberta' : 'concluída'}: ${f.titulo}`, x.id); salvar('demandas'); red() } }), h('div', {}, h('p', { class: 'text-sm font-semibold ' + (feitas.includes(i) ? 'line-through text-gray-400' : '') }, f.titulo), h('p', { class: 'text-xs text-gray-500' }, f.texto))))), h('p', { class: 'text-[11px] text-gray-400 mt-2' }, `${feitas.length}/${vr.fases.length} etapas concluídas · texto do Padrão Operacional do escritório.`)) : alerta('info', null, 'Defina o procedimento (ex.: Divórcio — Extrajudicial) para ver as etapas e gerar o checklist de documentos.'))
}
function dAnalise(x, red) {
  const campos = [['analise', 'Análise (fundamentos)'], ['fatos', 'Fatos'], ['estrategia', 'Estratégia'], ['riscos', 'Riscos'], ['conclusao', 'Conclusão']]; const notas = DB.notas.filter(n => n.caso_id === x.id).sort((a, b) => b.created_at.localeCompare(a.created_at))
  const nota = h('textarea', { class: 'modal-input', rows: 2, placeholder: 'Nova anotação datada (o raciocínio evolui; nada se sobrescreve)…', 'data-testid': 'nota-texto' }); const tipoN = h('select', { class: 'selecao' }, Object.entries(CRM.TIPOS_NOTA_DEMANDA).map(([k, v]) => h('option', { value: k }, v)))
  const decisao = h('div', { class: 'grid gap-2 sm:grid-cols-3' }, Object.entries(CRM.DECISOES_DEMANDA).map(([k, d]) => h('button', { type: 'button', class: 'rounded-2xl border p-3 text-left ' + (x.decisao === k ? 'border-primary bg-primary/5 dark:bg-white/5 ring-1 ring-primary' : 'border-gray-200 dark:border-zinc-700 hover:border-primary'), onclick: () => { x.decisao = k; registrar(x.contato_id, 'Anotação', 'Decisão da análise: ' + d.nome, x.id); salvar('demandas'); red() }, 'data-testid': 'decisao-' + k }, h('p', { class: 'font-semibold text-sm' }, d.nome), h('p', { class: 'text-[11px] text-gray-500' }, d.dica))))
  const refs = {}
  return h('div', { class: 'space-y-4' }, h('h4', { class: 'section-label' }, 'Decisão'), decisao, h('h4', { class: 'section-label' }, 'Análise profissional'), campos.map(([k, rot]) => { const t = h('textarea', { class: 'modal-input', rows: 3, 'aria-label': rot }, ''); t.value = x[k] || ''; refs[k] = t; return h('label', { class: 'block' }, rotuloCampo(rot), t) }), btn('Salvar análise', { icone: 'ph:floppy-disk-bold', tid: 'salvar-analise', onclick: () => { campos.forEach(([k]) => { x[k] = refs[k].value.trim() || null }); registrar(x.contato_id, 'Peça / pesquisa', 'Análise do escritório atualizada.', x.id); salvar('demandas'); aviso('Análise salva.'); red() } }),
    h('h4', { class: 'section-label' }, 'Anotações datadas'), h('div', { class: 'flex gap-2 items-end' }, h('div', { class: 'flex-1' }, nota), tipoN, btn('Adicionar', { mini: true, onclick: () => { if (!nota.value.trim()) return; DB.notas.push({ id: proximoId('notas'), caso_id: x.id, tipo: tipoN.value, texto: nota.value.trim(), created_at: agora(), autor_nome: CONFIG.perfil.nome }); salvar('notas'); red() } })), notas.length ? lista(notas.map(n => [h('div', { class: 'flex-1' }, h('p', { class: 'text-[11px] text-gray-400' }, `${CRM.TIPOS_NOTA_DEMANDA[n.tipo]} · ${dataHora(n.created_at)} · ${n.autor_nome}`), h('p', {}, n.texto))])) : null)
}
function dProcessos(x, red) {
  const ps = processosDe(x.id)
  return h('div', { class: 'space-y-3' }, h('div', { class: 'flex justify-end' }, btn('Registrar processo/procedimento', { mini: true, icone: 'ph:plus-bold', onclick: () => editarProcesso(null, { caso_id: x.id }), tid: 'novo-processo' })), ps.length ? ps.map(p => cartaoProcesso(p)) : estadoVazio('ph:gavel-bold', 'Sem processo ou procedimento', 'Demandas consultivas e documentais não precisam. Registre quando houver processo judicial ou procedimento em cartório.'))
}
function dPartes(x, red) {
  const ps = DB.partes.filter(a => a.caso_id === x.id); const jud = processosDe(x.id).some(p => p.natureza === 'judicial'); const ext = processosDe(x.id).some(p => p.natureza === 'extrajudicial')
  const form = pt => modalForm(pt ? 'Editar parte' : 'Nova parte / interessado', [{ chave: 'contato_id', rotulo: 'Pessoa já cadastrada', tipo: 'select', opcoes: [['', '— digitar manualmente —'], ...DB.contatos.map(c => [c.id, c.nome])], numerico: true, dica: 'Ligar a uma pessoa evita duplicar cadastro.' }, { chave: 'nome', rotulo: 'Nome', obrigatorio: true }, { chave: 'papel', rotulo: 'Papel', tipo: 'select', opcoes: CRM.papeisSugeridos(jud, ext, ps.map(a => a.papel)) }, { chave: 'polo', rotulo: 'Polo (judicial)', tipo: 'select', opcoes: [['', '—'], ...Object.entries(CRM.POLOS_PARTE)] }, { chave: 'documento', rotulo: 'Documento' }, { chave: 'telefone', rotulo: 'Telefone' }, { chave: 'email', rotulo: 'E-mail' }, { chave: 'observacao', rotulo: 'Observação', tipo: 'textarea' }], pt || { papel: 'Parte contrária' }, v => { if (v.contato_id && !v.nome) v.nome = nomeContato(v.contato_id); if (pt) Object.assign(pt, v); else DB.partes.push({ id: proximoId('partes'), created_at: agora(), caso_id: x.id, processo_id: null, ...v }); salvar('partes') }, { extra: pt ? btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Remover parte?', pt.nome, 'Remover', () => { DB.partes = DB.partes.filter(a => a !== pt); salvar('partes'); red() }) }) : null })
  return h('div', { class: 'space-y-3' }, h('div', { class: 'flex justify-end' }, btn('Adicionar parte', { mini: true, icone: 'ph:plus-bold', onclick: () => form(null), tid: 'nova-parte' })), ps.length ? tabela([{ nome: 'Nome', cel: a => a.contato_id ? link(a.nome, () => abrirFicha(a.contato_id)) : a.nome }, { nome: 'Papel', cel: a => a.papel }, { nome: 'Polo', cel: a => a.polo ? CRM.POLOS_PARTE[a.polo] : '—' }, { nome: 'Contato', cel: a => a.telefone ? telefoneFormatado(a.telefone) : (a.email || '—') }], ps, { clique: form }) : estadoVazio('ph:users-three-bold', 'Nenhuma parte cadastrada', 'Parte contrária, herdeiros, cônjuge, interessados.'))
}
const dDocs = (x, red) => painelDocumentos(x, red)
const dFicha = (x, red) => fichaPerguntasDemanda(x, red)

/* ================= PROCESSOS / PROCEDIMENTOS ================= */
function cartaoProcesso(p) {
  const jud = p.natureza === 'judicial'; const e = DB.etapas.filter(x => x.processo_id === p.id); const atual = jud ? p.fase : (CRM.etapaAtual(e) || p.fase)
  const pend = DB.pendencias.filter(x => x.processo_id === p.id && !x.resolvida_em).length
  return h('div', { class: 'painel !p-4 space-y-2', 'data-testid': 'processo-card' }, h('div', { class: 'flex flex-wrap items-start justify-between gap-2' }, h('div', { class: 'min-w-0' }, h('button', { type: 'button', class: 'text-left font-semibold text-primary dark:text-cafe-creme hover:underline', onclick: () => abrirProcesso(p.id), 'data-testid': 'abrir-processo' }, p.numero || p.tipo_procedimento || 'Sem número'), h('p', { class: 'text-[11px] text-gray-500' }, [nomeContato(p.contato_id), p.orgao, p.comarca && p.uf ? `${p.comarca}/${p.uf}` : null].filter(Boolean).join(' · '))), h('div', { class: 'flex gap-1.5' }, badge(CRM.NATUREZAS_PROCESSO[p.natureza], jud ? 'roxo' : 'azul'), badge(CRM.STATUS_DEMANDA[p.status], p.status === 'ativo' ? 'verde' : 'cinza'))), h('p', { class: 'text-xs text-gray-600 dark:text-zinc-300' }, 'Fase: ', h('b', {}, atual || '—'), pend ? h('span', { class: 'ml-2 text-amber-700 dark:text-amber-300' }, `· ${pend} pendência(s)`) : null))
}
VIEWS.processos = (p) => {
  if (p && p.abrir) setTimeout(() => { R.p = {}; abrirProcesso(p.abrir) }, 0)
  const { f, nat, q } = UI.processos; const itens = DB.processos.filter(x => (f === 'todos' || x.status === f) && (nat === 'todas' || x.natureza === nat) && (!q || semAcento((x.numero || '') + nomeContato(x.contato_id) + (x.orgao || '')).includes(semAcento(q))))
  return pagina('Processos e procedimentos', 'Processo judicial (por fases e movimentações) ou procedimento extrajudicial (por etapas formais e pendências).', [btn('Registrar', { icone: 'ph:plus-bold', onclick: () => editarProcesso(null), tid: 'registrar-processo' })],
    h('div', { class: 'flex flex-wrap items-center gap-3 justify-between' }, h('div', { class: 'flex flex-wrap gap-3' }, filtros([{ id: 'todos', nome: 'Todos' }, { id: 'ativo', nome: 'Ativos' }, { id: 'encerrado', nome: 'Encerrados' }], f, id => { UI.processos.f = id; render() }), filtros([{ id: 'todas', nome: 'Judicial + extrajudicial' }, { id: 'judicial', nome: 'Judiciais' }, { id: 'extrajudicial', nome: 'Extrajudiciais' }], nat, id => { UI.processos.nat = id; render() })), h('div', { class: 'w-full sm:w-72' }, busca(q, v => { UI.processos.q = v; render() }, 'Número, cliente ou órgão'))),
    itens.length ? h('div', { class: 'grid gap-3 md:grid-cols-2' }, itens.map(cartaoProcesso)) : estadoVazio('ph:gavel-bold', 'Nenhum processo nesta visão'))
}
function editarProcesso(p, padrao = {}) {
  const base = p || { natureza: 'judicial', status: 'ativo', data_inicio: hojeISO(), uf: 'BA', tribunal: 'tjba', ...padrao }
  const campos = [{ chave: 'caso_id', rotulo: 'Demanda', tipo: 'select', opcoes: DB.demandas.map(d => [d.id, d.titulo]), numerico: true, obrigatorio: true }, { chave: 'natureza', rotulo: 'Natureza', tipo: 'select', opcoes: Object.entries(CRM.NATUREZAS_PROCESSO) }, { chave: 'numero', rotulo: 'Número CNJ (judicial)', dica: 'Validado pelo dígito verificador.', valida: (v, o) => o.natureza === 'judicial' && v && !CRM.numeroCnjValido(v) ? 'Número CNJ inválido (dígito verificador não confere).' : null }, { chave: 'tipo_procedimento', rotulo: 'Tipo de procedimento (extrajudicial)', tipo: 'select', opcoes: [['', '—'], ...CRM.TIPOS_PROCEDIMENTO_EXTRAJUDICIAL.map(t => t.nome)] }, { chave: 'orgao', rotulo: 'Órgão / vara / cartório' }, { chave: 'comarca', rotulo: 'Comarca' }, { chave: 'uf', rotulo: 'UF', tipo: 'select', opcoes: CRM.UFS }, { chave: 'tribunal', rotulo: 'Calendário forense', tipo: 'select', opcoes: Object.entries(CRM.TRIBUNAIS) }, { chave: 'valor', rotulo: 'Valor da causa', tipo: 'numero' }, { chave: 'data_inicio', rotulo: 'Início', tipo: 'data' }, { chave: 'observacoes', rotulo: 'Observações', tipo: 'textarea' }]
  modalForm(p ? 'Editar' : 'Registrar processo ou procedimento', campos, base, v => {
    const d = demanda(v.caso_id); v.contato_id = d.contato_id; if (v.numero && v.natureza === 'judicial') v.numero = CRM.formatarCnj(v.numero)
    if (p) Object.assign(p, v); else {
      const n = { id: proximoId('processos'), created_at: agora(), fase: v.natureza === 'judicial' ? CRM.FASES_PROCESSUAIS[0] : CRM.FASES_EXTRAJUDICIAIS[0], status: 'ativo', link: null, data_encerramento: null, desfecho: null, responsavel_nome: CONFIG.perfil.nome, ...v }; DB.processos.push(n)
      if (n.natureza === 'extrajudicial') { const t = CRM.tipoProcedimentoPorNome(n.tipo_procedimento) || CRM.sugerirTipoProcedimento(d.procedimento?.split('/')[0]); (t?.etapas || []).forEach((e, i) => DB.etapas.push({ id: proximoId('etapas'), processo_id: n.id, ordem: i + 1, titulo: e.titulo, status: 'pendente', data_prevista: null, concluida_em: null, observacao: null })); salvar('etapas') }
      if (d.tipo === 'consultivo' || d.tipo === 'documental') { d.tipo = n.natureza; registrar(d.contato_id, 'Anotação', `Atuação da demanda passou a ${CRM.TIPOS_DEMANDA[d.tipo]} (processo registrado).`, d.id); salvar('demandas') }
      registrar(d.contato_id, 'Anotação', 'Processo/procedimento registrado: ' + (n.numero || n.tipo_procedimento || n.orgao), d.id)
    }
    salvar('processos')
  }, { largura: 'max-w-2xl' })
}
function abrirProcesso(id) {
  const p = processo(id); if (!p) return; let m; const corpo = h('div', { 'data-testid': 'processo-detalhe' }); const jud = p.natureza === 'judicial'
  const red = () => {
    const movs = DB.movimentacoes.filter(x => x.processo_id === p.id).sort((a, b) => b.data.localeCompare(a.data)); const etapas = DB.etapas.filter(x => x.processo_id === p.id).sort((a, b) => a.ordem - b.ordem); const pends = DB.pendencias.filter(x => x.processo_id === p.id); const prazos = DB.compromissos.filter(x => x.processo_id === p.id)
    const concluir = () => modalForm('Concluir ' + (jud ? 'processo' : 'procedimento'), [{ chave: 'desfecho', rotulo: 'Desfecho', tipo: 'select', opcoes: CRM.desfechosDa(p.natureza).map(d => d.valor), obrigatorio: true }], {}, v => { p.status = 'encerrado'; p.desfecho = v.desfecho; p.data_encerramento = hojeISO(); registrar(p.contato_id, 'Anotação', 'Concluído: ' + v.desfecho, p.caso_id); salvar('processos') }, { rotulo: 'Concluir' })
    corpo.replaceChildren(
      h('div', { class: 'flex flex-wrap items-center gap-2 mb-3' }, h('div', { class: 'min-w-0 flex-1' }, h('h3', { class: 'font-serif text-xl text-primary dark:text-zinc-100 break-all' }, p.numero || p.tipo_procedimento || 'Sem número'), h('p', { class: 'text-xs text-gray-500' }, `${nomeContato(p.contato_id)} · ${nomeDemanda(p.caso_id)}`)), badge(CRM.NATUREZAS_PROCESSO[p.natureza], jud ? 'roxo' : 'azul'), badge(CRM.STATUS_DEMANDA[p.status], p.status === 'ativo' ? 'verde' : 'cinza')),
      h('div', { class: 'flex flex-wrap gap-2 mb-4' }, btn('Editar', { mini: true, tipo: 'sec', icone: 'ph:pencil-simple-bold', onclick: () => editarProcesso(p) }), p.status === 'ativo' ? btn('Concluir', { mini: true, icone: 'ph:flag-checkered-bold', onclick: concluir, tid: 'processo-concluir' }) : btn('Reabrir', { mini: true, tipo: 'sec', onclick: () => { p.status = 'ativo'; p.desfecho = null; p.data_encerramento = null; salvar('processos'); red() } }), btn('Excluir', { mini: true, tipo: 'fantasma', icone: 'ph:trash-bold', onclick: () => confirmar('Excluir ' + (jud ? 'processo' : 'procedimento') + '?', 'Remove movimentações, etapas e pendências; os prazos ficam sem vínculo.', 'Excluir', () => { excluirProcesso(p); document.querySelector('[data-testid=fechar]')?.click(); render() }) })),
      h('div', { class: 'grid gap-3 sm:grid-cols-3 mb-4' }, campoLeitura('Órgão', p.orgao), campoLeitura('Comarca', p.comarca ? `${p.comarca}/${p.uf}` : null), campoLeitura('Responsável', p.responsavel_nome), campoLeitura('Início', dataLonga(p.data_inicio)), campoLeitura('Valor', p.valor ? brl(p.valor) : null), campoLeitura('Desfecho', p.desfecho)),
      jud ? h('div', { class: 'space-y-4' }, painel('Fase', h('div', { class: 'flex flex-wrap gap-1.5' }, CRM.FASES_PROCESSUAIS.map(f => h('button', { type: 'button', class: 'filtro ' + (p.fase === f ? 'filtro-ativo' : ''), onclick: () => { p.fase = f; registrar(p.contato_id, 'Anotação', 'Fase: ' + f, p.caso_id); salvar('processos'); red() } }, f)))),
        painel('Movimentações', h('div', { class: 'flex justify-end mb-2' }, btn('Registrar andamento', { mini: true, icone: 'ph:plus-bold', tid: 'nova-mov', onclick: () => modalForm('Registrar andamento', [{ chave: 'data', rotulo: 'Data', tipo: 'data', obrigatorio: true }, { chave: 'tipo', rotulo: 'Tipo', tipo: 'select', opcoes: CRM.TIPOS_MOVIMENTACAO }, { chave: 'texto', rotulo: 'O que aconteceu', tipo: 'textarea', obrigatorio: true }], { data: hojeISO(), tipo: 'Andamento' }, v => { DB.movimentacoes.push({ id: proximoId('movimentacoes'), created_at: agora(), processo_id: p.id, ...v }); registrar(p.contato_id, 'Peça / pesquisa', `Movimentação (${v.tipo}): ${v.texto.slice(0, 80)}`, p.caso_id); salvar('movimentacoes') }) })), movs.length ? h('ol', { class: 'relative border-l border-gray-200 dark:border-zinc-700 ml-2 space-y-3' }, movs.map(mv => h('li', { class: 'pl-4 relative' }, h('span', { class: 'absolute -left-[5px] top-1.5 w-2.5 h-2.5 rounded-full bg-secondary' }), h('p', { class: 'text-[11px] text-gray-400' }, `${mv.tipo} · ${dataLonga(mv.data)}`), h('p', { class: 'text-sm' }, mv.texto)))) : estadoVazio('ph:list-bullets-bold', 'Sem movimentações')))
        : h('div', { class: 'space-y-4' }, painel(`Etapas do procedimento (${etapas.filter(e => e.status !== 'pendente').length}/${etapas.length})`, etapas.length ? h('ol', { class: 'space-y-1.5' }, etapas.map(e => h('li', { class: 'flex items-center gap-2.5 text-sm' }, h('input', { type: 'checkbox', class: 'accent-[#6f5636]', checked: e.status === 'concluida', 'aria-label': e.titulo, onclick: () => { e.status = e.status === 'concluida' ? 'pendente' : 'concluida'; e.concluida_em = e.status === 'concluida' ? agora() : null; p.fase = CRM.etapaAtual(etapas) || 'Concluídas'; salvar('etapas'); salvar('processos'); red() } }), h('span', { class: 'flex-1 ' + (e.status === 'concluida' ? 'line-through text-gray-400' : '') }, e.titulo), e.status === 'pendente' && CRM.etapaAtual(etapas) === e.titulo ? badge('Em andamento', 'azul') : null, e.status === 'dispensada' ? badge('Dispensada', 'cinza') : null, e.status === 'pendente' ? btn('Dispensar', { mini: true, tipo: 'fantasma', onclick: () => { e.status = 'dispensada'; salvar('etapas'); red() } }) : null))) : estadoVazio('ph:list-checks-bold', 'Sem etapas', 'Escolha o tipo de procedimento para carregar as etapas.')),
          painel('Pendências / exigências', h('div', { class: 'flex justify-end mb-2' }, btn('Nova pendência', { mini: true, icone: 'ph:plus-bold', tid: 'nova-pendencia', onclick: () => modalForm('Nova pendência', [{ chave: 'descricao', rotulo: 'O que trava o andamento', obrigatorio: true, largo: true }, { chave: 'aguardando', rotulo: 'Quem precisa resolver', tipo: 'select', opcoes: Object.entries(CRM.AGUARDANDO_PENDENCIA) }, { chave: 'prazo', rotulo: 'Prazo', tipo: 'data' }], { aguardando: 'cliente' }, v => { DB.pendencias.push({ id: proximoId('pendencias'), processo_id: p.id, resolvida_em: null, observacao: null, created_at: agora(), ...v }); salvar('pendencias') }) })), pends.length ? lista(pends.map(x => [h('input', { type: 'checkbox', class: 'mt-1 accent-[#6f5636]', checked: !!x.resolvida_em, 'aria-label': 'Resolver: ' + x.descricao, onclick: () => { x.resolvida_em = x.resolvida_em ? null : agora(); salvar('pendencias'); red() } }), h('div', { class: 'flex-1 ' + (x.resolvida_em ? 'line-through text-gray-400' : '') }, x.descricao, h('p', { class: 'text-[11px] text-gray-500 no-underline' }, 'Aguardando: ' + CRM.AGUARDANDO_PENDENCIA[x.aguardando])), x.prazo && !x.resolvida_em ? badgeData(x.prazo) : null])) : estadoVazio('ph:check-circle-bold', 'Sem pendências'))),
      painel('Prazos e audiências do processo', h('div', { class: 'flex justify-end mb-2' }, btn('Novo prazo', { mini: true, icone: 'ph:plus-bold', onclick: () => editarCompromisso(null, { tipo: 'prazo', contato_id: p.contato_id, caso_id: p.caso_id, processo_id: p.id }) })), prazos.length ? h('div', { class: 'divide-y divide-gray-100 dark:divide-zinc-800' }, prazos.map(x => linhaPrazo(x))) : estadoVazio('ph:hourglass-high-bold', 'Sem prazos vinculados')))
  }
  REDES.add(red); m = modal({ titulo: jud ? 'Processo judicial' : 'Procedimento extrajudicial', largura: 'max-w-4xl', corpo, aoFechar: () => { REDES.delete(red); render() } }); red()
}

/* ================= DOCUMENTOS ================= */
const DOC_CICLO = { pendente: 'recebido', recebido: 'conferido', conferido: 'pendente', dispensado: 'pendente', rascunho: 'final', final: 'rascunho' }
const DOC_COR = { pendente: 'ambar', recebido: 'azul', conferido: 'verde', dispensado: 'cinza', rascunho: 'cinza', final: 'verde' }
function painelDocumentos(x, red) {
  const docs = docsDe(x.contato_id, x.id).sort((a, b) => a.ordem - b.ordem); const sol = docs.filter(d => d.origem !== 'produzido'); const prod = docs.filter(d => d.origem === 'produzido'); const r = docsResumo(x.contato_id, x.id); const c = contato(x.contato_id)
  const mover = (d, status) => { d.status = status; d.atualizado_em = agora(); registrar(d.contato_id, 'Documento recebido', `${d.descricao}: ${CRM.STATUS_DOCUMENTO[status]}`, d.caso_id); salvar('documentos'); (red || render)() }
  const linha = d => h('div', { class: 'flex flex-wrap items-center gap-2 py-2.5', 'data-testid': 'documento' }, h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'text-sm font-semibold' }, d.descricao, d.obrigatorio ? h('span', { class: 'text-danger ml-1', title: 'Obrigatório' }, '*') : null), d.arquivo_nome || d.arquivo_url ? h('a', { href: linkOk(d.arquivo_url) || null, target: '_blank', rel: 'noopener', class: 'text-[11px] text-primary dark:text-cafe-creme underline' }, d.arquivo_nome || d.arquivo_url) : h('p', { class: 'text-[11px] text-gray-400' }, 'Sem arquivo vinculado')),
    h('select', { class: 'text-xs rounded-full border border-gray-200 dark:border-zinc-700 bg-transparent px-2 py-1', 'aria-label': 'Status de ' + d.descricao, onchange: ev => mover(d, ev.target.value), 'data-testid': 'doc-status' }, Object.entries(CRM.STATUS_DOCUMENTO).filter(([k]) => d.origem === 'produzido' ? ['rascunho', 'final'].includes(k) : !['rascunho', 'final'].includes(k)).map(([k, t]) => h('option', { value: k, selected: d.status === k }, t))), badge(CRM.STATUS_DOCUMENTO[d.status], DOC_COR[d.status]),
    btnIcone('ph:link-bold', 'Vincular arquivo (link)', () => modalForm('Vincular arquivo', [{ chave: 'arquivo_nome', rotulo: 'Nome do arquivo', dica: 'Padrão: ' + CRM.nomeArquivoPadrao({ data: hojeISO(), contatoId: d.contato_id, tipo: 'DOC', descricao: d.descricao.slice(0, 20), extensao: 'pdf' }) }, { chave: 'arquivo_url', rotulo: 'Link (Drive, etc.)', valida: v => v && !linkOk(v) ? 'Link inválido (use https://…).' : null }], d, v => { Object.assign(d, v, { arquivo_provedor: v.arquivo_url ? 'link' : null, arquivo_em: agora() }); if (v.arquivo_url && d.status === 'pendente') d.status = 'recebido'; salvar('documentos') })), btnIcone('ph:trash-bold', 'Remover item', () => confirmar('Remover documento?', d.descricao, 'Remover', () => { DB.documentos = DB.documentos.filter(z => z !== d); salvar('documentos'); (red || render)() })))
  return h('div', { class: 'space-y-4' }, h('div', { class: 'flex flex-wrap items-center gap-3' }, h('div', { class: 'flex-1 min-w-[200px]' }, h('div', { class: 'flex justify-between text-xs text-gray-500 mb-1' }, h('span', {}, `${r.ok} de ${r.total} recebidos`), r.pend ? h('span', { class: 'text-amber-700 dark:text-amber-300' }, `${r.pend} obrigatório(s) pendente(s)`) : h('span', { class: 'text-emerald-700 dark:text-emerald-300' }, 'Obrigatórios em dia')), h('div', { class: 'h-2 rounded-full bg-gray-200 dark:bg-zinc-800 overflow-hidden' }, h('div', { class: 'h-full bg-primary dark:bg-cafe-claro', style: `width:${r.total ? Math.round(r.ok / r.total * 100) : 0}%` }))), btn('Cobrar pendentes', { mini: true, tipo: 'sec', icone: 'ph:chat-circle-text-bold', onclick: () => abrirMensagem(x.contato_id, '/documentos') }), btn('Adicionar documento', { mini: true, icone: 'ph:plus-bold', tid: 'novo-doc', onclick: () => modalForm('Novo documento', [{ chave: 'descricao', rotulo: 'Descrição', obrigatorio: true, largo: true }, { chave: 'origem', rotulo: 'Origem', tipo: 'select', opcoes: [['solicitado', 'Pedido ao cliente'], ['produzido', 'Produzido pelo escritório']] }, { chave: 'obrigatorio', rotulo: 'Obrigatório', tipo: 'check' }], { origem: 'solicitado' }, v => { DB.documentos.push({ id: proximoId('documentos'), contato_id: x.contato_id, caso_id: x.id, processo_id: null, parte_id: null, arquivo_provedor: null, arquivo_ref: null, arquivo_url: null, arquivo_nome: null, arquivo_em: null, status: v.origem === 'produzido' ? 'rascunho' : 'pendente', observacao: null, ordem: DB.documentos.length + 1, atualizado_em: agora(), ...v, obrigatorio: !!v.obrigatorio }); salvar('documentos') }) })),
    h('h4', { class: 'section-label' }, 'Pedidos ao cliente'), sol.length ? h('div', { class: 'divide-y divide-gray-100 dark:divide-zinc-800' }, sol.map(linha)) : estadoVazio('ph:file-dashed-bold', 'Sem documentos solicitados', 'Demandas contratadas geram o checklist da área automaticamente.'),
    prod.length ? [h('h4', { class: 'section-label' }, 'Produzidos pelo escritório'), h('div', { class: 'divide-y divide-gray-100 dark:divide-zinc-800' }, prod.map(linha))] : null,
    h('h4', { class: 'section-label' }, 'Pasta do cliente (Drive)'), h('div', { class: 'text-xs text-gray-600 dark:text-zinc-300 space-y-1' }, h('p', {}, c?.drive_pasta_url ? 'Pasta vinculada.' : 'Ainda sem pasta vinculada.'), h('ul', { class: 'grid sm:grid-cols-2 gap-x-4 list-disc pl-5' }, CRM.ESTRUTURA_PASTA_CLIENTE.map(p => h('li', {}, p.nome))), c ? btn(c.drive_pasta_url ? 'Trocar link da pasta' : 'Vincular pasta do Drive', { mini: true, tipo: 'sec', icone: 'ph:folder-bold', onclick: () => modalForm('Pasta do cliente no Drive', [{ chave: 'drive_pasta_url', rotulo: 'Link da pasta (https://…)', obrigatorio: true, valida: v => v && !linkOk(v) ? 'Link inválido.' : null }], c, v => { c.drive_pasta_url = linkOk(v.drive_pasta_url); registrar(c.id, 'Anotação', 'Pasta do Drive vinculada.'); salvar('contatos') }) }) : null, c?.drive_pasta_url ? h('a', { href: c.drive_pasta_url, target: '_blank', rel: 'noopener', class: 'text-primary dark:text-cafe-creme underline' }, 'Abrir pasta no Drive') : null, h('p', { class: 'text-[11px] text-gray-400' }, 'O CRM guarda só o link; os arquivos ficam no Drive. Padrão de nome: ' + CRM.nomeArquivoPadrao({ data: hojeISO(), contatoId: x.contato_id, tipo: 'PETICAO', descricao: 'resumo', versao: 1, extensao: 'docx' }))))
}
VIEWS.documentos = (p) => {
  if (p && p.demanda) { UI.docs.demanda = p.demanda; R.p = {} }
  const ativos = DB.demandas.filter(x => x.tipo !== 'consultivo'); const sel = demanda(UI.docs.demanda) || ativos[0]
  const select = h('select', { class: 'selecao', 'aria-label': 'Demanda', 'data-testid': 'doc-demanda', onchange: ev => { UI.docs.demanda = Number(ev.target.value); render() } }, ativos.map(x => h('option', { value: x.id, selected: sel && x.id === sel.id }, `${nomeContato(x.contato_id)} — ${x.titulo}`)))
  const resumo = ativos.map(x => ({ x, r: docsResumo(x.contato_id, x.id) }))
  return pagina('Documentos', 'Checklist por demanda: pedido → recebido → conferido. O checklist do atendimento só lê o resultado.', null,
    grade(3, resumo.slice(0, 3).map(({ x, r }) => kpi(nomeContato(x.contato_id), `${r.ok}/${r.total}`, r.pend ? `${r.pend} obrigatório(s) pendente(s)` : 'obrigatórios em dia', () => { UI.docs.demanda = x.id; render() }))),
    h('div', {}, select), sel ? painel(sel.titulo, painelDocumentos(sel, render)) : estadoVazio('ph:files-bold', 'Nenhuma demanda com documentos'))
}

/* ================= DEMANDAS (módulo: Demandas · Processos · Documentos · Petições iniciais) ================= */
UI.dm = { aba: 'demandas' }
VIEWS.demandas = (p) => {
  if (p && p.aba) UI.dm.aba = p.aba; else if (p && p.abrir) UI.dm.aba = 'demandas'
  const A = UI.dm.aba; const pend = DB.demandas.filter(x => x.status === 'ativo' && x.tipo !== 'consultivo' && docsResumo(x.contato_id, x.id).pend).length; const ini = CRM.INI.seloIniciais(DB.iniciais, hojeISO())
  return modulo({ titulo: 'Demandas', sub: 'O serviço contratado e tudo que nasce dele: processos e procedimentos, documentos e petições iniciais.', abasDef: [{ id: 'demandas', nome: 'Demandas', icone: 'ph:briefcase-bold', n: DB.demandas.filter(x => x.status === 'ativo' && x.tipo !== 'consultivo').length }, { id: 'processos', nome: 'Processos e procedimentos', icone: 'ph:gavel-bold' }, { id: 'documentos', nome: 'Documentos', icone: 'ph:files-bold', n: pend || null }, { id: 'iniciais', nome: 'Petições iniciais', icone: 'ph:file-text-bold', n: ini || null }], ativa: A, aoMudar: id => { UI.dm.aba = id; render() }, conteudo: a => VIEWS[{ demandas: 'lista_demandas', processos: 'processos', documentos: 'documentos', iniciais: 'iniciais' }[a]](p) })
}
