'use strict'
/* ============ Dinheiro: Financeiro (honorários, contas, gestão) e Relatórios ============ */
UI.fin = { aba: 'honorarios' }; UI.rel = { aba: 'visao' }
const corHon = s => s === 'Pago' ? 'verde' : s === 'Contratado' ? 'azul' : s === 'Cancelado' ? 'cinza' : 'ambar'
function editarHonorario(x, padrao = {}) {
  const base = x || { tipo: 'Contrato fixo', status: 'Proposta', forma_pagamento: 'PIX', parcelas: 1, ...padrao }
  modalForm(x ? 'Editar honorário' : 'Novo honorário', [{ chave: 'contato_id', rotulo: 'Cliente', tipo: 'select', opcoes: DB.contatos.filter(c => c.etapa !== 'relacionado').map(c => [c.id, c.nome]), numerico: true, obrigatorio: true }, { chave: 'caso_id', rotulo: 'Demanda', tipo: 'select', opcoes: opcoesDemandas(), numerico: true, dica: 'Cada demanda tem a sua proposta.' }, { chave: 'tipo', rotulo: 'Tipo', tipo: 'select', opcoes: CRM.TIPOS_HONORARIO }, { chave: 'status', rotulo: 'Status', tipo: 'select', opcoes: CRM.STATUS_HONORARIO }, { chave: 'valor', rotulo: 'Valor total (R$)', tipo: 'numero', obrigatorio: true, dica: 'Piso de referência: ' + brl(pisoPreco().minimo) + ' (veja os parâmetros em Financeiro)' }, { chave: 'entrada', rotulo: 'Entrada / arranque (R$)', tipo: 'numero' }, { chave: 'mensalidade', rotulo: 'Mensalidade (R$)', tipo: 'numero' }, { chave: 'exito_pct', rotulo: 'Êxito (%)', tipo: 'numero' }, { chave: 'forma_pagamento', rotulo: 'Forma de pagamento' }, { chave: 'parcelas', rotulo: 'Parcelas', tipo: 'numero' }, { chave: 'observacoes', rotulo: 'Observações', tipo: 'textarea' }], base, v => {
    if (v.valor != null && v.valor < 0) return { erro: 'Valor não pode ser negativo.' }
    if (x) { Object.assign(x, v, { updated_at: agora() }); registrar(x.contato_id, 'Anotação', `Honorário ${x.status}: ${brl(x.valor)}`, x.caso_id) } else { const n = { id: proximoId('honorarios'), created_at: agora(), updated_at: agora(), ...v }; DB.honorarios.push(n); registrar(n.contato_id, 'Anotação', `Honorário registrado (${n.status}): ${brl(n.valor)}`, n.caso_id) }
    salvar('honorarios')
  }, { largura: 'max-w-2xl', extra: x ? [btn('Gerar contrato (.doc)', { tipo: 'sec', icone: 'ph:file-doc-bold', tid: 'gerar-contrato', onclick: () => gerarContrato(x) }), btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Excluir honorário?', brl(x.valor), 'Excluir', () => { DB.honorarios = DB.honorarios.filter(z => z !== x); salvar('honorarios') }) })] : null })
}
function editarLancamento(l) {
  const tipoSel = l?.tipo || 'receber'
  modalForm(l ? 'Editar lançamento' : 'Novo lançamento', [{ chave: 'tipo', rotulo: 'Tipo', tipo: 'select', opcoes: [['receber', 'A receber'], ['pagar', 'A pagar']] }, { chave: 'descricao', rotulo: 'Descrição', obrigatorio: true, largo: true }, { chave: 'categoria', rotulo: 'Categoria', tipo: 'select', opcoes: [...new Set([...CRM.CATEGORIAS_LANCAMENTO.receber, ...CRM.CATEGORIAS_LANCAMENTO.pagar])] }, { chave: 'valor', rotulo: 'Valor (R$)', tipo: 'numero', obrigatorio: true, valida: v => v != null && v <= 0 ? 'Valor deve ser maior que zero.' : null }, { chave: 'vencimento', rotulo: 'Vencimento', tipo: 'data', obrigatorio: true }, { chave: 'pago_em', rotulo: 'Pago em', tipo: 'data' }, { chave: 'contato_id', rotulo: 'Cliente', tipo: 'select', opcoes: opcoesContatos(), numerico: true }, { chave: 'recorrente', rotulo: 'Recorrente (mensal)', tipo: 'check' }], l || { tipo: tipoSel, categoria: 'Honorários', vencimento: hojeISO() }, v => { if (l) Object.assign(l, v); else DB.lancamentos.push({ id: proximoId('lancamentos'), caso_id: null, honorario_id: null, observacao: null, ...v }); salvar('lancamentos') }, { largura: 'max-w-2xl', extra: l ? btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Excluir lançamento?', l.descricao, 'Excluir', () => { DB.lancamentos = DB.lancamentos.filter(z => z !== l); salvar('lancamentos') }) }) : null })
}
VIEWS.financeiro = (p) => {
  if (p && p.aba) { UI.fin.aba = p.aba; R.p = {} }
  const A = UI.fin.aba; const rec = DB.honorarios.filter(h_ => CRM.STATUS_RECEITA.includes(h_.status)); const contratado = rec.reduce((s, x) => s + x.valor, 0); const pago = DB.honorarios.filter(x => x.status === 'Pago').reduce((s, x) => s + x.valor, 0); const prop = DB.honorarios.filter(x => x.status === 'Proposta').reduce((s, x) => s + x.valor, 0)
  const aReceber = DB.lancamentos.filter(l => l.tipo === 'receber' && !l.pago_em); const aPagar = DB.lancamentos.filter(l => l.tipo === 'pagar' && !l.pago_em)
  const g = CONFIG.gestao; const custoHora = g.horas_produtivas_mes ? g.pro_labore / g.horas_produtivas_mes : 0; const minimo = CRM.precoMinimo(g.horas_estimadas || 0, custoHora, g.margem_desejada || 0)
  let corpo
  if (A === 'honorarios') corpo = [grade(4, kpi('Contratado + pago', brl(contratado)), kpi('Pago', brl(pago)), kpi('Em proposta', brl(prop), 'ainda não fechado'), kpi('Honorários', DB.honorarios.length)), paramPreco(), DB.honorarios.length ? tabela([{ nome: 'Cliente', cel: x => link(nomeContato(x.contato_id), () => abrirFicha(x.contato_id)) }, { nome: 'Demanda', cel: x => x.caso_id ? nomeDemanda(x.caso_id) : '—' }, { nome: 'Tipo', cel: x => x.tipo }, { nome: 'Valor', cel: x => brl2(x.valor), cls: 'tabular-nums text-right' }, { nome: 'Status', cel: x => badge(x.status, corHon(x.status)) }], DB.honorarios, { clique: editarHonorario }) : estadoVazio('ph:wallet-bold', 'Nenhum honorário')]
  else if (A === 'contas') {
    const col = (titulo, itens, tipo) => painel(`${titulo} · ${brl(itens.reduce((s, l) => s + l.valor, 0))}`, itens.length ? h('div', { class: 'divide-y divide-gray-100 dark:divide-zinc-800' }, itens.sort((a, b) => a.vencimento.localeCompare(b.vencimento)).map(l => h('div', { class: 'flex items-center gap-2 py-2.5', 'data-testid': 'lancamento' }, h('div', { class: 'min-w-0 flex-1' }, h('button', { type: 'button', class: 'text-left text-sm font-semibold hover:underline truncate block max-w-full', onclick: () => editarLancamento(l) }, l.descricao), h('p', { class: 'text-[11px] text-gray-500' }, l.categoria + (l.recorrente ? ' · recorrente' : ''))), h('b', { class: 'tabular-nums text-sm' }, brl2(l.valor)), badgeData(l.vencimento, 'Vencido'), btnIcone('ph:check-bold', 'Marcar como pago', () => { l.pago_em = hojeISO(); salvar('lancamentos'); render(); aviso('Baixa registrada.') })))) : estadoVazio('ph:check-circle-bold', 'Nada em aberto'))
    corpo = [h('div', { class: 'flex justify-end gap-2' }, btn('Novo lançamento', { icone: 'ph:plus-bold', onclick: () => editarLancamento(null), tid: 'novo-lancamento' })), h('div', { class: 'grid gap-5 lg:grid-cols-2' }, col('A receber', aReceber, 'receber'), col('A pagar', aPagar, 'pagar')), grade(3, kpi('Saldo em caixa', brl(g.saldo_caixa)), kpi('A receber (aberto)', brl(aReceber.reduce((s, l) => s + l.valor, 0))), kpi('A pagar (aberto)', brl(aPagar.reduce((s, l) => s + l.valor, 0))))]
  }
  return pagina('Financeiro', 'Honorários por demanda, contas a pagar e receber, e o piso de preço.', A === 'honorarios' ? [btn('Novo honorário', { icone: 'ph:plus-bold', onclick: () => editarHonorario(null), tid: 'novo-honorario' })] : null, abas([{ id: 'honorarios', nome: 'Honorários', icone: 'ph:handshake-bold' }, { id: 'contas', nome: 'Contas', icone: 'ph:receipt-bold' }], A, id => { UI.fin.aba = id; render() }), ...corpo)
}

/* ================= RELATÓRIOS ================= */
VIEWS.relatorios = (p) => {
  if (p && p.aba) { UI.rel.aba = p.aba; R.p = {} }
  const A = UI.rel.aba; let corpo
  if (A === 'visao') {
    const leads = DB.contatos.filter(c => c.etapa !== 'relacionado'); const ganhos = leads.filter(c => CRM.ETAPAS_GANHAS.includes(c.etapa)); const conv = leads.length ? Math.round(ganhos.length / leads.length * 100) : 0
    const enc = DB.demandas.filter(x => x.status === 'encerrado' && x.resultado); const exito = enc.filter(x => ['exito', 'acordo', 'parcial'].includes(x.resultado)).length
    const nps = DB.contatos.filter(c => c.nps != null); const npsMed = nps.length ? (nps.reduce((s, c) => s + c.nps, 0) / nps.length).toFixed(1) : '—'
    const porOrigem = {}; leads.forEach(c => { const k = c.origem || 'Sem origem'; (porOrigem[k] = porOrigem[k] || { t: 0, g: 0 }).t++; if (CRM.ETAPAS_GANHAS.includes(c.etapa)) porOrigem[k].g++ })
    const porMotivo = {}; DB.contatos.filter(c => c.etapa === 'perdido').forEach(c => { porMotivo[c.motivo_perda || '—'] = (porMotivo[c.motivo_perda || '—'] || 0) + 1 })
    const barra = (rot, n, max, extra) => h('div', { class: 'flex items-center gap-3 text-sm' }, h('span', { class: 'w-44 shrink-0 truncate text-gray-600 dark:text-zinc-300' }, rot), h('span', { class: 'flex-1 h-4 rounded-full bg-gray-100 dark:bg-zinc-800 overflow-hidden' }, h('span', { class: 'block h-full bg-primary dark:bg-cafe-claro rounded-full', style: `width:${Math.round(n / Math.max(1, max) * 100)}%` })), h('b', { class: 'w-20 text-right text-xs tabular-nums' }, extra || n))
    corpo = [grade(4, kpi('Conversão em cliente', conv + '%', `${ganhos.length} de ${leads.length} contatos`), kpi('Taxa de êxito', enc.length ? Math.round(exito / enc.length * 100) + '%' : '—', `${enc.length} demandas encerradas`), kpi('NPS médio', npsMed, `${nps.length} respostas`), kpi('Demandas ativas', DB.demandas.filter(x => x.status === 'ativo' && x.tipo !== 'consultivo').length)), h('div', { class: 'grid gap-5 lg:grid-cols-2' }, painel('Origem dos contatos', h('div', { class: 'space-y-2' }, Object.entries(porOrigem).sort((a, b) => b[1].t - a[1].t).map(([k, v]) => barra(k, v.t, leads.length, `${v.g}/${v.t} fecharam`)))), painel('Por que não contrataram', Object.keys(porMotivo).length ? h('div', { class: 'space-y-2' }, Object.entries(porMotivo).map(([k, n]) => barra(k, n, 5))) : estadoVazio('ph:chart-bar-bold', 'Sem dados')))]
  } else if (A === 'qualidade') {
    const ativos = DB.demandas.filter(x => x.status === 'ativo' && x.tipo !== 'consultivo')
    const novaRev = x => { const itens = {}; const f = h('div', { class: 'space-y-2' }, CRM.ITENS_REVISAO.map(i => { itens[i.chave] = 'ok'; return h('div', { class: 'flex flex-wrap items-center gap-2 justify-between text-sm' }, h('span', {}, i.rotulo), h('div', { class: 'flex gap-1' }, [['ok', 'OK'], ['falha', 'Falha'], ['na', 'N/A']].map(([v, t]) => h('label', { class: 'cursor-pointer' }, h('input', { type: 'radio', name: 'rev-' + i.chave, value: v, checked: v === 'ok', class: 'peer sr-only', onclick: () => { itens[i.chave] = v } }), h('span', { class: 'filtro inline-block peer-checked:bg-primary peer-checked:text-white peer-checked:border-primary' }, t))))) })); const plano = h('textarea', { class: 'modal-input', rows: 2, placeholder: 'Plano de ação (obrigatório se houver falha)' })
      modal({ titulo: 'Revisão — ' + x.titulo, largura: 'max-w-xl', corpo: [f, h('div', { class: 'mt-3' }, plano)], rodape: fechar => [btn('Cancelar', { tipo: 'sec', onclick: fechar }), btn('Registrar revisão', { tid: 'revisao-salvar', onclick: () => { const falhas = Object.entries(itens).filter(([, v]) => v === 'falha'); if (falhas.length && !plano.value.trim()) { aviso('Descreva o plano de ação para as falhas.', 'erro'); return } CONFIG.revisoes.unshift({ id: Date.now(), created_at: agora(), caso_id: x.id, itens: { ...itens }, aprovado: !falhas.length, plano_acao: plano.value.trim() || null }); falhas.forEach(([k]) => DB.tarefas.push({ id: proximoId('tarefas'), titulo: `Corrigir (${CRM.ITENS_REVISAO.find(i => i.chave === k).rotulo}) — ${x.titulo}`, descricao: plano.value.trim(), concluida: false, prazo: somarDias(hojeISO(), 3), prioridade: 'alta', contato_id: x.contato_id, caso_id: x.id, processo_id: null, created_at: agora(), updated_at: agora() })); salvar('tarefas'); salvar('config'); fechar(); render(); aviso(falhas.length ? 'Falhas viraram tarefas com prazo.' : 'Revisão aprovada.') } })] }) }
    corpo = [painel('Revisão por amostragem', h('p', { class: 'text-xs text-gray-500 mb-3' }, 'Revise demandas por amostragem. Falha vira tarefa com prazo.'), ativos.length ? lista(ativos.map(x => [h('div', { class: 'flex-1 min-w-0' }, h('p', { class: 'font-semibold truncate' }, x.titulo), h('p', { class: 'text-[11px] text-gray-500' }, (() => { const u = CONFIG.revisoes.find(r => r.caso_id === x.id); return u ? 'Última revisão: ' + dataLonga(u.created_at) + (u.aprovado ? ' (aprovada)' : ' (com falhas)') : 'Nunca revisada' })())), btn('Revisar', { mini: true, tipo: 'sec', onclick: () => novaRev(x), tid: 'revisar' })])) : estadoVazio('ph:shield-check-bold', 'Sem demandas ativas')), painel('Histórico de revisões', CONFIG.revisoes.length ? lista(CONFIG.revisoes.map(r => [h('div', { class: 'flex-1' }, h('p', { class: 'font-semibold' }, nomeDemanda(r.caso_id)), h('p', { class: 'text-[11px] text-gray-500' }, dataHora(r.created_at) + (r.plano_acao ? ' · ' + r.plano_acao : ''))), badge(r.aprovado ? 'Aprovada' : 'Com falhas', r.aprovado ? 'verde' : 'vermelho')])) : estadoVazio('ph:clock-counter-clockwise-bold', 'Nenhuma revisão ainda'))]
  } else {
    const grupos = CRM.ETAPAS.filter(e => e.aberta).map(e => ({ e, cs: DB.contatos.filter(c => c.etapa === e.id) }))
    corpo = [painel('Tempo médio na etapa', tabela([{ nome: 'Etapa', cel: g => g.e.nome }, { nome: 'Contatos', cel: g => g.cs.length }, { nome: 'Dias médios', cel: g => g.cs.length ? Math.round(g.cs.reduce((s, c) => s + diasEntre(diaDe(c.etapa_desde), hojeISO()), 0) / g.cs.length) : '—' }], grupos)), painel('Carteira por classificação', grade(4, Object.entries(CRM.CLASSIFICACOES).map(([k, v]) => kpi(v.nome, DB.contatos.filter(c => c.classificacao === k).length, v.dica))))]
  }
  return pagina('Relatórios', 'Indicadores do escritório: funil, resultados, satisfação e qualidade.', null, abas([{ id: 'visao', nome: 'Visão geral', icone: 'ph:chart-bar-bold' }, { id: 'funil', nome: 'Funil e carteira', icone: 'ph:funnel-bold' }, { id: 'qualidade', nome: 'Qualidade', icone: 'ph:shield-check-bold' }], A, id => { UI.rel.aba = id; render() }), ...corpo)
}

/* Piso de preço: parâmetros recolhíveis na aba Honorários; o piso aparece também ao registrar um honorário (onde a decisão é tomada). */
function pisoPreco(horas) { const g = CONFIG.gestao; const custoHora = g.horas_produtivas_mes ? g.pro_labore / g.horas_produtivas_mes : 0; return { custoHora, minimo: CRM.precoMinimo(horas ?? g.horas_estimadas ?? 0, custoHora, g.margem_desejada || 0) } }
function paramPreco() {
  const g = CONFIG.gestao; const campo = (k, rot) => h('label', { class: 'block' }, rotuloCampo(rot), h('input', { class: 'modal-input', inputmode: 'decimal', value: g[k] ?? '', 'aria-label': rot, 'data-testid': 'gestao-' + k, onchange: ev => { g[k] = numOuNull(ev.target.value) ?? 0; salvar('config'); render() } })); const pp = pisoPreco()
  return h('details', { class: 'painel', 'data-testid': 'param-preco' }, h('summary', { class: 'cursor-pointer font-semibold text-sm text-primary dark:text-zinc-100' }, `Piso de preço: ${brl(pp.minimo)} para ${g.horas_estimadas || 0} h (custo ${brl2(pp.custoHora)}/h)`), h('div', { class: 'grid gap-3 sm:grid-cols-2 lg:grid-cols-3 mt-3' }, campo('pro_labore', 'Pró-labore desejado (R$/mês)'), campo('horas_produtivas_mes', 'Horas produtivas por mês'), campo('margem_desejada', 'Margem desejada (%)'), campo('horas_estimadas', 'Horas estimadas da demanda'), campo('saldo_caixa', 'Saldo em caixa (R$)')), h('p', { class: 'text-[11px] text-gray-400 mt-2' }, 'Aparece como referência quando você registra um honorário. A âncora de valor vem da análise: o que está em jogo.'))
}
