'use strict'
/* ============ Formulários: lista, construtor (estilo Google Forms), prévia, preenchimento público, respostas ligadas ao cadastro ============
   Regras (tipos, operadores, lógica condicional, visibilidade, validação) = shared/data/formulario.ts REAL, via CRM.*. */
UI.form = { aba: 'formularios', ctx: 'todos', rq: '', rf: '', rde: '', rate: '' }
const novoIdPergunta = () => { const m = Math.max(0, ...DB.formularios.flatMap(f => f.secoes.flatMap(s => s.itens.map(i => i.pergunta_id)))); CONFIG.seq.pergunta = Math.max(CONFIG.seq.pergunta || 0, m) + 1; return CONFIG.seq.pergunta }
const token = () => Array.from(crypto.getRandomValues(new Uint8Array(12)), b => b.toString(16).padStart(2, '0')).join('')

/* ---------- sementes ---------- */
function semearFormularios() {
  let n = 0; const P = (texto, tipo, opcoes, ajuda, obrigatoria, mostrar_se) => ({ pergunta_id: ++n, texto, tipo, opcoes: opcoes || [], ajuda: ajuda || null, obrigatoria: !!obrigatoria, mostrar_se: mostrar_se || null })
  // Formulário REAL (migração 20260929180000 + 20260929260000): perguntas da análise da consulta, contexto demanda.
  const dados = [P('O que o cliente trouxe', 'texto_longo', [], 'Com as palavras dele(a).'), P('Causa raiz (5 porquês)', 'texto_longo', [], 'Pergunte "por quê" até chegar no motivo real; um por linha.'), P('O que o cliente quer que mude', 'texto_longo'),
    P('Viabilidade — verificações feitas', 'checklist', ['Está na área de atuação do escritório', 'Prescrição e decadência verificadas', 'Foro/competência e via (judicial ou cartório) definidos', 'Legitimidade das partes confirmada', 'Provas e documentos suficientes (ou obtêníveis)', 'Sem conflito de interesses', 'Expectativa do cliente é realista e foi alinhada', 'Falei com quem decide (e sobre quem paga)'], 'Marque o que já foi checado antes de propor.'),
    P('Riscos e ressalvas', 'texto_longo', [], 'Vão por escrito na proposta.'), P('Capacidade de pagamento', 'selecao_unica', ['Paga à vista ou em poucas parcelas', 'Precisa de parcelamento', 'Condição restrita (avaliar gratuidade/indicar Defensoria)', 'Ainda não sei']), P('O que está em jogo', 'texto_curto', [], 'Ex.: a meação do apartamento; 12 meses de pensão.'), P('Valor aproximado em jogo (R$)', 'numero'), P('Decisão da consulta', 'selecao_unica', ['Viável', 'Viável com ressalvas', 'Não viável'])]
  // Exemplos (montados com o mesmo motor): pré-consulta com lógica condicional e dados para o contrato.
  const tf = P('Tem filhos menores?', 'sim_nao', [], null, true)
  const pre = [P('Conte um pouco da sua situação', 'texto_longo', [], 'Escreva do seu jeito, sem pressa.', true), tf, P('Quantos filhos?', 'numero', [], null, true, { juntar: 'e', regras: [{ pergunta_id: tf.pergunta_id, operador: 'igual', valor: 'Sim' }] }), P('Como prefere ser contatada?', 'selecao_multipla', ['WhatsApp', 'Ligação', 'E-mail'], null, false)]
  const reg = P('Regime de bens do casamento', 'lista_suspensa', ['Comunhão parcial', 'Comunhão universal', 'Separação total', 'Participação final nos aquestos', 'Não sei'], null, false)
  const dc = [P('Nome completo', 'texto_curto', [], null, true), P('Telefone', 'telefone', [], 'WhatsApp com DDD', true), P('E-mail', 'email'), P('Estado civil', 'lista_suspensa', CRM.ESTADOS_CIVIS, null, true), reg, P('Profissão', 'texto_curto'), P('Possui imóveis?', 'sim_nao')]
  const sec = (titulo, itens, descricao, mostrar_se) => ({ id: null, titulo, descricao: descricao || null, mostrar_se: mostrar_se || null, itens })
  return [
    { id: 1, nome: 'Dados da consulta', descricao: 'Dados coletados na consulta (perguntas). A análise profissional do escritório fica na própria demanda.', contexto: 'demanda', procedimentos: [], ativo: true, situacao: 'publicado', updated_at: agora(), secoes: [sec('Dados da consulta', dados)] },
    { id: 2, nome: 'Pré-consulta (exemplo)', descricao: 'Exemplo com lógica condicional: “Quantos filhos?” só aparece se a resposta anterior for Sim.', contexto: 'consulta', procedimentos: [], ativo: true, situacao: 'publicado', updated_at: agora(), secoes: [sec('Sua situação', pre.slice(0, 2), 'Para chegar à consulta já com o essencial.'), sec('Detalhes', pre.slice(2), null, null)] },
    { id: 3, nome: 'Dados para o contrato (exemplo)', descricao: 'Reúne os dados formais para procuração e contrato, depois de fechar.', contexto: 'cliente', procedimentos: [], ativo: true, situacao: 'publicado', updated_at: agora(), secoes: [sec('Identificação', dc.slice(0, 3)), sec('Família e patrimônio', dc.slice(3), null, { juntar: 'e', regras: [{ pergunta_id: dc[0].pergunta_id, operador: 'preenchida' }] })] },
  ]
}
function semearEnvios() {
  return [
    { id: 1, created_at: agora(-60 * 24 * 3), formulario_id: 2, contato_id: 3, token: 'a1b2c3d4e5f6a1b2c3d4e5f6', expira_em: agora(60 * 24 * 27), visualizado_em: agora(-60 * 24 * 2), respondido_em: agora(-60 * 24 * 2), status: 'respondido', resumo: 'Vamos nos casar em três meses e queremos separação total de bens.', respostas: { 5: 'Sim', 6: '1', 7: ['WhatsApp'] } },
    { id: 2, created_at: agora(-60 * 24), formulario_id: 2, contato_id: 4, token: 'f6e5d4c3b2a1f6e5d4c3b2a1', expira_em: agora(60 * 24 * 29), visualizado_em: agora(-60 * 5), respondido_em: null, status: 'visualizado', resumo: null, respostas: {} },
    { id: 3, created_at: agora(-60 * 24 * 6), formulario_id: 3, contato_id: 9, token: '0a1b2c3d4e5f0a1b2c3d4e5f', expira_em: agora(60 * 24 * 24), visualizado_em: null, respondido_em: null, status: 'enviado', resumo: null, respostas: {} },
  ]
}
const formularioDe = id => por('formularios', id)
const itensDe = f => f.secoes.flatMap(s => s.itens)
const formsDoEscopo = (escopo, proc) => DB.formularios.filter(f => situacaoForm(f) === 'publicado' && CRM.escopoDoContexto(f.contexto) === escopo && (escopo === 'cliente' || CRM.procedimentoCasa(f.procedimentos, proc)))
const bancoPerguntas = () => { const m = new Map(); DB.formularios.forEach(f => itensDe(f).forEach(i => { if (!m.has(i.pergunta_id)) m.set(i.pergunta_id, { ...i, formularios: [] }); m.get(i.pergunta_id).formularios.push(f.nome) })); return [...m.values()] }
const contarRespostas = pid => DB.contatos.filter(c => c.respostas && c.respostas[pid] != null).length + DB.demandas.filter(d => d.respostas && d.respostas[pid] != null).length
const textoResposta = v => respostaVazia(v) ? '(sem resposta)' : textoEspecial(v)

/* ---------- componente de preenchimento (mesmo do construtor "Visualizar", da página pública e da ficha) ---------- */
function Preenchimento({ secoes, valores, aoMudar, aoPasso, arquivos, rotuloEnviar = 'Enviar respostas', aoEnviar, modoFicha = false, enviando = false, slotInicio, slotFim }) {
  const raiz = h('form', { class: 'space-y-5', novalidate: true, 'data-testid': 'preenchimento' }); let passo = 0; const erros = {}; raiz.__arquivos = arquivos || {}
  const uteis = () => secoes.map(s => ({ ...s, itens: s.itens.filter(i => !CRM.tipoInterno(i.tipo) || modoFicha) }))
  const vis = () => CRM.calcularVisibilidade(uteis(), valores)
  const passos = () => { const v = vis(); return uteis().map((s, i) => ({ s, i })).filter(x => v.secoes.has(x.i) && x.s.itens.some(p => v.perguntas.has(p.pergunta_id))) }
  const definir = (p, v) => { delete erros[p.pergunta_id]; valores[p.pergunta_id] = v === '' ? null : v; aoMudar && aoMudar(p, valores[p.pergunta_id]); const a = document.activeElement; const k = a && a.getAttribute && a.getAttribute('data-pid'); desenhar(); if (k) { const el = raiz.querySelector(`[data-pid="${k}"]`); if (el && el.tagName !== 'SELECT' && el.type !== 'radio' && el.type !== 'checkbox') { el.focus(); try { el.setSelectionRange(el.value.length, el.value.length) } catch (e) { /* tipo sem seleção */ } } } }
  const campo = p => {
    const v = valores[p.pergunta_id] ?? null; const txt = typeof v === 'string' ? v : ''; const lst = Array.isArray(v) ? v : []; const a = { 'data-pid': p.pergunta_id }
    const entrada = (tipo, extra) => { const e = h('input', { type: tipo, class: 'modal-input', value: txt, ...a, ...extra }); e.addEventListener('input', () => { valores[p.pergunta_id] = e.value === '' ? null : e.value; aoMudar && aoMudar(p, valores[p.pergunta_id]); delete erros[p.pergunta_id]; clearTimeout(e.__t); e.__t = setTimeout(() => definir(p, e.value), 350) }); return e }
    if (p.tipo === 'texto_longo') { const e = h('textarea', { class: 'modal-input', rows: 4, ...a }); e.value = txt; e.addEventListener('input', () => { valores[p.pergunta_id] = e.value || null; aoMudar && aoMudar(p, valores[p.pergunta_id]); clearTimeout(e.__t); e.__t = setTimeout(() => definir(p, e.value), 350) }); return e }
    if (p.tipo === 'numero') return entrada('number', { step: 'any', inputmode: 'decimal' })
    if (p.tipo === 'data') return entrada('date'); if (p.tipo === 'email') return entrada('email'); if (p.tipo === 'telefone') return entrada('tel')
    if (p.tipo === 'sim_nao' || p.tipo === 'selecao_unica') return h('div', { class: 'flex flex-col gap-1.5 text-sm ' + (p.tipo === 'sim_nao' ? 'sm:flex-row sm:gap-5' : '') }, (p.tipo === 'sim_nao' ? ['Sim', 'Não'] : p.opcoes).map(o => h('label', { class: 'flex items-center gap-2 cursor-pointer' }, h('input', { type: 'radio', name: 'p' + p.pergunta_id + (modoFicha ? 'f' : ''), checked: v === o, class: 'accent-[#6f5636]', onclick: () => definir(p, o), 'data-testid': 'op-' + p.pergunta_id + '-' + o }), o)))
    if (p.tipo === 'lista_suspensa') { const s = h('select', { class: 'modal-input', ...a }, h('option', { value: '' }, 'Escolha…'), p.opcoes.map(o => h('option', { value: o, selected: v === o }, o))); s.addEventListener('change', () => definir(p, s.value)); return s }
    if (p.tipo === 'selecao_multipla' || p.tipo === 'checklist') return h('div', { class: 'flex flex-col gap-1.5 text-sm' }, p.opcoes.map(o => h('label', { class: 'flex items-center gap-2 cursor-pointer' }, h('input', { type: 'checkbox', checked: lst.includes(o), class: 'accent-[#6f5636]', onclick: () => definir(p, lst.includes(o) ? lst.filter(x => x !== o) : [...lst, o]), 'data-testid': 'op-' + p.pergunta_id + '-' + o }), o)))
    const esp = campoEspecial(p, { v, definir: x => definir(p, x), silencioso: x => { delete erros[p.pergunta_id]; valores[p.pergunta_id] = respostaVazia(x) ? null : x; aoMudar && aoMudar(p, valores[p.pergunta_id]) }, arquivos: raiz.__arquivos }); if (esp) return esp
    return entrada('text')
  }
  const validar = () => {
    const v = vis(); let primeiro = null
    for (const { s, i } of passos()) for (const p of s.itens) { if (!v.perguntas.has(p.pergunta_id)) continue; const val = valores[p.pergunta_id]; const vazio = respostaVazia(val)
      let msg = null; if (p.obrigatoria && vazio && !CRM.tipoInterno(p.tipo)) msg = 'Resposta obrigatória.'; else if (!vazio && p.tipo === 'email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val)) msg = 'E-mail inválido.'; else if (!vazio && p.tipo === 'telefone' && String(val).replace(/\D/g, '').length < 10) msg = 'Telefone incompleto (com DDD).'; else if (!vazio && p.tipo === 'numero' && !Number.isFinite(Number(String(val).replace(',', '.')))) msg = 'Informe um número.'
      if (!msg && !vazio) msg = validarEspecial(p, val); if (msg) { erros[p.pergunta_id] = msg; primeiro = primeiro ?? i } }
    return primeiro
  }
  function desenhar() {
    const ps = passos(); if (passo > ps.length - 1) passo = Math.max(0, ps.length - 1); const v = vis(); raiz.replaceChildren()
    if (passo === 0 && slotInicio) raiz.append(slotInicio())
    const blocos = modoFicha ? ps : ps.slice(passo, passo + 1)
    if (!modoFicha && ps.length > 1) raiz.append(h('div', { class: 'flex items-center gap-2 text-xs text-gray-500' }, h('div', { class: 'flex-1 h-1.5 rounded-full bg-gray-200 dark:bg-zinc-800 overflow-hidden' }, h('div', { class: 'h-full bg-secondary transition-all', style: `width:${Math.round((passo + 1) / ps.length * 100)}%` })), h('span', { 'data-testid': 'passo-info' }, `Etapa ${passo + 1} de ${ps.length}`)))
    blocos.forEach(({ s }) => raiz.append(h('section', { class: modoFicha ? 'space-y-4' : 'card space-y-5', 'data-testid': 'secao-' + s.titulo }, s.titulo || s.descricao ? h('header', {}, h(modoFicha ? 'h4' : 'h2', { class: modoFicha ? 'section-label' : 'text-xl text-primary dark:text-zinc-100' }, s.titulo), s.descricao ? h('p', { class: 'text-sm text-gray-500 mt-0.5' }, s.descricao) : null) : null, s.itens.filter(p => v.perguntas.has(p.pergunta_id)).map(p => h('div', { class: 'campo', 'data-testid': 'pergunta-' + p.texto }, h('span', { class: 'rotulo' }, p.texto, p.obrigatoria ? h('b', { class: 'text-danger' }, ' *') : null), p.ajuda ? h('small', { class: 'text-xs text-gray-400 -mt-1' }, p.ajuda) : null, campo(p), erros[p.pergunta_id] ? h('p', { class: 'text-xs text-danger', role: 'alert' }, erros[p.pergunta_id]) : null)))))
    if (!ps.length) raiz.append(h('p', { class: 'text-sm text-gray-400' }, 'Este formulário ainda não tem perguntas visíveis.'))
    if (slotFim && passo >= ps.length - 1) raiz.append(slotFim())
    if (!modoFicha) raiz.append(h('div', { class: 'flex items-center gap-3' }, passo > 0 ? btn('Voltar', { tipo: 'sec', tid: 'voltar', onclick: () => { passo--; desenhar() } }) : null, h('button', { type: 'submit', class: 'rounded-full bg-primary text-white px-6 py-2.5 text-xs font-semibold uppercase tracking-wider disabled:opacity-40', disabled: enviando, 'data-testid': 'avancar' }, passo >= ps.length - 1 ? rotuloEnviar : 'Continuar')))
  }
  raiz.addEventListener('submit', ev => { ev.preventDefault(); const ps = passos(); const e = validar(); if (e != null) { const idx = ps.findIndex(x => x.i === e); if (idx >= 0 && !modoFicha) passo = idx; desenhar(); return } if (passo < ps.length - 1) { passo++; aoPasso && aoPasso(passo); desenhar(); window.scrollTo(0, 0); return } aoEnviar && aoEnviar() })
  desenhar(); raiz.__validar = validar; raiz.__redesenhar = desenhar; return raiz
}

/* ---------- ficha: respostas ligadas ao cadastro (cliente e demanda) ---------- */
function blocoFicha(forms, alvo, red, titulo) {
  alvo.respostas = alvo.respostas || {}
  if (!forms.length) return estadoVazio('ph:clipboard-text-bold', 'Nenhum formulário ativo para esta ficha', 'Crie ou ative um formulário em Formulários.', btn('Ir para Formulários', { onclick: () => ir('formularios') }))
  return h('div', { class: 'space-y-5' }, forms.map(f => { const salvarDebounced = () => { clearTimeout(f.__t); f.__t = setTimeout(() => { salvar(alvo.titulo ? 'demandas' : 'contatos') }, 300) }; return painel(f.nome + (titulo ? '' : ''), f.descricao ? h('p', { class: 'text-xs text-gray-500 mb-3' }, f.descricao) : null, Preenchimento({ secoes: f.secoes, valores: alvo.respostas, modoFicha: true, aoMudar: () => { alvo.respostas_em = agora(); salvarDebounced() } })) }))
}
function fichaPerguntasDemanda(x, red) { const forms = formsDoEscopo('demanda', x.procedimento); return h('div', { class: 'space-y-3' }, h('p', { class: 'text-xs text-gray-500' }, 'Perguntas do serviço desta demanda. As respostas ficam aqui, sem copiar dados.'), blocoFicha(forms, x, red, true)) }

/* ---------- aplicar respostas recebidas no cadastro ---------- */

/* ================= PÁGINA PÚBLICA (/f/token) ================= */

/* ================= GERENCIADOR (lista + respostas) ================= */
function novoFormulario() {
  let ctx = 'cliente'; const nome = h('input', { class: 'modal-input', placeholder: 'Ex.: Dados familiares', 'data-testid': 'novo-nome' }); const grupo = h('div', { class: 'grid gap-2' })
  const des = () => grupo.replaceChildren(...Object.entries(CRM.CONTEXTOS).map(([k, c]) => h('label', { class: 'flex items-start gap-3 rounded-2xl border p-3 cursor-pointer ' + (ctx === k ? 'border-primary bg-primary/5' : 'border-gray-200 dark:border-zinc-700') }, h('input', { type: 'radio', name: 'ctx', class: 'mt-1 accent-[#6f5636]', checked: ctx === k, onclick: () => { ctx = k; des() }, 'data-testid': 'novo-ctx-' + k }), h('span', {}, h('b', { class: 'text-sm' }, c.nome), h('span', { class: 'block text-xs text-gray-500' }, c.dica)))))
  des()
  modal({ titulo: 'Novo formulário', largura: 'max-w-lg', corpo: h('div', { class: 'space-y-4' }, h('p', { class: 'text-xs text-gray-500' }, 'Você monta as perguntas na próxima tela.'), h('label', { class: 'block' }, rotuloCampo('Título'), nome), h('div', {}, rotuloCampo('Onde este formulário vale?'), grupo)), rodape: f => [btn('Cancelar', { tipo: 'sec', onclick: f }), btn('Criar e montar', { icone: 'ph:arrow-right-bold', tid: 'novo-criar', onclick: () => { const id = proximoId('formularios'); DB.formularios.push({ id, nome: nome.value.trim() || 'Formulário sem título', descricao: null, contexto: ctx, procedimentos: [], ativo: true, situacao: 'publicado', updated_at: agora(), secoes: [{ id: null, titulo: 'Seção 1', descricao: null, mostrar_se: null, itens: [] }] }); auditar('criar_formulario', nome.value); salvar('formularios'); f(); ir('formularios', { editar: id }) } })] })
}
function duplicarForm(f) { const id = proximoId('formularios'); const c = clonar(f); c.id = id; c.nome = f.nome + ' (cópia)'; c.updated_at = agora(); const mapa = {}; c.secoes.forEach(s => s.itens.forEach(i => { const novo = novoIdPergunta(); mapa[i.pergunta_id] = novo; i.pergunta_id = novo })); c.secoes.forEach(s => { const rm = o => { if (o) o.regras.forEach(r => { r.pergunta_id = mapa[r.pergunta_id] ?? r.pergunta_id }) }; rm(s.mostrar_se); s.itens.forEach(i => rm(i.mostrar_se)) }); DB.formularios.push(c); salvar('formularios'); aviso('Formulário duplicado.'); return id }

/* ================= CONSTRUTOR ================= */
function Construtor(id) {
  const orig = formularioDe(id); if (!orig) return pagina('Formulário não encontrado', null, [btn('Voltar', { onclick: () => ir('formularios') })])
  const F = clonar(orig); const estado = { modo: 'editar', sel: null, original: JSON.stringify(orig), previa: {}, previaOk: false }; let arrasto = null
  const raiz = h('div', { class: 'max-w-3xl mx-auto px-4 sm:px-6 pb-32 pt-4', 'data-testid': 'construtor' })
  const sujo = () => JSON.stringify(F) !== estado.original
  const anteriores = (si, i) => { const l = []; F.secoes.forEach((s, a) => s.itens.forEach((p, b) => { if (a < si || (a === si && b < i)) l.push(p) })); return l.filter(p => CRM.podeCondicionar(p.tipo)) }
  const anterioresSecao = si => { const l = []; F.secoes.forEach((s, a) => { if (a < si) s.itens.forEach(p => l.push(p)) }); return l.filter(p => CRM.podeCondicionar(p.tipo)) }
  const problema = () => CRM.validarCondicoes(F.secoes)
  const indicador = () => { const el = raiz.querySelector('[data-testid=estado-form]'); if (el) { el.textContent = sujo() ? 'Alterações não salvas' : ''; el.className = 'text-xs text-amber-600' } const b = raiz.querySelector('[data-testid=salvar]'); if (b) b.disabled = !sujo() }
  const toque = () => indicador()
  const desenhar = () => { const y = window.scrollY; raiz.replaceChildren(topo(), estado.modo === 'visualizar' ? previa() : edicao()); window.scrollTo(0, y) }
  const salvarForm = () => {
    if (!F.nome.trim()) F.nome = 'Formulário sem título'; const prob = problema(); if (prob) { aviso(prob, 'erro'); desenhar(); return }
    const idsEm = new Set(); for (const s of F.secoes) for (const i of s.itens) { if (!i.texto.trim()) { aviso('Há pergunta sem texto.', 'erro'); return } if (CRM.tipoComOpcoes(i.tipo) && !i.opcoes.filter(o => o.trim()).length) { aviso(`“${i.texto}” precisa de pelo menos uma opção.`, 'erro'); return } if (idsEm.has(i.pergunta_id)) { aviso('Pergunta repetida no formulário.', 'erro'); return } idsEm.add(i.pergunta_id); i.opcoes = i.opcoes.map(o => o.trim()).filter(Boolean) }
    F.updated_at = agora(); F.ativo = situacaoForm(F) === 'publicado'; Object.assign(orig, clonar(F))
    DB.formularios.forEach(o => { if (o.id === orig.id) return; o.secoes.forEach(s => s.itens.forEach(i => { const m = itensDe(orig).find(x => x.pergunta_id === i.pergunta_id); if (m) { i.texto = m.texto; i.tipo = m.tipo; i.opcoes = [...m.opcoes]; i.ajuda = m.ajuda } })) })
    estado.original = JSON.stringify(F); auditar('salvar_formulario', F.nome); salvar('formularios'); aviso('Formulário salvo.'); desenhar()
  }
  function topo() {
    return h('div', { class: 'sticky top-14 lg:top-16 z-20 -mx-4 px-4 py-3 mb-4 bg-[#edeae2]/95 dark:bg-zinc-950/95 backdrop-blur border-b border-gray-200/70 dark:border-zinc-800 flex flex-wrap items-center gap-3' },
      h('button', { type: 'button', class: 'text-sm text-gray-500 hover:text-primary flex items-center gap-1', onclick: () => { if (sujo()) confirmar('Sair sem salvar?', 'As alterações deste formulário serão perdidas.', 'Sair sem salvar', () => ir('formularios')); else ir('formularios') }, 'data-testid': 'voltar-lista' }, ic('ph:arrow-left-bold'), 'Formulários'),
      h('div', { class: 'flex rounded-full border border-gray-300 dark:border-zinc-700 overflow-hidden text-xs font-semibold uppercase tracking-wider mx-auto', role: 'tablist' }, h('button', { type: 'button', role: 'tab', class: 'px-4 py-1.5 ' + (estado.modo === 'editar' ? 'bg-primary text-white' : 'text-gray-500'), onclick: () => { estado.modo = 'editar'; desenhar() }, 'data-testid': 'modo-editar' }, 'Editar'), h('button', { type: 'button', role: 'tab', class: 'px-4 py-1.5 ' + (estado.modo === 'visualizar' ? 'bg-primary text-white' : 'text-gray-500'), onclick: () => { estado.modo = 'visualizar'; estado.previa = {}; estado.previaOk = false; desenhar() }, 'data-testid': 'modo-visualizar' }, 'Visualizar')),
      botoesSituacao(F, salvarForm, desenhar), h('span', { class: 'text-xs text-amber-600', 'data-testid': 'estado-form' }, sujo() ? 'Alterações não salvas' : ''), h('button', { type: 'button', class: 'inline-flex items-center gap-1.5 rounded-full bg-primary text-white px-4 py-2 text-xs font-semibold uppercase tracking-wider disabled:opacity-40', disabled: !sujo(), onclick: salvarForm, 'data-testid': 'salvar' }, ic('ph:floppy-disk-bold'), 'Salvar alterações'))
  }
  function previa() {
    const limpas = F.secoes.map(s => ({ ...s, itens: s.itens.filter(i => !CRM.tipoInterno(i.tipo)) })); const caixa = h('div', {})
    const des = () => { caixa.replaceChildren(Preenchimento({ secoes: limpas, valores: estado.previa, rotuloEnviar: 'Enviar (só prévia)', aoEnviar: () => { estado.previaOk = true; des() } }), estado.previaOk ? h('p', { class: 'text-sm text-emerald-700 dark:text-emerald-400 text-center mt-3', 'data-testid': 'previa-ok' }, 'Prévia concluída: todas as obrigatórias foram respondidas. Nada foi enviado.') : null, h('div', { class: 'text-center mt-2' }, h('button', { type: 'button', class: 'text-xs underline text-gray-500', onclick: () => { estado.previa = {}; estado.previaOk = false; des() } }, 'Limpar respostas da prévia'))) }; des()
    return h('div', { class: 'space-y-4', 'data-testid': 'painel-previa' }, h('div', { class: 'rounded-2xl border border-secondary/40 bg-secondary/10 p-3 text-xs text-center font-semibold text-secondary-dark dark:text-cafe-creme' }, 'Prévia — é assim que quem preenche vê o formulário. Nada aqui é enviado ou salvo.'), h('section', { class: 'card border-t-8 !border-t-secondary space-y-1' }, h('h1', { class: 'text-3xl text-primary dark:text-zinc-100' }, F.nome || 'Formulário sem título'), F.descricao ? h('p', { class: 'text-sm text-gray-500 whitespace-pre-line' }, F.descricao) : null), caixa)
  }
  /* --- edição --- */
  const campoLimpo = (cls, o) => { const i = h('input', { class: 'w-full bg-transparent border-b border-transparent hover:border-gray-300 focus:border-primary outline-none ' + cls, ...o.attrs }); i.value = o.valor || ''; i.addEventListener('input', () => { o.aoMudar(i.value); toque() }); return i }
  function editorCondicao(cond, ant, aoMudar) {
    if (!ant.length) return h('p', { class: 'text-xs text-gray-400' }, 'Não há pergunta anterior para usar como condição. Coloque esta pergunta depois de uma pergunta de escolha, sim/não, número ou texto.')
    const regras = cond?.regras || []; const juntar = cond?.juntar || 'e'; const emitir = (rs, j = juntar) => { aoMudar(rs.length ? { juntar: j, regras: rs } : null); desenhar() }
    const pr = id => ant.find(a => a.pergunta_id === id); const ops = id => CRM.operadoresDoTipo(pr(id)?.tipo || 'texto_curto'); const opcoes = id => { const p = pr(id); return !p ? [] : p.tipo === 'sim_nao' ? ['Sim', 'Não'] : CRM.tipoComOpcoes(p.tipo) ? p.opcoes : [] }
    return h('div', { class: 'space-y-2', 'data-testid': 'condicao-editor' }, regras.map((r, i) => h('div', { class: 'flex flex-wrap items-center gap-2 rounded-xl bg-white/70 dark:bg-zinc-900/60 border border-gray-200 dark:border-zinc-700 p-2' }, h('span', { class: 'text-xs font-semibold text-gray-500 w-6' }, i === 0 ? 'Se' : juntar === 'ou' ? 'ou' : 'e'),
      h('select', { class: 'modal-input !w-auto flex-1 min-w-[10rem]', 'aria-label': 'Pergunta da condição', 'data-testid': 'cond-pergunta', onchange: ev => { const id_ = Number(ev.target.value); emitir(regras.map((x, k) => k === i ? { pergunta_id: id_, operador: ops(id_)[0].valor, valor: '' } : x)) } }, ant.map(a => h('option', { value: a.pergunta_id, selected: a.pergunta_id === r.pergunta_id }, a.texto || '(pergunta sem texto)'))),
      h('select', { class: 'modal-input !w-auto', 'aria-label': 'Operador', 'data-testid': 'cond-operador', onchange: ev => emitir(regras.map((x, k) => k === i ? { ...x, operador: ev.target.value, valor: CRM.OPERADORES[ev.target.value].comValor ? (x.valor || '') : undefined } : x)) }, ops(r.pergunta_id).map(o => h('option', { value: o.valor, selected: o.valor === r.operador }, o.nome))),
      CRM.OPERADORES[r.operador]?.comValor ? (opcoes(r.pergunta_id).length ? h('select', { class: 'modal-input !w-auto flex-1 min-w-[8rem]', 'aria-label': 'Valor', 'data-testid': 'cond-valor', onchange: ev => { regras[i] = { ...r, valor: ev.target.value }; aoMudar({ juntar, regras }); toque(); desenhar() } }, h('option', { value: '' }, 'Escolha…'), opcoes(r.pergunta_id).map(o => h('option', { value: o, selected: r.valor === o }, o))) : h('input', { class: 'modal-input !w-auto flex-1 min-w-[8rem]', value: r.valor ?? '', placeholder: 'valor', 'aria-label': 'Valor', 'data-testid': 'cond-valor', oninput: ev => { regras[i] = { ...r, valor: ev.target.value }; aoMudar({ juntar, regras }); toque() } })) : null,
      h('button', { type: 'button', class: 'ml-auto text-gray-400 hover:text-danger', 'aria-label': 'Remover condição', onclick: () => emitir(regras.filter((_, k) => k !== i)) }, ic('ph:x-bold')))),
      h('div', { class: 'flex flex-wrap items-center gap-3' }, h('button', { type: 'button', class: 'text-xs font-semibold text-secondary-dark dark:text-cafe-creme hover:underline', 'data-testid': 'cond-adicionar', onclick: () => { const p = ant[ant.length - 1]; emitir([...regras, { pergunta_id: p.pergunta_id, operador: CRM.operadoresDoTipo(p.tipo)[0].valor, valor: '' }]) } }, '+ ' + (regras.length ? 'outra condição' : 'adicionar condição')), regras.length > 1 ? h('label', { class: 'text-xs text-gray-500 flex items-center gap-1.5' }, 'mostrar quando', h('select', { class: 'modal-input !w-auto !py-1', onchange: ev => emitir(regras, ev.target.value) }, h('option', { value: 'e', selected: juntar === 'e' }, 'todas forem verdadeiras'), h('option', { value: 'ou', selected: juntar === 'ou' }, 'qualquer uma for verdadeira'))) : null))
  }
  function cartaoPergunta(p, si, i) {
    const ativa = estado.sel === p.pergunta_id; const t = CRM.TIPO(p.tipo); const s = F.secoes[si]; const pode = (si > 0 || i > 0, true)
    const invalida = (() => { const ant = new Map(anteriores(si, i).map(a => [a.pergunta_id, a])); for (const r of p.mostrar_se?.regras || []) { const a = ant.get(r.pergunta_id); if (!a) return 'A condição depende de uma pergunta que não existe ou vem depois.'; if (!CRM.operadorValido(a.tipo, r.operador)) return 'Operador incompatível com o tipo da pergunta.' } return null })()
    const desc = p.mostrar_se ? CRM.descreverCondicao(p.mostrar_se, id => itensDe(F).find(x => x.pergunta_id === id)?.texto ?? '?', id => itensDe(F).find(x => x.pergunta_id === id)?.tipo ?? 'texto_curto') : ''
    const mover = d => { const l = F.secoes; let [a, b] = [si, i]; if (d < 0) { if (b > 0) { [s.itens[b - 1], s.itens[b]] = [s.itens[b], s.itens[b - 1]] } else if (a > 0) { s.itens.splice(b, 1); l[a - 1].itens.push(p) } else return } else { if (b < s.itens.length - 1) { [s.itens[b + 1], s.itens[b]] = [s.itens[b], s.itens[b + 1]] } else if (a < l.length - 1) { s.itens.splice(b, 1); l[a + 1].itens.unshift(p) } else return } desenhar() }
    const card = h('article', { class: 'rounded-2xl border bg-white dark:bg-zinc-900/70 transition-shadow ' + (ativa ? 'border-primary shadow-md ring-1 ring-primary/20' : 'border-gray-200 dark:border-zinc-800 hover:border-primary/50'), 'data-testid': 'card-' + (p.texto || 'nova'), onclick: () => { if (!ativa) { estado.sel = p.pergunta_id; desenhar() } } },
      h('div', { class: 'flex items-center justify-between px-3 pt-1.5 text-gray-300' }, h('span', { class: 'cursor-grab active:cursor-grabbing px-2', draggable: 'true', title: 'Arraste para reordenar ou mover para outra seção', 'data-testid': 'alca-pergunta', ondragstart: ev => { arrasto = { si, i }; ev.dataTransfer.setData('text/plain', 'pergunta'); ev.dataTransfer.effectAllowed = 'move' } }, ic('ph:dots-six-bold')), !ativa ? h('span', { class: 'text-[10px] uppercase tracking-widest text-gray-400' }, t?.nome, p.obrigatoria ? h('span', { class: 'text-danger' }, ' · obrigatória') : null) : null))
    if (!ativa) card.append(h('div', { class: 'px-5 pb-4 space-y-1.5' }, h('p', { class: 'text-base font-medium text-primary dark:text-zinc-100' }, p.texto || 'Pergunta sem texto', p.obrigatoria ? h('b', { class: 'text-danger' }, ' *') : null), p.ajuda ? h('p', { class: 'text-xs text-gray-400' }, p.ajuda) : null, t?.comOpcoes ? h('ul', { class: 'text-sm text-gray-500 space-y-0.5' }, p.opcoes.slice(0, 6).map(o => h('li', { class: 'flex items-center gap-2' }, h('span', { class: 'inline-block size-3 border border-gray-400 ' + (t.multipla ? 'rounded-sm' : 'rounded-full') }), o)), p.opcoes.length > 6 ? h('li', { class: 'text-xs text-gray-400' }, `+ ${p.opcoes.length - 6} opção(ões)`) : null) : p.tipo === 'sim_nao' ? h('p', { class: 'text-sm text-gray-500 flex gap-4' }, h('span', {}, '○ Sim'), h('span', {}, '○ Não')) : h('p', { class: 'text-xs text-gray-400 border-b border-dashed border-gray-300 dark:border-zinc-700 pb-1 w-2/3' }, t?.dica), p.mostrar_se ? h('p', { class: 'text-[11px] text-secondary-dark dark:text-cafe-creme flex items-start gap-1', 'data-testid': 'resumo-logica' }, ic('ph:git-branch-bold', 'mt-0.5 shrink-0'), 'Aparece se ' + desc) : null, invalida ? h('p', { class: 'text-[11px] text-danger flex items-start gap-1' }, ic('ph:warning-bold', 'mt-0.5'), invalida) : null))
    else {
      const nResp = contarRespostas(p.pergunta_id); const usada = DB.formularios.filter(f => f.id !== F.id && itensDe(f).some(x => x.pergunta_id === p.pergunta_id))
      const opcoesBox = h('div', { class: 'space-y-1.5', 'data-testid': 'opcoes' }); let dragOp = null
      const desOpcoes = () => { opcoesBox.replaceChildren(...p.opcoes.map((o, k) => h('div', { class: 'flex items-center gap-2 rounded-lg', 'data-testid': 'opcao-' + k, ondragover: ev => ev.preventDefault(), ondrop: ev => { ev.preventDefault(); if (dragOp != null && dragOp !== k) { const [m] = p.opcoes.splice(dragOp, 1); p.opcoes.splice(k, 0, m); desOpcoes(); toque() } } }, h('span', { class: 'cursor-grab text-gray-300 px-1', draggable: 'true', title: 'Arraste para reordenar', ondragstart: ev => { dragOp = k; ev.dataTransfer.setData('text/plain', 'opcao') } }, ic('ph:dots-six-vertical-bold')), h('span', { class: 'inline-block size-3.5 border border-gray-400 shrink-0 ' + (t.multipla ? 'rounded-sm' : 'rounded-full') }), (() => { const e = h('input', { class: 'flex-1 bg-transparent border-b border-transparent hover:border-gray-300 focus:border-primary outline-none py-1 text-sm', placeholder: 'Opção ' + (k + 1), 'data-testid': 'opcao-texto' }); e.value = o; e.addEventListener('input', () => { p.opcoes[k] = e.value; toque() }); e.addEventListener('keydown', ev => { if (ev.key === 'Enter') { ev.preventDefault(); p.opcoes.splice(k + 1, 0, ''); desOpcoes(); opcoesBox.querySelectorAll('[data-testid=opcao-texto]')[k + 1]?.focus(); toque() } }); return e })(), h('button', { type: 'button', class: 'text-gray-300 hover:text-primary disabled:opacity-30', disabled: k === 0, 'aria-label': 'Subir opção', onclick: () => { [p.opcoes[k - 1], p.opcoes[k]] = [p.opcoes[k], p.opcoes[k - 1]]; desOpcoes(); toque() } }, ic('ph:arrow-up-bold')), h('button', { type: 'button', class: 'text-gray-300 hover:text-primary disabled:opacity-30', disabled: k === p.opcoes.length - 1, 'aria-label': 'Descer opção', onclick: () => { [p.opcoes[k + 1], p.opcoes[k]] = [p.opcoes[k], p.opcoes[k + 1]]; desOpcoes(); toque() } }, ic('ph:arrow-down-bold')), h('button', { type: 'button', class: 'text-gray-300 hover:text-danger', 'aria-label': 'Excluir opção', 'data-testid': 'opcao-excluir', onclick: () => { p.opcoes.splice(k, 1); desOpcoes(); toque() } }, ic('ph:x-bold')))), h('button', { type: 'button', class: 'text-xs font-semibold text-secondary-dark dark:text-cafe-creme hover:underline pl-1', 'data-testid': 'opcao-adicionar', onclick: () => { p.opcoes.push(''); desOpcoes(); opcoesBox.querySelectorAll('[data-testid=opcao-texto]')[p.opcoes.length - 1]?.focus(); toque() } }, '+ Adicionar opção')) }; if (t?.comOpcoes) desOpcoes()
      const tipoSel = h('select', { class: 'modal-input', 'aria-label': 'Tipo de resposta', 'data-testid': 'edit-tipo', onchange: ev => { const novo = ev.target.value; const antes = CRM.TIPO(p.tipo); if (nResp && !(antes.comOpcoes && CRM.tipoComOpcoes(novo))) { p.pergunta_id = novoIdPergunta(); aviso('Como já havia respostas, criei uma nova pergunta; as respostas antigas ficam preservadas.') } p.tipo = novo; if (!CRM.tipoComOpcoes(novo)) p.opcoes = []; else if (!p.opcoes.length) p.opcoes = ['Opção 1']; if (CRM.tipoInterno(novo)) { p.obrigatoria = false; p.mostrar_se = null } estado.sel = p.pergunta_id; desenhar() } }, GRUPOS_TIPO.map(g => h('optgroup', { label: g }, CRM.TIPOS_PERGUNTA.filter(x => x.grupo === g).map(x => h('option', { value: x.valor, selected: x.valor === p.tipo }, x.nome)))))
      card.append(h('div', { class: 'px-5 pb-4 space-y-4', onclick: ev => ev.stopPropagation() },
        h('div', { class: 'grid grid-cols-1 sm:grid-cols-[1fr_15rem] gap-3' }, (() => { const e = h('input', { class: 'modal-input !text-base font-medium', placeholder: 'Pergunta', 'data-testid': 'edit-texto' }); e.value = p.texto; e.addEventListener('input', () => { p.texto = e.value; toque() }); return e })(), tipoSel),
        (() => { const e = h('input', { class: 'modal-input !text-xs', placeholder: 'Descrição ou ajuda (opcional)', 'data-testid': 'edit-ajuda' }); e.value = p.ajuda || ''; e.addEventListener('input', () => { p.ajuda = e.value || null; toque() }); return e })(),
        nResp ? h('p', { class: 'text-xs rounded-lg bg-secondary/10 border border-secondary/30 p-2 text-secondary-dark dark:text-cafe-creme' }, `Esta pergunta já tem ${nResp} resposta(s) guardada(s). Ajustar o texto ou as opções mantém as respostas; trocar o tipo cria uma nova pergunta e preserva as antigas.`) : null,
        usada.length ? h('p', { class: 'text-xs text-gray-500' }, 'Esta pergunta também é usada em: ' + usada.map(f => f.nome).join(', ') + ' — a edição vale para todos.') : null,
        t?.comOpcoes ? opcoesBox : p.tipo === 'sim_nao' ? h('p', { class: 'text-sm text-gray-500 flex gap-4' }, h('span', {}, '○ Sim'), h('span', {}, '○ Não')) : null,
        t?.interno ? h('p', { class: 'text-xs text-gray-500' }, 'Checklist interno: acompanha o que o escritório já fez. Não é perguntado a quem preenche.') : null,
        mapeamentoPergunta(p, F, toque, desenhar),
        h('details', { open: !!p.mostrar_se, class: 'rounded-xl border border-dashed border-gray-300 dark:border-zinc-700 p-3' }, h('summary', { class: 'cursor-pointer text-xs font-semibold uppercase tracking-wider text-gray-500 flex items-center gap-1.5', 'data-testid': 'logica-toggle' }, ic('ph:git-branch-bold'), 'Lógica condicional', p.mostrar_se ? h('span', { class: 'normal-case tracking-normal font-normal text-secondary-dark dark:text-cafe-creme' }, '— ativa') : null), h('div', { class: 'mt-3 space-y-2' }, h('p', { class: 'text-xs text-gray-500' }, 'Mostrar esta pergunta só se… (sem condição, ela sempre aparece)'), editorCondicao(p.mostrar_se, anteriores(si, i), v => { p.mostrar_se = v; toque() }))),
        h('div', { class: 'flex flex-wrap items-center justify-between gap-3 pt-2 border-t border-gray-100 dark:border-zinc-800' }, !t?.interno ? h('label', { class: 'flex items-center gap-2 text-sm cursor-pointer' }, h('input', { type: 'checkbox', class: 'accent-[#6f5636]', checked: p.obrigatoria, 'data-testid': 'edit-obrigatoria', onclick: ev => { p.obrigatoria = ev.target.checked; toque() } }), 'Obrigatória') : h('span'), h('div', { class: 'flex items-center gap-1 text-gray-400' }, btnIcone('ph:arrow-up-bold', 'Subir', () => mover(-1), 'p-subir'), btnIcone('ph:arrow-down-bold', 'Descer', () => mover(1), 'p-descer'), btnIcone('ph:copy-bold', 'Duplicar pergunta', () => { const c = clonar(p); c.pergunta_id = novoIdPergunta(); c.mostrar_se = null; s.itens.splice(i + 1, 0, c); estado.sel = c.pergunta_id; desenhar() }, 'duplicar-pergunta'), btnIcone('ph:trash-bold', 'Excluir pergunta', () => { const dep = F.secoes.some(x => x.mostrar_se?.regras.some(r => r.pergunta_id === p.pergunta_id) || x.itens.some(y => y.mostrar_se?.regras.some(r => r.pergunta_id === p.pergunta_id))); const exec = () => { s.itens.splice(i, 1); F.secoes.forEach(x => { const lim = c => c && (c.regras = c.regras.filter(r => r.pergunta_id !== p.pergunta_id), c.regras.length ? c : null); x.mostrar_se = lim(x.mostrar_se); x.itens.forEach(y => { y.mostrar_se = lim(y.mostrar_se) }) }); estado.sel = null; desenhar() }; if (dep || nResp) confirmar('Excluir pergunta?', (dep ? 'Outras perguntas dependem dela (as condições serão removidas). ' : '') + (nResp ? `As ${nResp} resposta(s) já guardadas continuam no histórico. ` : '') + 'Isto só vale ao salvar o formulário.', 'Excluir', exec); else exec() }, 'excluir-pergunta')))))
    }
    return h('div', { ondragover: ev => { if (arrasto) { ev.preventDefault(); ev.dataTransfer.dropEffect = 'move' } }, ondrop: ev => { if (!arrasto) return; ev.preventDefault(); const { si: a, i: b } = arrasto; arrasto = null; const [m] = F.secoes[a].itens.splice(b, 1); let alvo = i; if (a === si && b < i) alvo--; F.secoes[si].itens.splice(alvo, 0, m); desenhar() } }, card)
  }
  function abrirBanco(si) {
    const q = h('input', { type: 'search', class: 'modal-input', placeholder: 'Buscar pergunta…', 'data-testid': 'banco-busca' }); const caixa = h('div', { class: 'space-y-2 mt-3' }); let mm
    const des = () => { const tx = semAcento(q.value); const ja = new Set(itensDe(F).map(i => i.pergunta_id)); const itens = bancoPerguntas().filter(b => !ja.has(b.pergunta_id) && (!tx || semAcento(b.texto).includes(tx)) && !(F.contexto !== 'demanda' && F.contexto !== 'cliente' && false)); caixa.replaceChildren(...(itens.length ? itens.map(b => h('button', { type: 'button', class: 'w-full text-left rounded-xl border border-gray-200 dark:border-zinc-700 hover:border-primary p-3', 'data-testid': 'banco-item-' + b.pergunta_id, onclick: () => { F.secoes[si].itens.push({ ...clonar(b), formularios: undefined, mostrar_se: null }); estado.sel = b.pergunta_id; mm.fechar(); desenhar() } }, h('p', { class: 'text-sm font-medium' }, b.texto), h('p', { class: 'text-xs text-gray-400' }, CRM.TIPO(b.tipo)?.nome + (b.opcoes.length ? ' — ' + b.opcoes.join(', ') : '') + ' · em: ' + b.formularios.join(', ')))) : [h('p', { class: 'text-sm text-gray-400' }, 'Nenhuma pergunta disponível.')])) }; q.addEventListener('input', des); des()
    mm = modal({ titulo: 'Usar uma pergunta que já existe', largura: 'max-w-lg', corpo: [h('p', { class: 'text-xs text-gray-500' }, 'A resposta é a mesma em todos os formulários: quem já respondeu não precisa responder de novo.'), q, caixa] })
  }
  function edicao() {
    const prob = problema(); const proc = F.procedimentos
    const ctxBox = h('div', { class: 'flex flex-wrap items-center gap-2' }, h('span', { class: 'text-[11px] font-semibold uppercase tracking-wider text-gray-500' }, 'Vale para'), ...Object.entries(CRM.CONTEXTOS).map(([k, c]) => h('button', { type: 'button', class: 'chip ' + (F.contexto === k ? 'chip-escuro' : ''), title: c.dica, 'data-testid': 'ctx-' + k, onclick: () => { F.contexto = k; if (k !== 'demanda') F.procedimentos = []; desenhar() } }, c.nome)), h('label', { class: 'ml-auto flex items-center gap-2 text-xs text-gray-500 cursor-pointer' }, h('input', { type: 'checkbox', class: 'accent-[#6f5636]', checked: F.ativo, 'data-testid': 'form-ativo', onclick: ev => { F.ativo = ev.target.checked; toque() } }), 'Ativo'))
    const servicos = F.contexto === 'demanda' ? h('div', { class: 'space-y-1.5' }, h('span', { class: 'text-[11px] font-semibold uppercase tracking-wider text-gray-500' }, 'Só para estes serviços ', h('span', { class: 'normal-case tracking-normal font-normal text-gray-400' }, '(nenhum marcado = todas as demandas)')), h('div', { class: 'space-y-1.5', 'data-testid': 'servicos' }, CRM.SERVICOS.map(sv => h('div', { class: 'flex flex-wrap items-center gap-1.5' }, h('label', { class: 'text-xs px-2.5 py-1 rounded-full border cursor-pointer font-semibold ' + (proc.includes(sv.id + '/*') ? 'bg-secondary/30 border-secondary' : 'border-gray-300 dark:border-zinc-700'), 'data-testid': 'servico-' + sv.id }, h('input', { type: 'checkbox', class: 'sr-only', checked: proc.includes(sv.id + '/*'), onclick: ev => { F.procedimentos = ev.target.checked ? [...proc.filter(x => !x.startsWith(sv.id + '/')), sv.id + '/*'] : proc.filter(x => x !== sv.id + '/*'); desenhar() } }), sv.nome), sv.variantes.length > 1 && !proc.includes(sv.id + '/*') ? sv.variantes.map(vr => h('label', { class: 'text-[11px] px-2 py-0.5 rounded-full border cursor-pointer ' + (proc.includes(sv.id + '/' + vr.id) ? 'bg-secondary/20 border-secondary' : 'border-gray-200 dark:border-zinc-700') }, h('input', { type: 'checkbox', class: 'sr-only', checked: proc.includes(sv.id + '/' + vr.id), onclick: ev => { const k = sv.id + '/' + vr.id; F.procedimentos = ev.target.checked ? [...proc, k] : proc.filter(x => x !== k); desenhar() } }), 'só ' + vr.nome)) : null)))) : null
    const cab = h('section', { class: 'card border-t-8 !border-t-primary space-y-3', 'data-testid': 'cabecalho-form' }, campoLimpo('text-3xl font-serif text-primary dark:text-zinc-100 pb-1', { valor: F.nome, attrs: { placeholder: 'Título do formulário', 'data-testid': 'form-titulo', 'aria-label': 'Título do formulário' }, aoMudar: v => { F.nome = v } }), (() => { const t = h('textarea', { rows: 2, class: 'w-full bg-transparent text-sm text-gray-600 dark:text-zinc-300 border-b border-transparent hover:border-gray-300 focus:border-primary outline-none resize-none', placeholder: 'Descrição do formulário (opcional)', 'data-testid': 'form-descricao', 'aria-label': 'Descrição' }); t.value = F.descricao || ''; t.addEventListener('input', () => { F.descricao = t.value || null; toque() }); return t })(), h('div', { class: 'pt-2 border-t border-gray-100 dark:border-zinc-800 space-y-3' }, ctxBox, h('p', { class: 'text-xs text-gray-400' }, CRM.CONTEXTOS[F.contexto].dica), servicos), cabecalhoExtra(F, toque))
    const secoes = F.secoes.map((s, si) => h('section', { class: 'space-y-3', 'data-testid': 'secao-' + si }, h('div', { class: 'rounded-t-2xl rounded-b-lg bg-primary text-white px-4 py-2 flex flex-wrap items-center gap-2' }, h('span', { class: 'text-xs uppercase tracking-widest opacity-80' }, `Seção ${si + 1} de ${F.secoes.length}`), h('div', { class: 'ml-auto flex items-center gap-1' }, ...[['ph:arrow-up-bold', 'Subir seção', () => { [F.secoes[si - 1], F.secoes[si]] = [F.secoes[si], F.secoes[si - 1]]; desenhar() }, si === 0, 'secao-subir'], ['ph:arrow-down-bold', 'Descer seção', () => { [F.secoes[si + 1], F.secoes[si]] = [F.secoes[si], F.secoes[si + 1]]; desenhar() }, si === F.secoes.length - 1, 'secao-descer'], ['ph:copy-bold', 'Duplicar seção', () => { const c = clonar(s); c.titulo += ' (cópia)'; c.mostrar_se = null; c.itens.forEach(i => { i.pergunta_id = novoIdPergunta(); i.mostrar_se = null }); F.secoes.splice(si + 1, 0, c); desenhar() }, false, 'secao-duplicar'], ['ph:trash-bold', 'Excluir seção', () => { const ex = () => { F.secoes.splice(si, 1); if (!F.secoes.length) F.secoes.push({ id: null, titulo: 'Seção 1', descricao: null, mostrar_se: null, itens: [] }); desenhar() }; s.itens.length ? confirmar('Excluir seção?', `A seção “${s.titulo}” e suas ${s.itens.length} pergunta(s) saem do formulário ao salvar.`, 'Excluir', ex) : ex() }, false, 'secao-excluir']].map(([ico, tt, fn, dis, tid]) => h('button', { type: 'button', class: 'acao-sec', title: tt, 'aria-label': tt, disabled: dis, onclick: fn, 'data-testid': tid }, ic(ico))))), h('div', { class: 'card !p-4 space-y-2' }, campoLimpo('text-xl text-primary dark:text-zinc-100', { valor: s.titulo, attrs: { placeholder: 'Título da seção', 'data-testid': 'secao-titulo', 'aria-label': 'Título da seção' }, aoMudar: v => { s.titulo = v } }), campoLimpo('text-xs text-gray-500', { valor: s.descricao, attrs: { placeholder: 'Descrição da seção (opcional)', 'aria-label': 'Descrição da seção' }, aoMudar: v => { s.descricao = v || null } }), si > 0 ? h('details', { open: !!s.mostrar_se, class: 'text-xs' }, h('summary', { class: 'cursor-pointer font-semibold uppercase tracking-wider text-gray-500 flex items-center gap-1.5', 'data-testid': 'secao-logica' }, ic('ph:git-branch-bold'), 'Mostrar esta seção só se…', s.mostrar_se ? h('span', { class: 'normal-case tracking-normal font-normal' }, '— ativa') : null), h('div', { class: 'mt-2' }, editorCondicao(s.mostrar_se, anterioresSecao(si), v => { s.mostrar_se = v; toque() }))) : null),
      h('div', { class: 'space-y-3', 'data-testid': 'itens-' + si, ondragover: ev => { if (arrasto) ev.preventDefault() }, ondrop: ev => { if (!arrasto || ev.target.closest('article')) return; ev.preventDefault(); const { si: a, i: b } = arrasto; arrasto = null; const [m] = F.secoes[a].itens.splice(b, 1); F.secoes[si].itens.push(m); desenhar() } }, ...s.itens.map((p, i) => cartaoPergunta(p, si, i)), !s.itens.length ? h('p', { class: 'text-sm text-gray-400 text-center border border-dashed border-gray-300 dark:border-zinc-700 rounded-2xl py-6' }, 'Seção vazia. Adicione perguntas ou arraste uma pergunta para cá.') : null, h('div', { class: 'flex flex-wrap gap-2' }, h('button', { type: 'button', class: 'chip', 'data-testid': 'add-pergunta-' + si, onclick: () => { const np = { pergunta_id: novoIdPergunta(), texto: '', tipo: 'texto_curto', opcoes: [], ajuda: null, obrigatoria: false, mostrar_se: null }; s.itens.push(np); estado.sel = np.pergunta_id; desenhar(); setTimeout(() => raiz.querySelector('[data-testid=edit-texto]')?.focus(), 0) } }, ic('ph:plus-bold'), ' Nova pergunta'), h('button', { type: 'button', class: 'chip', 'data-testid': 'add-existente-' + si, onclick: () => abrirBanco(si) }, ic('ph:books-bold'), ' Usar pergunta existente')))))
    return h('div', { class: 'space-y-4' }, cab, prob ? h('p', { class: 'rounded-xl bg-danger/10 border border-danger/30 text-danger text-sm p-3', 'data-testid': 'problema' }, ic('ph:warning-bold', 'align-middle'), ' ' + prob) : null, ...secoes, h('div', { class: 'flex flex-wrap gap-2 justify-center pt-2' }, h('button', { type: 'button', class: 'chip', 'data-testid': 'add-secao', onclick: () => { F.secoes.push({ id: null, titulo: 'Seção ' + (F.secoes.length + 1), descricao: null, mostrar_se: null, itens: [] }); desenhar() } }, ic('ph:rows-bold'), ' Adicionar seção')),
      F.contexto !== 'demanda' ? h('p', { class: 'text-xs text-gray-500 text-center pt-4' }, ic('ph:paper-plane-tilt-bold', 'align-middle'), ' Para enviar: abra a ficha da pessoa (Clientes ou Leads) → aba Cliente → Enviar formulário.') : h('p', { class: 'text-xs text-gray-500 text-center pt-4' }, 'Formulário de demanda: preenchido na ficha, dentro de cada demanda (não é enviado por link).'),
      h('div', { class: 'flex flex-wrap gap-2 justify-between pt-8 border-t border-gray-200 dark:border-zinc-800 mt-8' }, h('button', { type: 'button', class: 'chip', 'data-testid': 'duplicar-form', onclick: () => { const nid = duplicarForm(orig); ir('formularios', { editar: nid }) } }, ic('ph:copy-bold'), ' Duplicar formulário'), h('button', { type: 'button', class: 'chip hover:!text-danger hover:!border-danger', 'data-testid': 'excluir-form', onclick: () => { const env = DB.envios.filter(e => e.formulario_id === orig.id).length; confirmar('Excluir formulário?', `“${orig.nome}” será removido.` + (env ? ` Os ${env} envio(s) e respostas já recebidos continuam na ficha dos clientes.` : '') + ' Esta ação não pode ser desfeita.', 'Excluir', () => { DB.formularios = DB.formularios.filter(f => f.id !== orig.id); DB.envios.forEach(e => { if (e.formulario_id === orig.id) e.formulario_id = null }); auditar('excluir_formulario', orig.nome); salvar('formularios'); salvar('envios'); ir('formularios'); aviso('Formulário excluído.') }) } }, ic('ph:trash-bold'), ' Excluir formulário')))
  }
  desenhar(); return raiz
}
