'use strict'
/* ============ FORMULÁRIOS › FLUXO COMPLETO (criar → publicar → enviar → receber → revisar → aplicar ao cadastro) ============
   REAL no artifact:   gerenciador (rascunho/publicado/arquivado), novos tipos, link individual por cliente/demanda, WhatsApp (wa.me) e e-mail (Gmail)
                       com a mensagem pronta, status e prazos, lembretes manuais, revisão, edição interna, aplicação ao cadastro com conferência,
                       anexos para o Drive (se houver pasta vinculada), preenchimento "no atendimento" (a própria Dra. com a cliente).
   REAL via conector:  criar/ler o envio no CRM do site (Supabase) = link público que a cliente abre no celular SEM login.
   DEPENDE:            link público 100% dentro do artifact (exigiria login no claude.ai), notificação push/e-mail ao responder, lembrete automático,
                       upload/assinatura pelo celular da cliente (o site atual não tem esses campos). */

/* ---------- novos tipos de pergunta (só no artifact; o site precisa do mesmo tipo para exibir) ---------- */
;[
  { valor: 'horario', nome: 'Horário', grupo: 'Dados', icone: 'ph:clock-bold', comOpcoes: false, multipla: false, dica: 'Melhor horário para contato, horário do fato' },
  { valor: 'cpf_cnpj', nome: 'CPF / CNPJ', grupo: 'Dados', icone: 'ph:identification-card-bold', comOpcoes: false, multipla: false, dica: 'Valida os dígitos; use só quando a finalidade exigir' },
  { valor: 'endereco', nome: 'Endereço', grupo: 'Dados', icone: 'ph:map-pin-bold', comOpcoes: false, multipla: false, dica: 'CEP, rua, número, bairro, cidade e UF' },
  { valor: 'arquivo', nome: 'Envio de arquivo', grupo: 'Anexos', icone: 'ph:paperclip-bold', comOpcoes: false, multipla: false, dica: 'PDF ou foto (até 10 MB cada); vai para a pasta do Drive' },
  { valor: 'assinatura', nome: 'Assinatura', grupo: 'Anexos', icone: 'ph:signature-bold', comOpcoes: false, multipla: false, dica: 'Assinatura desenhada na tela (ciência/consentimento)' },
].forEach(t => { if (!CRM.TIPOS_PERGUNTA.some(x => x.valor === t.valor)) CRM.TIPOS_PERGUNTA.push(t) })
const GRUPOS_TIPO = ['Texto', 'Dados', 'Escolha', 'Anexos']
const TIPOS_SENSIVEIS = { cpf_cnpj: 'documento pessoal', arquivo: 'documentos do cliente', assinatura: 'assinatura', endereco: 'endereço residencial' }
const ARQ_TIPOS = ['application/pdf', 'image/jpeg', 'image/png', 'image/heic', 'image/webp']; const ARQ_MAX = 10 * 1024 * 1024
const UFS = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
const cnpjValido = v => { const d = String(v).replace(/\D/g, ''); if (d.length !== 14 || /^(\d)\1+$/.test(d)) return false; const dv = n => { let s = 0, p = n - 7; for (let i = 0; i < n; i++) { s += Number(d[i]) * p--; if (p < 2) p = 9 } const r = s % 11; return r < 2 ? 0 : 11 - r }; return dv(12) === Number(d[12]) && dv(13) === Number(d[13]) }
const mascaraCpfCnpj = v => { const d = String(v).replace(/\D/g, '').slice(0, 14); return d.length <= 11 ? d.replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})$/, '$1-$2') : d.replace(/^(\d{2})(\d)/, '$1.$2').replace(/^(\d{2})\.(\d{3})(\d)/, '$1.$2.$3').replace(/\.(\d{3})(\d)/, '.$1/$2').replace(/(\d{4})(\d{1,2})$/, '$1-$2') }
const respostaVazia = v => v == null || v === '' || (Array.isArray(v) && !v.length) || (typeof v === 'object' && !Array.isArray(v) && !Object.values(v).some(x => x))
const textoEspecial = v => Array.isArray(v) ? v.map(x => x && typeof x === 'object' ? x.nome : x).join(', ') : v && typeof v === 'object' ? [[v.logradouro, v.numero, v.complemento].filter(Boolean).join(', '), v.bairro, [v.cidade, v.uf].filter(Boolean).join('/'), v.cep && 'CEP ' + v.cep].filter(Boolean).join(' — ') : /^data:image\//.test(String(v)) ? '(assinatura registrada)' : String(v)
function validarEspecial(p, val) {
  if (p.tipo === 'cpf_cnpj') { const d = String(val).replace(/\D/g, ''); if (d.length === 11) return CRM.cpfValido(d) ? null : 'CPF inválido.'; if (d.length === 14) return cnpjValido(d) ? null : 'CNPJ inválido.'; return 'Informe um CPF (11 dígitos) ou CNPJ (14).' }
  if (p.tipo === 'endereco') { if (val.cep && String(val.cep).replace(/\D/g, '').length !== 8) return 'CEP deve ter 8 dígitos.'; if (!val.logradouro || !val.cidade || !val.uf) return 'Informe pelo menos rua, cidade e UF.' }
  if (p.tipo === 'horario' && !/^\d{2}:\d{2}$/.test(val)) return 'Horário inválido.'
  return null
}
function campoEspecial(p, { v, definir, silencioso, arquivos }) {
  const a = { 'data-pid': p.pergunta_id }
  if (p.tipo === 'horario') { const e = h('input', { type: 'time', class: 'modal-input', value: typeof v === 'string' ? v : '', ...a }); e.addEventListener('input', () => silencioso(e.value)); return e }
  if (p.tipo === 'cpf_cnpj') { const e = h('input', { type: 'text', inputmode: 'numeric', autocomplete: 'off', class: 'modal-input', placeholder: '000.000.000-00 ou 00.000.000/0000-00', value: typeof v === 'string' ? v : '', ...a }); e.addEventListener('input', () => { e.value = mascaraCpfCnpj(e.value); silencioso(e.value) }); return e }
  if (p.tipo === 'endereco') {
    const o = v && typeof v === 'object' ? v : {}; const cp = (k, rot, cls, extra) => { const e = h('input', { class: 'modal-input', placeholder: rot, 'aria-label': rot, value: o[k] || '', 'data-pid': p.pergunta_id + '-' + k, ...extra }); e.addEventListener('input', () => { if (k === 'cep') e.value = e.value.replace(/\D/g, '').slice(0, 8).replace(/^(\d{5})(\d)/, '$1-$2'); o[k] = e.value; silencioso({ ...o }) }); return h('label', { class: cls }, h('span', { class: 'text-[10px] uppercase tracking-widest text-gray-400' }, rot), e) }
    const uf = h('select', { class: 'modal-input', 'aria-label': 'UF', 'data-pid': p.pergunta_id + '-uf' }, h('option', { value: '' }, 'UF'), UFS.map(u => h('option', { value: u, selected: o.uf === u }, u))); uf.addEventListener('change', () => { o.uf = uf.value; silencioso({ ...o }) })
    return h('div', { class: 'grid grid-cols-6 gap-2', 'data-testid': 'endereco-' + p.pergunta_id }, cp('cep', 'CEP', 'col-span-2', { inputmode: 'numeric' }), cp('logradouro', 'Rua / avenida', 'col-span-4'), cp('numero', 'Número', 'col-span-2'), cp('complemento', 'Complemento', 'col-span-4'), cp('bairro', 'Bairro', 'col-span-3'), cp('cidade', 'Cidade', 'col-span-2'), h('label', { class: 'col-span-1' }, h('span', { class: 'text-[10px] uppercase tracking-widest text-gray-400' }, 'UF'), uf))
  }
  if (p.tipo === 'arquivo') {
    const lst = arquivos[p.pergunta_id] || []; const e = h('input', { type: 'file', multiple: true, accept: ARQ_TIPOS.join(','), class: 'text-sm', 'data-pid': p.pergunta_id, 'data-testid': 'arquivo-' + p.pergunta_id })
    e.addEventListener('change', () => { const novos = [...e.files].filter(f => { if (!ARQ_TIPOS.includes(f.type)) { aviso(`“${f.name}”: só PDF ou imagem (JPG, PNG, HEIC, WebP).`, 'erro'); return false } if (f.size > ARQ_MAX) { aviso(`“${f.name}” passa de 10 MB.`, 'erro'); return false } return true }); arquivos[p.pergunta_id] = [...lst, ...novos].slice(0, 15); definir(arquivos[p.pergunta_id].map(f => ({ nome: f.name, tamanho: f.size, tipo: f.type }))) })
    return h('div', { class: 'space-y-2' }, e, lst.length ? h('ul', { class: 'text-sm space-y-1' }, lst.map((f, i) => h('li', { class: 'flex items-center gap-2' }, ic('ph:paperclip-bold', 'text-gray-400'), h('span', { class: 'truncate' }, f.name), h('span', { class: 'text-[11px] text-gray-400' }, Math.max(1, Math.round(f.size / 1024)) + ' KB'), h('button', { type: 'button', class: 'text-gray-400 hover:text-danger', 'aria-label': 'Remover arquivo', onclick: () => { arquivos[p.pergunta_id] = lst.filter((_, k) => k !== i); definir(arquivos[p.pergunta_id].map(x => ({ nome: x.name, tamanho: x.size, tipo: x.type }))) } }, ic('ph:x-bold'))))) : null, h('p', { class: 'text-[11px] text-gray-400' }, 'PDF ou foto, até 10 MB cada.'))
  }
  if (p.tipo === 'assinatura') {
    const cv = h('canvas', { width: 640, height: 180, class: 'w-full rounded-xl border border-dashed border-gray-300 dark:border-zinc-600 bg-white touch-none', 'data-testid': 'assinatura-canvas', 'aria-label': 'Área de assinatura' }); const g = cv.getContext('2d'); g.lineWidth = 2.5; g.lineCap = 'round'; g.strokeStyle = '#1b1b1b'
    if (typeof v === 'string' && v.startsWith('data:image/')) { const im = new Image(); im.onload = () => g.drawImage(im, 0, 0); im.src = v }
    let desenhando = false; const pt = ev => { const r = cv.getBoundingClientRect(); return [(ev.clientX - r.left) * cv.width / r.width, (ev.clientY - r.top) * cv.height / r.height] }
    cv.addEventListener('pointerdown', ev => { desenhando = true; cv.setPointerCapture && cv.setPointerCapture(ev.pointerId); const [x, y] = pt(ev); g.beginPath(); g.moveTo(x, y); g.lineTo(x + .1, y + .1); g.stroke() })
    cv.addEventListener('pointermove', ev => { if (!desenhando) return; const [x, y] = pt(ev); g.lineTo(x, y); g.stroke() })
    const fim = () => { if (!desenhando) return; desenhando = false; silencioso(cv.toDataURL('image/png')) }; cv.addEventListener('pointerup', fim); cv.addEventListener('pointerleave', fim)
    return h('div', { class: 'space-y-1.5' }, cv, h('div', { class: 'flex items-center justify-between' }, h('p', { class: 'text-[11px] text-gray-400' }, 'Assine com o dedo ou o mouse. Vale como ciência/consentimento (assinatura simples), não substitui assinatura eletrônica qualificada.'), btn('Limpar', { mini: true, tipo: 'fantasma', onclick: () => { g.clearRect(0, 0, cv.width, cv.height); silencioso(null) } })))
  }
  return null
}

/* ---------- situação do formulário e estado do envio ---------- */
const SITUACOES = { rascunho: ['Rascunho', 'cinza'], publicado: ['Publicado', 'verde'], arquivado: ['Arquivado', 'ambar'] }
const situacaoForm = f => f.situacao || (f.ativo === false ? 'arquivado' : 'publicado')
const FORM_CFG = () => ({ validade: 30, lembreteDias: 3, ...(CONFIG.form || {}) })
const novoToken = () => { const b = crypto.getRandomValues(new Uint8Array(24)); return btoa(String.fromCharCode(...b)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '') }
const ESTADOS = { gerado: ['Link gerado (não enviado)', 'cinza'], enviado: ['Enviado', 'azul'], visualizado: ['Visualizado', 'ambar'], iniciado: ['Iniciado', 'ambar'], parcial: ['Parcialmente preenchido', 'ambar'], respondido: ['Respondido', 'verde'], expirado: ['Expirado', 'vermelho'], cancelado: ['Cancelado', 'cinza'] }
const estadoEnvio = e => e.status === 'cancelado' ? 'cancelado' : e.status === 'respondido' ? 'respondido' : e.expira_em && new Date(e.expira_em) < new Date() ? 'expirado' : e.status
const abertoEnvio = e => !['respondido', 'cancelado', 'expirado'].includes(estadoEnvio(e))
const atrasadoEnvio = e => abertoEnvio(e) && e.prazo_resposta && e.prazo_resposta < hojeISO()
const badgeEnvio = e => { const k = estadoEnvio(e); const [n, c] = ESTADOS[k] || [k, 'cinza']; return h('span', { class: 'inline-flex gap-1 items-center', 'data-testid': 'status-envio' }, badge(n, c), atrasadoEnvio(e) ? badge('Prazo vencido', 'vermelho') : null, e.nova ? badge('Nova', 'roxo') : null) }
const siteUrl = () => String((CONFIG.integr || {}).site_url || '').replace(/\/+$/, '')
const linkDoEnvio = e => e.modo === 'site' ? (siteUrl() ? `${siteUrl()}/pc/${e.token}` : '') : `#/publico/${e.token}`
const linkRealDoEnvio = e => e.modo === 'site' && siteUrl() ? `${siteUrl()}/pc/${e.token}` : ''
const eventosEnvio = e => [[e.created_at, 'Link gerado'], [e.enviado_em, 'Enviado por ' + ({ whatsapp: 'WhatsApp', email: 'e-mail' }[e.canal_envio] || 'meio informado')], ...(e.lembretes || []).map(l => [l.em, 'Lembrete enviado por ' + ({ whatsapp: 'WhatsApp', email: 'e-mail' }[l.canal] || 'meio informado')]), [e.visualizado_em, 'Cliente abriu o link'], [e.iniciado_em, 'Começou a preencher'], [e.respondido_em, 'Respondeu'], [e.revisado_em, 'Revisado no escritório'], [e.aplicado_em, 'Dados aplicados ao cadastro'], [e.cancelado_em, 'Link cancelado']].filter(x => x[0]).sort((a, b) => a[0].localeCompare(b[0]))
const nomeFormEnvio = e => (formularioDe(e.formulario_id) || {}).nome || e.formulario_nome || 'Formulário'
const estruturaDoEnvio = e => e.snap || (formularioDe(e.formulario_id) ? itensDe(formularioDe(e.formulario_id)).filter(i => !CRM.tipoInterno(i.tipo)).map(i => ({ pergunta_id: i.pergunta_id, texto: i.texto, tipo: i.tipo, mapear: i.mapear || null, doc: i.doc_desc || null })) : [])

/* ---------- mapeamento resposta → cadastro (decisão consciente: nada é gravado sem conferência) ---------- */
const DESTINOS = [['', 'Não levar ao cadastro (fica só no histórico)'], ['nome', 'Nome completo'], ['telefone', 'Telefone'], ['email', 'E-mail'], ['data_nascimento', 'Data de nascimento'], ['cpf', 'CPF'], ['rg', 'RG'], ['estado_civil', 'Estado civil'], ['profissao', 'Profissão'], ['nacionalidade', 'Nacionalidade'], ['endereco', 'Endereço (rua, bairro, cidade, UF, CEP)']]
const DESTINO_TIPOS = { nome: ['texto_curto'], telefone: ['telefone', 'texto_curto'], email: ['email', 'texto_curto'], data_nascimento: ['data'], cpf: ['cpf_cnpj', 'texto_curto'], rg: ['texto_curto'], estado_civil: ['lista_suspensa', 'selecao_unica', 'texto_curto'], profissao: ['texto_curto'], nacionalidade: ['texto_curto'], endereco: ['endereco'] }
function propostasDoEnvio(e) {
  const c = contato(e.contato_id); if (!c) return []; const q = c.qualificacao || {}; const out = []
  const atual = { nome: q.nome_completo || c.nome, telefone: c.telefone, email: c.email, data_nascimento: c.data_nascimento, cpf: q.cpf, rg: q.rg, estado_civil: q.estado_civil, profissao: q.profissao, nacionalidade: q.nacionalidade, endereco: [q.endereco, q.bairro, q.cidade && q.uf ? q.cidade + '/' + q.uf : q.cidade, q.cep].filter(Boolean).join(', ') }
  for (const it of estruturaDoEnvio(e)) { const val = e.respostas[it.pergunta_id]; if (!it.mapear || respostaVazia(val) || !DESTINOS.some(d => d[0] === it.mapear)) continue
    const novo = it.mapear === 'endereco' ? [val.logradouro && (val.logradouro + (val.numero ? ', ' + val.numero : '') + (val.complemento ? ' ' + val.complemento : '')), val.bairro, val.cidade && val.uf ? val.cidade + '/' + val.uf : val.cidade, val.cep].filter(Boolean).join(', ') : it.mapear === 'cpf' ? mascararDocumentoCompleto(val) : String(val)
    out.push({ campo: it.mapear, rotulo: DESTINOS.find(d => d[0] === it.mapear)[1].replace(/ \(.*/, ''), pergunta: it.texto, atual: atual[it.mapear] || '', novo, bruto: val, marcar: !atual[it.mapear] || atual[it.mapear] === novo }) }
  return out
}
const mascararDocumentoCompleto = v => { const d = String(v).replace(/\D/g, ''); return d.length === 11 ? d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, '$1.$2.$3-$4') : d.length === 14 ? mascaraCpfCnpj(d) : String(v) }
function aplicarPropostas(e, escolhidas) {
  const c = contato(e.contato_id); c.qualificacao = c.qualificacao || {}; const q = c.qualificacao; const log = []
  const set = (alvo, k, v, nome) => { const antes = alvo[k] ?? ''; if (antes === v) return; log.push({ campo: nome, antes, depois: v }); alvo[k] = v }
  for (const p of escolhidas) {
    if (p.campo === 'nome') { set(q, 'nome_completo', p.novo, 'Nome completo'); if (!c.nome) set(c, 'nome', p.novo, 'Nome') }
    else if (p.campo === 'telefone') { const d = String(p.bruto).replace(/\D/g, ''); set(c, 'telefone', d.length <= 11 ? '55' + d : d, 'Telefone') }
    else if (p.campo === 'email') set(c, 'email', String(p.bruto).trim().toLowerCase(), 'E-mail')
    else if (p.campo === 'data_nascimento') set(c, 'data_nascimento', p.bruto, 'Data de nascimento')
    else if (p.campo === 'endereco') { const v = p.bruto; set(q, 'endereco', [v.logradouro, v.numero].filter(Boolean).join(', ') + (v.complemento ? ' ' + v.complemento : ''), 'Endereço'); set(q, 'bairro', v.bairro || '', 'Bairro'); set(q, 'cidade', v.cidade || '', 'Cidade'); set(q, 'uf', v.uf || '', 'UF'); set(q, 'cep', v.cep || '', 'CEP'); if (v.cidade) c.cidade = v.cidade }
    else set(q, p.campo, p.novo, p.rotulo)
  }
  c.updated_at = agora(); salvar('contatos'); return log
}
function aplicarArquivosAoCaso(e) {
  const out = []; const caso = e.caso_id
  for (const it of estruturaDoEnvio(e)) { if (it.tipo !== 'arquivo') continue; for (const a of (e.anexos || []).filter(x => x.pergunta_id === it.pergunta_id && x.drive_id)) {
    const alvo = DB.documentos.find(d => d.contato_id === e.contato_id && (!caso || d.caso_id === caso) && d.status === 'pendente' && it.doc && semAcento(d.descricao).includes(semAcento(it.doc)))
    if (alvo) { vincularArquivoADocumento(alvo, { id: a.drive_id, nome: a.nome, link: a.link }); out.push(`“${a.nome}” → ${alvo.descricao}`) } } }
  return out
}
function revisarEAplicar(e) {
  const props = propostasDoEnvio(e); const docsPossiveis = estruturaDoEnvio(e).filter(i => i.tipo === 'arquivo' && i.doc && (e.anexos || []).some(a => a.pergunta_id === i.pergunta_id && a.drive_id))
  const marcas = props.map(p => p.marcar)
  const linhas = props.map((p, i) => h('label', { class: 'flex items-start gap-3 rounded-xl border border-gray-200 dark:border-zinc-700 p-3 text-sm cursor-pointer', 'data-testid': 'proposta-' + p.campo }, h('input', { type: 'checkbox', checked: marcas[i], class: 'mt-1 accent-[#6f5636]', onchange: ev => { marcas[i] = ev.target.checked } }), h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'font-semibold' }, p.rotulo, h('span', { class: 'font-normal text-gray-400 text-xs' }, ' · pergunta: ' + p.pergunta)), h('p', { class: 'text-xs text-gray-500' }, 'Hoje no cadastro: ', p.atual ? h('span', {}, p.atual) : h('i', {}, 'vazio')), h('p', { class: 'text-xs' }, 'Resposta: ', h('b', {}, p.novo)), p.atual && p.atual !== p.novo ? h('p', { class: 'text-[11px] text-amber-700 dark:text-amber-300' }, 'Já existe um valor diferente. Marque só se a cliente corrigiu o dado.') : null)))
  modal({ titulo: 'Revisar e aplicar ao cadastro', largura: 'max-w-2xl', corpo: h('div', { class: 'space-y-3', 'data-testid': 'revisao-cadastro' }, h('p', { class: 'text-xs text-gray-500' }, 'Nada é gravado sem a sua conferência. Campos vazios vêm marcados; onde já existe outro valor, a escolha é sua. O que for alterado fica registrado (antes → depois) no histórico.'), ...(linhas.length ? linhas : [h('p', { class: 'text-sm text-gray-500' }, 'Nenhuma pergunta deste formulário está ligada a um campo do cadastro. No construtor, abra a pergunta e escolha “Levar ao cadastro”.')]), docsPossiveis.length ? alerta('info', null, 'Os arquivos enviados serão vinculados aos documentos pendentes da demanda: ' + docsPossiveis.map(i => i.doc).join(', ') + '.') : null),
    rodape: fechar => [btn('Cancelar', { tipo: 'sec', onclick: fechar }), btn('Aplicar selecionados', { tid: 'aplicar-cadastro', onclick: () => {
      const log = aplicarPropostas(e, props.filter((_, i) => marcas[i])); const docs = aplicarArquivosAoCaso(e); e.aplicado_em = agora(); e.aplicado_log = [...(e.aplicado_log || []), ...log]; e.revisado_em = e.revisado_em || agora(); e.nova = false
      registrar(e.contato_id, 'Anotação', `Dados do formulário “${nomeFormEnvio(e)}” aplicados ao cadastro` + (log.length ? ': ' + log.map(l => l.campo).join(', ') : ' (nenhuma alteração)') + (docs.length ? '. Documentos: ' + docs.join('; ') : ''), e.caso_id); auditar('form_aplicar_cadastro', nomeContato(e.contato_id) + ' · ' + nomeFormEnvio(e)); salvar('envios'); fechar(); aviso(log.length || docs.length ? 'Dados aplicados ao cadastro.' : 'Nada para alterar.'); render(); atualizarCamadas() } })] })
}

/* ---------- registrar resposta recebida ---------- */
function registrarEnvio(e, valores, extras = {}) {
  const f = formularioDe(e.formulario_id); e.snap = estruturaDoEnvio(e); e.formulario_nome = f ? f.nome : e.formulario_nome; e.respostas = clonar(valores); e.resumo = extras.resumo || e.resumo || null; e.respondente = extras.respondente || null; e.consentimento_em = extras.consentimento ? agora() : e.consentimento_em; e.anexos = extras.anexos || e.anexos || []
  e.respondido_em = agora(); e.status = 'respondido'; e.parcial = null; e.nova = true
  const c = contato(e.contato_id); const alvo = f && f.contexto === 'demanda' && e.caso_id ? demanda(e.caso_id) : c
  if (alvo) { alvo.respostas = { ...(alvo.respostas || {}) }; for (const [pid, val] of Object.entries(valores)) if (!respostaVazia(val) && !/^data:image\//.test(String(val))) alvo.respostas[pid] = val; alvo.respostas_em = agora(); if (c && f && f.contexto === 'consulta') c.pre_form_respondido_em = agora(); if (c) c.updated_at = agora(); salvar(alvo === c ? 'contatos' : 'demandas') }
  if (c) registrar(c.id, 'Documento recebido', `Formulário respondido: ${nomeFormEnvio(e)}` + (extras.respondente ? ` (por ${extras.respondente})` : ''), e.caso_id)
  salvar('envios')
}
const salvarParcial = (e, valores, passo) => { const n = Object.values(valores).filter(v => !respostaVazia(v) && !/^data:image\//.test(String(v))).length; if (!e.iniciado_em) { e.iniciado_em = agora() } e.parcial = clonar(valores); if (e.status !== 'respondido') e.status = n && passo > 0 ? 'parcial' : (e.status === 'parcial' ? 'parcial' : 'iniciado'); e.parcial_em = agora(); salvar('envios') }

/* ---------- anexos do envio → Drive do cliente (REAL quando há pasta vinculada) ---------- */
async function guardarAnexosNoDrive(e, arquivos) {
  const c = contato(e.contato_id); const feitos = []
  for (const [pid, lista] of Object.entries(arquivos)) for (const f of lista) {
    if (!c.drive_pasta_id) throw { code: 'sem_pasta', message: 'Vincule a pasta do Drive do cliente (ficha › Drive do cliente) antes de receber arquivos.' }
    const pai = (c.drive_subpastas && c.drive_subpastas.documentos) || c.drive_pasta_id
    const r = await enviarArquivoDrive(f, pai); const a = arquivosDe({ files: [r && r.file ? r.file : r] })[0] || {}
    feitos.push({ pergunta_id: Number(pid), nome: f.name, tamanho: f.size, tipo: f.type, drive_id: a.id || null, link: a.link || '' })
  }
  return feitos
}

/* ---------- ponte com o CRM do site (Supabase): link público real, sem login da cliente ---------- */
const SQL_STR = s => "'" + String(s).replace(/'/g, "''") + "'"
const projetoSite = () => { const p = String((CONFIG.integr || {}).supabase || '').trim(); if (!/^[a-z0-9]{20}$/.test(p)) throw { code: 'sem_projeto' }; return p }
async function sqlEnvioSite(q) { // única escrita permitida: INSERT/UPDATE montados aqui, só em formulario_envios, com valores validados
  if (!/^(insert into public\.formulario_envios \(formulario_id, contato_id, token, expira_em, status\) values \(\d+, \d+, '[A-Za-z0-9_-]{32,64}', '[0-9T:.\-+Z]+', 'enviado'\) returning id|update public\.formulario_envios set expira_em = now\(\) where id = \d+ and respondido_em is null)$/.test(q)) throw { code: 'recusado' }
  return linhasSql(await conector('Supabase', 'execute_sql', { project_id: projetoSite(), query: q }))
}
async function criarEnvioNoSite(e) {
  if (!siteUrl()) throw { code: 'sem_site' }; const c = contato(e.contato_id); const f = formularioDe(e.formulario_id)
  const fone = String(c.telefone || ''); if (!/^\d{12,13}$/.test(fone)) throw { code: 'invalido', message: 'o cadastro precisa de telefone completo (com DDI 55) para achar a pessoa no CRM do site' }
  const pc = await sqlLeitura(`select id from public.contatos where telefone = ${SQL_STR(fone)} limit 1`); if (!pc.length) throw { code: 'invalido', message: 'essa pessoa ainda não existe no CRM do site (telefone ' + fone + ')' }
  const pf = await sqlLeitura(`select f.id, (select count(*) from public.formulario_itens i where i.formulario_id = f.id) as perguntas from public.formularios f where lower(f.nome) = lower(${SQL_STR(f.nome)}) limit 1`); if (!pf.length) throw { code: 'invalido', message: `o formulário “${f.nome}” ainda não existe no CRM do site` }
  const r = await sqlEnvioSite(`insert into public.formulario_envios (formulario_id, contato_id, token, expira_em, status) values (${Number(pf[0].id)}, ${Number(pc[0].id)}, '${e.token}', '${e.expira_em}', 'enviado') returning id`)
  e.site_id = r[0] && r[0].id; e.site_perguntas = Number(pf[0].perguntas); return e.site_id
}
async function revogarEnvioNoSite(e) { if (e.modo === 'site' && e.site_id) await sqlEnvioSite(`update public.formulario_envios set expira_em = now() where id = ${Number(e.site_id)} and respondido_em is null`) }
async function sincronizarEnviosDoSite() {
  const fones = [...new Set(DB.contatos.map(c => String(c.telefone || '')).filter(t => /^\d{12,13}$/.test(t)))]; if (!fones.length) { aviso('Nenhum cadastro com telefone completo (DDI 55).', 'erro'); return 0 }
  try {
    const rows = await sqlLeitura(`select e.id, e.token, e.status, e.created_at, e.visualizado_em, e.respondido_em, e.expira_em, f.nome as formulario, c.telefone from public.formulario_envios e join public.contatos c on c.id = e.contato_id left join public.formularios f on f.id = e.formulario_id where c.telefone in (${fones.map(SQL_STR).join(',')}) and e.created_at > now() - interval '120 days' order by e.created_at asc limit 200`)
    let novas = 0, mudou = 0
    for (const r of rows) {
      const c = DB.contatos.find(x => x.telefone === String(r.telefone)); if (!c) continue; let e = DB.envios.find(x => x.token === r.token)
      if (!e) { e = { id: proximoId('envios'), created_at: r.created_at, formulario_id: (DB.formularios.find(f => semAcento(f.nome) === semAcento(r.formulario || '')) || {}).id || null, formulario_nome: r.formulario || 'Formulário do site', contato_id: c.id, caso_id: null, token: r.token, modo: 'site', origem: 'site', site_id: r.id, expira_em: r.expira_em, status: r.status === 'respondido' ? 'visualizado' : r.status, enviado_em: null, visualizado_em: r.visualizado_em, respondido_em: null, respostas: {}, lembretes: [] }; DB.envios.push(e); mudou++ }
      const antes = e.status; if (r.visualizado_em && !e.visualizado_em) e.visualizado_em = r.visualizado_em; if (e.status !== 'respondido' && r.status === 'respondido') { e.status = 'respondido'; e.respondido_em = r.respondido_em; e.nova = true; novas++
        const rs = await sqlLeitura(`select ordem, pergunta_texto, pergunta_tipo, resposta from public.formulario_envio_respostas where envio_id = ${Number(r.id)} order by ordem asc limit 200`)
        e.snap = rs.map((x, i) => ({ pergunta_id: 'site' + i, texto: x.pergunta_texto, tipo: x.pergunta_tipo, mapear: null })); e.respostas = Object.fromEntries(rs.map((x, i) => ['site' + i, x.resposta])); registrar(c.id, 'Documento recebido', `Formulário respondido no site: ${e.formulario_nome}`) }
      else if (e.status === 'enviado' && r.status === 'visualizado') e.status = 'visualizado'
      if (e.status !== antes) mudou++
    }
    CONFIG.integr.form_sync = agora(); salvar('envios'); salvar('config'); aviso(novas ? `${plural(novas, 'resposta nova', 'respostas novas')} do site.` : mudou ? 'Status atualizados a partir do site.' : 'Nada novo no site.'); return novas
  } catch (err) { aviso(erroConector(err, 'Supabase'), 'erro'); return 0 }
}

/* ---------- mensagem ao cliente (WhatsApp/e-mail) ---------- */
const primeiroNome = c => String(c.nome || '').trim().split(/\s+/)[0] || ''
function textoEnvio(e, lembrete) {
  const c = contato(e.contato_id); const adv = (CONFIG.escritorio || {}).advogada_nome || 'a Dra. Lara'; const link = linkRealDoEnvio(e) || '[LINK AINDA NÃO GERADO NO SITE]'
  const prazo = e.prazo_resposta ? ` Se puder, responda até ${dataLonga(e.prazo_resposta)}.` : ''
  return lembrete ? `Olá, ${primeiroNome(c)}! Passando para lembrar do formulário “${nomeFormEnvio(e)}”, que ajuda a ${adv} a cuidar do seu caso.${prazo} Leva poucos minutos e dá para preencher pelo celular: ${link}\nO link é só seu e vale até ${dataLonga(e.expira_em)}. Qualquer dúvida, é só responder aqui.`
    : `Olá, ${primeiroNome(c)}! Aqui é do escritório da ${adv}. Para avançarmos, preciso que você preencha o formulário “${nomeFormEnvio(e)}”: ${link}${prazo}\nO link é individual (só você acessa), abre direto no celular, sem cadastro, e vale até ${dataLonga(e.expira_em)}. As informações são usadas só para o seu atendimento, conforme a LGPD.`
}
function marcarEnvioPorTexto(cid, texto, canal) {
  let n = 0; for (const e of DB.envios) { if (e.contato_id !== cid || !e.token || !String(texto).includes(e.token)) continue; if (!e.enviado_em) { e.enviado_em = agora(); e.canal_envio = canal; if (e.status === 'gerado') e.status = 'enviado' } else { (e.lembretes = e.lembretes || []).push({ em: agora(), canal }) } n++ }
  if (n) salvar('envios'); return n
}

/* ---------- criar envio (link individual por cliente/demanda) ---------- */
function enviarFormulario(c, f, opc = {}) {
  const forms = DB.formularios.filter(x => situacaoForm(x) === 'publicado'); if (!forms.length) { aviso('Publique um formulário antes de enviar.', 'erro'); return }
  const S = { cid: c ? c.id : '', fid: f ? f.id : (opc.caso ? forms[0] : forms.find(x => x.contexto !== 'demanda') || forms[0]).id, caso: opc.caso || '', validade: FORM_CFG().validade, prazo: '', modo: siteUrl() ? 'site' : 'teste' }
  const corpo = h('div', { class: 'space-y-4', 'data-testid': 'envio-config' }); let m
  const des = () => {
    const form = forms.find(x => x.id === Number(S.fid)); const casos = S.cid ? demandasDe(Number(S.cid)) : []
    const sel = (rot, valor, ops, onchange, tid) => h('label', { class: 'block' }, rotuloCampo(rot), h('select', { class: 'modal-input', 'data-testid': tid, onchange: ev => { onchange(ev.target.value); des() } }, ops.map(([v, t]) => h('option', { value: v, selected: String(v) === String(valor) }, t))))
    corpo.replaceChildren(
      c ? h('p', { class: 'text-sm' }, h('b', {}, 'Cliente: '), c.nome) : sel('Cliente', S.cid, [['', 'Escolha…'], ...DB.contatos.map(x => [x.id, x.nome || x.telefone])], v => { S.cid = v ? Number(v) : ''; S.caso = '' }, 'env-cliente'),
      sel('Formulário (só os publicados)', S.fid, forms.map(x => [x.id, `${x.nome} — ${CRM.CONTEXTOS[x.contexto].nome}`]), v => { S.fid = Number(v); const g = forms.find(x => x.id === Number(v)); S.validade = g.validade_dias || FORM_CFG().validade }, 'env-form'),
      S.cid ? sel(form.contexto === 'demanda' ? 'Demanda (obrigatória para este formulário)' : 'Vincular a uma demanda (opcional)', S.caso, [['', form.contexto === 'demanda' ? 'Escolha…' : '— nenhuma —'], ...casos.map(x => [x.id, x.titulo])], v => { S.caso = v ? Number(v) : '' }, 'env-caso') : null,
      h('div', { class: 'grid grid-cols-2 gap-3' }, h('label', {}, rotuloCampo('Link vale por (dias)'), h('input', { type: 'number', min: 1, max: 90, class: 'modal-input', value: S.validade, 'data-testid': 'env-validade', oninput: ev => { S.validade = Number(ev.target.value) } })), h('label', {}, rotuloCampo('Pedir resposta até (opcional)'), h('input', { type: 'date', class: 'modal-input', value: S.prazo, 'data-testid': 'env-prazo', onchange: ev => { S.prazo = ev.target.value } }))),
      h('div', {}, rotuloCampo('Tipo de link'), h('div', { class: 'grid gap-2' },
        h('label', { class: 'flex items-start gap-3 rounded-2xl border p-3 text-sm ' + (S.modo === 'site' ? 'border-primary bg-primary/5' : 'border-gray-200 dark:border-zinc-700') + (siteUrl() ? ' cursor-pointer' : ' opacity-60') }, h('input', { type: 'radio', name: 'modo', class: 'mt-1 accent-[#6f5636]', disabled: !siteUrl(), checked: S.modo === 'site', onclick: () => { S.modo = 'site'; des() }, 'data-testid': 'modo-site' }), h('div', {}, h('p', { class: 'font-semibold' }, 'Link real (CRM do site)'), h('p', { class: 'text-xs text-gray-500' }, siteUrl() ? 'A cliente abre no celular, sem login. Cria o envio no banco do CRM do site (Supabase), com confirmação.' : 'Indisponível: informe o endereço do site em Configurações › Conexões.'))),
        h('label', { class: 'flex items-start gap-3 rounded-2xl border p-3 text-sm cursor-pointer ' + (S.modo === 'teste' ? 'border-primary bg-primary/5' : 'border-gray-200 dark:border-zinc-700') }, h('input', { type: 'radio', name: 'modo', class: 'mt-1 accent-[#6f5636]', checked: S.modo === 'teste', onclick: () => { S.modo = 'teste'; des() }, 'data-testid': 'modo-teste' }), h('div', {}, h('p', { class: 'font-semibold' }, 'Teste / atendimento (neste artifact)'), h('p', { class: 'text-xs text-gray-500' }, 'Só abre aqui, para você. Serve para testar o fluxo ou preencher junto com a cliente na consulta. Não dá para enviar à cliente.'))))))
  }
  des(); m = modal({ titulo: 'Enviar formulário', largura: 'max-w-xl', corpo, rodape: fechar => [btn('Cancelar', { tipo: 'sec', onclick: fechar }), btn('Gerar link', { tid: 'gerar-link', onclick: async () => {
    const form = forms.find(x => x.id === Number(S.fid)); if (!S.cid) { aviso('Escolha o cliente.', 'erro'); return } if (form.contexto === 'demanda' && !S.caso) { aviso('Este formulário é de uma demanda: escolha a demanda.', 'erro'); return } if (!(S.validade >= 1 && S.validade <= 90)) { aviso('Validade entre 1 e 90 dias.', 'erro'); return }
    const e = { id: proximoId('envios'), created_at: agora(), formulario_id: form.id, formulario_nome: form.nome, contato_id: Number(S.cid), caso_id: S.caso ? Number(S.caso) : null, token: novoToken(), modo: S.modo, origem: 'artefato', expira_em: agora(S.validade * 1440), prazo_resposta: S.prazo || null, status: 'gerado', enviado_em: null, canal_envio: null, lembretes: [], visualizado_em: null, iniciado_em: null, respondido_em: null, respostas: {}, resumo: null }
    const grava = async () => { try { if (e.modo === 'site') await criarEnvioNoSite(e); DB.envios.push(e); registrar(e.contato_id, 'Anotação', `Link do formulário “${form.nome}” gerado (${e.modo === 'site' ? 'link real do site' : 'link de teste'}).`, e.caso_id); auditar('form_gerar_link', nomeContato(e.contato_id) + ' · ' + form.nome); salvar('envios'); fechar(); render(); painelEnvio(e) } catch (err) { aviso(err && err.code === 'sem_site' ? 'Informe o endereço do site em Configurações › Conexões.' : err && err.code === 'invalido' ? 'Não consegui criar o link real: ' + err.message + '.' : erroConector(err, 'Supabase'), 'erro') } }
    if (e.modo === 'site') confirmar('Criar o envio no CRM do site?', 'Será gravada UMA linha em formulario_envios (formulário, pessoa, código do link e validade) no banco do CRM do site, pelo conector do Supabase. Nada mais é alterado. Pode ser cancelada depois.', 'Criar link real', grava, false)
    else grava()
  } })] })
}

/* ---------- painel de um envio: link, envio por WhatsApp/e-mail, QR, prazo, cancelamento ---------- */
function qrSvg(texto) { try { return CRM.qrSvg ? CRM.qrSvg(texto) : null } catch (e) { return null } }
function painelEnvio(e, lembrete) {
  const c = contato(e.contato_id); const real = linkRealDoEnvio(e); const aberto = abertoEnvio(e); const texto = textoEnvio(e, lembrete || (e.enviado_em && !lembrete ? false : false))
  const cx = h('div', { class: 'space-y-4', 'data-testid': 'painel-envio' }, h('div', { class: 'flex flex-wrap items-center gap-2' }, badgeEnvio(e), badge(e.modo === 'site' ? 'Link real (site)' : 'Link de teste', e.modo === 'site' ? 'verde' : 'cinza'), h('span', { class: 'text-xs text-gray-500' }, `${nomeContato(e.contato_id)} · ${nomeFormEnvio(e)}` + (e.caso_id ? ' · ' + nomeDemanda(e.caso_id) : ''))),
    e.modo === 'site' ? h('div', { class: 'space-y-1' }, h('input', { class: 'modal-input', readonly: true, value: real, 'data-testid': 'link-form', onfocus: ev => ev.target.select() }), h('p', { class: 'text-[11px] text-gray-500' }, 'Link individual de ' + primeiroNome(c) + ': o CRM reconhece o cadastro por ele. Vale até ' + dataLonga(e.expira_em) + '. Quem tiver este link consegue responder: envie só para a própria cliente.'))
      : alerta('aviso', 'Link de teste', 'Este link só abre dentro deste artifact, para você. Para enviar de verdade à cliente, gere um link real (precisa do endereço do site em Configurações › Conexões). Abaixo, a mensagem que seria enviada:'),
    h('textarea', { class: 'modal-input text-sm', rows: 5, readonly: true, 'data-testid': 'msg-previa' }, texto),
    h('div', { class: 'flex flex-wrap gap-2' }, btn('Copiar link', { mini: true, tipo: 'sec', icone: 'ph:copy-bold', disabled: !real, tid: 'copiar-link', onclick: () => copiar(real) }), btn('Copiar mensagem', { mini: true, tipo: 'sec', icone: 'ph:chat-text-bold', disabled: !real, tid: 'copiar-msg', onclick: () => copiar(texto) }),
      btn(lembrete ? 'Lembrete por WhatsApp' : 'Enviar por WhatsApp', { mini: true, icone: 'ph:whatsapp-logo-bold', disabled: !real || !aberto, title: !real ? 'Precisa de link real' : '', tid: 'env-whatsapp', onclick: () => { abrirComunicacao(c.id, { canal: 'whatsapp', caso: e.caso_id || undefined, texto }) } }),
      btn(lembrete ? 'Lembrete por e-mail' : 'Enviar por e-mail', { mini: true, icone: 'ph:envelope-simple-bold', disabled: !real || !aberto, tid: 'env-email', onclick: () => { abrirComunicacao(c.id, { canal: 'email', caso: e.caso_id || undefined, texto, assunto: (lembrete ? 'Lembrete: ' : '') + nomeFormEnvio(e) }) } }),
      btn('QR Code', { mini: true, tipo: 'sec', icone: 'ph:qr-code-bold', disabled: !real, tid: 'env-qr', onclick: () => { const svg = qrSvg(real); modal({ titulo: 'QR Code do link', largura: 'max-w-sm', corpo: h('div', { class: 'text-center space-y-2' }, (() => { const d = h('div', { class: 'mx-auto w-56 bg-white p-2 rounded-xl', 'data-testid': 'qr-svg' }); d.innerHTML = svg || ''; return d })(), h('p', { class: 'text-xs text-gray-500' }, 'Para atendimento presencial: a cliente aponta a câmera do celular. O QR leva ao mesmo link individual.')) }) } }),
      btn('Preencher aqui (atendimento)', { mini: true, tipo: 'fantasma', icone: 'ph:user-focus-bold', disabled: !aberto, tid: 'abrir-como-cliente', onclick: () => { fecharTodas(); ir('publico', { token: e.token }) } })),
    h('div', { class: 'flex flex-wrap gap-2 items-end border-t border-gray-100 dark:border-zinc-800 pt-3' }, h('label', { class: 'text-xs' }, rotuloCampo('Prorrogar até'), h('input', { type: 'date', class: 'modal-input !py-1.5', id: 'prorrogar-data', min: hojeISO(1) })), btn('Prorrogar', { mini: true, tipo: 'sec', tid: 'prorrogar', disabled: !aberto && estadoEnvio(e) !== 'expirado', onclick: () => { const d = document.getElementById('prorrogar-data').value; if (!d || d <= hojeISO()) { aviso('Escolha uma data futura.', 'erro'); return } e.expira_em = new Date(d + 'T23:59:00-03:00').toISOString(); salvar('envios'); aviso('Validade prorrogada. ' + (e.modo === 'site' ? 'Atenção: no CRM do site a validade original continua valendo (gere um novo link).' : '')); render(); atualizarCamadas() } }),
      btn('Cancelar link', { mini: true, tipo: 'fantasma', icone: 'ph:prohibit-bold', disabled: !aberto, tid: 'cancelar-link', onclick: () => confirmar('Cancelar este link?', 'A cliente não poderá mais abrir. ' + (e.modo === 'site' ? 'No site, a validade será encerrada agora.' : ''), 'Cancelar link', async () => { try { await revogarEnvioNoSite(e) } catch (err) { aviso('Não consegui encerrar no site: ' + erroConector(err, 'Supabase'), 'erro'); return } e.status = 'cancelado'; e.cancelado_em = agora(); auditar('form_cancelar_link', nomeContato(e.contato_id)); salvar('envios'); render(); atualizarCamadas() }) })),
    h('ol', { class: 'text-xs text-gray-500 space-y-0.5', 'data-testid': 'historico-envio' }, eventosEnvio(e).map(([t, n]) => h('li', {}, dataHora(t) + ' — ' + n))))
  modal({ titulo: lembrete ? 'Lembrete de formulário' : 'Enviar ao cliente', largura: 'max-w-xl', corpo: cx, aoFechar: render })
}

/* ---------- ver / revisar / editar respostas ---------- */
function verEnvio(e) {
  const c = contato(e.contato_id); const itens = estruturaDoEnvio(e); const f = formularioDe(e.formulario_id)
  if (e.nova) { e.nova = false; salvar('envios') }
  const secoesDe = f ? f.secoes.map(s => ({ titulo: s.titulo, ids: new Set(s.itens.map(i => i.pergunta_id)) })) : [{ titulo: 'Respostas', ids: new Set(itens.map(i => i.pergunta_id)) }]
  const mostrar = it => { const v = e.respostas[it.pergunta_id]; if (it.tipo === 'assinatura' && typeof v === 'string' && v.startsWith('data:image/')) return h('img', { src: v, alt: 'Assinatura', class: 'h-20 bg-white rounded-lg border' }); if (it.tipo === 'arquivo') { const an = (e.anexos || []).filter(a => a.pergunta_id === it.pergunta_id); return an.length ? h('div', { class: 'space-y-0.5' }, an.map(a => a.link ? h('a', { href: a.link, target: '_blank', rel: 'noopener', class: 'underline text-sm block' }, '📎 ' + a.nome + ' (Drive)') : h('span', { class: 'text-sm block' }, '📎 ' + a.nome + ' — arquivo não guardado'))) : h('span', { class: 'text-sm' }, textoResposta(v)) } return h('span', { class: 'text-sm whitespace-pre-line' }, it.tipo === 'cpf_cnpj' && !respostaVazia(v) ? mascararDocumentoCompleto(v) : textoResposta(v)) }
  const corpoRespostas = h('div', { class: 'space-y-4', 'data-testid': 'respostas-lista' }, secoesDe.map(s => { const its = itens.filter(i => s.ids.has(i.pergunta_id)); return its.length ? h('section', { class: 'space-y-2' }, h('h4', { class: 'section-label' }, s.titulo || 'Respostas'), ...its.map(it => h('div', { class: 'rounded-xl bg-white/60 dark:bg-zinc-900/50 border border-gray-200/70 dark:border-zinc-800 px-3 py-2', 'data-testid': 'resp-' + it.texto }, h('p', { class: 'text-[11px] text-gray-500' }, it.texto, it.mapear ? h('span', { class: 'ml-1 text-secondary' }, '→ ' + DESTINOS.find(d => d[0] === it.mapear)?.[1].replace(/ \(.*/, '')) : null), mostrar(it)))) : null }), !f || itens.some(i => !secoesDe.some(s => s.ids.has(i.pergunta_id))) ? h('section', { class: 'space-y-2' }, ...itens.filter(i => !secoesDe.some(s => s.ids.has(i.pergunta_id))).map(it => h('div', { class: 'rounded-xl bg-white/60 dark:bg-zinc-900/50 border border-gray-200/70 dark:border-zinc-800 px-3 py-2' }, h('p', { class: 'text-[11px] text-gray-500' }, it.texto), mostrar(it)))) : null)
  modal({ titulo: 'Respostas recebidas', largura: 'max-w-2xl', corpo: h('div', { class: 'space-y-4', 'data-testid': 'detalhe-resposta' },
    h('div', { class: 'grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-1 text-sm' }, h('p', {}, h('b', {}, 'Cliente: '), c ? c.nome : '—'), h('p', {}, h('b', {}, 'Formulário: '), nomeFormEnvio(e)), e.caso_id ? h('p', {}, h('b', {}, 'Demanda: '), nomeDemanda(e.caso_id)) : null, h('p', {}, h('b', {}, 'Respondido em: '), e.respondido_em ? dataHora(e.respondido_em) : '—'), h('p', {}, h('b', {}, 'Quem respondeu: '), e.respondente ? `${e.respondente} (declarado) — pelo link individual de ${c ? c.nome : 'cliente'}` : `pelo link individual de ${c ? c.nome : 'cliente'}`), h('p', {}, h('b', {}, 'Origem: '), e.origem === 'site' ? 'CRM do site' : e.modo === 'teste' ? 'Teste / atendimento' : 'Artifact'), e.consentimento_em ? h('p', {}, h('b', {}, 'Ciência da privacidade: '), dataHora(e.consentimento_em)) : null),
    e.resumo ? h('div', { class: 'rounded-2xl bg-secondary/10 border border-secondary/30 p-4' }, h('p', { class: 'text-xs font-semibold uppercase tracking-wider text-secondary-dark dark:text-cafe-creme mb-1' }, 'Resumo em palavras da cliente'), h('p', { class: 'text-sm whitespace-pre-line' }, e.resumo)) : null,
    e.revisado_em ? alerta('ok', null, 'Revisado em ' + dataHora(e.revisado_em) + '.') : null, e.editado_em ? alerta('info', null, 'Respostas editadas internamente em ' + dataHora(e.editado_em) + '. As respostas originais da cliente ficam guardadas.') : null,
    corpoRespostas, e.aplicado_log && e.aplicado_log.length ? h('div', { class: 'text-xs text-gray-500' }, h('b', {}, 'Aplicado ao cadastro: '), e.aplicado_log.map(l => `${l.campo}: ${l.antes || '(vazio)'} → ${l.depois}`).join(' · ')) : null,
    h('ol', { class: 'text-xs text-gray-500 space-y-0.5' }, eventosEnvio(e).map(([t, n]) => h('li', {}, dataHora(t) + ' — ' + n)))),
    rodape: fechar => [btn('Abrir ficha', { tipo: 'fantasma', onclick: () => { fechar(); abrirFicha(e.contato_id) } }), btn('Exportar (.csv)', { tipo: 'sec', icone: 'ph:download-bold', tid: 'exportar-csv', onclick: () => exportarEnvio(e) }), btn('Editar respostas', { tipo: 'sec', tid: 'editar-respostas', onclick: () => { fechar(); editarRespostas(e) } }), btn('Aplicar ao cadastro', { tipo: 'sec', tid: 'revisar-aplicar', onclick: () => { fechar(); revisarEAplicar(e) } }), btn(e.revisado_em ? 'Revisado' : 'Marcar como revisado', { tid: 'marcar-revisado', disabled: !!e.revisado_em, onclick: () => { e.revisado_em = agora(); salvar('envios'); fechar(); render(); atualizarCamadas() } })], aoFechar: render })
}
function editarRespostas(e) {
  const itens = estruturaDoEnvio(e).filter(i => ['texto_curto', 'texto_longo', 'numero', 'data', 'email', 'telefone', 'horario', 'cpf_cnpj'].includes(i.tipo)); const novo = clonar(e.respostas)
  modal({ titulo: 'Editar respostas (uso interno)', largura: 'max-w-xl', corpo: h('div', { class: 'space-y-3', 'data-testid': 'editar-resp' }, alerta('info', null, 'Use para corrigir um dado evidente (ex.: erro de digitação). As respostas originais da cliente ficam guardadas e a alteração é auditada. Perguntas de escolha, endereço, arquivos e assinatura não são editáveis aqui.'), ...itens.map(it => h('label', { class: 'block' }, rotuloCampo(it.texto), (it.tipo === 'texto_longo' ? h('textarea', { class: 'modal-input', rows: 3, value: novo[it.pergunta_id] || '', 'data-testid': 'ed-' + it.pergunta_id, oninput: ev => { novo[it.pergunta_id] = ev.target.value } }) : h('input', { class: 'modal-input', value: novo[it.pergunta_id] || '', 'data-testid': 'ed-' + it.pergunta_id, oninput: ev => { novo[it.pergunta_id] = ev.target.value } }))))),
    rodape: fechar => [btn('Cancelar', { tipo: 'sec', onclick: fechar }), btn('Salvar edição', { tid: 'salvar-edicao', onclick: () => { const mud = itens.filter(i => (novo[i.pergunta_id] || '') !== (e.respostas[i.pergunta_id] || '')); if (!mud.length) { fechar(); return } e.respostas_originais = e.respostas_originais || clonar(e.respostas); mud.forEach(i => { e.respostas[i.pergunta_id] = novo[i.pergunta_id] || null }); e.editado_em = agora(); auditar('form_editar_resposta', nomeContato(e.contato_id) + ' · ' + mud.map(i => i.texto).join(', ')); registrar(e.contato_id, 'Anotação', 'Respostas do formulário corrigidas internamente: ' + mud.map(i => i.texto).join(', '), e.caso_id); salvar('envios'); fechar(); aviso('Edição salva (original preservado).'); render(); atualizarCamadas() } })] })
}
async function exportarEnvio(e) {
  const csv = '﻿pergunta;resposta\n' + estruturaDoEnvio(e).map(p => `"${p.texto.replace(/"/g, '""')}";"${(p.tipo === 'assinatura' ? '(assinatura)' : textoResposta(e.respostas[p.pergunta_id])).replace(/"/g, '""')}"`).join('\n')
  try { const dl = window.claude && window.claude.use ? await window.claude.use('downloads') : null; if (!dl) throw new Error('indisponível'); await dl.save({ filename: `respostas-${nomeFormEnvio(e).toLowerCase().replace(/[^a-z0-9]+/g, '-')}.csv`, data: csv }) } catch (err) { copiar(csv); aviso('Download indisponível aqui: copiei o CSV para a área de transferência.') }
}

/* ---------- ficha do cliente / da demanda ---------- */
const linhaEnvio = e => [h('div', { class: 'flex-1 min-w-0' }, h('p', { class: 'font-semibold truncate' }, nomeFormEnvio(e)), h('p', { class: 'text-[11px] text-gray-500' }, 'Gerado ' + dataLonga(e.created_at) + (e.caso_id ? ' · ' + nomeDemanda(e.caso_id) : '') + (e.respondido_em ? ' · respondido ' + dataLonga(e.respondido_em) : e.prazo_resposta ? ' · responder até ' + dataLonga(e.prazo_resposta) : ''))), badgeEnvio(e), e.status === 'respondido' ? btn('Ver', { mini: true, tipo: 'sec', onclick: () => verEnvio(e), tid: 'ver-resposta' }) : btn(abertoEnvio(e) ? 'Enviar / lembrar' : 'Abrir', { mini: true, tipo: 'sec', tid: 'abrir-envio', onclick: () => painelEnvio(e, !!e.enviado_em) })]
function fichaPerguntas(c) {
  const forms = formsDoEscopo('cliente'); const envios = DB.envios.filter(e => e.contato_id === c.id).sort((a, b) => b.created_at.localeCompare(a.created_at))
  return h('div', { class: 'space-y-5' }, painel('Formulários enviados', h('div', { class: 'flex justify-end mb-2' }, btn('Enviar formulário', { mini: true, icone: 'ph:paper-plane-tilt-bold', tid: 'enviar-formulario', onclick: () => enviarFormulario(c) })), envios.length ? lista(envios.map(linhaEnvio)) : estadoVazio('ph:paper-plane-tilt-bold', 'Nenhum formulário enviado', 'Escolha um formulário publicado, gere o link individual e envie.')), h('h4', { class: 'section-label' }, 'Informações do cliente (respostas)'), blocoFicha(forms, c, () => {}))
}
const painelFormulariosDaDemanda = x => { const envios = DB.envios.filter(e => e.caso_id === x.id).sort((a, b) => b.created_at.localeCompare(a.created_at)); return painel('Formulários desta demanda', h('div', { class: 'flex justify-end mb-2' }, btn('Enviar formulário', { mini: true, icone: 'ph:paper-plane-tilt-bold', tid: 'enviar-form-demanda', onclick: () => enviarFormulario(contato(x.contato_id), null, { caso: x.id }) })), envios.length ? lista(envios.map(linhaEnvio)) : h('p', { class: 'text-sm text-gray-400' }, 'Nenhum formulário ligado a esta demanda.')) }

/* ---------- itens para o “Hoje” e contador do menu ---------- */
function itensFormularioHoje() {
  const out = []; const h0 = hojeISO(); const dias = FORM_CFG().lembreteDias
  for (const e of DB.envios) {
    if (e.nova && e.status === 'respondido') out.push({ tipo: 'formulario', envio_id: e.id, envio_acao: 'revisar', contato_id: e.contato_id, titulo: `Formulário respondido para revisar: ${nomeFormEnvio(e)}`, quando: diaDe(e.respondido_em) })
    else if (abertoEnvio(e) && (atrasadoEnvio(e) || (dias > 0 && e.enviado_em && diasEntre(diaDe((e.lembretes || []).at(-1)?.em || e.enviado_em), h0) >= dias))) out.push({ tipo: 'formulario', envio_id: e.id, envio_acao: 'lembrar', contato_id: e.contato_id, titulo: `Formulário sem resposta há ${diasEntre(diaDe((e.lembretes || []).at(-1)?.em || e.enviado_em), h0)} dias: ${nomeFormEnvio(e)}`, quando: diaDe((e.lembretes || []).at(-1)?.em || e.enviado_em), atraso: atrasadoEnvio(e) })
  }
  return out
}
const formulariosARever = () => DB.envios.filter(e => e.nova && e.status === 'respondido').length

/* ---------- gerenciador: lista e caixa de entrada ---------- */
UI.form.sit = 'publicado'; UI.form.est = 'todos'
VIEWS.formularios = (p) => {
  if (p && p.editar) { if (!CONSTR || CONSTR.id !== p.editar) CONSTR = { id: p.editar, el: Construtor(p.editar) }; return CONSTR.el }
  if (p && p.aba) UI.form.aba = p.aba
  const A = UI.form.aba; let corpo
  const nomeProc = v => (v.endsWith('/*') ? CRM.SERVICOS.find(s => s.id === v.slice(0, -2))?.nome : CRM.PROCEDIMENTOS.find(x => x.valor === v)?.rotulo) || v
  const chips = (lista_, atual, aoEscolher, pre) => h('div', { class: 'flex flex-wrap gap-2' }, lista_.map(([k, t]) => h('button', { type: 'button', class: 'chip ' + (atual === k ? 'chip-escuro' : ''), 'data-testid': pre + k, onclick: () => { aoEscolher(k); render() } }, t)))
  if (A === 'formularios') {
    const vis_ = DB.formularios.filter(f => (UI.form.ctx === 'todos' || f.contexto === UI.form.ctx) && (UI.form.sit === 'todos' || situacaoForm(f) === UI.form.sit))
    const qtd = s => DB.formularios.filter(f => situacaoForm(f) === s).length
    corpo = [h('div', { class: 'flex flex-wrap gap-x-6 gap-y-2' }, chips([['todos', 'Todos'], ...Object.entries(CRM.CONTEXTOS).map(([k, c]) => [k, c.nome])], UI.form.ctx, k => { UI.form.ctx = k }, 'ctx-filtro-'), chips([['publicado', `Publicados (${qtd('publicado')})`], ['rascunho', `Rascunhos (${qtd('rascunho')})`], ['arquivado', `Arquivados (${qtd('arquivado')})`], ['todos', 'Todas as situações']], UI.form.sit, k => { UI.form.sit = k }, 'sit-filtro-')),
      vis_.length ? h('div', { class: 'grid grid-cols-1 lg:grid-cols-2 gap-4' }, vis_.map(f => { const sit = situacaoForm(f); const env = DB.envios.filter(e => e.formulario_id === f.id); return h('article', { class: 'rounded-3xl bg-white/70 dark:bg-zinc-900/60 border-l-[3px] border-secondary border-y border-r border-gray-200/70 dark:border-zinc-800 p-5 flex flex-col gap-3', 'data-testid': 'form-' + f.id },
        h('header', { class: 'flex items-start justify-between gap-3' }, h('div', { class: 'min-w-0' }, h('button', { type: 'button', class: 'font-semibold text-lg text-primary dark:text-zinc-100 hover:underline text-left', onclick: () => ir('formularios', { editar: f.id }) }, f.nome), f.descricao ? h('p', { class: 'text-xs text-gray-500 mt-0.5 line-clamp-2' }, f.descricao) : null), h('div', { class: 'flex flex-col items-end gap-1 shrink-0' }, badge(SITUACOES[sit][0], SITUACOES[sit][1]), h('span', { class: 'text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full bg-secondary/20 text-secondary-dark dark:text-cafe-creme' }, CRM.CONTEXTOS[f.contexto].nome))),
        h('p', { class: 'text-xs text-gray-400' }, `${itensDe(f).length} pergunta(s)`, f.contexto === 'demanda' ? ' · ' + (f.procedimentos.length ? f.procedimentos.map(nomeProc).join(', ') : 'todas as demandas') : '', ` · ${env.length} envio(s) · ${env.filter(e => e.status === 'respondido').length} respondido(s) · ${env.filter(abertoEnvio).length} pendente(s)`),
        h('div', { class: 'flex flex-wrap gap-2 mt-auto' }, h('button', { type: 'button', class: 'chip', onclick: () => ir('formularios', { editar: f.id }), 'data-testid': 'editar-' + f.id }, 'Editar'), sit === 'publicado' ? h('button', { type: 'button', class: 'chip', 'data-testid': 'enviar-' + f.id, onclick: () => enviarFormulario(null, f) }, 'Enviar') : null, h('button', { type: 'button', class: 'chip', onclick: () => { const id = duplicarForm(f); ir('formularios', { editar: id }) }, 'data-testid': 'duplicar-' + f.id }, 'Duplicar'), sit === 'arquivado' || sit === 'rascunho' ? h('button', { type: 'button', class: 'chip', 'data-testid': 'publicar-' + f.id, onclick: () => { f.situacao = 'publicado'; f.ativo = true; salvar('formularios'); render() } }, 'Publicar') : h('button', { type: 'button', class: 'chip', 'data-testid': 'arquivar-' + f.id, onclick: () => { f.situacao = 'arquivado'; f.ativo = false; salvar('formularios'); render(); aviso('Formulário arquivado. Envios já feitos continuam valendo.') } }, 'Arquivar'))) })) : estadoVazio('ph:clipboard-text-bold', 'Nenhum formulário aqui', UI.form.sit === 'publicado' ? 'Crie um formulário ou veja os rascunhos.' : 'Nada nesta situação.', btn('Novo formulário', { onclick: novoFormulario }))]
  } else {
    const q = semAcento(UI.form.rq); const est = UI.form.est
    const todos = DB.envios.filter(e => (!q || semAcento(nomeContato(e.contato_id)).includes(q)) && (!UI.form.rf || e.formulario_id === Number(UI.form.rf)) && (!UI.form.rde || diaDe(e.respondido_em || e.created_at) >= UI.form.rde) && (!UI.form.rate || diaDe(e.respondido_em || e.created_at) <= UI.form.rate))
    const cont = { todos: todos.length, revisar: todos.filter(e => e.nova && e.status === 'respondido').length, pendentes: todos.filter(abertoEnvio).length, respondidos: todos.filter(e => e.status === 'respondido').length, expirados: todos.filter(e => ['expirado', 'cancelado'].includes(estadoEnvio(e))).length }
    const rows = todos.filter(e => est === 'todos' || (est === 'revisar' && e.nova && e.status === 'respondido') || (est === 'pendentes' && abertoEnvio(e)) || (est === 'respondidos' && e.status === 'respondido') || (est === 'expirados' && ['expirado', 'cancelado'].includes(estadoEnvio(e)))).sort((a, b) => (b.respondido_em || b.created_at).localeCompare(a.respondido_em || a.created_at))
    corpo = [h('div', { class: 'flex flex-wrap gap-2 items-center' }, chips([['todos', `Todos (${cont.todos})`], ['revisar', `A revisar (${cont.revisar})`], ['pendentes', `Aguardando resposta (${cont.pendentes})`], ['respondidos', `Respondidos (${cont.respondidos})`], ['expirados', `Expirados/cancelados (${cont.expirados})`]], est, k => { UI.form.est = k }, 'est-filtro-')),
      h('div', { class: 'flex flex-wrap gap-2 items-center' }, h('div', { class: 'w-64' }, busca(UI.form.rq, v => { UI.form.rq = v; render() }, 'Buscar por nome da cliente…')), h('select', { class: 'selecao', 'aria-label': 'Formulário', onchange: ev => { UI.form.rf = ev.target.value; render() } }, h('option', { value: '' }, 'Todos os formulários'), DB.formularios.map(f => h('option', { value: f.id, selected: String(f.id) === String(UI.form.rf) }, f.nome))), h('label', { class: 'flex items-center gap-1.5 text-xs text-gray-500' }, 'De', h('input', { type: 'date', class: 'selecao', value: UI.form.rde, 'aria-label': 'De', onchange: ev => { UI.form.rde = ev.target.value; render() } })), h('label', { class: 'flex items-center gap-1.5 text-xs text-gray-500' }, 'até', h('input', { type: 'date', class: 'selecao', value: UI.form.rate, 'aria-label': 'Até', onchange: ev => { UI.form.rate = ev.target.value; render() } })), btn('Buscar respostas do site', { mini: true, tipo: 'sec', icone: 'ph:cloud-arrow-down-bold', tid: 'sincronizar-form-site', onclick: sincronizarEnviosDoSite }),
        h('span', { class: 'text-[11px] text-gray-400' }, CONFIG.integr.form_sync ? 'Última busca no site: ' + dataHora(CONFIG.integr.form_sync) : 'Respostas dadas no CRM do site entram por aqui (somente leitura).')),
      tabela([{ nome: 'Cliente', cel: e => link(nomeContato(e.contato_id), () => abrirFicha(e.contato_id)) }, { nome: 'Formulário', cel: e => h('span', {}, nomeFormEnvio(e), e.caso_id ? h('span', { class: 'block text-[11px] text-gray-400' }, nomeDemanda(e.caso_id)) : null) }, { nome: 'Status', cel: badgeEnvio }, { nome: 'Enviado', cel: e => e.enviado_em ? dataHora(e.enviado_em) : h('span', { class: 'text-gray-400' }, 'não enviado') }, { nome: 'Respondeu / prazo', cel: e => e.respondido_em ? dataHora(e.respondido_em) : e.prazo_resposta ? 'até ' + dataLonga(e.prazo_resposta) : '—' }, { nome: '', cel: e => e.status === 'respondido' ? btn('Ver respostas', { mini: true, tipo: 'sec', onclick: () => verEnvio(e), tid: 'ver-resposta' }) : btn(abertoEnvio(e) ? (e.enviado_em ? 'Lembrar / reenviar' : 'Enviar') : 'Abrir', { mini: true, tipo: 'sec', tid: 'abrir-envio', onclick: () => painelEnvio(e, !!e.enviado_em) }) }], rows, { vazio: est === 'todos' ? 'Nenhum envio ainda' : 'Nada nesta visão', vazioTexto: 'Envie um formulário pela ficha do cliente ou pela lista de formulários.', icone: 'ph:paper-plane-tilt-bold' })]
  }
  return pagina('Formulários', 'Crie o formulário uma vez, gere o link individual do cliente, envie por WhatsApp ou e-mail e receba as respostas já ligadas ao cadastro e à demanda.', A === 'formularios' ? [btn('Novo formulário', { icone: 'ph:plus-bold', onclick: novoFormulario, tid: 'novo-formulario' })] : null,
    h('div', { class: 'flex gap-2' }, h('button', { type: 'button', class: 'tab-btn ' + (A === 'formularios' ? 'tab-btn-ativo' : ''), onclick: () => { UI.form.aba = 'formularios'; render() }, 'data-testid': 'aba-formularios' }, 'Meus formulários'), h('button', { type: 'button', class: 'tab-btn ' + (A === 'respostas' ? 'tab-btn-ativo' : ''), onclick: () => { UI.form.aba = 'respostas'; render() }, 'data-testid': 'aba-respostas' }, 'Envios e respostas' + (formulariosARever() ? ` (${formulariosARever()})` : ''))), ...corpo)
}

/* ---------- construtor: instruções, finalidade, validade, “levar ao cadastro” e situação ---------- */
function cabecalhoExtra(F, toque) {
  const campo = (rot, chave, ph, linhas, tid) => h('label', { class: 'block' }, rotuloCampo(rot), (() => { const t = h(linhas ? 'textarea' : 'input', { class: 'modal-input !text-sm', rows: linhas, placeholder: ph, 'data-testid': tid }); t.value = F[chave] || ''; t.addEventListener('input', () => { F[chave] = t.value || null; toque() }); return t })())
  const val = h('input', { type: 'number', min: 1, max: 90, class: 'modal-input !w-28', value: F.validade_dias || '', placeholder: String(FORM_CFG().validade), 'data-testid': 'form-validade', oninput: ev => { F.validade_dias = ev.target.value ? Number(ev.target.value) : null; toque() } })
  const sens = [...new Set(F.secoes.flatMap(s => s.itens).map(i => TIPOS_SENSIVEIS[i.tipo]).filter(Boolean))]
  return h('details', { class: 'rounded-xl border border-dashed border-gray-300 dark:border-zinc-700 p-3', open: !!(F.instrucoes || F.finalidade || F.mensagem_final), 'data-testid': 'config-envio' }, h('summary', { class: 'cursor-pointer text-xs font-semibold uppercase tracking-wider text-gray-500' }, 'Instruções, privacidade e envio'),
    h('div', { class: 'space-y-3 mt-3' }, campo('Instruções para quem preenche (aparecem no topo)', 'instrucoes', 'Ex.: Tenha em mãos RG, CPF e certidão de casamento. Leva uns 10 minutos.', 3, 'form-instrucoes'), campo('Para que usamos estes dados (finalidade — LGPD)', 'finalidade', 'Ex.: Preparar o seu inventário e a procuração. Os dados não são usados para outra finalidade.', 2, 'form-finalidade'), campo('Mensagem ao concluir', 'mensagem_final', 'Ex.: Recebemos! A Dra. Lara entra em contato em até 2 dias úteis.', 2, 'form-mensagem-final'),
      h('label', { class: 'flex items-center gap-2 text-sm' }, 'Link vale por', val, 'dias (padrão do escritório: ' + FORM_CFG().validade + ')'), sens.length ? h('p', { class: 'text-xs rounded-lg bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-900 p-2 text-amber-900 dark:text-amber-200', 'data-testid': 'aviso-sensivel' }, 'Este formulário coleta ' + sens.join(', ') + '. Peça só o necessário, informe a finalidade acima e envie apenas por link individual.') : null))
}
function mapeamentoPergunta(p, F, toque, desenhar) {
  if (CRM.tipoInterno(p.tipo) || F.contexto === 'demanda') return null
  const ok = Object.entries(DESTINO_TIPOS).filter(([, ts]) => ts.includes(p.tipo)).map(([k]) => k); if (!ok.length && p.tipo !== 'arquivo') return null
  if (p.tipo === 'arquivo') { const i = h('input', { class: 'modal-input !text-sm', placeholder: 'Documento pendente que este arquivo comprova (ex.: Certidão de casamento)', 'data-testid': 'edit-doc' }); i.value = p.doc_desc || ''; i.addEventListener('input', () => { p.doc_desc = i.value || null; toque() }); return h('label', { class: 'block' }, rotuloCampo('Vincular ao documento da demanda'), i, h('span', { class: 'text-[11px] text-gray-400' }, 'Ao revisar, o arquivo é ligado ao documento pendente de mesmo nome na demanda do envio.')) }
  return h('label', { class: 'block' }, rotuloCampo('Levar ao cadastro'), h('select', { class: 'modal-input !text-sm', 'data-testid': 'edit-mapear', onchange: ev => { p.mapear = ev.target.value || null; toque() } }, DESTINOS.filter(d => !d[0] || ok.includes(d[0])).map(d => h('option', { value: d[0], selected: (p.mapear || '') === d[0] }, d[1]))), h('span', { class: 'text-[11px] text-gray-400' }, 'A resposta só vai ao cadastro depois da sua conferência.'))
}
function botoesSituacao(F, salvarForm, desenhar) {
  const sit = situacaoForm(F); const mudar = (s, msg) => { F.situacao = s; F.ativo = s === 'publicado'; salvarForm(); if (msg) aviso(msg) }
  return h('div', { class: 'flex items-center gap-2' }, badge(SITUACOES[sit][0], SITUACOES[sit][1]), sit !== 'publicado' ? btn('Publicar', { mini: true, tid: 'publicar-form', onclick: () => mudar('publicado', 'Formulário publicado: já pode ser enviado.') }) : btn('Arquivar', { mini: true, tipo: 'sec', tid: 'arquivar-form', onclick: () => mudar('arquivado', 'Arquivado: some da lista de envio; o histórico fica.') }), sit === 'publicado' ? btn('Enviar…', { mini: true, tipo: 'sec', icone: 'ph:paper-plane-tilt-bold', tid: 'enviar-do-construtor', onclick: () => { const o = formularioDe(F.id); if (JSON.stringify(o) !== JSON.stringify(F)) { aviso('Salve as alterações antes de enviar.', 'erro'); return } enviarFormulario(null, o) } }) : null)
}

/* ================= PÁGINA DA CLIENTE (/publico/token) ================= */
function FormulariosPublico() {
  const p = R.p || {}; const e0 = p.token ? DB.envios.find(x => x.token === p.token) : null
  const pagina_ = (...kids) => h('div', { class: 'min-h-screen bg-[#edeae2] dark:bg-zinc-950 text-gray-900 dark:text-zinc-100' }, h('header', { class: 'bg-cafe px-4 py-4 flex items-center justify-between' }, h('img', { src: LOGOS.wordmarkLight, alt: 'Lara Café', class: 'h-6 w-auto' }), btn('Voltar ao CRM', { tipo: 'sec', mini: true, class: '!text-cafe-creme !border-cafe-creme/40', onclick: () => ir('formularios', { aba: 'respostas' }), tid: 'voltar-crm' })), h('div', { class: 'max-w-2xl mx-auto px-4 py-8 space-y-4' }, h('div', { class: 'rounded-2xl border border-secondary/40 bg-secondary/10 p-2 text-[11px] text-center font-semibold text-secondary-dark dark:text-cafe-creme' }, 'Visão da cliente (teste / atendimento) — dentro do artifact. A cliente de verdade usa o link real do site, sem login.'), ...kids), h('p', { class: 'text-xs text-gray-400 text-center pb-8' }, 'Lara Café Advocacia · seus dados são usados só para o seu atendimento (LGPD).'))
  if (!p.token) { const abertos = DB.envios.filter(abertoEnvio); return pagina_(h('h1', { class: 'text-2xl text-primary dark:text-zinc-100' }, 'Preencher como a cliente'), h('p', { class: 'text-sm text-gray-500' }, 'Escolha um envio em aberto para preencher (teste ou atendimento presencial).'), abertos.length ? lista(abertos.map(e => [h('div', { class: 'flex-1' }, h('p', { class: 'font-semibold' }, nomeFormEnvio(e)), h('p', { class: 'text-[11px] text-gray-500' }, 'Para ' + nomeContato(e.contato_id))), btn('Preencher', { mini: true, onclick: () => ir('publico', { token: e.token }) })])) : estadoVazio('ph:tray-bold', 'Nenhum envio em aberto')) }
  if (!e0) return pagina_(alerta('erro', 'Link inválido', 'Este link não existe ou foi removido.'))
  const e = e0; const est = estadoEnvio(e)
  if (p.agradecer) return pagina_(h('div', { class: 'card text-center space-y-2', 'data-testid': 'obrigada' }, ic('ph:check-circle-bold', 'text-4xl text-success'), h('h1', { class: 'text-2xl text-primary dark:text-zinc-100' }, 'Recebemos suas respostas'), h('p', { class: 'text-sm text-gray-500 whitespace-pre-line' }, (formularioDe(e.formulario_id) || {}).mensagem_final || 'Obrigada! A Dra. Lara já vê tudo na sua ficha, sem você precisar repetir nada.')))
  if (est === 'cancelado' || est === 'expirado') return pagina_(alerta('aviso', est === 'expirado' ? 'Link expirado' : 'Link cancelado', 'Peça um novo link ao escritório.'))
  if (est === 'respondido') return pagina_(alerta('ok', 'Respostas já enviadas', 'Obrigada! Recebemos suas respostas.'))
  const f = formularioDe(e.formulario_id); if (!f) return pagina_(alerta('erro', 'Formulário indisponível', 'Este formulário não está mais disponível.'))
  if (e.modo === 'site') return pagina_(alerta('aviso', 'Este é um link real', 'A cliente responde pelo endereço do site, não aqui. Use “Preencher aqui” só em envios de teste/atendimento.'))
  if (['gerado', 'enviado'].includes(e.status)) { e.status = 'visualizado'; e.visualizado_em = agora(); salvar('envios') }
  const valores = clonar(e.parcial || {}); const arquivos = {}; const resumoI = h('textarea', { class: 'modal-input', rows: 4, placeholder: 'Escreva do seu jeito', 'data-testid': 'resumo-livre' }); const nomeI = h('input', { class: 'modal-input', placeholder: 'Seu nome (quem está preenchendo)', value: '', 'data-testid': 'respondente' }); const aceite = h('input', { type: 'checkbox', class: 'mt-1 accent-[#6f5636]', 'data-testid': 'aceite-privacidade' }); const aviso_ = h('p', { class: 'text-sm text-danger hidden', 'data-testid': 'erro-envio' })
  let passoAtual = 0; let enviando = false
  const form = Preenchimento({ secoes: f.secoes, valores, arquivos, rotuloEnviar: 'Enviar respostas', aoMudar: () => { if (!e.iniciado_em || e.status === 'visualizado') salvarParcial(e, valores, passoAtual); else { e.parcial = clonar(valores); clearTimeout(e.__t); e.__t = setTimeout(() => salvar('envios'), 500) } }, aoPasso: n => { passoAtual = n; salvarParcial(e, valores, n) },
    aoEnviar: async () => { if (enviando) return; if (!aceite.checked) { aviso_.textContent = 'Para enviar, confirme que leu o aviso de privacidade.'; aviso_.classList.remove('hidden'); return } aviso_.classList.add('hidden'); enviando = true
      try { const anexos = Object.keys(arquivos).some(k => arquivos[k].length) ? await guardarAnexosNoDrive(e, arquivos) : []; registrarEnvio(e, valores, { resumo: resumoI.value.trim(), respondente: nomeI.value.trim(), consentimento: true, anexos }); ir('publico', { token: e.token, agradecer: true }) }
      catch (err) { enviando = false; aviso_.textContent = err && err.code === 'sem_pasta' ? err.message : erroConector(err, 'Google Drive'); aviso_.classList.remove('hidden') } },
    slotInicio: () => h('div', { class: 'space-y-4' }, f.instrucoes ? h('section', { class: 'card' }, h('p', { class: 'text-sm whitespace-pre-line', 'data-testid': 'instrucoes' }, f.instrucoes)) : null, f.contexto === 'consulta' ? h('section', { class: 'card space-y-2' }, h('span', { class: 'rotulo' }, 'Conte um pouco da sua situação'), resumoI) : null),
    slotFim: () => h('section', { class: 'card space-y-3' }, h('label', { class: 'block' }, rotuloCampo('Quem está preenchendo?'), nomeI), h('label', { class: 'flex items-start gap-2 text-sm cursor-pointer' }, aceite, h('span', {}, 'Li o aviso de privacidade e concordo com o uso destas informações para o meu atendimento. ', h('span', { class: 'text-gray-500' }, f.finalidade ? 'Finalidade: ' + f.finalidade : 'Os dados são usados apenas para a prestação do serviço jurídico e protegidos pelo sigilo profissional.'))), aviso_) })
  return pagina_(h('section', { class: 'card border-t-8 !border-t-secondary space-y-1' }, h('h1', { class: 'text-3xl text-primary dark:text-zinc-100', 'data-testid': 'publico-titulo' }, f.nome), f.descricao ? h('p', { class: 'text-sm text-gray-500 whitespace-pre-line' }, f.descricao) : null, h('p', { class: 'text-xs text-gray-400' }, 'Olá, ' + primeiroNome(contato(e.contato_id) || {}) + '. * indica resposta obrigatória.' + (e.parcial ? ' Você pode continuar de onde parou.' : ''))), form)
}
