'use strict'
/* ============ Escritório: Padrões operacionais, Mapa operacional, Configurações, Auditoria, Perfil, Secretária ============ */
UI.manual = { fase: 'atendimento' }; UI.audit = { q: '' }; UI.sec = { aba: 'inicio', q: '', area: '' }; UI.mapa = { sel: null }
const ehAdmin = () => CONFIG.perfil.papel === 'admin'
const semPermissao = (nome) => pagina(nome, null, null, estadoVazio('ph:lock-key-bold', 'Sem permissão', 'Esta área é só da administradora. Troque o papel em Meu perfil para ver a diferença.', btn('Ir para Meu perfil', { onclick: () => ir('perfil') })))

/* ================= PADRÕES OPERACIONAIS (texto real do CRM) ================= */
VIEWS.padroes = () => {
  const f = MANUAL_FASES.find(x => x.id === UI.manual.fase) || MANUAL_FASES[0]
  return pagina('Padrões operacionais', 'O fluxo do escritório, da primeira mensagem ao pós-venda — e onde cada passo vive no CRM.', null,
    painel('Cada tipo de coisa tem um único lugar', h('div', { class: 'grid gap-3 sm:grid-cols-2 lg:grid-cols-3' }, MANUAL_REGRAS.map(r => h('div', { class: 'rounded-2xl bg-white dark:bg-zinc-800/60 p-3.5' }, h('p', { class: 'font-semibold text-sm flex items-center gap-1.5 text-primary dark:text-zinc-100' }, ic(r.icone), r.nome), h('p', { class: 'text-xs text-gray-600 dark:text-zinc-300 mt-1' }, r.texto))))),
    h('div', { class: 'grid gap-5 lg:grid-cols-[260px_1fr]' },
      h('nav', { class: 'flex lg:flex-col gap-2 overflow-x-auto', 'aria-label': 'Fases' }, MANUAL_FASES.map(x => h('button', { type: 'button', class: 'text-left rounded-2xl px-4 py-3 border whitespace-nowrap lg:whitespace-normal ' + (x.id === f.id ? 'bg-primary text-white border-primary' : 'border-gray-200 dark:border-zinc-700 hover:border-primary'), onclick: () => { UI.manual.fase = x.id; render() }, 'data-testid': 'fase-' + x.id }, h('span', { class: 'block text-sm font-semibold' }, x.nome)))),
      painel(f.nome, h('p', { class: 'text-sm text-gray-500 mb-4' }, f.resumo), h('ol', { class: 'space-y-3' }, f.passos.map((p, i) => h('li', { class: 'flex gap-3', 'data-testid': 'passo' }, h('span', { class: 'w-7 h-7 rounded-full bg-cafe text-cafe-creme text-xs font-bold inline-flex items-center justify-center shrink-0' }, i + 1), h('div', { class: 'min-w-0' }, h('p', { class: 'font-semibold text-sm flex flex-wrap items-center gap-2' }, p.titulo, p.automatico === 'faz' ? badge('O sistema faz sozinho', 'verde') : p.automatico === 'avisa' ? badge('O sistema avisa, você envia', 'ambar') : null), h('p', { class: 'text-sm text-gray-600 dark:text-zinc-300 mt-0.5' }, p.texto), h('p', { class: 'mt-1.5 text-[11px] text-gray-400 flex items-center gap-1.5' }, ic('ph:map-pin-bold'), 'No CRM: ', h('b', { class: 'text-gray-600 dark:text-zinc-300 font-semibold' }, MANUAL_ONDE[`${f.id}:${i}`] ?? '—')))))), f.links ? h('div', { class: 'flex flex-wrap gap-2 mt-4' }, f.links.map(l => btn(l.nome, { tipo: 'sec', mini: true, onclick: () => ir({ '/crm': 'hoje', '/mensagens': 'mensagens', '/honorarios': 'financeiro', '/demandas': 'demandas', '/agenda': 'agenda', '/crm?aba=remarketing': 'remarketing' }[l.to] || 'hoje') }))) : null)))
}

/* ================= MAPA OPERACIONAL: dados → cadastros → formulários → respostas → clientes → demandas → documentos → tarefas → prazos → histórico ================= */
VIEWS.mapa = () => {
  const respostas = DB.envios.filter(e => e.status === 'respondido').length
  const nos = [
    { id: 'dados', nome: 'Dados do escritório', icone: 'ph:buildings-bold', n: Object.values(CONFIG.escritorio).filter(Boolean).length + ' campos', rota: 'config', texto: 'Escritório, modelos de mensagem, procedimentos e regras. Alimentam mensagens e documentos.' },
    { id: 'cadastros', nome: 'Cadastros', icone: 'ph:address-book-bold', n: DB.contatos.length + ' pessoas', rota: 'leads', texto: 'Todo contato nasce aqui. Telefone único; etapa define o fluxo.' },
    { id: 'formularios', nome: 'Formulários', icone: 'ph:clipboard-text-bold', n: DB.formularios.length + ' formulários', rota: 'formularios', texto: 'Perguntas, seções e lógica condicional; valem para cliente, consulta ou demanda.' },
    { id: 'respostas', nome: 'Respostas', icone: 'ph:chat-centered-text-bold', n: respostas + ' recebidas', rota: 'formularios', p: { aba: 'respostas' }, texto: 'Chegam pelo link público e se ligam sozinhas à ficha — sem copiar dados.' },
    { id: 'clientes', nome: 'Clientes', icone: 'ph:users-bold', n: DB.contatos.filter(ehCliente).length + ' clientes', rota: 'clientes', texto: 'Lead que contrata vira cliente ativo ao abrir a primeira demanda.' },
    { id: 'demandas', nome: 'Demandas', icone: 'ph:briefcase-bold', n: DB.demandas.length + ' demandas', rota: 'demandas', texto: 'Serviço contratado. Define etapas, documentos e processos.' },
    { id: 'documentos', nome: 'Documentos', icone: 'ph:files-bold', n: DB.documentos.length + ' itens', rota: 'documentos', texto: 'Checklist por área: pendente → recebido → conferido.' },
    { id: 'tarefas', nome: 'Tarefas', icone: 'ph:check-square-bold', n: DB.tarefas.filter(t => !t.concluida).length + ' abertas', rota: 'tarefas', texto: 'O que exige execução; com data, aparece no Hoje.' },
    { id: 'prazos', nome: 'Prazos', icone: 'ph:hourglass-high-bold', n: DB.compromissos.filter(c => c.tipo === 'prazo' && c.status === 'pendente').length + ' abertos', rota: 'prazos', texto: 'Data-limite contada em dias úteis, com feriados e recesso.' },
    { id: 'historico', nome: 'Linha do tempo', icone: 'ph:clock-counter-clockwise-bold', n: (DB.atividades.length + DB.comunicacoes.length) + ' registros', rota: 'pessoas', p: { aba: 'clientes' }, texto: 'Comunicações, andamentos e anotações se gravam sozinhos na linha do tempo do cliente e da demanda.' },
  ]
    const sel = nos.find(n => n.id === UI.mapa.sel) || nos[1]
  const alvo = DB.contatos.find(c => c.id === UI.mapa.cliente) || DB.contatos.find(c => c.id === 6)
  const dms = demandasDe(alvo.id); const dr = docsResumo(alvo.id)
  const trilha = [['Cadastro', 'ph:address-book-bold', `${CRM.etapa(alvo.etapa).nome} · ${CRM.codigoCliente(alvo.id)}`], ['Formulários enviados', 'ph:paper-plane-tilt-bold', plural(DB.envios.filter(e => e.contato_id === alvo.id).length, 'envio', 'envios')], ['Respostas na ficha', 'ph:chat-centered-text-bold', plural(Object.keys(alvo.respostas || {}).length, 'resposta', 'respostas')], ['Demandas', 'ph:briefcase-bold', plural(dms.length, 'demanda', 'demandas')], ['Documentos', 'ph:files-bold', dr.total ? `${dr.ok}/${dr.total} recebidos` : 'sem checklist'], ['Tarefas', 'ph:check-square-bold', plural(DB.tarefas.filter(t => t.contato_id === alvo.id && !t.concluida).length, 'aberta', 'abertas')], ['Prazos', 'ph:hourglass-high-bold', plural(DB.compromissos.filter(c => c.contato_id === alvo.id && c.tipo === 'prazo' && c.status === 'pendente').length, 'aberto', 'abertos')], ['Linha do tempo', 'ph:clock-counter-clockwise-bold', plural(linhaDoTempo({ contato_id: alvo.id }).length, 'registro', 'registros')]]
  return pagina('Fluxo operacional', 'Como a informação percorre o escritório: um dado entra uma vez e alimenta todas as etapas seguintes. Clique num passo para abrir o módulo.', null,
    h('div', { class: 'overflow-x-auto pb-2' }, h('ol', { class: 'flex items-stretch gap-0 min-w-max', 'data-testid': 'cadeia' }, nos.map((n, i) => h('li', { class: 'flex items-center' }, h('button', { type: 'button', class: 'w-40 rounded-2xl border p-3 text-left transition-colors ' + (n.id === sel.id ? 'bg-primary text-white border-primary' : 'bg-white/80 dark:bg-zinc-900/70 border-gray-200 dark:border-zinc-800 hover:border-primary'), onclick: () => { UI.mapa.sel = n.id; render() }, 'data-testid': 'no-' + n.id }, h('span', { class: 'text-[10px] font-bold uppercase tracking-widest opacity-60' }, i + 1), h('span', { class: 'flex items-center gap-1.5 text-sm font-semibold' }, ic(n.icone), n.nome), h('span', { class: 'block text-[11px] opacity-70 mt-0.5' }, n.n)), i < nos.length - 1 ? ic('ph:arrow-right-bold', 'mx-1.5 text-gray-400 shrink-0') : null)))),
    painel(sel.nome, h('p', { class: 'text-sm text-gray-600 dark:text-zinc-300' }, sel.texto), h('div', { class: 'mt-3' }, btn('Abrir ' + sel.nome, { icone: 'ph:arrow-square-out-bold', onclick: () => ir(sel.rota, sel.p || {}), tid: 'abrir-no' }))),
    painel('Regras que ligam as etapas', lista([
      ['Contato novo → Cadastro', 'Telefone único; etapa “Novo contato” e próxima ação “Responder pessoalmente”.'], ['Cadastro → Formulário', 'Envie pela ficha: gera link de 30 dias, sem login.'], ['Formulário → Resposta → Ficha', 'A resposta grava no cadastro (cliente) ou na demanda; marca “pré-formulário respondido” no checklist.'], ['Contratou → Demanda', 'Abrir a 1ª demanda move o contato para Cliente ativo e cria o checklist de documentos da área.'], ['Demanda → Documentos / Processos', 'Procedimento define as etapas; processo registrado muda a atuação da demanda.'], ['Tarefa e prazo → Hoje', 'Vencendo ou atrasado, aparece no Hoje e no sininho.'], ['Qualquer ação → Linha do tempo', 'Etapa, comunicação (WhatsApp, e-mail, ligação), documento, tarefa e formulário se registram na linha do tempo e na auditoria.'], ['Encerrar última demanda → Concluído', 'Cliente segue cadastrado; pós-venda de 30 dias agendado.']].map(([a, b]) => [ic('ph:arrow-elbow-down-right-bold', 'text-gray-400 mt-0.5'), h('div', {}, h('b', { class: 'text-sm' }, a), h('p', { class: 'text-xs text-gray-500' }, b))]))),
    painel('Acompanhe um cliente pela cadeia', h('label', { class: 'block max-w-xs mb-3' }, rotuloCampo('Cliente'), h('select', { class: 'modal-input', 'aria-label': 'Cliente', 'data-testid': 'mapa-cliente', onchange: ev => { UI.mapa.cliente = Number(ev.target.value); render() } }, DB.contatos.filter(c => c.etapa !== 'relacionado').map(c => h('option', { value: c.id, selected: c.id === alvo.id }, c.nome)))), h('ol', { class: 'grid gap-2 sm:grid-cols-2 lg:grid-cols-4' }, trilha.map(([t, i_, v], k) => h('li', { class: 'rounded-2xl border border-gray-200/70 dark:border-zinc-800 p-3 flex items-start gap-3' }, h('span', { class: 'w-8 h-8 rounded-full bg-cafe text-cafe-creme inline-flex items-center justify-center shrink-0' }, ic(i_)), h('div', {}, h('p', { class: 'text-[10px] font-bold uppercase tracking-widest text-gray-400' }, `${k + 1}. ${t}`), h('p', { class: 'text-sm font-semibold' }, v))))), h('div', { class: 'mt-3' }, btn('Abrir ficha', { tipo: 'sec', mini: true, onclick: () => abrirFicha(alvo.id) }))))
}

/* ================= CONFIGURAÇÕES (admin) ================= */
VIEWS.cfg_escritorio = () => {
  const grupos = [...new Set(CRM.ESCRITORIO_CAMPOS.map(c => c.grupo))]; const refs = {}
  const salvarCfg = () => { for (const [k, el] of Object.entries(refs)) CONFIG.escritorio[k] = el.value.trim() || null; auditar('editar_escritorio', 'Dados do escritório'); salvar('config'); aviso('Dados do escritório salvos.'); render() }
    return pagina('Escritório', 'Dados do escritório (alimentam mensagens e documentos).', [btn('Salvar', { icone: 'ph:floppy-disk-bold', onclick: salvarCfg, tid: 'config-salvar' })],
    grupos.map(g => painel(g, h('div', { class: 'grid gap-3 sm:grid-cols-2' }, CRM.ESCRITORIO_CAMPOS.filter(c => c.grupo === g).map(c => h('label', { class: 'block ' + (/valor|dados|nao_atende|tom|proposta/.test(c.chave) ? 'sm:col-span-2' : '') }, rotuloCampo(c.rotulo), (() => { const e = /valor_de|tom|proposta|nao_atende|dados_banc/.test(c.chave) ? h('textarea', { class: 'modal-input', rows: 2 }) : h('input', { class: 'modal-input' }); e.value = CONFIG.escritorio[c.chave] || ''; e.placeholder = c.exemplo; e.setAttribute('data-campo', 'cfg-' + c.chave); refs[c.chave] = e; return e })()))))),
    painel('Dados desta demonstração', h('p', { class: 'text-sm text-gray-600 dark:text-zinc-300 mb-3' }, `Estado: ${ARM.estado}. Os dados de clientes são fictícios; os 66 modelos de mensagem são os reais do escritório.`), h('div', { class: 'flex flex-wrap gap-2' }, btn('Exportar tudo (.json)', { tipo: 'sec', icone: 'ph:download-bold', onclick: exportarTudo, tid: 'exportar-tudo' }), btn('Restaurar dados de exemplo', { tipo: 'perigo', icone: 'ph:arrow-counter-clockwise-bold', tid: 'restaurar', onclick: () => confirmar('Restaurar dados de exemplo?', 'Apaga tudo o que você criou ou editou nesta demonstração e volta ao conjunto inicial. Não afeta o CRM real.', 'Restaurar', () => { restaurarExemplo(); ir('dashboard'); aviso('Dados de exemplo restaurados.') }) }))))
}
async function exportarTudo() { const json = JSON.stringify({ DB, CONFIG }, null, 2); try { const dl = window.claude && window.claude.use ? await window.claude.use('downloads') : null; if (!dl) throw new Error('x'); await dl.save({ filename: 'crm-lara-cafe-demo.json', data: json }) } catch (e) { copiar(json); aviso('Download indisponível aqui: JSON copiado para a área de transferência.') } }

/* ================= AUDITORIA (admin) ================= */
VIEWS.auditoria = () => {
  const q = semAcento(UI.audit.q); const rows = DB.auditoria.filter(a => !q || semAcento(a.acao + a.detalhe + a.quem).includes(q))
  return pagina('Auditoria', 'Quem fez o quê: mudanças de etapa, cadastros, exclusões e acesso a dados confidenciais.', null, h('div', { class: 'w-full sm:w-80' }, busca(UI.audit.q, v => { UI.audit.q = v; render() }, 'Buscar ação ou detalhe')), tabela([{ nome: 'Quando', cel: a => dataHora(a.em) }, { nome: 'Quem', cel: a => a.quem }, { nome: 'Ação', cel: a => h('code', { class: 'tag' }, a.acao) }, { nome: 'Detalhe', cel: a => a.detalhe }], rows, { vazio: 'Nenhum registro ainda', vazioTexto: 'Faça alguma alteração no CRM e volte aqui.', icone: 'ph:shield-check-bold' }))
}

/* ================= PERFIL ================= */
VIEWS.perfil = () => {
  const p = CONFIG.perfil; const nome = h('input', { class: 'modal-input', value: p.nome, 'aria-label': 'Nome', 'data-campo': 'perfil-nome' }); const email = h('input', { class: 'modal-input', type: 'email', value: p.email, 'aria-label': 'E-mail', 'data-campo': 'perfil-email' })
  return pagina('Meu perfil', null, null, painel('Dados', h('div', { class: 'flex items-center gap-4 mb-4' }, avatar(p.nome, true), h('p', { class: 'text-xs text-gray-500' }, 'A foto vem do cadastro de usuário no CRM real; aqui usamos as iniciais.')), h('div', { class: 'grid gap-3 sm:grid-cols-2' }, h('label', {}, rotuloCampo('Nome'), nome), h('label', {}, rotuloCampo('E-mail'), email)), h('div', { class: 'mt-3' }, btn('Salvar perfil', { onclick: () => { if (!nome.value.trim()) { aviso('Informe o nome.', 'erro'); return } p.nome = nome.value.trim(); p.email = email.value.trim(); salvar('config'); render(); aviso('Perfil salvo.') }, tid: 'perfil-salvar' }))),
    painel('Acesso', h('p', { class: 'text-sm text-gray-600 dark:text-zinc-300' }, 'Seu papel neste CRM: ', h('b', {}, ehAdmin() ? 'Administradora (dona do artefato)' : 'Equipe (pode editar, sem Configurações)')), h('p', { class: 'text-xs text-gray-500 mt-1' }, 'O acesso é definido pelo compartilhamento do artefato: quem é dono vê tudo; quem recebe permissão de edição vê o trabalho do dia a dia.')),
    painel('Aparência', h('div', { class: 'flex flex-wrap gap-2' }, [['sistema', 'Seguir o sistema'], ['claro', 'Claro'], ['escuro', 'Escuro']].map(([k, t]) => h('button', { type: 'button', class: 'tab-btn ' + (TEMA.pref === k ? 'tab-btn-ativo' : ''), onclick: () => { TEMA.pref = k; lsSet('tema', k); aplicarTema(); render() }, 'data-testid': 'tema-' + k }, t)))))
}

/* Petições iniciais (antes numa aba da Secretária): pertencem às demandas. */
const gSecretaria = (tit, ...c) => painel(tit, h('div', { class: 'space-y-3' }, ...c))
let formInicial = () => {}
function iniciaisSecretaria() {
  const hoje = hojeISO(); const I = CRM.INI; const filtradas = I.filtrarIniciais(DB.iniciais, UI.sec.q, UI.sec.area); const rs = I.resumoIniciais(DB.iniciais, hoje); const faixa = I.prazosProximos(DB.iniciais, hoje)
  const editar = formInicial = (i) => modalForm(i ? 'Inicial — ' + i.cliente : 'Nova inicial', [{ chave: 'cliente', rotulo: 'Cliente', obrigatorio: true }, { chave: 'acao', rotulo: 'Ação', dica: 'Sugestões: ' + I.acoesDaArea(i?.area).slice(0, 3).join(', ') }, { chave: 'area', rotulo: 'Área', tipo: 'select', opcoes: [['', '—'], ...I.AREAS_INI] }, { chave: 'parte_contraria', rotulo: 'Parte contrária' }, { chave: 'meta_protocolo', rotulo: 'Meta de protocolo', tipo: 'data' }, { chave: 'prazo_fatal', rotulo: 'Prazo fatal', tipo: 'data' }, { chave: 'prazo_fatal_tipo', rotulo: 'Tipo do prazo fatal', tipo: 'select', opcoes: [['', '—'], ...I.TIPOS_FATAL] }, { chave: 'prioridade', rotulo: 'Prioridade', tipo: 'select', opcoes: I.PRIORIDADES }, { chave: 'processo_numero', rotulo: 'Nº do processo (após protocolo)', valida: v => v && !CRM.numeroCnjValido(v) ? 'Número CNJ inválido.' : null }, { chave: 'obs', rotulo: 'Observações', tipo: 'textarea' }], i || { prioridade: 'normal' }, v => { if (v.processo_numero) v.processo_numero = CRM.formatarCnj(v.processo_numero); if (i) Object.assign(i, v); else DB.iniciais.push({ id: proximoId('iniciais'), etapa: 'aguardando', etapa_desde: agora(), checklist: [], protocolo_data: null, ...v }); salvar('iniciais') }, { largura: 'max-w-2xl', extra: i ? btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Excluir inicial?', i.cliente, 'Excluir', () => { DB.iniciais = DB.iniciais.filter(x => x !== i); salvar('iniciais'); render() }) }) : null })
  const checklist = i => modal({ titulo: 'Documentos — ' + i.cliente, largura: 'max-w-lg', corpo: h('div', { 'data-testid': 'ini-checklist' }), aoFechar: render, rodape: f => btn('Fechar', { onclick: f }) })
  const cartao = i => { const a = I.alerta(i, hoje); const pend = I.checklistPendente(i).length; const prox = I.proximaEtapa(i.etapa); return h('div', { class: 'rounded-2xl bg-white dark:bg-zinc-900 border border-gray-200/70 dark:border-zinc-800 p-3 space-y-1.5', 'data-testid': 'inicial-card' }, h('div', { class: 'flex justify-between gap-2' }, h('button', { type: 'button', class: 'font-semibold text-sm text-left hover:underline', onclick: () => editar(i) }, i.cliente), i.prioridade === 'alta' ? badge('Alta', 'vermelho') : null), h('p', { class: 'text-[11px] text-gray-500' }, [i.acao, i.area].filter(Boolean).join(' · ')), a && a.data ? badge((a.tipo === 'fatal' ? 'Fatal ' : 'Meta ') + dataCurta(a.data) + (a.nivel === 'atrasada' ? ' · atrasada' : ''), a.nivel === 'atrasada' ? 'vermelho' : a.nivel === 'vencendo' ? 'ambar' : 'cinza') : null, pend ? h('button', { type: 'button', class: 'block text-[11px] text-amber-700 dark:text-amber-300 underline', onclick: () => abrirChecklistInicial(i) }, plural(pend, 'documento pendente', 'documentos pendentes')) : null, prox ? btn('Avançar', { mini: true, tipo: 'sec', tid: 'ini-avancar', onclick: () => { i.etapa = prox; i.etapa_desde = agora(); if (prox === 'protocolada') i.protocolo_data = hoje; salvar('iniciais'); render() } }) : null) }
  return [gSecretaria('Petições iniciais', grade(3, kpi('Em andamento', rs.andamento), kpi('Atrasadas', rs.atrasadas), kpi('Vencendo em 7 dias', rs.vencendo)), faixa.length ? h('div', { class: 'rounded-2xl bg-white/70 dark:bg-white/5 p-3 text-sm', 'data-testid': 'faixa-7' }, h('b', {}, 'Prazos dos próximos 7 dias'), h('ul', { class: 'mt-1 space-y-0.5' }, faixa.map(p => h('li', { class: p.atrasado ? 'text-danger' : '' }, `${dataCurta(p.data)} · ${p.cliente} — ${p.tipo === 'fatal' ? 'prazo fatal' : 'meta'}${p.atrasado ? ' (atrasado)' : ''}`)))) : null, h('div', { class: 'flex flex-wrap gap-3 items-center' }, h('div', { class: 'w-64' }, busca(UI.sec.q, v => { UI.sec.q = v; render() }, 'Cliente, ação ou processo')), h('select', { class: 'selecao', 'aria-label': 'Área', onchange: ev => { UI.sec.area = ev.target.value; render() } }, h('option', { value: '' }, 'Todas as áreas'), I.AREAS_INI.map(a => h('option', { value: a, selected: a === UI.sec.area }, a))), btn('Nova inicial', { icone: 'ph:plus-bold', onclick: () => editar(null), tid: 'nova-inicial' })), h('div', { class: 'flex gap-3 overflow-x-auto pb-2 items-start' }, I.ETAPAS_INI.map(([id, nome]) => h('div', { class: 'w-64 shrink-0 rounded-2xl bg-white/50 dark:bg-white/5 p-2.5 space-y-2', 'data-testid': 'ini-col-' + id }, h('p', { class: 'text-xs font-bold text-[#8a6a26] dark:text-[#d4af5a]' }, nome + ` (${filtradas.filter(x => x.etapa === id).length})`), I.ordenarColuna(filtradas, id, hoje).map(cartao)))))]
}
function abrirChecklistInicial(i) {
  const I = CRM.INI; const corpo = h('div', { class: 'space-y-3' }); let m
  const des = () => { corpo.replaceChildren(h('ul', { class: 'space-y-1.5' }, i.checklist.map((c, k) => h('li', { class: 'flex items-center gap-2 text-sm' }, h('input', { type: 'checkbox', class: 'accent-[#6f5636]', checked: c.ok, 'aria-label': c.texto, onclick: () => { c.ok = !c.ok; salvar('iniciais'); des() } }), h('span', { class: c.ok ? 'line-through text-gray-400 flex-1' : 'flex-1' }, c.texto), btnIcone('ph:x-bold', 'Remover', () => { i.checklist.splice(k, 1); salvar('iniciais'); des() })))), h('p', { class: 'section-label' }, 'Sugestões da área'), h('div', { class: 'flex flex-wrap gap-1.5' }, I.docsSugeridos(i.area, i.checklist).map(d => h('button', { type: 'button', class: 'chip', onclick: () => { i.checklist = I.adicionarDoc(i.checklist, d); salvar('iniciais'); des() } }, '+ ' + d)))) }
  des(); m = modal({ titulo: 'Documentos — ' + i.cliente, largura: 'max-w-lg', corpo, aoFechar: render })
}

VIEWS.iniciais = () => pagina('Petições iniciais', 'Do pedido ao protocolo: etapa, prazo fatal, documentos pendentes.', null, ...iniciaisSecretaria())
/* ================= módulos com abas ================= */
UI.man = { aba: 'padroes' }; UI.cfg = { aba: 'escritorio' }
VIEWS.manual = (p) => {
  if (p && p.aba) { UI.man.aba = p.aba; R.p = {} }
  return modulo({ titulo: 'Padrões operacionais', sub: 'Como o escritório trabalha — e como a informação percorre o CRM.', abasDef: [{ id: 'padroes', nome: 'Passo a passo', icone: 'ph:list-checks-bold' }, { id: 'fluxo', nome: 'Fluxo do CRM', icone: 'ph:flow-arrow-bold' }], ativa: UI.man.aba, aoMudar: id => { UI.man.aba = id; render() }, conteudo: a => (a === 'fluxo' ? VIEWS.mapa() : VIEWS.padroes()) })
}
VIEWS.config = (p) => {
  if (!ehAdmin()) return semPermissao('Configurações')
  if (p && p.aba) { UI.cfg.aba = p.aba; R.p = {} }
  return modulo({ titulo: 'Configurações', sub: 'Dados do escritório, regras automáticas, conexões (e-mail, WhatsApp, IA) e auditoria.', abasDef: [{ id: 'escritorio', nome: 'Escritório e dados', icone: 'ph:buildings-bold' }, { id: 'automacoes', nome: 'Automações', icone: 'ph:lightning-bold' }, { id: 'conexoes', nome: 'Conexões e IA', icone: 'ph:plugs-connected-bold' }, { id: 'auditoria', nome: 'Auditoria', icone: 'ph:shield-check-bold' }], ativa: UI.cfg.aba, aoMudar: id => { UI.cfg.aba = id; render() }, conteudo: a => VIEWS[{ escritorio: 'cfg_escritorio', automacoes: 'cfg_automacoes', conexoes: 'conexoes', auditoria: 'auditoria' }[a]]() })
}

/* ================= CONFIGURAÇÕES › AUTOMAÇÕES: o que o CRM faz sozinho e como você quer que faça ================= */
const AUTOMACOES = [
  { chave: 'cadencia', tipo: 'liga', nome: 'Próxima ação ao mudar de etapa', texto: 'Ao mover um contato (novo → qualificação → consulta → proposta → ativo), o CRM define a próxima ação e a data pela cadência do escritório (ex.: convidar para a consulta em 1 dia; lembrete no dia anterior).', onde: 'Funil de leads · Início' },
  { chave: 'semNovidadeDias', tipo: 'dias', nome: 'Cliente ativo sem comunicação há…', texto: 'Quando um cliente ativo passa esse número de dias sem nenhuma comunicação registrada, aparece no Início com a sugestão de enviar a atualização. 0 desliga.', onde: 'Início · Comunicação', min: 0, max: 60 },
  { chave: 'antecedenciaPrazo', tipo: 'dias', nome: 'Prazos no Início com antecedência de…', texto: 'Prazos processuais entram na lista “Hoje” quando faltam até esse número de dias (atrasados entram sempre).', onde: 'Início · sino', min: 0, max: 15 },
  { chave: 'preparacaoPrazo', tipo: 'liga', nome: 'Criar tarefa de preparação ao registrar prazo', texto: 'Deixa marcada, por padrão, a opção de criar uma tarefa 3 dias úteis antes do vencimento. Você ainda pode desmarcar em cada prazo.', onde: 'Agenda › Prazos · Tarefas' },
  { chave: 'checklistAoAbrir', tipo: 'liga', nome: 'Checklist de documentos ao abrir demanda', texto: 'Ao abrir uma demanda contratada, cria a lista de documentos da área (identidade, certidões, procuração, contrato…).', onde: 'Demandas › Documentos' },
  { chave: 'remarketingDias', tipo: 'dias', nome: 'Intervalo do remarketing', texto: 'Dias mínimos entre conteúdos para quem não contratou. Nunca vale para quem pediu para não receber, nem fora da área, encaminhados ou conflito de interesses.', onde: 'Pessoas › Remarketing', min: 15, max: 180 },
  { chave: 'aniversarios', tipo: 'liga', nome: 'Aviso de aniversário', texto: 'Mostra no Início quem faz aniversário hoje, com o modelo de mensagem pronto.', onde: 'Início' },
]
const SEMPRE_ATIVAS = [
  ['Abrir a primeira demanda → o contato vira Cliente ativo.', 'Demandas'], ['Encerrar a última demanda → Concluído, com pós-venda em 30 dias.', 'Demandas · Início'], ['Nota NPS → classificação (promotora, neutra, detratora).', 'Pessoas'],
  ['Telefone único: não duplica cadastro.', 'Pessoas'], ['Mensagem, e-mail, ligação e andamento se registram na linha do tempo e atualizam o “último contato”.', 'Comunicação'], ['Resposta de formulário chega à ficha do cliente ou da demanda.', 'Formulários'],
  ['Excluir pessoa ou demanda com vínculos é bloqueado.', 'Pessoas · Demandas'], ['Revelar CPF/RG, gerar peça e ação da IA ficam na Auditoria.', 'Configurações'],
]
VIEWS.cfg_automacoes = () => pagina('Automações', 'O que o CRM faz sozinho. Cada regra aparece onde indicado; mudar aqui muda o comportamento do dia a dia.', [btn('Voltar ao padrão', { tipo: 'sec', icone: 'ph:arrow-counter-clockwise-bold', tid: 'auto-padrao', onclick: () => { CONFIG.auto = { ...AUTO_PADRAO }; auditar('automacoes', 'Regras voltaram ao padrão'); salvar('config'); render(); aviso('Regras no padrão.') } })],
  painel('Regras ajustáveis', h('div', { class: 'divide-y divide-gray-100 dark:divide-zinc-800' }, AUTOMACOES.map(a => { const v = AUTO()[a.chave]; const mudar = nv => { CONFIG.auto = { ...AUTO(), [a.chave]: nv }; auditar('automacoes', `${a.nome}: ${nv}`); salvar('config'); render() }
    return h('div', { class: 'py-3 flex flex-wrap items-start gap-3', 'data-testid': 'auto-' + a.chave }, h('div', { class: 'min-w-0 flex-1 basis-64' }, h('p', { class: 'font-semibold text-sm' }, a.nome), h('p', { class: 'text-xs text-gray-500 mt-0.5' }, a.texto), h('p', { class: 'text-[11px] text-gray-400 mt-1 flex items-center gap-1' }, ic('ph:map-pin-bold'), 'Aparece em: ', a.onde)),
      a.tipo === 'liga' ? h('label', { class: 'inline-flex items-center gap-2 text-sm shrink-0' }, h('input', { type: 'checkbox', class: 'w-4 h-4 accent-[#6f5636]', checked: !!v, 'aria-label': a.nome, onchange: ev => mudar(ev.target.checked), 'data-testid': 'auto-check-' + a.chave }), v ? 'Ligada' : 'Desligada') : h('label', { class: 'inline-flex items-center gap-2 text-sm shrink-0' }, h('input', { type: 'number', class: 'modal-input !w-20 !py-1.5', min: a.min, max: a.max, value: v, 'aria-label': a.nome, onchange: ev => { const n = Math.max(a.min, Math.min(a.max, Math.round(Number(ev.target.value)))); mudar(Number.isFinite(n) ? n : a.min) }, 'data-testid': 'auto-num-' + a.chave }), 'dias')) }))),
  painel('Regras fixas (sempre ativas)', h('ul', { class: 'divide-y divide-gray-100 dark:divide-zinc-800' }, SEMPRE_ATIVAS.map(([t, o]) => h('li', { class: 'py-2 flex flex-wrap gap-x-3 text-sm' }, ic('ph:lock-simple-bold', 'text-gray-400 mt-0.5'), h('span', { class: 'flex-1 basis-64' }, t), h('span', { class: 'text-[11px] text-gray-400' }, o))))))
