'use strict'
/* ============ ATENDIMENTO: o espaço de trabalho de uma Pessoa/Demanda (a IA lê o caso; você revisa e decide) ============
   Abas: Visão geral · Conversas · Materiais · Formulário · Consultas · Contexto do caso · Pareceres · Linha do tempo · Chat com o Assistente.
   Estado comercial da pessoa (Novo contato … Convertido/Encerrado) com sugestão calculada a partir do que realmente aconteceu. */
const STATUS_ATEND = ['Novo contato', 'Em conversa', 'Em qualificação', 'Aguardando informações', 'Formulário enviado', 'Formulário respondido', 'Consulta agendada', 'Consulta realizada', 'Pós-consulta', 'Aguardando decisão', 'Convertido em demanda', 'Encerrado', 'Não avançou']
const COR_ATEND = { 'Novo contato': 'cinza', 'Em conversa': 'azul', 'Em qualificação': 'azul', 'Aguardando informações': 'ambar', 'Formulário enviado': 'ambar', 'Formulário respondido': 'verde', 'Consulta agendada': 'roxo', 'Consulta realizada': 'verde', 'Pós-consulta': 'verde', 'Aguardando decisão': 'ambar', 'Convertido em demanda': 'verde', 'Encerrado': 'cinza', 'Não avançou': 'vermelho' }
const CASO_ATUAL = { cid: null, casoId: null }
UI.caso = { aba: 'visao' }
const statusDe = c => (c.atendimento && c.atendimento.status) || 'Novo contato'
function definirStatus(c, status, manual) { const antes = statusDe(c); c.atendimento = { ...(c.atendimento || {}), status, desde: agora(), manual: !!manual, historico: [...((c.atendimento || {}).historico || []), { em: agora(), de: antes, para: status, manual: !!manual }] }; c.updated_at = agora(); salvar('contatos'); if (antes !== status) registrar(c.id, 'Anotação', `Atendimento: ${antes} → ${status}${manual ? '' : ' (sugerido pelo CRM e aplicado por você)'}.`) }
/** estado sugerido a partir do que realmente existe no CRM (nunca aplicado sozinho) */
function statusSugerido(c) {
  const envs = DB.envios.filter(e => e.contato_id === c.id); const cons = DB.consultas.filter(q => q.contato_id === c.id); const an = DB.analises.filter(a => a.contato_id === c.id)
  const atual = statusDe(c); if (['Aguardando decisão', 'Convertido em demanda', 'Encerrado', 'Não avançou'].includes(atual)) return atual
  if (DB.pareceres.some(p => p.contato_id === c.id) || an.some(a => a.tipo === 'followup')) return 'Pós-consulta'
  if (cons.some(q => q.status === 'realizada')) return 'Consulta realizada'
  if (cons.some(q => q.status !== 'realizada' && q.status !== 'cancelada')) return 'Consulta agendada'
  if (envs.some(e => e.status === 'respondido')) return 'Formulário respondido'
  if (envs.some(e => e.status !== 'cancelado')) return 'Formulário enviado'
  if (an.some(a => ['conversa', 'caso'].includes(a.tipo))) return 'Em qualificação'
  if (DB.comunicacoes.some(m => m.contato_id === c.id)) return 'Em conversa'
  return 'Novo contato'
}

/* ---------- linha do tempo (montada das fontes reais, sem duplicar dados) ---------- */
function linhaDoTempoCaso(c, casoId) {
  const f = doCaso(c, casoId); const ev = []; const add = (quando, icone, titulo, detalhe, fonte) => { if (quando) ev.push({ quando: String(quando), icone, titulo, detalhe, fonte }) }
  add(c.created_at, 'ph:user-plus-bold', 'Novo contato', c.origem ? 'Origem: ' + c.origem : '', 'F')
  for (const h_ of (c.atendimento && c.atendimento.historico) || []) add(h_.em, 'ph:flag-bold', `Atendimento: ${h_.de} → ${h_.para}`, h_.manual ? 'definido por você' : 'sugestão aplicada', null)
  for (const m of DB.materiais.filter(f)) { if (m.tipo === 'conversa') add(m.created_at, 'ph:chats-circle-bold', 'Conversa importada', `${plural(m.n_mensagens || 0, 'mensagem', 'mensagens')} — ${m.nome_arquivo || ''}`, 'M' + m.id); else if (m.tipo === 'transcricao') add(m.created_at, 'ph:subtitles-bold', 'Transcrição adicionada', m.titulo, 'M' + m.id); else add(m.created_at, ICONE_MAT[m.tipo] || 'ph:paperclip-bold', 'Material adicionado: ' + (TIPO_MAT[m.tipo] || m.tipo), m.titulo + (m.texto && m.texto.trim() ? '' : ' (não lido)'), 'M' + m.id) }
  for (const a of DB.analises.filter(f)) { if (a.tipo === 'resumo_conversa') continue; add(a.created_at, 'ph:sparkle-bold', 'Assistente: ' + a.titulo, a.status === 'revisada' ? 'revisada por você' : 'rascunho', null); if (a.enviado_manual_em) add(a.enviado_manual_em, 'ph:paper-plane-tilt-bold', 'Follow-up enviado manualmente por você', a.titulo, null) }
  for (const e of DB.envios.filter(f)) { add(e.created_at, 'ph:clipboard-text-bold', 'Formulário gerado: ' + nomeFormEnvio(e), '', 'R' + e.id); add(e.enviado_em, 'ph:paper-plane-tilt-bold', 'Formulário enviado', nomeFormEnvio(e), 'R' + e.id); add(e.respondido_em, 'ph:check-circle-bold', 'Formulário respondido', nomeFormEnvio(e), 'R' + e.id) }
  for (const q of DB.consultas.filter(f)) add(q.data_hora || q.created_at, 'ph:calendar-check-bold', (q.status === 'realizada' ? 'Consulta realizada' : 'Consulta agendada'), q.participantes || '', 'C' + q.id)
  for (const p of DB.pareceres.filter(f)) { add(p.created_at, 'ph:scales-bold', 'Parecer gerado: ' + p.titulo, '', 'P' + p.id); if (p.revisado_em) add(p.revisado_em, 'ph:seal-check-bold', 'Parecer revisado', p.titulo, 'P' + p.id); if (p.finalizado_em) add(p.finalizado_em, 'ph:seal-check-bold', 'Parecer finalizado', p.titulo, 'P' + p.id) }
  for (const t of DB.tarefas.filter(f)) add(t.created_at, 'ph:check-square-bold', 'Tarefa criada: ' + t.titulo, t.concluida ? 'concluída' : 'pendente', null)
  const msgs = DB.comunicacoes.filter(f).sort((a, b) => a.created_at.localeCompare(b.created_at)); if (msgs.length) { add(msgs[0].created_at, 'ph:chat-circle-bold', 'Primeira mensagem registrada', corta(msgs[0].texto, 100), 'W' + msgs[0].id); if (msgs.length > 1) add(msgs[msgs.length - 1].created_at, 'ph:chat-circle-bold', 'Última mensagem registrada', corta(msgs[msgs.length - 1].texto, 100), 'W' + msgs[msgs.length - 1].id) }
  for (const x of DB.atividades.filter(a => f(a) && ['Anotação', 'Reunião', 'Ligação'].includes(a.tipo) && !/^(Atendimento:|Contato criado|Cadastro atualizado|Conversa do WhatsApp importada|Arquivo|Texto adicionado|Transcrição adicionada|Envio do formulário|\d+ arquivo)/.test(a.texto || ''))) add(x.created_at, 'ph:note-pencil-bold', x.tipo, corta(x.texto, 140), 'A' + x.id)
  return ev.sort((a, b) => b.quando.localeCompare(a.quando))
}
function AbaTempo(c, casoId) {
  const ev = linhaDoTempoCaso(c, casoId); let dia = null
  return h('div', { class: 'space-y-1', 'data-testid': 'linha-tempo' }, ev.length ? ev.map(e => { const d = diaDe(e.quando); const cab = d !== dia ? (dia = d, h('p', { class: 'section-label !mt-4' }, dataLonga(d))) : null; return h('div', {}, cab, h('div', { class: 'flex items-start gap-2 rounded-xl px-2 py-1.5 hover:bg-gray-50 dark:hover:bg-zinc-800/50', 'data-testid': 'evento' }, ic(e.icone, 'text-lg text-primary dark:text-cafe-creme mt-0.5'), h('div', { class: 'min-w-0 flex-1 text-sm' }, h('p', { class: 'font-medium' }, e.titulo), e.detalhe ? h('p', { class: 'text-xs text-gray-500' }, e.detalhe) : null), h('span', { class: 'text-[10px] text-gray-400 shrink-0' }, horaCurta(e.quando)), e.fonte && e.fonte !== 'F' ? chipFonte(e.fonte) : null)) }) : [estadoVazio('ph:clock-counter-clockwise-bold', 'Sem eventos ainda', 'A linha do tempo se monta sozinha a partir do que você registra.')])
}

/* ---------- contexto do caso (memória revisada por você) ---------- */
const CATS_CTX = [['fato', 'Fatos'], ['pessoa', 'Pessoas envolvidas'], ['cronologia', 'Cronologia'], ['patrimonio', 'Patrimônio'], ['documento', 'Documentos'], ['questao', 'Questões'], ['duvida', 'Dúvidas'], ['confirmado', 'Informações confirmadas'], ['pendente', 'Pendentes'], ['contradicao', 'Contradições'], ['decisao', 'Decisões'], ['proximo_passo', 'Próximos passos']]
const STATUS_CTX = [['informado', 'INFORMADO'], ['extraido_documento', 'DOCUMENTO'], ['inferencia', 'INFERÊNCIA'], ['hipotese', 'HIPÓTESE'], ['ausente', 'AUSENTE'], ['confirmar', 'CONFIRMAR'], ['confirmado', 'CONFIRMADO']]
function editarItemContexto(x, aoFim) {
  const novo = !x.id; const v = { categoria: x.categoria || 'fato', status: x.status || 'informado', texto: x.texto || '', data_fato: x.data_fato || '', fontes: (x.fontes || []).join(', ') }
  modal({ titulo: novo ? 'Novo item do contexto' : 'Item do contexto', largura: 'max-w-lg', corpo: h('div', { class: 'space-y-3', 'data-testid': 'ctx-form' }, h('label', { class: 'block' }, rotuloCampo('Categoria'), h('select', { class: 'modal-input', 'data-testid': 'ctx-cat', onchange: ev => { v.categoria = ev.target.value } }, CATS_CTX.map(([k, t]) => h('option', { value: k, selected: k === v.categoria }, t)))), h('label', { class: 'block' }, rotuloCampo('Situação da informação'), h('select', { class: 'modal-input', 'data-testid': 'ctx-status', onchange: ev => { v.status = ev.target.value } }, STATUS_CTX.map(([k, t]) => h('option', { value: k, selected: k === v.status }, t)))), h('label', { class: 'block' }, rotuloCampo('Texto'), h('textarea', { class: 'modal-input', rows: 4, 'data-testid': 'ctx-texto', oninput: ev => { v.texto = ev.target.value } }, v.texto)), h('label', { class: 'block' }, rotuloCampo('Data do fato (opcional)'), h('input', { type: 'date', class: 'modal-input', value: v.data_fato, onchange: ev => { v.data_fato = ev.target.value } })), h('label', { class: 'block' }, rotuloCampo('Fontes (ex.: W12, M3)'), h('input', { class: 'modal-input', value: v.fontes, oninput: ev => { v.fontes = ev.target.value } })), x.fontes && x.fontes.length ? h('div', { class: 'flex flex-wrap gap-1' }, x.fontes.map(chipFonte)) : null),
    rodape: f => [!novo ? btn('Excluir', { tipo: 'perigo', onclick: () => { DB.ctx_itens = DB.ctx_itens.filter(i => i.id !== x.id); salvar('ctx_itens'); f(); aoFim && aoFim(); render() } }) : null, btn('Salvar', { tid: 'ctx-salvar', onclick: () => { if (!v.texto.trim()) { aviso('Escreva o texto.', 'erro'); return } const dados = { categoria: v.categoria, status: v.status, texto: v.texto.trim(), data_fato: v.data_fato || null, fontes: v.fontes.split(/[,;\s]+/).filter(t => /^([WMRNACPX]\d+|F)$/.test(t)), revisado: true }; if (novo) DB.ctx_itens.push({ id: proximoId('ctx_itens'), contato_id: x.contato_id, caso_id: x.caso_id || null, criado_por: 'manual', created_at: agora(), ...dados }); else Object.assign(x, dados); salvar('ctx_itens'); f(); aoFim && aoFim(); render() } })] })
}
function AbaContexto(c, casoId) {
  const raiz = h('div', { class: 'space-y-4', 'data-testid': 'aba-contexto' })
  const des = () => {
    const itens = DB.ctx_itens.filter(doCaso(c, casoId)); const cats = CATS_CTX.filter(([k]) => itens.some(i => i.categoria === k))
    raiz.replaceChildren(
      alerta('info', null, 'O Contexto do Caso é a memória que o Assistente usa depois: só entra o que você aceitar. Cada item aponta para a fonte original (botões [W12], [M3]…) e os materiais originais nunca são alterados.'),
      h('div', { class: 'flex flex-wrap gap-2' }, btn('Atualizar contexto com o Assistente', { icone: 'ph:sparkle-bold', class: 'ia-btn', tid: 'ctx-atualizar', onclick: () => atualizarContextoIA(c, casoId, des) }), btn('Adicionar item', { tipo: 'sec', icone: 'ph:plus-bold', tid: 'ctx-novo', onclick: () => editarItemContexto({ contato_id: c.id, caso_id: casoId || null }, des) })),
      itens.length ? h('div', { class: 'space-y-4' }, cats.map(([k, titulo]) => h('section', { class: 'space-y-1.5' }, h('h4', { class: 'section-label' }, titulo + ' (' + itens.filter(i => i.categoria === k).length + ')'), ...itens.filter(i => i.categoria === k).sort((a, b) => String(a.data_fato || a.created_at).localeCompare(String(b.data_fato || b.created_at))).map(i => h('div', { class: 'flex flex-wrap items-start gap-2 rounded-xl border border-gray-200 dark:border-zinc-700 px-3 py-2 text-sm', 'data-testid': 'ctx-item' }, h('div', { class: 'min-w-0 flex-1' }, h('p', {}, i.data_fato ? h('b', {}, dataLonga(i.data_fato) + ' — ') : null, i.texto), h('p', { class: 'text-[11px] text-gray-500 flex flex-wrap items-center gap-1' }, badge((STATUS_CTX.find(s => s[0] === i.status) || [0, i.status])[1], 'cinza'), i.criado_por === 'ia' ? 'sugerido pelo Assistente, aceito por você' : 'registrado por você', ...(i.fontes || []).map(chipFonte))), btn('Editar', { mini: true, tipo: 'fantasma', onclick: () => editarItemContexto(i, des) })))))) : estadoVazio('ph:brain-bold', 'Contexto vazio', 'Importe a conversa e adicione materiais; depois use “Atualizar contexto com o Assistente” e aceite o que estiver certo.'))
  }
  des(); return raiz
}

/* ---------- visão geral: onde estamos e o que fazer ---------- */
function etapasDoFluxo(c, casoId) {
  const f = doCaso(c, casoId); const envs = DB.envios.filter(f); const cons = DB.consultas.filter(f); const an = tp => DB.analises.some(a => f(a) && (Array.isArray(tp) ? tp.includes(a.tipo) : a.tipo === tp))
  return [['Conversa importada', DB.comunicacoes.some(f) || DB.materiais.some(m => f(m) && m.tipo === 'conversa')], ['Conversa analisada pelo Assistente', an('conversa')], ['Perguntas sugeridas', an('perguntas_formulario')], ['Formulário enviado', envs.length > 0], ['Formulário respondido', envs.some(e => e.status === 'respondido')], ['Documentos recebidos', DB.materiais.some(m => f(m) && ['documento', 'pdf', 'imagem'].includes(m.tipo))], ['Consulta preparada', an('briefing')], ['Consulta realizada', cons.some(q => q.status === 'realizada')], ['Transcrição/anotações da consulta', DB.materiais.some(m => f(m) && m.tipo === 'transcricao') || cons.some(q => q.anotacoes)], ['Parecer', DB.pareceres.some(f)], ['Follow-up', an('followup')]]
}
function proximaAcao(c, casoId) {
  const e = etapasDoFluxo(c, casoId).filter(x => !x[1]).map(x => x[0]); const s = statusSugerido(c)
  const dica = { 'Conversa importada': 'Importe a conversa do WhatsApp (aba Conversas).', 'Conversa analisada pelo Assistente': 'Clique em “Analisar conversa”.', 'Perguntas sugeridas': 'Gere as perguntas do formulário a partir da conversa.', 'Formulário enviado': 'Envie o formulário (aba Formulário).', 'Formulário respondido': 'Aguardando a cliente responder: leia a planilha em Formulários.', 'Documentos recebidos': 'Peça e anexe os documentos (aba Materiais).', 'Consulta preparada': 'Clique em “Preparar consulta”.', 'Consulta realizada': 'Registre a consulta (aba Consultas).', 'Transcrição/anotações da consulta': 'Cole a transcrição ou as anotações da consulta.', 'Parecer': 'Gere o parecer na aba Pareceres.', 'Follow-up': 'Gere o follow-up.' }
  return { falta: e, proxima: e.length ? dica[e[0]] : 'Fluxo completo: acompanhe pendências e tarefas.', sugerido: s }
}
function AbaVisao(c, casoId) {
  const raiz = h('div', { class: 'space-y-4', 'data-testid': 'aba-visao' })
  const des = () => {
    const f = doCaso(c, casoId); const etapas = etapasDoFluxo(c, casoId); const pa = proximaAcao(c, casoId); const atual = statusDe(c); const analises = DB.analises.filter(a => f(a) && a.tipo !== 'resumo_conversa').sort((a, b) => b.created_at.localeCompare(a.created_at)); const ctx0 = montarContextoCaso(c, casoId)
    raiz.replaceChildren(
      painel('Atendimento', h('div', { class: 'space-y-3' }, h('div', { class: 'flex flex-wrap items-center gap-2' }, badge(atual, COR_ATEND[atual]), h('select', { class: 'modal-input !w-auto text-sm', 'aria-label': 'Estado do atendimento', 'data-testid': 'atend-status', onchange: ev => { definirStatus(c, ev.target.value, true); render() } }, STATUS_ATEND.map(s => h('option', { value: s, selected: s === atual }, s))), pa.sugerido !== atual ? h('span', { class: 'text-xs text-gray-600 dark:text-zinc-300 flex items-center gap-1' }, 'O CRM sugere: ', badge(pa.sugerido, COR_ATEND[pa.sugerido]), btn('Aplicar', { mini: true, tipo: 'sec', tid: 'atend-aplicar', onclick: () => { definirStatus(c, pa.sugerido, false); render() } })) : null), h('p', { class: 'text-sm' }, h('b', {}, 'Próximo passo: '), pa.proxima), h('div', { class: 'flex flex-wrap gap-1.5' }, etapas.map(([t, feito]) => h('span', { class: 'inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[11px] ' + (feito ? 'border-green-300 bg-green-50 text-green-800 dark:bg-green-900/20 dark:text-green-200 dark:border-green-800' : 'border-gray-200 text-gray-500 dark:border-zinc-700'), 'data-testid': feito ? 'etapa-feita' : 'etapa-falta' }, ic(feito ? 'ph:check-circle-bold' : 'ph:circle-dashed-bold'), t))))),
      painel('Assistente sobre o material deste caso', h('div', { class: 'space-y-3' }, h('p', { class: 'text-xs text-gray-600 dark:text-zinc-300', 'data-testid': 'visao-lido' }, `O Assistente vai ler: ${plural(ctx0.stats.msgsIncluidas, 'mensagem', 'mensagens')} (de ${ctx0.stats.msgs}) · ${plural(ctx0.stats.materiais, 'material', 'materiais')}${ctx0.stats.materiaisSemTexto ? ` (${ctx0.stats.materiaisSemTexto} sem texto lido)` : ''} · ${plural(ctx0.stats.respostas, 'resposta de formulário', 'respostas de formulário')} · ${plural(ctx0.stats.consultas, 'consulta', 'consultas')}${ctx0.stats.itensX ? ` · ${ctx0.stats.itensX} item(ns) de contexto confirmado(s)` : ''}.`), ...ctx0.avisos.map(a => alerta('aviso', null, a)),
        h('div', { class: 'flex flex-wrap gap-2' }, [['Analisar conversa', 'ph:chat-circle-text-bold', () => analisarConversaIA(c, casoId), 'ia-analisar-conversa'], ['Gerar perguntas para o formulário', 'ph:list-checks-bold', () => perguntasParaFormulario(c, casoId), 'ia-perguntas'], ['Analisar todo o material do caso', 'ph:magnifying-glass-bold', () => analisarTudoIA(c, casoId), 'ia-analisar-tudo'], ['Preparar consulta', 'ph:presentation-bold', () => prepararConsultaIA(c, casoId), 'ia-preparar'], ['Cronologia', 'ph:clock-counter-clockwise-bold', () => cronologiaIA(c, casoId), 'ia-cronologia'], ['Inconsistências', 'ph:warning-diamond-bold', () => inconsistenciasIA(c, casoId), 'ia-inconsistencias'], ['Sugerir tarefas', 'ph:check-square-bold', () => tarefasIA(c, casoId), 'ia-tarefas'], ['Gerar follow-up', 'ph:paper-plane-tilt-bold', () => followUpIA(c, casoId), 'ia-followup']].map(([t, i, fn, tid]) => btn(t, { mini: true, tipo: 'sec', icone: i, class: 'ia-btn', tid, onclick: fn }))),
        ctx0.stats.msgs > ctx0.stats.msgsIncluidas ? btn('Resumir parte antiga da conversa (para o Assistente considerar tudo)', { mini: true, tipo: 'fantasma', tid: 'ia-resumir-antiga', onclick: () => resumirConversaAntiga(c, casoId) }) : null)),
      painel('Análises salvas (rascunhos para você revisar)', analises.length ? lista(analises.map(a => [ic('ph:sparkle-bold', 'text-xl text-primary dark:text-cafe-creme'), h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'font-semibold text-sm truncate' }, a.titulo), h('p', { class: 'text-[11px] text-gray-500' }, dataHora(a.created_at))), badge(a.status === 'revisada' ? 'Revisada' : 'Rascunho', a.status === 'revisada' ? 'verde' : 'ambar'), btn('Abrir', { mini: true, tipo: 'sec', tid: 'analise-abrir', onclick: () => abrirAnalise(a, des) })])) : h('p', { class: 'text-sm text-gray-500' }, 'Nenhuma análise salva ainda.')))
  }
  des(); return raiz
}
function abrirAnalise(a, aoFim) {
  const c = contato(a.contato_id); const area = h('textarea', { class: 'modal-input text-sm', rows: 14, 'data-testid': 'analise-texto' }); area.value = a.texto || (a.dados ? JSON.stringify(a.dados, null, 2) : '')
  modal({ titulo: a.titulo, largura: 'max-w-3xl', corpo: h('div', { class: 'space-y-3' }, h('p', { class: 'text-[11px] text-gray-500' }, `${dataHora(a.created_at)} · ${a.status === 'revisada' ? 'revisada por você' : 'rascunho gerado pelo Assistente — revise'}`), renderTextoIA(a.texto || ''), h('details', {}, h('summary', { class: 'cursor-pointer text-xs text-gray-500' }, 'Editar o texto'), area)), rodape: f => [btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Excluir esta análise?', 'O material original não é afetado.', 'Excluir', () => { DB.analises = DB.analises.filter(x => x.id !== a.id); salvar('analises'); f(); aoFim && aoFim(); render() }) }), btn('Copiar', { tipo: 'sec', onclick: () => copiar(area.value) }), a.tipo === 'followup' && !a.enviado_manual_em ? btn('Marcei como enviado por mim', { tipo: 'sec', tid: 'followup-enviado', onclick: () => { a.enviado_manual_em = agora(); salvar('analises'); registrar(a.contato_id, 'Mensagem', 'Follow-up enviado manualmente por você.', a.caso_id); f(); aoFim && aoFim(); render() } }) : null, btn(a.status === 'revisada' ? 'Revisada ✓' : 'Marcar como revisada', { tid: 'analise-revisar', disabled: a.status === 'revisada', onclick: () => { a.texto = area.value; a.status = 'revisada'; a.revisada_em = agora(); salvar('analises'); f(); aoFim && aoFim(); render() } })] })
}

/* ---------- tela do atendimento ---------- */
VIEWS.caso = (p) => {
  if (p && p.contato) { CASO_ATUAL.cid = Number(p.contato); CASO_ATUAL.casoId = p.caso != null && p.caso !== '' ? Number(p.caso) : null; if (p.aba) UI.caso.aba = p.aba; R.p = { ...p, contato: undefined, aba: undefined } }
  const c = contato(CASO_ATUAL.cid); if (!c) return pagina('Atendimento', null, null, estadoVazio('ph:brain-bold', 'Escolha uma pessoa', 'Abra pelo painel de Atendimento ou pela ficha da pessoa.', btn('Ir ao painel', { onclick: () => ir('atendimento') })))
  const casoId = CASO_ATUAL.casoId; const dms = demandasDe(c.id); const A = UI.caso.aba
  const abas = [['visao', 'Visão geral', 'ph:compass-bold'], ['conversas', 'Conversas', 'ph:chats-circle-bold'], ['materiais', 'Materiais', 'ph:folder-open-bold'], ['formulario', 'Formulário', 'ph:clipboard-text-bold'], ['consultas', 'Consultas', 'ph:calendar-check-bold'], ['contexto', 'Contexto do caso', 'ph:brain-bold'], ['pareceres', 'Pareceres', 'ph:scales-bold'], ['tempo', 'Linha do tempo', 'ph:clock-counter-clockwise-bold'], ['chat', 'Chat com o Assistente', 'ph:sparkle-bold']]
  const corpo = { visao: () => AbaVisao(c, casoId), conversas: () => AbaConversas(c, casoId), materiais: () => PainelMateriais(c, casoId), formulario: () => AbaFormulario(c, casoId), consultas: () => AbaConsultas(c, casoId), contexto: () => AbaContexto(c, casoId), pareceres: () => AbaPareceres(c, casoId), tempo: () => AbaTempo(c, casoId), chat: () => AbaChat(c, casoId) }[A]()
  return pagina('Atendimento — ' + c.nome, 'O Assistente lê tudo o que você inseriu sobre esta pessoa' + (casoId ? ' e demanda' : '') + ', organiza, aponta lacunas e sugere próximos passos. Você revisa e decide; nada é enviado sozinho.', [btn('Abrir ficha', { tipo: 'sec', icone: 'ph:user-bold', tid: 'caso-ficha', onclick: () => abrirFicha(c.id) }), btn('Painel', { tipo: 'fantasma', icone: 'ph:arrow-left-bold', tid: 'caso-painel', onclick: () => ir('atendimento') })],
    h('div', { class: 'flex flex-wrap items-center gap-2' }, h('label', { class: 'text-xs text-gray-500 flex items-center gap-2' }, 'Foco:', h('select', { class: 'modal-input !w-auto text-sm', 'aria-label': 'Demanda em foco', 'data-testid': 'caso-demanda', onchange: ev => { CASO_ATUAL.casoId = ev.target.value ? Number(ev.target.value) : null; render() } }, h('option', { value: '' }, 'Pessoa (todas as demandas)'), dms.map(d => h('option', { value: d.id, selected: d.id === casoId }, d.titulo)))), casoId ? h('span', { class: 'text-[11px] text-gray-500' }, 'O Assistente lê só esta demanda e o que é da pessoa sem demanda.') : h('span', { class: 'text-[11px] text-gray-500' }, 'Sem demanda escolhida: o Assistente lê tudo da pessoa.')),
    h('div', { class: 'flex flex-wrap gap-1.5' }, abas.map(([k, t, i]) => h('button', { type: 'button', class: 'tab-btn inline-flex items-center gap-1.5 ' + (A === k ? 'tab-btn-ativo' : ''), 'data-testid': 'caso-aba-' + k, onclick: () => { UI.caso.aba = k; render() } }, ic(i), t))), corpo)
}
function AbaConversas(c, casoId) { return h('div', { class: 'space-y-3', 'data-testid': 'aba-conversas' }, h('div', { class: 'flex flex-wrap gap-2' }, btn('Importar conversa do WhatsApp', { icone: 'ph:upload-simple-bold', tid: 'caso-importar-whats', onclick: () => importarConversaWhatsApp({ contato: c, caso: casoId || '' }) }), btn('Analisar conversa com o Assistente', { tipo: 'sec', icone: 'ph:sparkle-bold', class: 'ia-btn', tid: 'caso-analisar-conversa', onclick: () => analisarConversaIA(c, casoId) })), Thread(c.id, casoId != null ? { caso: casoId } : {})) }
function abrirAtendimento(cid, casoId, aba) { ir('caso', { contato: cid, caso: casoId == null ? '' : casoId, aba: aba || 'visao' }) }

/* ---------- painel de atendimento comercial ---------- */
UI.atend = { aba: 'painel', status: 'todos', q: '', exemplos: false }
VIEWS.atendimento = (p) => {
  if (p && p.aba) UI.atend.aba = p.aba
  return modulo({ titulo: 'Atendimento', sub: 'O Assistente lê o material de cada caso e ajuda a conduzir o atendimento; você revisa e decide.', abasDef: [{ id: 'painel', nome: 'Atendimentos', icone: 'ph:kanban-bold' }, { id: 'identidade', nome: 'Identidade visual', icone: 'ph:palette-bold' }], ativa: UI.atend.aba, aoMudar: id => { UI.atend.aba = id; render() }, conteudo: a => a === 'identidade' ? VIEWS.identidade() : painelAtendimento() })
}
const painelAtendimento = () => {
  const todos = DB.contatos.filter(c => UI.atend.exemplos || !ehExemplo(c)); const q = semAcento(UI.atend.q)
  const lista_ = todos.filter(c => (UI.atend.status === 'todos' || statusDe(c) === UI.atend.status) && (!q || semAcento(c.nome).includes(q)))
  return pagina('Atendimentos', 'Da primeira conversa à demanda: onde cada pessoa está e o que falta. O Assistente lê o material de cada caso.', [btn('Nova pessoa', { icone: 'ph:user-plus-bold', tid: 'atend-nova', onclick: () => editarContato(null) }), btn('Importar conversa do WhatsApp', { tipo: 'sec', icone: 'ph:whatsapp-logo-bold', tid: 'atend-importar', onclick: () => importarConversaWhatsApp({}) })],
    h('div', { class: 'flex flex-wrap items-center gap-2' }, h('div', { class: 'w-56' }, busca(UI.atend.q, v => { UI.atend.q = v; render() }, 'Buscar pessoa…')), h('label', { class: 'flex items-center gap-1.5 text-xs text-gray-500' }, h('input', { type: 'checkbox', class: 'accent-[#6f5636]', checked: UI.atend.exemplos, onchange: ev => { UI.atend.exemplos = ev.target.checked; render() } }), 'mostrar pessoas de exemplo')),
    h('div', { class: 'flex flex-wrap gap-1.5' }, [['todos', 'Todos'], ...STATUS_ATEND.map(s => [s, s])].map(([k, t]) => h('button', { type: 'button', class: 'filtro ' + (UI.atend.status === k ? 'filtro-ativo' : ''), 'data-testid': 'atend-filtro', onclick: () => { UI.atend.status = k; render() } }, `${t} (${k === 'todos' ? todos.length : todos.filter(c => statusDe(c) === k).length})`))),
    lista_.length ? lista(lista_.map(c => [avatar(c.nome), h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'font-semibold text-sm truncate' }, c.nome, ehExemplo(c) ? badge('exemplo', 'cinza') : null), h('p', { class: 'text-[11px] text-gray-500 truncate' }, [c.demanda, DB.comunicacoes.filter(m => m.contato_id === c.id).length + ' msg', DB.materiais.filter(m => m.contato_id === c.id && m.tipo !== 'conversa').length + ' materiais'].filter(Boolean).join(' · '))), badge(statusDe(c), COR_ATEND[statusDe(c)]), btn('Abrir', { mini: true, tid: 'atend-abrir', onclick: () => abrirAtendimento(c.id) })])) : estadoVazio('ph:users-three-bold', 'Ninguém aqui', 'Cadastre uma pessoa ou importe uma conversa do WhatsApp.'))
}
