'use strict'
/* ============ Ações de IA do atendimento: cada uma lê o MATERIAL REAL do caso e devolve rascunho com fontes; você revisa ============ */
const SEC = (...t) => 'Responda com EXATAMENTE estes títulos, nesta ordem, cada um em uma linha em maiúsculas seguida do conteúdo em tópicos curtos (se não houver nada, escreva “Nada consta no material”):\n' + t.map((x, i) => `${i + 1}. ${x}`).join('\n') + '\nEm cada tópico, rotule ([INFORMADO], [DOCUMENTO], [INFERÊNCIA], [HIPÓTESE], [AUSENTE], [CONFIRMAR], [PESQUISAR]) e cite as fontes ([W12], [M3]…).'

function analisarConversaIA(c, casoId) {
  janelaNucleo({ c, casoId, titulo: 'Análise da conversa — ' + c.nome, tipo: 'conversa', tarefa: 'Leia a CONVERSA (itens [W…]) por inteiro e me explique o que aconteceu e como conduzir o atendimento. Use as demais fontes só para confirmar ou contradizer. Diferencie claramente fato informado, informação de documento, inferência, hipótese, informação ausente e o que precisa ser confirmado.',
    formato: SEC('RESUMO DO CONTATO (o que aconteceu?)', 'DEMANDA APARENTE (o que a pessoa parece buscar?)', 'INFORMAÇÕES JÁ FORNECIDAS', 'INFORMAÇÕES AUSENTES (o que ainda não sabemos)', 'PESSOAS ENVOLVIDAS', 'DOCUMENTOS MENCIONADOS', 'DATAS IMPORTANTES', 'PONTOS DE ATENÇÃO', 'POSSÍVEIS INCONSISTÊNCIAS', 'PRÓXIMAS PERGUNTAS (o que perguntar agora)', 'DOCUMENTOS A SOLICITAR') })
}
function analisarTudoIA(c, casoId) {
  janelaNucleo({ c, casoId, titulo: 'Análise de todo o material — ' + c.nome, tipo: 'caso', tier: 'complex', tarefa: 'Leia TODAS as fontes do caso juntas (conversa, formulários, documentos, transcrições, anotações, contexto confirmado) e construa uma visão consolidada. Cruze as fontes: aponte onde uma fonte contradiz ou não esclarece outra, no formato “Na conversa foi informado X [W…], o documento mostra Y [M…] e o formulário não esclareceu Z [R…]”. Não deixe de apontar o que NÃO foi lido (materiais sem texto).',
    formato: SEC('VISÃO GERAL', 'FATOS CONSOLIDADOS (por fonte)', 'PESSOAS', 'PATRIMÔNIO E DOCUMENTOS', 'CRONOLOGIA', 'DIVERGÊNCIAS ENTRE FONTES', 'LACUNAS (o que falta saber)', 'PERGUNTAS A FAZER', 'DOCUMENTOS A SOLICITAR', 'PONTOS A PESQUISAR JURIDICAMENTE', 'PRÓXIMOS PASSOS') })
}
function prepararConsultaIA(c, casoId) {
  janelaNucleo({ c, casoId, titulo: 'Preparação da consulta — ' + c.nome, tipo: 'briefing', tier: 'complex', tarefa: 'Prepare um briefing para a advogada entrar na consulta preparada, lendo conversa, formulário, respostas, documentos, histórico e anotações. Seja objetivo e use só o material real.',
    formato: SEC('QUEM É A PESSOA', 'MOTIVO DO CONTATO', 'RESUMO DOS FATOS', 'CRONOLOGIA', 'PESSOAS ENVOLVIDAS', 'DOCUMENTOS RECEBIDOS', 'INFORMAÇÕES JÁ CONFIRMADAS', 'INFORMAÇÕES PENDENTES', 'INCONSISTÊNCIAS', 'PERGUNTAS QUE AINDA PRECISO FAZER', 'DOCUMENTOS QUE AINDA PRECISO SOLICITAR', 'PONTOS JURÍDICOS A ANALISAR', 'PONTOS QUE NÃO POSSO ESQUECER NA CONSULTA') })
}
const cronologiaIA = (c, casoId) => janelaNucleo({ c, casoId, titulo: 'Cronologia — ' + c.nome, tipo: 'cronologia', tarefa: 'Organize os fatos do caso em ORDEM CRONOLÓGICA (da data mais antiga à mais recente), uma linha por evento: data — o que aconteceu — rótulo — fonte. Eventos sem data ficam num bloco “Sem data definida”. Não invente datas.' })
const inconsistenciasIA = (c, casoId) => janelaNucleo({ c, casoId, titulo: 'Inconsistências — ' + c.nome, tipo: 'inconsistencias', tarefa: 'Procure CONTRADIÇÕES e divergências entre as fontes do caso (e dentro de uma mesma fonte): datas, nomes, valores, titularidade de bens, estado civil, filhos, versões dos fatos. Para cada uma, cite as duas fontes e diga o que precisa ser esclarecido. Se não houver divergência clara, diga isso; não force.' })

/* ---------- janela para respostas estruturadas (JSON) com revisão humana ---------- */
function janelaJSON({ c, casoId, titulo, tarefa, formato, tier, antes, mostrar }) {
  const corpo = h('div', { class: 'space-y-3', 'data-testid': 'nucleo-json' }, h('p', { class: 'text-sm text-gray-500' }, 'Lendo o material do caso…')); let ctl = null; let fecharFn = null
  const rodar = () => exigirIA(async s => {
    ctl && ctl.abort(); ctl = new AbortController(); corpo.replaceChildren(h('p', { class: 'text-sm text-gray-500' }, 'Pensando… (respostas estruturadas levam de 30 s a 2 min)'))
    try { const r = await rodarNucleo(s, { c, casoId, tarefa: typeof tarefa === 'function' ? tarefa() : tarefa, formato: typeof formato === 'function' ? formato() : formato, json: true, tier, signal: ctl.signal }); corpo.replaceChildren(...r.ctx.avisos.map(a => alerta('aviso', null, a)), mostrar(r.dados, r.ctx, () => fecharFn && fecharFn(), rodar)) }
    catch (e) { if (e && e.code === 'cancelled') return; corpo.replaceChildren(h('p', { class: 'text-sm text-danger' }, iaErro(e)), btn('Tentar de novo', { mini: true, onclick: rodar })) }
  })
  const abrir = (extra) => { modal({ titulo, largura: 'max-w-3xl', corpo: h('div', { class: 'space-y-3' }, alerta('info', null, 'Sugestões da IA a partir do material real. Nada é salvo nem enviado sem a sua revisão.'), extra || null, corpo), aoFechar: () => { ctl && ctl.abort() }, rodape: f => { fecharFn = f; return [btn('Fechar', { tipo: 'sec', onclick: f })] } }); rodar() }
  if (antes) antes(abrir); else abrir()
}
const arr = x => Array.isArray(x) ? x : []
const sTxt = x => typeof x === 'string' ? x : x == null ? '' : String(x)

/* ---------- formulário inteligente: só perguntas úteis, depois da conversa ---------- */
const TIPOS_GFORMS = ['Resposta curta', 'Parágrafo', 'Múltipla escolha', 'Caixas de seleção', 'Lista suspensa', 'Data', 'Horário', 'Upload de arquivo']
function perguntasParaFormulario(c, casoId) {
  let formSel = ''
  const existentes = () => { const f = formSel ? formularioDe(Number(formSel)) : null; return f ? itensDe(f).map(i => i.texto).filter(t => !/c[oó]digo/i.test(t)) : [] }
  janelaJSON({ c, casoId, titulo: 'Perguntas para o formulário — ' + c.nome, tier: 'complex',
    antes: abrir => modal({ titulo: 'Gerar perguntas para o formulário', largura: 'max-w-md', corpo: h('div', { class: 'space-y-3' }, h('p', { class: 'text-sm' }, 'A IA lê a conversa e o que já existe do caso e sugere SÓ o que falta. Nada entra no formulário sem a sua revisão.'), h('label', { class: 'block' }, rotuloCampo('Formulário que receberá as perguntas (opcional)'), h('select', { class: 'modal-input', 'data-testid': 'pf-form', onchange: ev => { formSel = ev.target.value } }, h('option', { value: '' }, '— ainda não escolhi —'), DB.formularios.map(f => h('option', { value: f.id }, f.nome)))), h('p', { class: 'text-xs text-gray-500' }, 'Se escolher, a IA não repete as perguntas que o formulário já tem.')), rodape: f => [btn('Cancelar', { tipo: 'sec', onclick: f }), btn('Gerar', { tid: 'pf-gerar', onclick: () => { f(); abrir() } })] }),
    tarefa: () => { const ex = existentes(); return 'Com base no que a pessoa JÁ DISSE (conversa [W…]), no que já consta em documentos, formulários e contexto confirmado, identifique as LACUNAS e proponha SOMENTE perguntas úteis para preenchê-las. NÃO pergunte o que já foi informado (liste isso em ja_respondidas, com a fonte). Prefira perguntas complementares que decorram do que foi dito (ex.: se disse que é casada há 15 anos e tem dois filhos, não pergunte se é casada; pergunte regime de bens, se os filhos são menores, bens adquiridos no casamento, etc.). Perguntas claras, em linguagem simples, uma ideia por pergunta, sem juridiquês.' + (ex.length ? '\nO formulário escolhido JÁ tem estas perguntas (não repita): ' + ex.map(t => '“' + t + '”').join('; ') : '') },
    formato: () => { return 'Responda SOMENTE com JSON válido neste formato (arrays podem ser vazios; não invente fontes):\n{"ja_respondidas":[{"pergunta":"…","resposta":"…","fonte":"W12"}],"faltam":[{"tema":"…","motivo":"…"}],"perguntas_sugeridas":[{"texto":"…","tipo":"' + TIPOS_GFORMS.join('|') + '","opcoes":["…"],"obrigatoria":true,"motivo":"por que perguntar","fontes":["W12"]}],"documentos_sugeridos":[{"documento":"…","motivo":"…"}],"confirmar_na_consulta":[{"ponto":"…","motivo":"…"}]}' },
    mostrar: (d, ctx, fechar, refazer) => {
      const sug = arr(d.perguntas_sugeridas).map(q => ({ texto: sTxt(q.texto), tipo: TIPOS_GFORMS.includes(q.tipo) ? q.tipo : 'Resposta curta', opcoes: arr(q.opcoes).map(sTxt), obrigatoria: !!q.obrigatoria, motivo: sTxt(q.motivo), fontes: arr(q.fontes).map(sTxt), marcada: true })).filter(q => q.texto)
      const alvo = h('select', { class: 'modal-input !w-auto text-sm', 'data-testid': 'pf-alvo', 'aria-label': 'Formulário de destino' }, h('option', { value: '' }, 'Escolha o formulário…'), DB.formularios.map(f => h('option', { value: f.id, selected: String(f.id) === formSel }, f.nome)))
      const bloco = (titulo, itens, fn) => itens.length ? h('section', { class: 'space-y-1' }, h('h4', { class: 'section-label' }, titulo + ' (' + itens.length + ')'), h('ul', { class: 'list-disc pl-5 text-sm space-y-0.5' }, itens.map(fn))) : null
      const lista_ = h('div', { class: 'space-y-2', 'data-testid': 'pf-sugeridas' }, sug.map((q, i) => h('div', { class: 'rounded-xl border border-gray-200 dark:border-zinc-700 p-2.5 space-y-1.5' }, h('label', { class: 'flex items-start gap-2' }, h('input', { type: 'checkbox', class: 'mt-1 accent-[#6f5636]', checked: q.marcada, 'data-testid': 'pf-marcar', onchange: ev => { q.marcada = ev.target.checked } }), h('input', { class: 'modal-input !text-sm flex-1', value: q.texto, 'aria-label': 'Pergunta', oninput: ev => { q.texto = ev.target.value } })), h('div', { class: 'flex flex-wrap items-center gap-2 pl-6 text-xs' }, h('select', { class: 'modal-input !w-auto !py-1 !text-xs', 'aria-label': 'Tipo', onchange: ev => { q.tipo = ev.target.value } }, TIPOS_GFORMS.map(t => h('option', { value: t, selected: t === q.tipo }, t))), h('label', { class: 'flex items-center gap-1' }, h('input', { type: 'checkbox', checked: q.obrigatoria, class: 'accent-[#6f5636]', onchange: ev => { q.obrigatoria = ev.target.checked } }), 'obrigatória'), q.opcoes.length ? h('span', { class: 'text-gray-500' }, 'opções: ' + q.opcoes.join(' / ')) : null), q.motivo ? h('p', { class: 'pl-6 text-[11px] text-gray-500' }, 'Por quê: ' + q.motivo, ...q.fontes.map(t => chipFonte(t))) : null)))
      const texto = () => sug.filter(q => q.marcada).map((q, i) => `${i + 1}. ${q.texto} [${q.tipo}${q.obrigatoria ? ', obrigatória' : ''}${q.opcoes.length ? ': ' + q.opcoes.join(' / ') : ''}]`).join('\n')
      return h('div', { class: 'space-y-4', 'data-testid': 'pf-resultado' },
        bloco('Perguntas JÁ RESPONDIDAS', arr(d.ja_respondidas), x => h('li', {}, h('b', {}, sTxt(x.pergunta) + ': '), sTxt(x.resposta), ...(x.fonte ? [chipFonte(sTxt(x.fonte))] : []))), bloco('O que AINDA FALTA', arr(d.faltam), x => h('li', {}, h('b', {}, sTxt(x.tema) + ' — '), sTxt(x.motivo))),
        h('section', { class: 'space-y-2' }, h('h4', { class: 'section-label' }, 'Perguntas SUGERIDAS (revise, edite e marque as que entram)'), sug.length ? lista_ : h('p', { class: 'text-sm text-gray-500' }, 'A IA não sugeriu perguntas novas: o material já responde o essencial.')),
        bloco('Documentos sugeridos', arr(d.documentos_sugeridos), x => h('li', {}, h('b', {}, sTxt(x.documento) + ' — '), sTxt(x.motivo))), bloco('Pontos para confirmar na consulta', arr(d.confirmar_na_consulta), x => h('li', {}, h('b', {}, sTxt(x.ponto) + ' — '), sTxt(x.motivo))),
        h('div', { class: 'flex flex-wrap items-center gap-2 border-t border-gray-100 dark:border-zinc-800 pt-3' }, alvo, btn('Guardar selecionadas no formulário', { mini: true, icone: 'ph:list-plus-bold', tid: 'pf-guardar', onclick: () => { const f = formularioDe(Number(alvo.value)); if (!f) { aviso('Escolha o formulário.', 'erro'); return } const sel = sug.filter(q => q.marcada && q.texto.trim()); if (!sel.length) { aviso('Marque ao menos uma pergunta.', 'erro'); return } f.planejado = [...(f.planejado || []), ...sel.map(q => ({ id: Date.now() + Math.random(), texto: q.texto.trim(), tipo: q.tipo, opcoes: q.opcoes, obrigatoria: q.obrigatoria, origem: 'IA (conversa de ' + c.nome + ')', em: agora() }))]; salvar('formularios'); aviso(`${plural(sel.length, 'pergunta guardada', 'perguntas guardadas')} em “${f.nome}” (aba Formulário). Crie-as no Google Forms para valerem para a cliente.`) } }), btn('Copiar selecionadas', { mini: true, tipo: 'sec', icone: 'ph:copy-bold', tid: 'pf-copiar', onclick: () => texto() ? copiar(texto()) : aviso('Marque ao menos uma pergunta.', 'erro') }), btn('Salvar análise', { mini: true, tipo: 'fantasma', tid: 'pf-salvar', onclick: () => { salvarAnalise({ c, casoId, tipo: 'perguntas_formulario', titulo: 'Perguntas para o formulário', texto: 'PERGUNTAS JÁ RESPONDIDAS\n' + arr(d.ja_respondidas).map(x => `- ${sTxt(x.pergunta)}: ${sTxt(x.resposta)} ${x.fonte ? '[' + sTxt(x.fonte) + ']' : ''}`).join('\n') + '\n\nO QUE AINDA FALTA\n' + arr(d.faltam).map(x => `- ${sTxt(x.tema)} — ${sTxt(x.motivo)}`).join('\n') + '\n\nPERGUNTAS SUGERIDAS\n' + (texto() || sug.map((q, i) => `${i + 1}. ${q.texto}`).join('\n')) + '\n\nDOCUMENTOS SUGERIDOS\n' + arr(d.documentos_sugeridos).map(x => `- ${sTxt(x.documento)} — ${sTxt(x.motivo)}`).join('\n') + '\n\nPONTOS PARA CONFIRMAR NA CONSULTA\n' + arr(d.confirmar_na_consulta).map(x => `- ${sTxt(x.ponto)} — ${sTxt(x.motivo)}`).join('\n'), dados: d }); aviso('Análise salva.') } }), btn('Refazer', { mini: true, tipo: 'fantasma', onclick: refazer })), h('p', { class: 'text-[11px] text-gray-500' }, 'O Google Forms não pode ser editado pelo CRM: as perguntas guardadas ficam como lista para você criar lá.'))
    } })
}

/* ---------- tarefas sugeridas (você revisa antes de salvar) ---------- */
function tarefasIA(c, casoId) {
  janelaJSON({ c, casoId, titulo: 'Tarefas sugeridas — ' + c.nome,
    tarefa: 'Identifique no material TAREFAS e PENDÊNCIAS concretas: o que a cliente ficou de enviar ou fazer (tarefa “aguardar”), o que o escritório precisa verificar/pesquisar/preparar/solicitar. Uma tarefa por item, título curto no imperativo, sem duplicar tarefas já existentes no CRM. Prazo só se o material indicar uma data ou prazo claro; caso contrário null. Nada inventado.',
    formato: 'Responda SOMENTE com JSON: {"tarefas":[{"titulo":"…","descricao":"…","prazo":"AAAA-MM-DD ou null","prioridade":"baixa|media|alta","responsavel":"escritorio|cliente","fonte":"W12"}]}',
    mostrar: (d, ctx, fechar) => {
      const ts = arr(d.tarefas).map(t => ({ titulo: sTxt(t.titulo), descricao: sTxt(t.descricao), prazo: /^\d{4}-\d{2}-\d{2}$/.test(sTxt(t.prazo)) ? t.prazo : '', prioridade: ['baixa', 'media', 'alta'].includes(t.prioridade) ? t.prioridade : 'media', responsavel: t.responsavel === 'cliente' ? 'cliente' : 'escritorio', fonte: sTxt(t.fonte), marcada: true })).filter(t => t.titulo)
      return h('div', { class: 'space-y-3', 'data-testid': 'ts-resultado' }, ts.length ? ts.map(t => h('div', { class: 'rounded-xl border border-gray-200 dark:border-zinc-700 p-2.5 space-y-1.5' }, h('label', { class: 'flex items-start gap-2' }, h('input', { type: 'checkbox', class: 'mt-1 accent-[#6f5636]', checked: true, 'data-testid': 'ts-marcar', onchange: ev => { t.marcada = ev.target.checked } }), h('input', { class: 'modal-input !text-sm flex-1', value: (t.responsavel === 'cliente' ? 'Aguardar: ' : '') + t.titulo, 'aria-label': 'Título', oninput: ev => { t.titulo = ev.target.value; t.responsavel = 'escritorio' } })), h('div', { class: 'flex flex-wrap items-center gap-2 pl-6 text-xs' }, h('input', { type: 'date', class: 'modal-input !w-auto !py-1 !text-xs', value: t.prazo, 'aria-label': 'Prazo', onchange: ev => { t.prazo = ev.target.value } }), h('select', { class: 'modal-input !w-auto !py-1 !text-xs', 'aria-label': 'Prioridade', onchange: ev => { t.prioridade = ev.target.value } }, ['baixa', 'media', 'alta'].map(p_ => h('option', { value: p_, selected: p_ === t.prioridade }, p_))), t.fonte ? chipFonte(t.fonte) : null), t.descricao ? h('p', { class: 'pl-6 text-[11px] text-gray-500' }, t.descricao) : null)) : [h('p', { class: 'text-sm text-gray-500' }, 'A IA não encontrou tarefas claras no material.')],
        ts.length ? btn('Criar as tarefas marcadas', { tid: 'ts-criar', icone: 'ph:check-square-bold', onclick: () => { const sel = ts.filter(t => t.marcada && t.titulo.trim()); sel.forEach(t => DB.tarefas.push({ id: proximoId('tarefas'), titulo: ((t.responsavel === 'cliente' && !/^Aguardar/i.test(t.titulo)) ? 'Aguardar: ' : '') + t.titulo.trim(), descricao: (t.descricao || '') + '\n(Sugerida pela IA a partir do caso; revisada por você.)', concluida: false, prazo: t.prazo || somarDias(hojeISO(), 3), prioridade: t.prioridade, contato_id: c.id, caso_id: casoId || null, processo_id: null, created_at: agora(), updated_at: agora(), origem: 'ia' })); salvar('tarefas'); registrar(c.id, 'Anotação', `${plural(sel.length, 'tarefa criada', 'tarefas criadas')} a partir da análise da IA (revisadas por você).`, casoId); fechar(); aviso(`${plural(sel.length, 'tarefa criada', 'tarefas criadas')}.`); render() } }) : null)
    } })
}

/* ---------- contexto do caso: a IA propõe, você aceita ---------- */
function atualizarContextoIA(c, casoId, aoFim) {
  janelaJSON({ c, casoId, titulo: 'Atualizar o contexto do caso — ' + c.nome, tier: 'complex',
    tarefa: 'Extraia do material os itens que devem compor o CONTEXTO DO CASO: fatos, pessoas, cronologia, patrimônio, documentos, questões, dúvidas, informações pendentes, contradições, decisões e próximos passos. Só itens SUPORTADOS pelo material, um fato por item, texto curto e objetivo, com fontes. Não repita o que já está no contexto confirmado [X…]; se algo novo contradiz um [X], registre como “contradicao”. Para cada item, diga a situação da informação.',
    formato: 'Responda SOMENTE com JSON: {"itens":[{"categoria":"' + CATS_CTX.map(x => x[0]).join('|') + '","texto":"…","status":"informado|extraido_documento|inferencia|hipotese|ausente|confirmar","data_fato":"AAAA-MM-DD ou null","fontes":["W12","M3"]}]}',
    mostrar: (d, ctx, fechar) => {
      const its = arr(d.itens).map(i => ({ categoria: CATS_CTX.some(x => x[0] === i.categoria) ? i.categoria : 'fato', texto: sTxt(i.texto), status: STATUS_CTX.some(x => x[0] === i.status) ? i.status : 'informado', data_fato: /^\d{4}-\d{2}-\d{2}$/.test(sTxt(i.data_fato)) ? i.data_fato : '', fontes: arr(i.fontes).map(sTxt).filter(t => /^([WMRNACPX]\d+|F)$/.test(t) && ctx.fontes[t]), marcada: ['informado', 'extraido_documento', 'ausente', 'confirmar'].includes(i.status) })).filter(i => i.texto)
      return h('div', { class: 'space-y-3', 'data-testid': 'cx-resultado' }, h('p', { class: 'text-xs text-gray-500' }, 'Itens sugeridos: marque os que estão certos (inferências e hipóteses vêm desmarcadas). Itens sem fonte válida perdem o vínculo com a origem.'), its.length ? its.map(i => h('div', { class: 'rounded-xl border border-gray-200 dark:border-zinc-700 p-2.5 space-y-1' }, h('label', { class: 'flex items-start gap-2' }, h('input', { type: 'checkbox', class: 'mt-1 accent-[#6f5636]', checked: i.marcada, 'data-testid': 'cx-marcar', onchange: ev => { i.marcada = ev.target.checked } }), h('textarea', { class: 'modal-input !text-sm flex-1', rows: 2, 'aria-label': 'Texto', oninput: ev => { i.texto = ev.target.value } }, i.texto)), h('div', { class: 'pl-6 flex flex-wrap items-center gap-1 text-[11px] text-gray-500' }, badge((CATS_CTX.find(x => x[0] === i.categoria) || [0, i.categoria])[1], 'azul'), badge((STATUS_CTX.find(x => x[0] === i.status) || [0, i.status])[1], 'cinza'), i.data_fato ? dataLonga(i.data_fato) : '', ...i.fontes.map(chipFonte)))) : [h('p', { class: 'text-sm text-gray-500' }, 'Nada novo para acrescentar ao contexto.')],
        its.length ? btn('Aceitar os marcados no contexto do caso', { tid: 'cx-aceitar', icone: 'ph:check-bold', onclick: () => { const sel = its.filter(i => i.marcada && i.texto.trim()); sel.forEach(i => DB.ctx_itens.push({ id: proximoId('ctx_itens'), contato_id: c.id, caso_id: casoId || null, categoria: i.categoria, texto: i.texto.trim(), status: i.status, data_fato: i.data_fato || null, fontes: i.fontes, revisado: true, criado_por: 'ia', created_at: agora() })); salvar('ctx_itens'); registrar(c.id, 'Anotação', `${plural(sel.length, 'item aceito', 'itens aceitos')} no contexto do caso (sugeridos pela IA, revisados por você).`, casoId); fechar(); aviso(`${plural(sel.length, 'item aceito', 'itens aceitos')}.`); aoFim && aoFim(); render() } }) : null)
    } })
}

/* ---------- follow-up (rascunho; nunca enviado) ---------- */
function followUpIA(c, casoId, opc = {}) {
  janelaNucleo({ c, casoId, titulo: 'Follow-up — ' + c.nome, tipo: 'followup', salvarComo: 'followup',
    tarefa: 'Escreva UMA mensagem de follow-up para a cliente, no estilo WhatsApp (até ~900 caracteres, acolhedora e profissional, sem juridiquês, sem promessa de resultado), baseada no que foi EFETIVAMENTE combinado/dito (consultas, transcrições, conversa). Agradeça, resuma os próximos passos, peça os documentos pendentes e confirme informações, conforme o material. Se NÃO houver consulta ou combinado registrado, escreva a mensagem a partir da conversa e comece a resposta com uma linha “[ATENÇÃO: não há consulta registrada; baseado só na conversa]”. Não invente o que foi combinado. Use [COLCHETES] para o que faltar. Responda só com a mensagem (e a linha de atenção, se for o caso).' + (opc.extra ? '\nOrientação da advogada: ' + opc.extra : ''),
    extraRodape: get => [h('a', { href: c.telefone ? '#' : null, target: '_blank', rel: 'noopener', 'data-testid': 'followup-whats', class: 'btn-mini inline-flex items-center gap-1.5 !px-4 !py-1.5 rounded-full bg-primary text-white dark:bg-cafe-creme dark:text-cafe text-xs' + (c.telefone ? '' : ' opacity-50 pointer-events-none'), title: 'Abre o WhatsApp com o texto: você revisa e toca em enviar', onclick: ev => { const t = get(); if (!t) { ev.preventDefault(); aviso('Espere a IA terminar.', 'erro'); return } ev.currentTarget.href = whatsappLink(c.telefone) + '?text=' + encodeURIComponent(t) } }, ic('ph:whatsapp-logo-bold'), 'Abrir no WhatsApp (você envia)')] })
}

/* ---------- aba formulário do caso ---------- */
function AbaFormulario(c, casoId) {
  const envs = DB.envios.filter(doCaso(c, casoId)).sort((a, b) => b.created_at.localeCompare(a.created_at)); const plan = DB.formularios.filter(f => (f.planejado || []).length)
  return h('div', { class: 'space-y-4', 'data-testid': 'aba-formulario' },
    alerta('info', null, 'O formulário público é do Google Forms; as respostas voltam pela planilha e viram contexto do caso. A IA só SUGERE perguntas; você decide o que criar.'),
    h('div', { class: 'flex flex-wrap gap-2' }, btn('Gerar perguntas para o formulário (IA)', { icone: 'ph:sparkle-bold', class: 'ia-btn', tid: 'caso-gerar-perguntas', onclick: () => perguntasParaFormulario(c, casoId) }), btn('Enviar formulário', { tipo: 'sec', icone: 'ph:paper-plane-tilt-bold', tid: 'caso-enviar-form', onclick: () => enviarFormulario(c, null, casoId ? { caso: casoId } : {}) }), btn('Ler respostas do Google', { tipo: 'sec', icone: 'ph:cloud-arrow-down-bold', tid: 'caso-ler-respostas', onclick: () => sincronizarRespostasGoogle() })),
    painel('Formulários deste caso', envs.length ? lista(envs.map(linhaEnvio)) : h('p', { class: 'text-sm text-gray-500' }, 'Nenhum formulário enviado a esta pessoa.')),
    plan.length ? painel('Perguntas planejadas (sugeridas pela IA, revisadas por você)', h('div', { class: 'space-y-3' }, plan.map(f => h('div', { class: 'space-y-1' }, h('p', { class: 'font-semibold text-sm' }, f.nome), h('ol', { class: 'list-decimal pl-5 text-sm space-y-0.5', 'data-testid': 'planejadas' }, f.planejado.map(q => h('li', {}, q.texto, h('span', { class: 'text-[11px] text-gray-500' }, ` [${q.tipo}${q.obrigatoria ? ', obrigatória' : ''}${(q.opcoes || []).length ? ': ' + q.opcoes.join(' / ') : ''}]`), btn('✕', { mini: true, tipo: 'fantasma', title: 'Remover', onclick: () => { f.planejado = f.planejado.filter(x => x.id !== q.id); salvar('formularios'); render() } })))), btn('Copiar lista para o Google Forms', { mini: true, tipo: 'sec', icone: 'ph:copy-bold', onclick: () => copiar(f.planejado.map((q, i) => `${i + 1}. ${q.texto} [${q.tipo}${q.obrigatoria ? ', obrigatória' : ''}${(q.opcoes || []).length ? ': ' + q.opcoes.join(' / ') : ''}]`).join('\n')) }))))) : null)
}

/* ---------- chat com a IA dentro do caso ---------- */
const PERGUNTAS_RAPIDAS = ['Leia tudo e me dê uma visão geral.', 'Quais são os principais problemas?', 'O que está faltando?', 'Quais perguntas devo fazer agora?', 'Quais informações essa pessoa já me passou?', 'Leia a conversa e o formulário juntos.', 'Compare os documentos com o que foi informado.', 'Existe alguma inconsistência?', 'Quais pontos eu deveria pesquisar juridicamente?', 'O que ficou pendente?', 'Organize a cronologia.', 'Prepare a consulta.']
function AbaChat(c, casoId) {
  const raiz = h('div', { class: 'space-y-3', 'data-testid': 'aba-chat' }); let ctl = null; let ocupado = false
  const msgs = () => DB.chat_ia.filter(m => m.contato_id === c.id && (m.caso_id || null) === (casoId || null)).sort((a, b) => a.id - b.id)
  const caixa = h('div', { class: 'rounded-2xl bg-[#e9e1d2] dark:bg-zinc-950 p-3 space-y-2 max-h-[28rem] overflow-y-auto', 'data-testid': 'chat-caixa' }); const entrada = h('textarea', { class: 'modal-input', rows: 2, placeholder: 'Pergunte sobre este caso… (ex.: “Quais perguntas devo fazer agora?”)', 'data-testid': 'chat-entrada', 'aria-label': 'Mensagem para a IA' })
  const bolha = m => h('div', { class: 'flex ' + (m.papel === 'user' ? 'justify-end' : ''), 'data-testid': 'chat-msg' }, h('div', { class: 'max-w-[92%] rounded-2xl px-3 py-2 ' + (m.papel === 'user' ? 'bg-primary text-white text-sm whitespace-pre-line' : 'bg-white dark:bg-zinc-800') }, m.papel === 'user' ? m.texto : h('div', {}, renderTextoIA(m.texto), h('div', { class: 'flex gap-2 mt-1.5' }, btn('Copiar', { mini: true, tipo: 'fantasma', onclick: () => copiar(m.texto) }), btn('Salvar como análise', { mini: true, tipo: 'fantasma', tid: 'chat-salvar', onclick: () => { salvarAnalise({ c, casoId, tipo: 'chat', titulo: 'Chat: ' + corta((msgs().filter(x => x.id < m.id && x.papel === 'user').pop() || {}).texto || 'resposta', 50), texto: m.texto }); aviso('Salvo em Análises.') } })))))
  const pintar = () => { const l = msgs(); caixa.replaceChildren(...(l.length ? l.map(bolha) : [h('p', { class: 'text-sm text-gray-500 text-center py-4' }, 'Converse com a IA sobre este caso. Ela responde com base no material real e cita as fontes.')])); caixa.scrollTop = caixa.scrollHeight }
  const enviar = (texto) => {
    const t = String(texto || entrada.value).trim(); if (!t || ocupado) return
    exigirIA(async s => {
      ocupado = true; const hist = msgs().slice(-10).map(m => `${m.papel === 'user' ? 'ADVOGADA' : 'ASSISTENTE'}: ${corta(m.texto, 1500)}`).join('\n'); DB.chat_ia.push({ id: proximoId('chat_ia'), contato_id: c.id, caso_id: casoId || null, papel: 'user', texto: t, created_at: agora() }); entrada.value = ''; salvar('chat_ia'); pintar()
      const vivo = h('div', { class: 'flex' }, h('div', { class: 'max-w-[92%] rounded-2xl px-3 py-2 bg-white dark:bg-zinc-800 text-sm text-gray-500' }, 'Pensando…')); caixa.append(vivo); caixa.scrollTop = caixa.scrollHeight; ctl = new AbortController()
      try { const r = await rodarNucleo(s, { c, casoId, signal: ctl.signal, tarefa: `Você está num CHAT com a advogada sobre este caso. Responda à ÚLTIMA mensagem dela de forma direta e útil, com base no material real. Quando for sugerir perguntas, não repita o que já foi respondido. Quando ela pedir um rascunho (mensagem, parecer, roteiro), entregue o rascunho pronto para revisão, sem enviar nada.\n\nCONVERSA DO CHAT ATÉ AGORA:\n${hist || '(início)'}\n\nÚLTIMA MENSAGEM DA ADVOGADA: ${t}`, onText: ({ text }) => { vivo.replaceChildren(h('div', { class: 'max-w-[92%] rounded-2xl px-3 py-2 bg-white dark:bg-zinc-800' }, renderTextoIA(text))); caixa.scrollTop = caixa.scrollHeight } }); DB.chat_ia.push({ id: proximoId('chat_ia'), contato_id: c.id, caso_id: casoId || null, papel: 'assistant', texto: r.texto, created_at: agora() }); salvar('chat_ia') }
      catch (e) { if (!(e && e.code === 'cancelled')) aviso(iaErro(e), 'erro') } finally { ocupado = false; pintar() }
    })
  }
  entrada.addEventListener('keydown', ev => { if (ev.key === 'Enter' && (ev.ctrlKey || ev.metaKey)) enviar() })
  pintar()
  raiz.append(alerta('info', null, 'A IA lê o caso (ficha, conversas, materiais, formulários, consultas, contexto confirmado) a cada pergunta e não mistura outras pessoas. Ela não envia nada: você revisa e decide.'), h('div', { class: 'flex flex-wrap gap-1.5' }, PERGUNTAS_RAPIDAS.map(q => h('button', { type: 'button', class: 'chip', 'data-testid': 'chat-rapida', onclick: () => enviar(q) }, q))), caixa, entrada, h('div', { class: 'flex gap-2' }, btn('Enviar (Ctrl+Enter)', { tid: 'chat-enviar', icone: 'ph:paper-plane-right-bold', onclick: () => enviar() }), btn('Parar', { tipo: 'fantasma', onclick: () => ctl && ctl.abort() }), btn('Limpar conversa do chat', { tipo: 'fantasma', tid: 'chat-limpar', onclick: () => confirmar('Limpar o chat deste caso?', 'Apaga só as mensagens do chat (as análises salvas ficam).', 'Limpar', () => { DB.chat_ia = DB.chat_ia.filter(m => !(m.contato_id === c.id && (m.caso_id || null) === (casoId || null))); salvar('chat_ia'); pintar() }) })))
  return raiz
}
