'use strict'
/* ============ CONSULTAS / REUNIÕES e TRANSCRIÇÕES ============
   Aqui entram anotações e a transcrição (colada, de arquivo texto/Word/PDF, ou do Drive). O Artifact NÃO transcreve áudio: a transcrição é feita fora
   (ferramenta de sua escolha) e colada aqui; o Assistente então lê o texto. Cada consulta fica ligada à Pessoa, à Demanda, à data e aos participantes. */
function novaConsulta(c, casoId, aoFim) {
  modalForm('Nova consulta / reunião — ' + c.nome, [{ chave: 'tipo', rotulo: 'Tipo', tipo: 'select', opcoes: [['consulta', 'Consulta'], ['reuniao', 'Reunião']] }, { chave: 'data_hora', rotulo: 'Data e hora', tipo: 'datahora', obrigatorio: true }, { chave: 'status', rotulo: 'Situação', tipo: 'select', opcoes: [['agendada', 'Agendada'], ['realizada', 'Realizada']] }, { chave: 'participantes', rotulo: 'Participantes', dica: 'Ex.: Dra. Lara, Maria Souza' }, { chave: 'caso_id', rotulo: 'Demanda', tipo: 'select', opcoes: [['', '— sem demanda —'], ...demandasDe(c.id).map(d => [d.id, d.titulo])], numerico: true }], { tipo: 'consulta', status: 'agendada', participantes: 'Dra. Lara, ' + c.nome, caso_id: casoId || '' }, v => {
    const q = { id: proximoId('consultas'), contato_id: c.id, caso_id: v.caso_id || null, tipo: v.tipo, data_hora: v.data_hora, status: v.status, participantes: v.participantes || '', anotacoes: '', encaminhamentos: '', created_at: agora() }; DB.consultas.push(q); if (v.status === 'agendada') c.consulta_em = v.data_hora; salvar('consultas'); salvar('contatos'); registrar(c.id, 'Reunião', (v.tipo === 'reuniao' ? 'Reunião' : 'Consulta') + (v.status === 'realizada' ? ' registrada' : ' agendada') + ' para ' + dataHora(v.data_hora) + '.', q.caso_id); aoFim && aoFim(q); render()
  }, { rotulo: 'Criar' })
}
const ACOES_CONSULTA = [
  ['resumir', 'Resumir', 'Faça um RESUMO TÉCNICO da consulta/reunião: pontos principais em ordem, o que o cliente informou, o que foi explicado pela advogada, o que ficou combinado.'],
  ['fatos', 'Extrair fatos', 'Extraia os FATOS relatados pelo cliente na consulta/reunião (um por item, em ordem cronológica quando possível), separando o que foi DITO nesta consulta do que já constava antes.'],
  ['questoes', 'Extrair questões', 'Extraia as QUESTÕES levantadas (jurídicas e práticas), separando as que a advogada já respondeu das que ficaram em aberto e das que exigem pesquisa [PESQUISAR].'],
  ['pendencias', 'Identificar pendências', 'Identifique as PENDÊNCIAS: pontos sem resposta, informações a confirmar, o que cada parte (cliente/escritório) ficou de fazer, com responsável quando claro.'],
  ['documentos', 'Identificar documentos', 'Liste os DOCUMENTOS mencionados na consulta: já recebidos, a solicitar e a verificar; com o motivo de cada um.'],
  ['cronologia', 'Criar cronologia', 'Monte a CRONOLOGIA dos fatos relatados na consulta, em ordem cronológica, com fonte e rótulo; eventos sem data em bloco separado.'],
]
function abrirConsulta(q) {
  const c = contato(q.contato_id); const corpo = h('div', { class: 'space-y-4', 'data-testid': 'consulta-detalhe' })
  const des = () => {
    const trs = DB.materiais.filter(m => m.consulta_id === q.id && m.tipo === 'transcricao'); const outros = DB.materiais.filter(m => m.consulta_id === q.id && m.tipo !== 'transcricao')
    const campo = (rot, chave, linhas, tid) => h('label', { class: 'block' }, rotuloCampo(rot), h('textarea', { class: 'modal-input text-sm', rows: linhas, 'data-testid': tid, oninput: ev => { q[chave] = ev.target.value } }, q[chave] || ''))
    const pergunta = h('input', { class: 'modal-input !text-sm', placeholder: 'Pergunte ao Assistente sobre esta reunião (ex.: “O que foi decidido?”, “O que mudou desde a primeira conversa?”)', 'data-testid': 'consulta-pergunta' })
    const perguntar = t => janelaNucleo({ c, casoId: q.caso_id, titulo: 'Sobre a consulta — ' + c.nome, tipo: 'consulta_pergunta', tarefa: `Responda à pergunta da advogada sobre a CONSULTA/REUNIÃO [C${q.id}] (use as anotações [C${q.id}] e as transcrições/materiais da consulta; compare com a conversa inicial e o formulário quando a pergunta pedir). Pergunta: ${t}` })
    corpo.replaceChildren(
      h('div', { class: 'grid gap-3 sm:grid-cols-3' }, h('label', { class: 'block' }, rotuloCampo('Data e hora'), h('input', { type: 'datetime-local', class: 'modal-input', value: q.data_hora ? String(q.data_hora).slice(0, 16) : '', 'data-testid': 'consulta-data', onchange: ev => { q.data_hora = ev.target.value ? new Date(ev.target.value).toISOString() : q.data_hora } })), h('label', { class: 'block' }, rotuloCampo('Situação'), h('select', { class: 'modal-input', 'data-testid': 'consulta-status', onchange: ev => { q.status = ev.target.value } }, [['agendada', 'Agendada'], ['realizada', 'Realizada'], ['cancelada', 'Cancelada']].map(([v, t]) => h('option', { value: v, selected: v === q.status }, t)))), h('label', { class: 'block' }, rotuloCampo('Participantes'), h('input', { class: 'modal-input', value: q.participantes || '', 'data-testid': 'consulta-participantes', oninput: ev => { q.participantes = ev.target.value } }))),
      campo('Anotações', 'anotacoes', 6, 'consulta-anotacoes'), campo('Encaminhamentos / combinados', 'encaminhamentos', 3, 'consulta-encaminhamentos'),
      h('div', { class: 'flex flex-wrap gap-2' }, btn('Salvar', { mini: true, tid: 'consulta-salvar', onclick: () => { if (q.status === 'realizada' && c.consulta_em) { /* mantém histórico */ } salvar('consultas'); registrar(q.contato_id, 'Reunião', 'Consulta/reunião atualizada (' + q.status + ').', q.caso_id); aviso('Consulta salva.'); des() } }), btn('Marcar na agenda', { mini: true, tipo: 'sec', icone: 'ph:calendar-plus-bold', onclick: () => editarCompromisso(null, { tipo: 'consulta', titulo: (q.tipo === 'reuniao' ? 'Reunião' : 'Consulta') + ' — ' + c.nome, contato_id: c.id, caso_id: q.caso_id || '', inicio: q.data_hora ? String(q.data_hora).slice(0, 16) : '' }) }), btn('Excluir', { mini: true, tipo: 'perigo', onclick: () => confirmar('Excluir esta consulta?', 'As transcrições e materiais ligados continuam no caso.', 'Excluir', () => { DB.consultas = DB.consultas.filter(x => x.id !== q.id); DB.materiais.forEach(m => { if (m.consulta_id === q.id) m.consulta_id = null }); salvar('consultas'); salvar('materiais'); fecharTodas(); render() }) })),
      painel('Transcrições e documentos desta consulta', h('div', { class: 'space-y-2' }, h('p', { class: 'text-xs text-gray-600 dark:text-zinc-300' }, 'Áudio da reunião? O Artifact não transcreve áudio: transcreva fora (ferramenta de sua escolha) e cole aqui, ou importe o arquivo de texto/Word/PDF da transcrição. O Assistente lê o TEXTO.'), h('div', { class: 'flex flex-wrap gap-2' }, btn('Colar transcrição', { mini: true, icone: 'ph:clipboard-text-bold', tid: 'consulta-colar', onclick: () => adicionarTexto(c, q.caso_id, { tipo: 'transcricao', consulta_id: q.id, titulo: 'Adicionar transcrição da consulta', tituloPadrao: 'Transcrição da consulta de ' + dataLonga(String(q.data_hora || hojeISO()).slice(0, 10)), data: q.data_hora, aoAdicionar: () => setTimeout(() => { fecharTodas(); abrirConsulta(q) }, 50) }) }), btn('Importar arquivo (texto/Word/PDF)', { mini: true, tipo: 'sec', icone: 'ph:upload-simple-bold', tid: 'consulta-arquivo', onclick: () => adicionarArquivos(c, q.caso_id, { tipo: 'transcricao', consulta_id: q.id, origem: 'transcrição importada' }) }), btn('Do Drive', { mini: true, tipo: 'sec', icone: 'ph:google-drive-logo-bold', onclick: () => importarDoDrive(c, q.caso_id, { consulta_id: q.id }) })), trs.length || outros.length ? lista([...trs, ...outros].map(m => [ic(ICONE_MAT[m.tipo] || 'ph:paperclip-bold', 'text-lg'), h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'text-sm font-semibold truncate' }, m.titulo), h('p', { class: 'text-[11px] text-gray-500' }, (m.texto && m.texto.trim() ? plural(m.texto.length, 'caractere', 'caracteres') : 'NÃO LIDO') + ' · ' + (m.texto_origem || ''))), btn('Abrir', { mini: true, tipo: 'sec', onclick: () => abrirMaterial(m) })])) : h('p', { class: 'text-sm text-gray-500' }, 'Nenhuma transcrição ainda.'))),
      painel('O Assistente lê a reunião', h('div', { class: 'space-y-3' }, h('div', { class: 'flex flex-wrap gap-1.5' }, ...ACOES_CONSULTA.map(([id, rot, instr]) => btn(rot, { mini: true, tipo: 'sec', class: 'ia-btn', tid: 'cons-ia-' + id, onclick: () => janelaNucleo({ c, casoId: q.caso_id, titulo: rot + ' — consulta de ' + c.nome, tipo: 'consulta_' + id, tarefa: `${instr} Fonte principal: a CONSULTA/REUNIÃO [C${q.id}] (anotações e a(s) transcrição(ões) dela, marcadas “da consulta C${q.id}” nos materiais). Use as demais fontes só para comparar.` }) })),
        btn('Processar consulta (tudo de uma vez)', { mini: true, class: 'ia-btn', tid: 'cons-ia-processar', onclick: () => janelaNucleo({ c, casoId: q.caso_id, titulo: 'Processar consulta — ' + c.nome, tipo: 'consulta_processada', tier: 'complex', tarefa: `Processe a CONSULTA/REUNIÃO [C${q.id}] (anotações e transcrição). Compare com a conversa inicial e o formulário e aponte o que mudou.`, formato: SEC('RESUMO', 'PENDÊNCIAS', 'DOCUMENTOS FALTANTES', 'PRÓXIMOS PASSOS', 'TAREFAS (itens objetivos, com responsável)', 'PONTOS PARA PESQUISA JURÍDICA', 'PONTOS PARA CONFIRMAÇÃO', 'O QUE MUDOU DESDE A PRIMEIRA CONVERSA / CONTRADIÇÕES', 'RASCUNHO DE FOLLOW-UP (mensagem curta à cliente, sem enviar)', 'ESTRUTURA SUGERIDA DO PARECER (títulos e pontos de cada seção)') }) }),
        btn('Atualizar contexto do caso', { mini: true, tipo: 'sec', class: 'ia-btn', tid: 'cons-ia-contexto', onclick: () => atualizarContextoIA(c, q.caso_id) }), btn('Sugerir tarefas', { mini: true, tipo: 'sec', class: 'ia-btn', onclick: () => tarefasIA(c, q.caso_id) }), btn('Gerar parecer', { mini: true, class: 'ia-btn', tid: 'cons-ia-parecer', onclick: () => gerarDocumentoIA(c, q.caso_id, { consultaId: q.id }) }), btn('Gerar follow-up', { mini: true, tipo: 'sec', class: 'ia-btn', tid: 'cons-ia-followup', onclick: () => followUpIA(c, q.caso_id) })),
        h('div', { class: 'flex gap-2' }, h('div', { class: 'flex-1' }, pergunta), btn('Perguntar', { mini: true, tid: 'consulta-perguntar', class: 'ia-btn', onclick: () => { if (!pergunta.value.trim()) { aviso('Escreva a pergunta.', 'erro'); return } perguntar(pergunta.value.trim()) } })),
        h('div', { class: 'flex flex-wrap gap-1.5' }, ['O que foi decidido?', 'O que o cliente informou?', 'O que eu expliquei?', 'Quais pontos ficaram sem resposta?', 'Quais documentos foram mencionados?', 'Quais providências foram combinadas?', 'Existe alguma contradição com a conversa inicial?', 'O que mudou entre o primeiro contato e a consulta?'].map(t => h('button', { type: 'button', class: 'chip', onclick: () => perguntar(t) }, t))))))
  }
  des(); modal({ titulo: (q.tipo === 'reuniao' ? 'Reunião' : 'Consulta') + ' — ' + (c ? c.nome : ''), largura: 'max-w-4xl', corpo, aoFechar: render })
}
function AbaConsultas(c, casoId) {
  const cons = DB.consultas.filter(doCaso(c, casoId)).sort((a, b) => String(b.data_hora || b.created_at).localeCompare(String(a.data_hora || a.created_at)))
  return h('div', { class: 'space-y-3', 'data-testid': 'aba-consultas' }, h('div', { class: 'flex flex-wrap gap-2' }, btn('Nova consulta / reunião', { icone: 'ph:plus-bold', tid: 'nova-consulta', onclick: () => novaConsulta(c, casoId, q => setTimeout(() => abrirConsulta(q), 80)) }), btn('Preparar consulta (Assistente)', { tipo: 'sec', icone: 'ph:presentation-bold', class: 'ia-btn', tid: 'cons-preparar', onclick: () => prepararConsultaIA(c, casoId) })),
    cons.length ? lista(cons.map(q => [ic('ph:calendar-check-bold', 'text-xl text-primary dark:text-cafe-creme'), h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'font-semibold text-sm' }, (q.tipo === 'reuniao' ? 'Reunião' : 'Consulta') + ' · ' + (q.data_hora ? dataHora(q.data_hora) : 'sem data')), h('p', { class: 'text-[11px] text-gray-500' }, `${q.participantes || '—'} · ${DB.materiais.filter(m => m.consulta_id === q.id).length} material(is) ligado(s)`)), badge(q.status === 'realizada' ? 'Realizada' : q.status === 'cancelada' ? 'Cancelada' : 'Agendada', q.status === 'realizada' ? 'verde' : q.status === 'cancelada' ? 'cinza' : 'roxo'), btn('Abrir', { mini: true, tid: 'consulta-abrir', onclick: () => abrirConsulta(q) })])) : estadoVazio('ph:calendar-check-bold', 'Nenhuma consulta registrada', 'Registre a consulta, cole a transcrição e deixe o Assistente ler a reunião.'))
}
