'use strict'
/* ============ DOCUMENTOS DO ATENDIMENTO: parecer, orientação pós-consulta, resumo, follow-up, solicitação de documentos, checklist, relatório ============
   A IA redige um RASCUNHO com base só no material real; você edita seção por seção, revisa, finaliza. Identidade visual do escritório (logo, cores,
   cabeçalho, rodapé, assinatura) entra na pré-visualização e nas exportações DOCX e PDF (geradas aqui no navegador, sem serviço externo).
   Nada é finalizado nem enviado automaticamente. Marcações da IA ([PESQUISAR], [CONFIRMAR], [AUSENTE]) ficam visíveis até você resolvê-las. */
const SECOES_PARECER = ['Identificação', 'Objeto da consulta', 'Síntese dos fatos', 'Informações fornecidas', 'Documentos analisados', 'Questões jurídicas identificadas', 'Análise', 'Possibilidades/alternativas', 'Riscos e pontos de atenção', 'Informações/documentos pendentes', 'Providências e encaminhamentos', 'Conclusão']
const TIPOS_DOC = { parecer: 'Parecer', orientacao_pos_consulta: 'Orientação pós-consulta', resumo_reuniao: 'Resumo de reunião', followup: 'Follow-up', solicitacao_documentos: 'Solicitação de documentos', checklist: 'Checklist', relatorio_interno: 'Relatório interno' }
const MODELOS_BASE = { parecer: SECOES_PARECER, orientacao_pos_consulta: ['Agradecimento e contexto', 'O que conversamos', 'Orientações', 'Próximos passos', 'Documentos a enviar', 'Prazos e observações'], resumo_reuniao: ['Dados da reunião', 'Participantes', 'Pontos discutidos', 'Decisões e combinados', 'Pendências', 'Próximos passos'], followup: ['Mensagem'], solicitacao_documentos: ['Introdução', 'Documentos solicitados', 'Como enviar', 'Prazo sugerido'], checklist: ['Documentos pessoais', 'Documentos do caso', 'Providências do escritório'], relatorio_interno: ['Resumo do caso', 'Situação atual', 'Pendências', 'Riscos', 'Próximos passos'] }
const modelosDe = tipo => [{ id: 'base', nome: TIPOS_DOC[tipo] + ' (modelo padrão)', tipo, base: true, secoes: MODELOS_BASE[tipo].map(t => ({ titulo: t, instrucao: '' })), instrucoes: '' }, ...DB.modelos_doc.filter(m => m.tipo === tipo)]
const IDENT_PADRAO = { nome_escritorio: '', advogada: '', oab: '', telefone: '', email: '', endereco: '', site: '', instagram: '', cor_primaria: '#6f5636', cor_secundaria: '#c9a96e', cabecalho_texto: '', rodape_texto: '', assinatura_texto: '' }
const identidade = () => { const e = CONFIG.escritorio || {}; const base = { ...IDENT_PADRAO, nome_escritorio: e.nome || e.escritorio_nome || 'Lara Café Advocacia', advogada: e.advogada_nome || 'Lara Café', email: e.email || '', telefone: e.telefone || '' }; return { ...base, ...(CONFIG.identidade || {}) } }

/* ---------- marcações da IA ---------- */
const RE_FONTES_TXT = /\s*\[(?:(?:[WMRNACPX]\d+|F)(?:\s*[,;]\s*(?:[WMRNACPX]\d+|F))*)\]/g
const RE_INFO_TXT = /\s*\[(?:INFORMADO|DOCUMENTO|INFER[ÊE]NCIA|HIP[ÓO]TESE)\]/g
const RE_PEND_TXT = /\[(?:PESQUISAR|CONFIRMAR|AUSENTE)[^\]]*\]/g
const textoLimpo = t => String(t || '').replace(RE_FONTES_TXT, '').replace(RE_INFO_TXT, '').replace(/[ \t]+\n/g, '\n').trim()
const pendenciasDoc = p => p.secoes.reduce((n, s) => n + ((s.texto || '').match(RE_PEND_TXT) || []).length + ((s.texto || '').match(/\[[A-ZÀ-Ý][^\]]{2,60}\]/g) || []).filter(x => !RE_PEND_TXT.test(x) && !/^\[(INFORMADO|DOCUMENTO|INFER|HIP)/.test(x)).length, 0)

/* ---------- gerar ---------- */
function gerarDocumentoIA(c, casoId, opc = {}) {
  const S = { tipo: opc.tipo || 'parecer', modelo: 'base', extra: '' }
  const corpo = h('div', { class: 'space-y-3' })
  const des = () => { const ms = modelosDe(S.tipo); corpo.replaceChildren(h('label', { class: 'block' }, rotuloCampo('Documento'), h('select', { class: 'modal-input', 'data-testid': 'gd-tipo', onchange: ev => { S.tipo = ev.target.value; S.modelo = 'base'; des() } }, Object.entries(TIPOS_DOC).map(([k, t]) => h('option', { value: k, selected: k === S.tipo }, t)))), h('label', { class: 'block' }, rotuloCampo('Modelo'), h('select', { class: 'modal-input', 'data-testid': 'gd-modelo', onchange: ev => { S.modelo = ev.target.value } }, ms.map(m => h('option', { value: m.id, selected: String(m.id) === String(S.modelo) }, m.nome)))), h('label', { class: 'block' }, rotuloCampo('Orientação adicional (opcional)'), h('textarea', { class: 'modal-input', rows: 3, 'data-testid': 'gd-extra', placeholder: 'Ex.: dar ênfase à partilha; tom mais objetivo; não citar valores', oninput: ev => { S.extra = ev.target.value } })), h('p', { class: 'text-xs text-gray-500' }, 'O rascunho usa só o material real do caso' + (opc.consultaId ? ' e a consulta [C' + opc.consultaId + ']' : '') + '. Você edita, revisa e finaliza; nada é enviado.')) }
  des()
  modal({ titulo: 'Gerar documento com a IA — ' + c.nome, largura: 'max-w-lg', corpo, rodape: f => [btn('Cancelar', { tipo: 'sec', onclick: f }), btn('Gerar rascunho', { tid: 'gd-gerar', onclick: () => { f(); rodarGeracaoDocumento(c, casoId, { ...opc, ...S, modeloObj: modelosDe(S.tipo).find(m => String(m.id) === String(S.modelo)) }) } })] })
}
function rodarGeracaoDocumento(c, casoId, o) {
  const m = o.modeloObj; const nomeDoc = TIPOS_DOC[o.tipo]
  janelaJSON({ c, casoId, titulo: `${nomeDoc} — rascunho para ${c.nome}`, tier: 'complex',
    tarefa: `Redija um RASCUNHO de ${nomeDoc.toUpperCase()} para revisão da advogada, com base APENAS no material real do caso${o.consultaId ? ', com foco na consulta/reunião [C' + o.consultaId + ']' : ''}. Siga EXATAMENTE as seções do modelo, na ordem, com os títulos dados. Linguagem técnica clara e objetiva. Regras: não invente fatos, documentos, falas, decisões judiciais ou leis; não apresente como certo o que depende de confirmação; onde faltar informação escreva [AUSENTE: o que falta]; onde exigir pesquisa jurídica escreva [PESQUISAR: o que verificar]; onde precisar de confirmação escreva [CONFIRMAR: o quê]. Cite as fontes dos trechos factuais ([W12], [M3]…): elas serão removidas na versão final. Materiais NÃO LIDOS não podem ser descritos.${m.instrucoes ? '\nInstruções do modelo: ' + m.instrucoes : ''}${o.extra ? '\nOrientação da advogada: ' + o.extra : ''}\nSEÇÕES DO MODELO:\n${m.secoes.map((s, i) => `${i + 1}. ${s.titulo}${s.instrucao ? ' — ' + s.instrucao : ''}`).join('\n')}`,
    formato: 'Responda SOMENTE com JSON: {"secoes":[{"titulo":"<título exato da seção>","texto":"<conteúdo da seção; parágrafos separados por \\n; listas com “- ”>"}]}',
    mostrar: (d, ctx, fechar) => {
      const secs = m.secoes.map(s => { const x = arr(d.secoes).find(y => semAcento(sTxt(y.titulo)) === semAcento(s.titulo)); return { id: Math.random(), titulo: s.titulo, texto: x ? sTxt(x.texto) : '[AUSENTE: a IA não preencheu esta seção]' } })
      return h('div', { class: 'space-y-3', 'data-testid': 'gd-resultado' }, h('p', { class: 'text-sm' }, `Rascunho pronto com ${secs.length} seção(ões). Abra o editor para revisar, editar e finalizar.`), btn('Abrir no editor', { icone: 'ph:pencil-simple-bold', tid: 'gd-abrir-editor', onclick: () => { const p = { id: proximoId('pareceres'), contato_id: c.id, caso_id: casoId || null, consulta_id: o.consultaId || null, tipo_doc: o.tipo, modelo_id: m.base ? null : m.id, titulo: `${nomeDoc} — ${c.nome}`, secoes: secs, status: 'rascunho', versao: 1, created_at: agora(), gerado_por_ia: true }; DB.pareceres.push(p); salvar('pareceres'); auditar('ia_documento', nomeDoc + ' · ' + c.nome); fechar(); render(); abrirParecer(p) } }))
    } })
}

/* ---------- editor ---------- */
function abrirParecer(p) {
  const c = contato(p.contato_id); const corpo = h('div', { class: 'space-y-3', 'data-testid': 'parecer-editor' }); const nomeDoc = TIPOS_DOC[p.tipo_doc || 'parecer']
  const des = () => {
    const pend = pendenciasDoc(p)
    corpo.replaceChildren(
      h('div', { class: 'flex flex-wrap items-center gap-2' }, badge(p.status === 'finalizado' ? 'Finalizado' : p.status === 'revisado' ? 'Revisado' : 'Rascunho', p.status === 'finalizado' ? 'verde' : p.status === 'revisado' ? 'azul' : 'ambar'), badge(nomeDoc, 'cinza'), p.gerado_por_ia ? badge('Rascunho gerado por IA', 'roxo') : null, pend ? badge(`${pend} ponto(s) a resolver`, 'vermelho') : badge('Sem marcações de pendência', 'verde')),
h('div', { class: 'flex flex-wrap gap-2', 'data-testid': 'parecer-status-barra' },     p.status === 'rascunho' ? btn('Marcar como revisado', { tid: 'parecer-revisado', onclick: () => { p.status = 'revisado'; p.revisado_em = agora(); persistir(); registrar(p.contato_id, 'Peça / pesquisa', `${nomeDoc} revisado por você: ${p.titulo}`, p.caso_id); des() } }) : p.status === 'revisado' ? btn('Finalizar', { tid: 'parecer-finalizar', onclick: () => { const pend = pendenciasDoc(p); const fin = () => { p.status = 'finalizado'; p.finalizado_em = agora(); p.versoes = [...(p.versoes || []), { em: agora(), secoes: JSON.parse(JSON.stringify(p.secoes)) }]; persistir(); registrar(p.contato_id, 'Peça / pesquisa', `${nomeDoc} finalizado por você: ${p.titulo}`, p.caso_id); des(); aviso('Documento finalizado.') }; pend ? confirmar('Ainda há pontos a resolver', `Restam ${pend} marcação(ões) [PESQUISAR]/[CONFIRMAR]/[AUSENTE] ou campos entre colchetes. Finalizar mesmo assim?`, 'Finalizar assim mesmo', fin) : fin() } }) : btn('Reabrir para edição', { tipo: 'sec', onclick: () => { p.status = 'rascunho'; persistir(); des() } })),
      alerta('info', null, 'Edite tudo antes de finalizar. Marcações [PESQUISAR], [CONFIRMAR], [AUSENTE] indicam o que ainda depende de verificação: resolva-as no texto. As fontes [W12], [M3]… servem à sua conferência e saem do documento final.'),
      h('label', { class: 'block' }, rotuloCampo('Título'), h('input', { class: 'modal-input', value: p.titulo, 'data-testid': 'parecer-titulo', oninput: ev => { p.titulo = ev.target.value } })),
      ...p.secoes.map((s, i) => h('section', { class: 'rounded-2xl border border-gray-200 dark:border-zinc-700 p-3 space-y-2', 'data-testid': 'parecer-secao' }, h('div', { class: 'flex items-center gap-2' }, h('input', { class: 'modal-input !text-sm !font-semibold flex-1', value: s.titulo, 'aria-label': 'Título da seção', oninput: ev => { s.titulo = ev.target.value } }), btn('↑', { mini: true, tipo: 'fantasma', title: 'Subir', onclick: () => { if (i > 0) { [p.secoes[i - 1], p.secoes[i]] = [p.secoes[i], p.secoes[i - 1]]; des() } } }), btn('↓', { mini: true, tipo: 'fantasma', title: 'Descer', onclick: () => { if (i < p.secoes.length - 1) { [p.secoes[i + 1], p.secoes[i]] = [p.secoes[i], p.secoes[i + 1]]; des() } } }), btn('✕', { mini: true, tipo: 'fantasma', title: 'Remover seção', onclick: () => { p.secoes.splice(i, 1); des() } })),
        h('textarea', { class: 'modal-input text-sm', rows: Math.min(14, Math.max(4, (s.texto || '').split('\n').length + 2)), 'data-testid': 'parecer-texto', 'aria-label': 'Texto da seção ' + s.titulo, oninput: ev => { s.texto = ev.target.value } }, s.texto || ''),
        h('div', { class: 'flex flex-wrap items-center gap-1' }, btn('Refazer esta seção com a IA…', { mini: true, tipo: 'fantasma', class: 'ia-btn', tid: 'parecer-refazer', onclick: () => refazerSecaoIA(p, s, des) }), ...[...new Set((s.texto || '').match(/\[(?:[WMRNACPX]\d+|F)(?:\s*[,;]\s*(?:[WMRNACPX]\d+|F))*\]/g) || [])].flatMap(t => t.slice(1, -1).split(/\s*[,;]\s*/)).filter((x, k, a) => a.indexOf(x) === k).slice(0, 8).map(chipFonte)))),
      h('div', { class: 'flex flex-wrap gap-2' }, btn('Adicionar seção', { mini: true, tipo: 'sec', icone: 'ph:plus-bold', onclick: () => { p.secoes.push({ id: Math.random(), titulo: 'Nova seção', texto: '' }); des() } })))
  }
  des()
  const persistir = () => { p.updated_at = agora(); salvar('pareceres') }
  modal({ titulo: nomeDoc + ' — ' + (c ? c.nome : ''), largura: 'max-w-4xl', corpo, aoFechar: () => { persistir(); render() }, rodape: f => [
    btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Excluir este documento?', 'Não pode ser desfeito.', 'Excluir', () => { DB.pareceres = DB.pareceres.filter(x => x.id !== p.id); salvar('pareceres'); f(); render() }) }),
    btn('Visualizar', { tipo: 'sec', icone: 'ph:eye-bold', tid: 'parecer-visualizar', onclick: () => { persistir(); visualizarDocumento(p) } }),
    btn('Exportar DOCX', { tipo: 'sec', icone: 'ph:file-doc-bold', tid: 'parecer-docx', onclick: () => { persistir(); exportarDocx(p) } }), btn('Exportar PDF', { tipo: 'sec', icone: 'ph:file-pdf-bold', tid: 'parecer-pdf', onclick: () => { persistir(); exportarPdf(p) } }),
    btn('Salvar', { tipo: 'sec', tid: 'parecer-salvar', onclick: () => { persistir(); aviso('Salvo.') } })
] })
}
function refazerSecaoIA(p, s, aoFim) {
  const instr = h('textarea', { class: 'modal-input', rows: 3, 'data-testid': 'refazer-instr', placeholder: 'O que mudar? (ex.: mais objetivo; incluir o ponto X; remover a menção a Y)' })
  modal({ titulo: 'Refazer a seção “' + s.titulo + '”', largura: 'max-w-lg', corpo: h('div', { class: 'space-y-2' }, h('p', { class: 'text-xs text-gray-500' }, 'A IA reescreve só esta seção, com o mesmo material do caso. O novo texto só entra se você aceitar.'), instr), rodape: f => [btn('Cancelar', { tipo: 'sec', onclick: f }), btn('Reescrever', { tid: 'refazer-ir', onclick: () => { const c = contato(p.contato_id); f(); exigirIA(async sm => { aviso('Reescrevendo…'); try { const r = await rodarNucleo(sm, { c, casoId: p.caso_id, tarefa: `Reescreva APENAS a seção “${s.titulo}” do documento “${p.titulo}”, no mesmo estilo e com as mesmas regras (sem inventar; [PESQUISAR]/[CONFIRMAR]/[AUSENTE] onde couber; cite fontes). Texto atual:\n${s.texto}\n\nOrientação da advogada: ${instr.value || '(melhorar clareza e objetividade)'}\n\nResponda só com o novo texto da seção.` }); confirmar('Substituir o texto da seção?', corta(r.texto, 700), 'Substituir', () => { s.texto = r.texto.trim(); aoFim(); aviso('Seção atualizada.') }) } catch (e) { aviso(iaErro(e), 'erro') } }) } })] })
}
function AbaPareceres(c, casoId) {
  const docs = DB.pareceres.filter(doCaso(c, casoId)).sort((a, b) => b.created_at.localeCompare(a.created_at))
  return h('div', { class: 'space-y-3', 'data-testid': 'aba-pareceres' }, h('div', { class: 'flex flex-wrap gap-2' }, btn('Gerar parecer', { icone: 'ph:scales-bold', class: 'ia-btn', tid: 'gerar-parecer', onclick: () => gerarDocumentoIA(c, casoId, { tipo: 'parecer' }) }), btn('Outro documento (orientação, resumo, checklist…)', { tipo: 'sec', icone: 'ph:file-text-bold', tid: 'gerar-outro-doc', onclick: () => gerarDocumentoIA(c, casoId, { tipo: 'orientacao_pos_consulta' }) }), btn('Identidade visual e modelos', { tipo: 'fantasma', icone: 'ph:palette-bold', onclick: () => ir('identidade') })),
    docs.length ? lista(docs.map(p => [ic('ph:scales-bold', 'text-xl text-primary dark:text-cafe-creme'), h('div', { class: 'min-w-0 flex-1' }, h('p', { class: 'font-semibold text-sm truncate' }, p.titulo), h('p', { class: 'text-[11px] text-gray-500' }, `${TIPOS_DOC[p.tipo_doc || 'parecer']} · ${dataHora(p.created_at)}${p.gerado_por_ia ? ' · rascunho de IA' : ''}`)), badge(p.status === 'finalizado' ? 'Finalizado' : p.status === 'revisado' ? 'Revisado' : 'Rascunho', p.status === 'finalizado' ? 'verde' : p.status === 'revisado' ? 'azul' : 'ambar'), btn('Abrir', { mini: true, tid: 'parecer-abrir', onclick: () => abrirParecer(p) })])) : estadoVazio('ph:scales-bold', 'Nenhum documento gerado', 'Depois da consulta, gere o parecer a partir da conversa, do formulário, dos documentos e da transcrição.'))
}

/* ---------- documento estruturado (para pré-visualização e exportações) ---------- */
function dadosDoc(p) {
  const id = identidade(); return { id, titulo: p.titulo, rascunho: p.status !== 'finalizado', secoes: p.secoes.map(s => ({ titulo: s.titulo, paragrafos: textoLimpo(s.texto).split(/\n+/).map(x => x.trim()).filter(Boolean) })), data: dataLonga(hojeISO()), cliente: nomeContato(p.contato_id) }
}
function visualizarDocumento(p) {
  const d = dadosDoc(p); const id = d.id
  const pagina_ = h('div', { class: 'mx-auto bg-white text-gray-900 shadow-lg', style: 'width:100%;max-width:794px;padding:40px 48px;font-family:Georgia,serif;font-size:14px;line-height:1.55', 'data-testid': 'doc-previa' },
    h('div', { style: `display:flex;align-items:center;gap:16px;border-bottom:3px solid ${id.cor_primaria};padding-bottom:12px;margin-bottom:20px` }, id.logo ? h('img', { src: id.logo, alt: 'Logo', style: 'max-height:64px;max-width:160px' }) : null, h('div', { style: 'flex:1' }, h('div', { style: `font-size:18px;font-weight:700;color:${id.cor_primaria}` }, id.nome_escritorio), h('div', { style: 'font-size:11px;color:#555' }, [id.advogada && id.oab ? `${id.advogada} · OAB ${id.oab}` : id.advogada, id.telefone, id.email, id.site].filter(Boolean).join(' · ')), id.cabecalho_texto ? h('div', { style: 'font-size:11px;color:#555' }, id.cabecalho_texto) : null)),
    d.rascunho ? h('div', { style: 'text-align:center;color:#b45309;font-size:11px;font-weight:700;letter-spacing:2px;margin-bottom:8px' }, 'RASCUNHO — NÃO FINALIZADO') : null,
    h('h1', { style: `font-size:20px;color:${id.cor_primaria};margin:0 0 4px` }, d.titulo), h('div', { style: 'font-size:12px;color:#666;margin-bottom:18px' }, d.data),
    ...d.secoes.flatMap((s, i) => [h('h2', { style: `font-size:15px;color:${id.cor_primaria};margin:18px 0 6px;border-left:4px solid ${id.cor_secundaria};padding-left:8px` }, `${i + 1}. ${s.titulo}`), ...s.paragrafos.map(t => h('p', { style: 'margin:0 0 8px;text-align:justify' }, t))]),
    h('div', { style: 'margin-top:36px' }, id.assinatura_img ? h('img', { src: id.assinatura_img, alt: 'Assinatura', style: 'max-height:60px' }) : null, h('div', { style: 'font-size:13px;white-space:pre-line' }, id.assinatura_texto || [id.advogada, id.oab ? 'OAB ' + id.oab : ''].filter(Boolean).join('\n'))),
    h('div', { style: `margin-top:28px;border-top:1px solid ${id.cor_secundaria};padding-top:8px;font-size:10px;color:#666;text-align:center` }, id.rodape_texto || [id.endereco, id.telefone, id.email, id.instagram].filter(Boolean).join(' · ')))
  modal({ titulo: 'Pré-visualização — ' + d.titulo, largura: 'max-w-4xl', corpo: h('div', { class: 'bg-gray-200 dark:bg-zinc-800 rounded-2xl p-3 overflow-x-auto' }, pagina_), rodape: f => [btn('Exportar DOCX', { tipo: 'sec', onclick: () => exportarDocx(p) }), btn('Exportar PDF', { tipo: 'sec', onclick: () => exportarPdf(p) }), btn('Fechar', { onclick: f })] })
}

/* ---------- exportações (no navegador) ---------- */
async function entregarArquivo(nome, dados) { try { const dl = window.claude && window.claude.use ? await window.claude.use('downloads') : null; if (!dl) throw new Error('indisponível'); await dl.save({ filename: nome, data: dados }); aviso('Arquivo pronto: ' + nome) } catch (e) { aviso('O download não está disponível neste ambiente (o arquivo foi gerado, mas não pôde ser salvo).', 'erro') } }
const bytesDeDataUrl = u => { const m = String(u || '').match(/^data:(image\/(png|jpe?g));base64,(.+)$/); return m ? { tipo: m[2] === 'png' ? 'png' : 'jpg', bytes: Uint8Array.from(atob(m[3]), c => c.charCodeAt(0)) } : null }
const nomeArquivoDoc = p => semAcento(p.titulo).replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60) || 'documento'
function dimensoesImagem(bytesUrl) { return new Promise(ok => { const im = new Image(); im.onload = () => ok({ w: im.naturalWidth, h: im.naturalHeight }); im.onerror = () => ok({ w: 160, h: 64 }); im.src = bytesUrl }) }
async function exportarDocx(p) {
  try {
    const d = dadosDoc(p); const id = d.id; const K = CRM; const cor = (id.cor_primaria || '#6f5636').replace('#', ''); const filhosCab = []
    const logo = bytesDeDataUrl(id.logo); if (logo) { const dim = await dimensoesImagem(id.logo); const alt = 56; filhosCab.push(new K.Paragraph({ children: [new K.ImageRun({ type: logo.tipo, data: logo.bytes, transformation: { width: Math.round(dim.w * alt / dim.h), height: alt } })] })) }
    filhosCab.push(new K.Paragraph({ children: [new K.TextRun({ text: id.nome_escritorio, bold: true, size: 28, color: cor })] }), new K.Paragraph({ border: { bottom: { style: K.BorderStyle.SINGLE, size: 12, color: cor, space: 4 } }, children: [new K.TextRun({ text: [id.advogada && id.oab ? `${id.advogada} · OAB ${id.oab}` : id.advogada, id.telefone, id.email, id.site].filter(Boolean).join(' · '), size: 18, color: '555555' })] }))
    if (d.rascunho) filhosCab.push(new K.Paragraph({ alignment: K.AlignmentType.CENTER, children: [new K.TextRun({ text: 'RASCUNHO — NÃO FINALIZADO', bold: true, color: 'B45309', size: 18 })] }))
    const corpo = [new K.Paragraph({ spacing: { before: 200, after: 60 }, children: [new K.TextRun({ text: d.titulo, bold: true, size: 36, color: cor })] }), new K.Paragraph({ spacing: { after: 240 }, children: [new K.TextRun({ text: d.data, size: 20, color: '666666' })] })]
    d.secoes.forEach((s, i) => { corpo.push(new K.Paragraph({ spacing: { before: 280, after: 100 }, children: [new K.TextRun({ text: `${i + 1}. ${s.titulo}`, bold: true, size: 26, color: cor })] })); s.paragrafos.forEach(t => corpo.push(new K.Paragraph({ alignment: K.AlignmentType.JUSTIFIED, spacing: { after: 120 }, children: [new K.TextRun({ text: t.replace(/^-\s+/, '• '), size: 22 })] }))) })
    const ass = bytesDeDataUrl(id.assinatura_img); if (ass) { const dim = await dimensoesImagem(id.assinatura_img); corpo.push(new K.Paragraph({ spacing: { before: 480 }, children: [new K.ImageRun({ type: ass.tipo, data: ass.bytes, transformation: { width: Math.round(dim.w * 50 / dim.h), height: 50 } })] })) }
    ;(id.assinatura_texto || [id.advogada, id.oab ? 'OAB ' + id.oab : ''].filter(Boolean).join('\n')).split('\n').forEach((l, k) => corpo.push(new K.Paragraph({ spacing: { before: k === 0 && !ass ? 480 : 0 }, children: [new K.TextRun({ text: l, size: 22 })] })))
    const doc = new K.Document({ creator: id.nome_escritorio, title: d.titulo, sections: [{ properties: { page: { margin: { top: 1100, bottom: 1100, left: 1300, right: 1300 } } }, headers: { default: new K.Header({ children: filhosCab }) }, footers: { default: new K.Footer({ children: [new K.Paragraph({ alignment: K.AlignmentType.CENTER, children: [new K.TextRun({ text: (id.rodape_texto || [id.endereco, id.telefone, id.email, id.instagram].filter(Boolean).join(' · ')) + '   ', size: 16, color: '666666' }), new K.TextRun({ children: [K.PageNumber.CURRENT], size: 16, color: '666666' })] })] }) }, children: corpo }] })
    const blob = await K.Packer.toBlob(doc); await entregarArquivo(nomeArquivoDoc(p) + '.docx', blob)
  } catch (e) { aviso('Não consegui gerar o DOCX: ' + String(e && e.message || e).slice(0, 120), 'erro') }
}
async function exportarPdf(p) {
  try {
    const d = dadosDoc(p); const id = d.id; const { PDFDocument, StandardFonts, rgb } = CRM; const pdf = await PDFDocument.create(); const reg = await pdf.embedFont(StandardFonts.TimesRoman); const neg = await pdf.embedFont(StandardFonts.TimesRomanBold); const hex = hx => { const m = String(hx || '#6f5636').replace('#', ''); return rgb(parseInt(m.slice(0, 2), 16) / 255, parseInt(m.slice(2, 4), 16) / 255, parseInt(m.slice(4, 6), 16) / 255) }
    const cp = hex(id.cor_primaria), cs = hex(id.cor_secundaria); const W = 595.28, H = 841.89, M = 56; const suporta = new Set(reg.getCharacterSet()); const limpa = t => Array.from(String(t).replace(/[“”]/g, '"').replace(/[‘’]/g, "'").replace(/[–—]/g, '-').replace(/…/g, '...').replace(/ /g, ' ')).map(ch => suporta.has(ch.codePointAt(0)) ? ch : '?').join('')
    let logoImg = null; const lg = bytesDeDataUrl(id.logo); if (lg) logoImg = lg.tipo === 'png' ? await pdf.embedPng(lg.bytes) : await pdf.embedJpg(lg.bytes); let assImg = null; const asg = bytesDeDataUrl(id.assinatura_img); if (asg) assImg = asg.tipo === 'png' ? await pdf.embedPng(asg.bytes) : await pdf.embedJpg(asg.bytes)
    const paginas = []; let pg, y
    const nova = () => { pg = pdf.addPage([W, H]); paginas.push(pg); let ty = H - M + 10; let x = M
      if (logoImg) { const alt = 44; const larg = Math.min(130, logoImg.width * alt / logoImg.height); pg.drawImage(logoImg, { x: M, y: H - M - alt + 10, width: larg, height: alt }); x = M + larg + 12 }
      pg.drawText(limpa(id.nome_escritorio), { x, y: ty - 8, size: 14, font: neg, color: cp }); pg.drawText(limpa([id.advogada && id.oab ? `${id.advogada} - OAB ${id.oab}` : id.advogada, id.telefone, id.email].filter(Boolean).join('  |  ')), { x, y: ty - 22, size: 8.5, font: reg, color: rgb(.35, .35, .35) })
      pg.drawLine({ start: { x: M, y: H - M - 38 }, end: { x: W - M, y: H - M - 38 }, thickness: 2, color: cp }); y = H - M - 62 }
    const quebrar = (t, fonte, tam, larg) => { const palavras = limpa(t).split(/\s+/); const ls = []; let l = ''; for (const w of palavras) { const x = l ? l + ' ' + w : w; if (fonte.widthOfTextAtSize(x, tam) > larg && l) { ls.push(l); l = w } else l = x } if (l) ls.push(l); return ls }
    const garantir = alt => { if (y - alt < M + 24) nova() }
    nova(); if (d.rascunho) { pg.drawText('RASCUNHO - NAO FINALIZADO', { x: W / 2 - 80, y, size: 9, font: neg, color: rgb(.7, .33, .04) }); y -= 16 }
    for (const ln of quebrar(d.titulo, neg, 17, W - 2 * M)) { garantir(22); pg.drawText(ln, { x: M, y, size: 17, font: neg, color: cp }); y -= 22 } pg.drawText(limpa(d.data), { x: M, y, size: 9.5, font: reg, color: rgb(.4, .4, .4) }); y -= 22
    d.secoes.forEach((s, i) => { garantir(40); pg.drawRectangle({ x: M, y: y - 3, width: 3, height: 14, color: cs }); for (const ln of quebrar(`${i + 1}. ${s.titulo}`, neg, 12.5, W - 2 * M - 10)) { garantir(18); pg.drawText(ln, { x: M + 9, y, size: 12.5, font: neg, color: cp }); y -= 17 } y -= 3
      s.paragrafos.forEach(par => { for (const ln of quebrar(par.replace(/^-\s+/, '• '), reg, 11, W - 2 * M)) { garantir(15); pg.drawText(ln, { x: M, y, size: 11, font: reg, color: rgb(.1, .1, .1) }); y -= 14.5 } y -= 5 }); y -= 6 })
    garantir(100); y -= 22; if (assImg) { const alt = 44; const larg = Math.min(160, assImg.width * alt / assImg.height); pg.drawImage(assImg, { x: M, y: y - alt, width: larg, height: alt }); y -= alt + 6 } for (const l of (id.assinatura_texto || [id.advogada, id.oab ? 'OAB ' + id.oab : ''].filter(Boolean).join('\n')).split('\n')) { pg.drawText(limpa(l), { x: M, y, size: 11, font: reg, color: rgb(.1, .1, .1) }); y -= 14 }
    const rod = limpa(id.rodape_texto || [id.endereco, id.telefone, id.email, id.instagram].filter(Boolean).join('  |  ')); paginas.forEach((q, k) => { q.drawLine({ start: { x: M, y: M - 4 }, end: { x: W - M, y: M - 4 }, thickness: .6, color: cs }); q.drawText(rod.slice(0, 120), { x: M, y: M - 16, size: 8, font: reg, color: rgb(.4, .4, .4) }); q.drawText(`${k + 1}/${paginas.length}`, { x: W - M - 24, y: M - 16, size: 8, font: reg, color: rgb(.4, .4, .4) }) })
    await entregarArquivo(nomeArquivoDoc(p) + '.pdf', await pdf.save())
  } catch (e) { aviso('Não consegui gerar o PDF: ' + String(e && e.message || e).slice(0, 120), 'erro') }
}

/* ---------- identidade visual e modelos de documento ---------- */
async function reduzirImagem(file, maxW, maxBytes) {
  const bmp = await createImageBitmap(file); const esc = Math.min(1, maxW / bmp.width); const cv = document.createElement('canvas'); cv.width = Math.round(bmp.width * esc); cv.height = Math.round(bmp.height * esc); const cx = cv.getContext('2d'); cx.drawImage(bmp, 0, 0, cv.width, cv.height)
  let u = cv.toDataURL('image/png'); if (u.length > maxBytes * 1.37) { cx.globalCompositeOperation = 'destination-over'; cx.fillStyle = '#fff'; cx.fillRect(0, 0, cv.width, cv.height); for (const q of [0.88, 0.75, 0.6, 0.45]) { u = cv.toDataURL('image/jpeg', q); if (u.length <= maxBytes * 1.37) break } }
  if (u.length > maxBytes * 1.37) throw new Error('imagem grande demais mesmo reduzida'); return u
}
function editarModeloDoc(m, aoFim) {
  const novo = !m.id; const v = { tipo: m.tipo || 'parecer', nome: m.nome || '', instrucoes: m.instrucoes || '', secoes: (m.secoes || MODELOS_BASE[m.tipo || 'parecer'].map(t => ({ titulo: t, instrucao: '' }))).map(s => ({ ...s })) }
  const corpo = h('div', { class: 'space-y-3', 'data-testid': 'modelo-editor' })
  const des = () => corpo.replaceChildren(h('div', { class: 'grid gap-3 sm:grid-cols-2' }, h('label', { class: 'block' }, rotuloCampo('Tipo de documento'), h('select', { class: 'modal-input', 'data-testid': 'modelo-tipo', disabled: !novo, onchange: ev => { v.tipo = ev.target.value; v.secoes = MODELOS_BASE[v.tipo].map(t => ({ titulo: t, instrucao: '' })); des() } }, Object.entries(TIPOS_DOC).map(([k, t]) => h('option', { value: k, selected: k === v.tipo }, t)))), h('label', { class: 'block' }, rotuloCampo('Nome do modelo'), h('input', { class: 'modal-input', value: v.nome, 'data-testid': 'modelo-nome', oninput: ev => { v.nome = ev.target.value } }))), h('label', { class: 'block' }, rotuloCampo('Instruções gerais para a IA (tom, extensão, o que sempre incluir)'), h('textarea', { class: 'modal-input', rows: 3, 'data-testid': 'modelo-instrucoes', oninput: ev => { v.instrucoes = ev.target.value } }, v.instrucoes)), h('p', { class: 'section-label' }, 'Seções'), ...v.secoes.map((s, i) => h('div', { class: 'rounded-xl border border-gray-200 dark:border-zinc-700 p-2 space-y-1.5' }, h('div', { class: 'flex gap-2' }, h('input', { class: 'modal-input !text-sm flex-1', value: s.titulo, 'aria-label': 'Título', oninput: ev => { s.titulo = ev.target.value } }), btn('↑', { mini: true, tipo: 'fantasma', onclick: () => { if (i) { [v.secoes[i - 1], v.secoes[i]] = [v.secoes[i], v.secoes[i - 1]]; des() } } }), btn('↓', { mini: true, tipo: 'fantasma', onclick: () => { if (i < v.secoes.length - 1) { [v.secoes[i + 1], v.secoes[i]] = [v.secoes[i], v.secoes[i + 1]]; des() } } }), btn('✕', { mini: true, tipo: 'fantasma', onclick: () => { v.secoes.splice(i, 1); des() } })), h('input', { class: 'modal-input !text-xs', placeholder: 'Instrução para esta seção (opcional)', value: s.instrucao || '', oninput: ev => { s.instrucao = ev.target.value } }))), btn('Adicionar seção', { mini: true, tipo: 'sec', icone: 'ph:plus-bold', onclick: () => { v.secoes.push({ titulo: 'Nova seção', instrucao: '' }); des() } }))
  des(); modal({ titulo: novo ? 'Novo modelo' : 'Editar modelo', largura: 'max-w-2xl', corpo, rodape: f => [!novo ? btn('Excluir', { tipo: 'perigo', onclick: () => confirmar('Excluir este modelo?', 'Documentos já gerados não são afetados.', 'Excluir', () => { DB.modelos_doc = DB.modelos_doc.filter(x => x.id !== m.id); salvar('modelos_doc'); f(); aoFim && aoFim(); render() }) }) : null, btn('Salvar modelo', { tid: 'modelo-salvar', onclick: () => { if (!v.nome.trim() || !v.secoes.length) { aviso('Dê um nome e mantenha ao menos uma seção.', 'erro'); return } const dados = { tipo: v.tipo, nome: v.nome.trim(), instrucoes: v.instrucoes, secoes: v.secoes.filter(s => s.titulo.trim()) }; if (novo) DB.modelos_doc.push({ id: proximoId('modelos_doc'), created_at: agora(), ...dados }); else Object.assign(m, dados); salvar('modelos_doc'); f(); aoFim && aoFim(); render() } })] })
}
VIEWS.identidade = () => {
  const id = identidade(); const ci = CONFIG.identidade = CONFIG.identidade || {}
  const campo = (rot, k, ph, tid) => h('label', { class: 'block' }, rotuloCampo(rot), (() => { const t = h('input', { class: 'modal-input', placeholder: ph || '', 'data-testid': tid }); t.value = id[k] || ''; t.addEventListener('change', () => { ci[k] = t.value.trim(); salvar('config') }); return t })())
  const cor = (rot, k, tid) => h('label', { class: 'block' }, rotuloCampo(rot), h('input', { type: 'color', class: 'h-10 w-full rounded-lg border border-gray-300 dark:border-zinc-700', value: id[k], 'data-testid': tid, onchange: ev => { ci[k] = ev.target.value; salvar('config'); render() } }))
  const imagem = (rot, k, maxW, tid) => h('div', { class: 'space-y-1' }, rotuloCampo(rot), id[k] ? h('img', { src: id[k], alt: rot, class: 'max-h-20 bg-white rounded border p-1', 'data-testid': tid + '-img' }) : h('p', { class: 'text-xs text-gray-500' }, 'Nenhuma imagem.'), h('div', { class: 'flex flex-wrap gap-2 items-center' }, h('input', { type: 'file', accept: 'image/png,image/jpeg', 'data-testid': tid, onchange: async ev => { const f = ev.target.files[0]; if (!f) return; try { ci[k] = await reduzirImagem(f, maxW, 110000); salvar('config'); aviso('Imagem salva (reduzida para caber no CRM).'); render() } catch (e) { aviso('Não consegui usar a imagem: ' + (e && e.message || e), 'erro') } } }), id[k] ? btn('Remover', { mini: true, tipo: 'fantasma', onclick: () => { delete ci[k]; salvar('config'); render() } }) : null))
  const mods = Object.keys(TIPOS_DOC)
  return pagina('Identidade visual e modelos', 'Usados nos pareceres e demais documentos: pré-visualização, DOCX e PDF.', null,
    painel('Identidade do escritório', h('div', { class: 'space-y-4' }, h('div', { class: 'grid gap-3 sm:grid-cols-2' }, campo('Nome do escritório', 'nome_escritorio', '', 'id-nome'), campo('Seu nome', 'advogada', '', 'id-advogada'), campo('OAB', 'oab', 'Ex.: BA 00000', 'id-oab'), campo('Telefone', 'telefone', '', 'id-telefone'), campo('E-mail', 'email', '', 'id-email'), campo('Endereço', 'endereco', '', 'id-endereco'), campo('Site', 'site', '', 'id-site'), campo('Instagram', 'instagram', '@…', 'id-instagram')), h('div', { class: 'grid gap-3 sm:grid-cols-2' }, cor('Cor principal', 'cor_primaria', 'id-cor1'), cor('Cor de apoio', 'cor_secundaria', 'id-cor2')), h('div', { class: 'grid gap-3 sm:grid-cols-2' }, campo('Texto do cabeçalho (opcional)', 'cabecalho_texto', '', 'id-cabecalho'), campo('Texto do rodapé (opcional)', 'rodape_texto', 'Se vazio: endereço · telefone · e-mail · Instagram', 'id-rodape')), h('label', { class: 'block' }, rotuloCampo('Assinatura (texto)'), h('textarea', { class: 'modal-input', rows: 3, 'data-testid': 'id-assinatura', placeholder: 'Se vazio: seu nome e OAB', onchange: ev => { ci.assinatura_texto = ev.target.value; salvar('config') } }, id.assinatura_texto || '')), h('div', { class: 'grid gap-4 sm:grid-cols-2' }, imagem('Logo (PNG/JPG)', 'logo', 700, 'id-logo'), imagem('Imagem da assinatura (opcional)', 'assinatura_img', 500, 'id-assinatura-img')), h('p', { class: 'text-xs text-gray-500' }, 'As imagens são reduzidas (≈100 KB) para caber no CRM.'))),
    painel('Modelos de documento', h('div', { class: 'space-y-3' }, h('p', { class: 'text-xs text-gray-600 dark:text-zinc-300' }, 'Cada tipo tem um modelo padrão; crie os seus com as seções e instruções que quiser. A IA segue as seções do modelo escolhido e a identidade visual é aplicada ao documento.'), mods.map(t => h('div', { class: 'space-y-1.5' }, h('p', { class: 'font-semibold text-sm' }, TIPOS_DOC[t]), h('div', { class: 'flex flex-wrap gap-1.5 items-center' }, h('span', { class: 'chip' }, 'Padrão: ' + MODELOS_BASE[t].length + ' seção(ões)'), ...DB.modelos_doc.filter(m => m.tipo === t).map(m => h('button', { type: 'button', class: 'chip chip-escuro', 'data-testid': 'modelo-item', onclick: () => editarModeloDoc(m) }, m.nome)), btn('Novo modelo', { mini: true, tipo: 'fantasma', icone: 'ph:plus-bold', tid: 'modelo-novo-' + t, onclick: () => editarModeloDoc({ tipo: t }) })))))))
}
